using AtomUI.Localization;

namespace AtomUIGallery.Localization;

[LanguageCatalog(ContractVersion = 1)]
public enum TransferShowCaseLangResourceKind
{
    BasicTitle = 1,
    BasicDescription = 2,
    ScenarioBasic = 3,
    ScenarioAdvanced = 4,
    ScenarioTreeStatus = 5,
    ScenarioExamples = 6,
    PageSubtitle = 7,
    PageDescription = 8,
    ComponentCategory = 9,
    ComponentStatusStable = 10,
    OneWayTitle = 11,
    OneWayDescription = 12,
    SearchTitle = 13,
    SearchDescription = 14,
    ControlledKeysTitle = 15,
    ControlledKeysDescription = 16,
    AdvancedTitle = 17,
    AdvancedDescription = 18,
    PaginationTitle = 19,
    PaginationDescription = 20,
    TreeTransferTitle = 21,
    TreeTransferDescription = 22,
    StatusTitle = 23,
    StatusDescription = 24,
    P2SourceTitle = 25,
    P2TargetTitle = 26,
    P2TextText = 27,
    P2HeaderName = 28,
    P2HeaderTag = 29,
    P2HeaderDescription = 30,
    P2ContentLeftButtonReload = 31,
    P2ContentRightButtonReload = 32,
    P2ContentAddTargetKey = 33,
    P2ContentClearTargetKeys = 34,
    P2ContentSelectSourceKey = 35,
    P2TargetKeysCountLabel = 36,
    P2SelectedKeysCountLabel = 37,
    P2OnContentDisable = 38,
    P2OffContentEnable = 39,
    P2FilterPlaceholderTextSearchHere = 40,
    P2ToSourceButtonTextToLeft = 41,
    P2ToTargetButtonTextToRight = 42,
    P2OnContentOnyWay = 43,
    P2OffContentOnyWay = 44,
    P2ItemContentFormat = 45,
    P2ItemDescriptionFormat = 46,
    P2TagCat = 47,
    P2TagDog = 48,
    P2TagBird = 49
}
