using AtomUI.Localization;

namespace AtomUIGallery.Localization;

[LanguageCatalog(ContractVersion = 2)]
public enum TransferShowCaseLangResourceKind
{
    BasicTitle,
    BasicDescription,
    ScenarioBasic,
    ScenarioAdvanced,
    ScenarioTreeStatus,
    ScenarioExamples,
    PageSubtitle,
    PageDescription,
    ComponentCategory,
    ComponentStatusStable,
    OneWayTitle,
    OneWayDescription,
    SearchTitle,
    SearchDescription,
    ControlledKeysTitle,
    ControlledKeysDescription,
    AdvancedTitle,
    AdvancedDescription,
    PaginationTitle,
    PaginationDescription,
    TreeTransferTitle,
    TreeTransferDescription,
    StatusTitle,
    StatusDescription,
    P2SourceTitle,
    P2TargetTitle,
    P2TextText,
    P2HeaderName,
    P2HeaderTag,
    P2HeaderDescription,
    P2ContentLeftButtonReload,
    P2ContentRightButtonReload,
    P2ContentAddTargetKey,
    P2ContentClearTargetKeys,
    P2ContentSelectSourceKey,
    P2TargetKeysCountLabel,
    P2SelectedKeysCountLabel,
    P2OnContentDisable,
    P2OffContentEnable,
    P2FilterPlaceholderTextSearchHere,
    P2ToSourceButtonTextToLeft,
    P2ToTargetButtonTextToRight,
    P2OnContentOnyWay,
    P2OffContentOnyWay,
    P2ItemContentFormat,
    P2ItemDescriptionFormat,
    P2TagCat,
    P2TagDog,
    P2TagBird
}
