// <auto-generated />

using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace AtomUIGallery.ShowCases.Views
{
    partial class FlexPanelShowCase
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton DirectionHorizontal;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton DirectionVertical;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Controls.FlexPanel BasicFlexPanel;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.Border BasicItem1;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.Border BasicItem2;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.Border BasicItem3;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.Border BasicItem4;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.Segmented JustifySegmented;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.Segmented AlignSegmented;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Controls.FlexPanel AlignFlexPanel;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton GapSmall;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton GapMiddle;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton GapLarge;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton GapCustomize;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.StackPanel GapCustomPanel;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.Slider GapValueSlider;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Controls.FlexPanel GapFlexPanel;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.Segmented AlignSelfSegmented;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Controls.FlexPanel AlignSelfFlexPanel;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.Border AlignSelfTarget;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton WrapEnabled;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton WrapDisabled;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.ScrollViewer WrapScrollViewer;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Controls.FlexPanel WrapFlexPanel;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.Segmented OrderSegmented;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.Border OrderItemA;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.Border OrderItemB;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.Border OrderItemC;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.Border OrderItemD;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.Segmented BasisKindSegmented;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.StackPanel BasisValuePanel;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.NumericUpDown BasisValueInput;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.TextBlock BasisValueUnit;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.StackPanel BasisPercentPanel;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.Slider BasisValueSlider;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.TextBlock BasisPercentText;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Controls.FlexPanel BasisFlexPanel;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.Border BasisItem;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.Border BasisGrowItem1;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.Border BasisGrowItem2;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.NumericUpDown GrowInputA;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.NumericUpDown GrowInputB;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Controls.FlexPanel GrowFlexPanel;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.Border GrowItemA;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.Border GrowItemB;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.Border GrowItemC;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.Slider ShrinkWidthSlider;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.TextBlock ShrinkWidthText;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.Border ShrinkContainer;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Controls.FlexPanel ShrinkFlexPanel;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.Segmented PlaygroundDirectionSegmented;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.Segmented PlaygroundWrapSegmented;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.Segmented PlaygroundJustifySegmented;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.Segmented PlaygroundAlignItemsSegmented;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.Segmented PlaygroundAlignContentSegmented;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.Slider PlaygroundColumnSpacingSlider;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.TextBlock PlaygroundColumnSpacingText;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.Slider PlaygroundRowSpacingSlider;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.TextBlock PlaygroundRowSpacingText;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.Slider PlaygroundWidthSlider;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.TextBlock PlaygroundWidthText;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.Slider PlaygroundHeightSlider;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.TextBlock PlaygroundHeightText;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.Segmented PlaygroundItemSegmented;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.Segmented PlaygroundAlignSelfSegmented;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.Segmented PlaygroundBasisKindSegmented;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.StackPanel PlaygroundBasisValuePanel;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.NumericUpDown PlaygroundBasisValueInput;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.TextBlock PlaygroundBasisValueUnit;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.StackPanel PlaygroundBasisPercentPanel;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.Slider PlaygroundBasisValueSlider;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.TextBlock PlaygroundBasisPercentText;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.NumericUpDown PlaygroundGrowInput;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.NumericUpDown PlaygroundShrinkInput;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Desktop.Controls.NumericUpDown PlaygroundOrderInput;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.Border PlaygroundContainer;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::AtomUI.Controls.FlexPanel PlaygroundFlexPanel;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.Border PlaygroundItemA;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.Border PlaygroundItemB;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        internal global::Avalonia.Controls.Border PlaygroundItemC;

        /// <summary>
        /// Wires up the controls and optionally loads XAML markup and attaches dev tools (if Avalonia.Diagnostics package is referenced).
        /// </summary>
        /// <param name="loadXaml">Should the XAML be loaded into the component.</param>

        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "12.0.1.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public void InitializeComponent(bool loadXaml = true)
        {
            if (loadXaml)
            {
                AvaloniaXamlLoader.Load(this);
            }

            var __thisNameScope__ = this.FindNameScope();
            DirectionHorizontal = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("DirectionHorizontal");
            DirectionVertical = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("DirectionVertical");
            BasicFlexPanel = __thisNameScope__?.Find<global::AtomUI.Controls.FlexPanel>("BasicFlexPanel");
            BasicItem1 = __thisNameScope__?.Find<global::Avalonia.Controls.Border>("BasicItem1");
            BasicItem2 = __thisNameScope__?.Find<global::Avalonia.Controls.Border>("BasicItem2");
            BasicItem3 = __thisNameScope__?.Find<global::Avalonia.Controls.Border>("BasicItem3");
            BasicItem4 = __thisNameScope__?.Find<global::Avalonia.Controls.Border>("BasicItem4");
            JustifySegmented = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Segmented>("JustifySegmented");
            AlignSegmented = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Segmented>("AlignSegmented");
            AlignFlexPanel = __thisNameScope__?.Find<global::AtomUI.Controls.FlexPanel>("AlignFlexPanel");
            GapSmall = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("GapSmall");
            GapMiddle = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("GapMiddle");
            GapLarge = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("GapLarge");
            GapCustomize = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("GapCustomize");
            GapCustomPanel = __thisNameScope__?.Find<global::Avalonia.Controls.StackPanel>("GapCustomPanel");
            GapValueSlider = __thisNameScope__?.Find<global::Avalonia.Controls.Slider>("GapValueSlider");
            GapFlexPanel = __thisNameScope__?.Find<global::AtomUI.Controls.FlexPanel>("GapFlexPanel");
            AlignSelfSegmented = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Segmented>("AlignSelfSegmented");
            AlignSelfFlexPanel = __thisNameScope__?.Find<global::AtomUI.Controls.FlexPanel>("AlignSelfFlexPanel");
            AlignSelfTarget = __thisNameScope__?.Find<global::Avalonia.Controls.Border>("AlignSelfTarget");
            WrapEnabled = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("WrapEnabled");
            WrapDisabled = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("WrapDisabled");
            WrapScrollViewer = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.ScrollViewer>("WrapScrollViewer");
            WrapFlexPanel = __thisNameScope__?.Find<global::AtomUI.Controls.FlexPanel>("WrapFlexPanel");
            OrderSegmented = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Segmented>("OrderSegmented");
            OrderItemA = __thisNameScope__?.Find<global::Avalonia.Controls.Border>("OrderItemA");
            OrderItemB = __thisNameScope__?.Find<global::Avalonia.Controls.Border>("OrderItemB");
            OrderItemC = __thisNameScope__?.Find<global::Avalonia.Controls.Border>("OrderItemC");
            OrderItemD = __thisNameScope__?.Find<global::Avalonia.Controls.Border>("OrderItemD");
            BasisKindSegmented = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Segmented>("BasisKindSegmented");
            BasisValuePanel = __thisNameScope__?.Find<global::Avalonia.Controls.StackPanel>("BasisValuePanel");
            BasisValueInput = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.NumericUpDown>("BasisValueInput");
            BasisValueUnit = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.TextBlock>("BasisValueUnit");
            BasisPercentPanel = __thisNameScope__?.Find<global::Avalonia.Controls.StackPanel>("BasisPercentPanel");
            BasisValueSlider = __thisNameScope__?.Find<global::Avalonia.Controls.Slider>("BasisValueSlider");
            BasisPercentText = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.TextBlock>("BasisPercentText");
            BasisFlexPanel = __thisNameScope__?.Find<global::AtomUI.Controls.FlexPanel>("BasisFlexPanel");
            BasisItem = __thisNameScope__?.Find<global::Avalonia.Controls.Border>("BasisItem");
            BasisGrowItem1 = __thisNameScope__?.Find<global::Avalonia.Controls.Border>("BasisGrowItem1");
            BasisGrowItem2 = __thisNameScope__?.Find<global::Avalonia.Controls.Border>("BasisGrowItem2");
            GrowInputA = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.NumericUpDown>("GrowInputA");
            GrowInputB = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.NumericUpDown>("GrowInputB");
            GrowFlexPanel = __thisNameScope__?.Find<global::AtomUI.Controls.FlexPanel>("GrowFlexPanel");
            GrowItemA = __thisNameScope__?.Find<global::Avalonia.Controls.Border>("GrowItemA");
            GrowItemB = __thisNameScope__?.Find<global::Avalonia.Controls.Border>("GrowItemB");
            GrowItemC = __thisNameScope__?.Find<global::Avalonia.Controls.Border>("GrowItemC");
            ShrinkWidthSlider = __thisNameScope__?.Find<global::Avalonia.Controls.Slider>("ShrinkWidthSlider");
            ShrinkWidthText = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.TextBlock>("ShrinkWidthText");
            ShrinkContainer = __thisNameScope__?.Find<global::Avalonia.Controls.Border>("ShrinkContainer");
            ShrinkFlexPanel = __thisNameScope__?.Find<global::AtomUI.Controls.FlexPanel>("ShrinkFlexPanel");
            PlaygroundDirectionSegmented = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Segmented>("PlaygroundDirectionSegmented");
            PlaygroundWrapSegmented = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Segmented>("PlaygroundWrapSegmented");
            PlaygroundJustifySegmented = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Segmented>("PlaygroundJustifySegmented");
            PlaygroundAlignItemsSegmented = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Segmented>("PlaygroundAlignItemsSegmented");
            PlaygroundAlignContentSegmented = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Segmented>("PlaygroundAlignContentSegmented");
            PlaygroundColumnSpacingSlider = __thisNameScope__?.Find<global::Avalonia.Controls.Slider>("PlaygroundColumnSpacingSlider");
            PlaygroundColumnSpacingText = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.TextBlock>("PlaygroundColumnSpacingText");
            PlaygroundRowSpacingSlider = __thisNameScope__?.Find<global::Avalonia.Controls.Slider>("PlaygroundRowSpacingSlider");
            PlaygroundRowSpacingText = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.TextBlock>("PlaygroundRowSpacingText");
            PlaygroundWidthSlider = __thisNameScope__?.Find<global::Avalonia.Controls.Slider>("PlaygroundWidthSlider");
            PlaygroundWidthText = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.TextBlock>("PlaygroundWidthText");
            PlaygroundHeightSlider = __thisNameScope__?.Find<global::Avalonia.Controls.Slider>("PlaygroundHeightSlider");
            PlaygroundHeightText = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.TextBlock>("PlaygroundHeightText");
            PlaygroundItemSegmented = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Segmented>("PlaygroundItemSegmented");
            PlaygroundAlignSelfSegmented = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Segmented>("PlaygroundAlignSelfSegmented");
            PlaygroundBasisKindSegmented = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Segmented>("PlaygroundBasisKindSegmented");
            PlaygroundBasisValuePanel = __thisNameScope__?.Find<global::Avalonia.Controls.StackPanel>("PlaygroundBasisValuePanel");
            PlaygroundBasisValueInput = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.NumericUpDown>("PlaygroundBasisValueInput");
            PlaygroundBasisValueUnit = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.TextBlock>("PlaygroundBasisValueUnit");
            PlaygroundBasisPercentPanel = __thisNameScope__?.Find<global::Avalonia.Controls.StackPanel>("PlaygroundBasisPercentPanel");
            PlaygroundBasisValueSlider = __thisNameScope__?.Find<global::Avalonia.Controls.Slider>("PlaygroundBasisValueSlider");
            PlaygroundBasisPercentText = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.TextBlock>("PlaygroundBasisPercentText");
            PlaygroundGrowInput = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.NumericUpDown>("PlaygroundGrowInput");
            PlaygroundShrinkInput = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.NumericUpDown>("PlaygroundShrinkInput");
            PlaygroundOrderInput = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.NumericUpDown>("PlaygroundOrderInput");
            PlaygroundContainer = __thisNameScope__?.Find<global::Avalonia.Controls.Border>("PlaygroundContainer");
            PlaygroundFlexPanel = __thisNameScope__?.Find<global::AtomUI.Controls.FlexPanel>("PlaygroundFlexPanel");
            PlaygroundItemA = __thisNameScope__?.Find<global::Avalonia.Controls.Border>("PlaygroundItemA");
            PlaygroundItemB = __thisNameScope__?.Find<global::Avalonia.Controls.Border>("PlaygroundItemB");
            PlaygroundItemC = __thisNameScope__?.Find<global::Avalonia.Controls.Border>("PlaygroundItemC");
        }
    }
}
