using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.ProgressBar;

[LanguageProvider(LanguageCode.en_US, ProgressBarShowCase.LanguageId)]
internal partial class en_US : LanguageProvider
{
    public const string ScenarioBasic = "Basic";
    public const string ScenarioAdvanced = "Advanced";
    public const string ScenarioLayout = "Layout";
    public const string ProgressBarTitle = "Progress bar";
    public const string ProgressBarDescription = "A standard progress bar.";
    public const string CircularProgressBarTitle = "Circular progress bar";
    public const string CircularProgressBarDescription = "A circular progress bar.";
    public const string MiniSizeTitle = "Mini size progress bar";
    public const string MiniSizeDescription = "Appropriate for a narrow area.";
    public const string SmallerCircularProgressBarTitle = "A smaller circular progress bar.";
    public const string SmallerCircularProgressBarDescription = "A smaller circular progress bar.";
    public const string DynamicTitle = "Dynamic";
    public const string DynamicDescription = "A dynamic progress bar is better.";
    public const string CustomTextFormatTitle = "Custom text format";
    public const string CustomTextFormatDescription = "You can set a custom text by setting the format prop.";
    public const string DashboardTitle = "Dashboard";
    public const string DashboardDescription = "By setting type=dashboard, you can get a dashboard style of progress easily. Modify gapDegree to set the degree of gap.";
    public const string SuccessSegmentTitle = "Progress bar with success segment";
    public const string SuccessSegmentDescription = "Show several parts of progress with different status.";
    public const string StrokeLinecapTitle = "Stroke Linecap";
    public const string StrokeLinecapDescription = "By setting strokeLinecap='butt', you can change the linecaps from round to butt, see stroke-linecap for more information.";
    public const string CustomLineGradientTitle = "Custom line gradient";
    public const string CustomLineGradientDescription = "Gradient encapsulation, circle and dashboard will ignore strokeLinecap when setting gradient.";
    public const string StepsTitle = "Progress bar with steps";
    public const string StepsDescription = "A progress bar with steps.";
    public const string CircularStepsTitle = "Circular progress bar whit steps";
    public const string CircularStepsDescription = "A circular progress bar that support steps and color segments, default gap is 2px.";
    public const string PercentPositionTitle = "Change progress value position";
    public const string PercentPositionDescription = "Change the position of the progress value, you can use percentPosition to adjust it so that the progress bar value is inside, outside or at the bottom of the progress bar.";
    public const string StepsPercentPositionTitle = "Change progress value position for StepsProgressBar";
    public const string StepsPercentPositionDescription = "Change the position of the progress value, you can use percentPosition to adjust it so that the progress bar value is inside, outside or at the bottom of the progress bar.";
    public const string VerticalLinearTitle = "Vertical progress bar";
    public const string VerticalLinearDescription = "Ordinary linear progress bar, supports position specification of additional areas";
    public const string VerticalStepsTitle = "Vertical progress bar";
    public const string VerticalStepsDescription = "Ordinary step progress bar, supports position specification of additional areas";
    public const string ToggleDisabledStatusTitle = "toggle disabled status";
    public const string ToggleDisabledStatusDescription = "The progress bar is in the disabled state and uses the disabled style.";
    public const string P2ContentSub = "Sub";
    public const string P2ContentAdd = "Add";
    public const string PageSubtitle = "Visualize task completion and operation progress.";
    public const string PageDescription = "ProgressBar, StepsProgressBar, CircleProgress, and DashboardProgress cover linear, stepped, circular, and dashboard progress indicators with status, size, gradient, and layout options.";
    public const string ComponentCategory = "Feedback";
    public const string ComponentStatusStable = ".NET 10";
    public const string ScenarioExamples = "Examples";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "Design Token";
    public const string ApiColumnProperty = "Property";
    public const string ApiColumnDescription = "Description";
    public const string ApiColumnType = "Type";
    public const string ApiColumnDefault = "Default";
    public const string ApiPropertyValue = "Current progress value.";
    public const string ApiPropertyMinimum = "Minimum value in the progress range.";
    public const string ApiPropertyMaximum = "Maximum value in the progress range.";
    public const string ApiPropertyIsIndeterminate = "Shows an indeterminate progress state when the value is unknown.";
    public const string ApiPropertyIsProgressInfoVisible = "Controls whether the progress text or completion icon is visible.";
    public const string ApiPropertyProgressTextFormat = "Format string used to render progress text.";
    public const string ApiPropertyStrokeBrush = "Brush used for the completed progress indicator.";
    public const string ApiPropertyTrailColor = "Color used for the remaining progress track.";
    public const string ApiPropertyStrokeLineCap = "Line cap used by linear, circular, and dashboard progress strokes.";
    public const string ApiPropertySizeType = "Preset size for the progress indicator.";
    public const string ApiPropertyStatus = "Visual status of the progress indicator.";
    public const string ApiPropertyIndicatorThickness = "Custom thickness for the progress indicator stroke.";
    public const string ApiPropertySuccessThreshold = "Success segment threshold shown inside the progress track.";
    public const string ApiPropertySuccessStrokeBrush = "Brush used to render the success segment.";
    public const string ApiPropertyOrientation = "Linear or steps progress orientation.";
    public const string ApiPropertyPercentPosition = "Controls whether progress text is placed inside or outside the indicator.";
    public const string ApiPropertySteps = "Number of steps for StepsProgressBar.";
    public const string ApiPropertyStepsStrokeBrush = "Brush collection used to color individual steps.";
    public const string ApiPropertyStepCount = "Number of segmented steps for circular and dashboard progress.";
    public const string ApiPropertyStepGap = "Gap between segmented circular or dashboard progress steps.";
    public const string ApiPropertyDashboardGapPosition = "Gap position for dashboard progress.";
    public const string ApiPropertyGapDegree = "Gap angle for dashboard progress.";
    public const string TokenColumnToken = "Token";
    public const string TokenColumnDescription = "Description";
    public const string TokenColumnScope = "Scope";
    public const string TokenColumnStatus = "Status";
    public const string TokenNameDefaultColor = "Default completed progress color.";
    public const string TokenNameRemainingColor = "Remaining track color.";
    public const string TokenNameCircleTextColor = "Text color inside circular progress.";
    public const string TokenNameLineBorderRadius = "Border radius for linear progress tracks.";
    public const string TokenNameCircleMinimumTextFontSize = "Minimum text size inside compact circular progress.";
    public const string TokenNameCircleMinimumIconSize = "Minimum completion icon size inside compact circular progress.";
    public const string TokenNameLineInfoIconSize = "Completion or status icon size for linear progress.";
    public const string TokenNameLineInfoIconSizeSM = "Small completion or status icon size for linear progress.";
    public const string TokenNameLineExtraInfoMargin = "Spacing between the linear progress track and extra information.";
    public const string TokenNameLineProgressPadding = "Internal padding for the linear progress track.";
    public const string TokenScopeComponent = "Component";
    public const string TokenStatusStable = "Stable";

    protected override Type GetResourceKindType() => typeof(ProgressBarShowCaseLangResourceKind);
}
