using AtomUI.Localization;

namespace AtomUIGallery.Localization;

[LanguageCatalog(ContractVersion = 1)]
public enum ProgressBarShowCaseLangResourceKind
{
    ScenarioBasic = 1,
    ScenarioAdvanced = 2,
    ScenarioLayout = 3,
    ProgressBarTitle = 4,
    ProgressBarDescription = 5,
    CircularProgressBarTitle = 6,
    CircularProgressBarDescription = 7,
    MiniSizeTitle = 8,
    MiniSizeDescription = 9,
    SmallerCircularProgressBarTitle = 10,
    SmallerCircularProgressBarDescription = 11,
    DynamicTitle = 12,
    DynamicDescription = 13,
    CustomTextFormatTitle = 14,
    CustomTextFormatDescription = 15,
    DashboardTitle = 16,
    DashboardDescription = 17,
    SuccessSegmentTitle = 18,
    SuccessSegmentDescription = 19,
    StrokeLinecapTitle = 20,
    StrokeLinecapDescription = 21,
    CustomLineGradientTitle = 22,
    CustomLineGradientDescription = 23,
    StepsTitle = 24,
    StepsDescription = 25,
    CircularStepsTitle = 26,
    CircularStepsDescription = 27,
    PercentPositionTitle = 28,
    PercentPositionDescription = 29,
    StepsPercentPositionTitle = 30,
    StepsPercentPositionDescription = 31,
    VerticalLinearTitle = 32,
    VerticalLinearDescription = 33,
    VerticalStepsTitle = 34,
    VerticalStepsDescription = 35,
    ToggleDisabledStatusTitle = 36,
    ToggleDisabledStatusDescription = 37,
    P2ContentSub = 38,
    P2ContentAdd = 39,
    PageSubtitle = 40,
    PageDescription = 41,
    ComponentCategory = 42,
    ComponentStatusStable = 43,
    ScenarioExamples = 44
}
