using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.ProgressBar;

[LanguageProvider(LanguageCode.zh_CN, ProgressBarShowCase.LanguageId)]
internal partial class zh_CN : LanguageProvider
{
    public const string ScenarioBasic = "基础";
    public const string ScenarioAdvanced = "进阶";
    public const string ScenarioLayout = "布局";
    public const string ProgressBarTitle = "进度条";
    public const string ProgressBarDescription = "标准进度条。";
    public const string CircularProgressBarTitle = "环形进度条";
    public const string CircularProgressBarDescription = "环形进度条。";
    public const string MiniSizeTitle = "迷你尺寸进度条";
    public const string MiniSizeDescription = "适合较窄区域。";
    public const string SmallerCircularProgressBarTitle = "更小的环形进度条";
    public const string SmallerCircularProgressBarDescription = "更小的环形进度条。";
    public const string DynamicTitle = "动态进度";
    public const string DynamicDescription = "动态进度条效果更好。";
    public const string CustomTextFormatTitle = "自定义文本格式";
    public const string CustomTextFormatDescription = "可以通过设置 format 属性自定义文本。";
    public const string DashboardTitle = "仪表盘";
    public const string DashboardDescription = "设置 type=dashboard 可以轻松获得仪表盘样式进度条。修改 gapDegree 可设置缺口角度。";
    public const string SuccessSegmentTitle = "带成功分段的进度条";
    public const string SuccessSegmentDescription = "展示多个不同状态的进度片段。";
    public const string StrokeLinecapTitle = "线帽样式";
    public const string StrokeLinecapDescription = "设置 strokeLinecap='butt' 可以将线帽从 round 改为 butt，更多信息请参考 stroke-linecap。";
    public const string CustomLineGradientTitle = "自定义线性渐变";
    public const string CustomLineGradientDescription = "渐变封装；设置渐变时 circle 和 dashboard 会忽略 strokeLinecap。";
    public const string StepsTitle = "步骤进度条";
    public const string StepsDescription = "带步骤的进度条。";
    public const string CircularStepsTitle = "带步骤的环形进度条";
    public const string CircularStepsDescription = "支持步骤和颜色分段的环形进度条，默认间隔为 2px。";
    public const string PercentPositionTitle = "调整进度值位置";
    public const string PercentPositionDescription = "改变进度值的位置，可使用 percentPosition 将进度值调整到进度条内部、外部或底部。";
    public const string StepsPercentPositionTitle = "调整步骤进度值位置";
    public const string StepsPercentPositionDescription = "改变步骤进度值的位置，可使用 percentPosition 将进度值调整到进度条内部、外部或底部。";
    public const string VerticalLinearTitle = "垂直线性进度条";
    public const string VerticalLinearDescription = "普通线性进度条，支持指定附加区域的位置。";
    public const string VerticalStepsTitle = "垂直步骤进度条";
    public const string VerticalStepsDescription = "普通步骤进度条，支持指定附加区域的位置。";
    public const string ToggleDisabledStatusTitle = "切换禁用状态";
    public const string ToggleDisabledStatusDescription = "进度条处于禁用状态并使用禁用样式。";
    public const string P2ContentSub = "Sub";
    public const string P2ContentAdd = "Add";
    public const string PageSubtitle = "展示任务完成度与操作进度。";
    public const string PageDescription = "ProgressBar、StepsProgressBar、CircleProgress 和 DashboardProgress 覆盖线性、步骤、环形与仪表盘进度展示，并支持状态、尺寸、渐变和布局配置。";
    public const string ComponentCategory = "反馈";
    public const string ComponentStatusStable = ".NET 10";
    public const string ScenarioExamples = "示例";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "设计变量";
    public const string ApiColumnProperty = "属性";
    public const string ApiColumnDescription = "说明";
    public const string ApiColumnType = "类型";
    public const string ApiColumnDefault = "默认值";
    public const string ApiPropertyValue = "当前进度值。";
    public const string ApiPropertyMinimum = "进度范围的最小值。";
    public const string ApiPropertyMaximum = "进度范围的最大值。";
    public const string ApiPropertyIsIndeterminate = "在进度未知时展示不确定进度状态。";
    public const string ApiPropertyIsProgressInfoVisible = "控制进度文本或完成图标是否可见。";
    public const string ApiPropertyProgressTextFormat = "用于渲染进度文本的格式字符串。";
    public const string ApiPropertyStrokeBrush = "已完成进度指示器使用的画刷。";
    public const string ApiPropertyTrailColor = "剩余进度轨道使用的颜色。";
    public const string ApiPropertyStrokeLineCap = "线性、环形和仪表盘进度描边使用的线帽。";
    public const string ApiPropertySizeType = "进度指示器的预设尺寸。";
    public const string ApiPropertyStatus = "进度指示器的视觉状态。";
    public const string ApiPropertyIndicatorThickness = "进度指示器描边的自定义厚度。";
    public const string ApiPropertySuccessThreshold = "进度轨道内展示的成功分段阈值。";
    public const string ApiPropertySuccessStrokeBrush = "渲染成功分段时使用的画刷。";
    public const string ApiPropertyOrientation = "线性或步骤进度的方向。";
    public const string ApiPropertyPercentPosition = "控制进度文本显示在指示器内部还是外部。";
    public const string ApiPropertySteps = "StepsProgressBar 的步骤数量。";
    public const string ApiPropertyStepsStrokeBrush = "用于为单个步骤着色的画刷集合。";
    public const string ApiPropertyStepCount = "环形和仪表盘进度的分段步骤数量。";
    public const string ApiPropertyStepGap = "环形或仪表盘分段进度之间的间距。";
    public const string ApiPropertyDashboardGapPosition = "仪表盘进度的缺口位置。";
    public const string ApiPropertyGapDegree = "仪表盘进度的缺口角度。";
    public const string TokenColumnToken = "变量";
    public const string TokenColumnDescription = "说明";
    public const string TokenColumnScope = "范围";
    public const string TokenColumnStatus = "状态";
    public const string TokenNameDefaultColor = "默认已完成进度颜色。";
    public const string TokenNameRemainingColor = "剩余轨道颜色。";
    public const string TokenNameCircleTextColor = "环形进度内部文本颜色。";
    public const string TokenNameLineBorderRadius = "线性进度轨道圆角。";
    public const string TokenNameCircleMinimumTextFontSize = "紧凑环形进度内部文本最小字号。";
    public const string TokenNameCircleMinimumIconSize = "紧凑环形进度内部完成图标最小尺寸。";
    public const string TokenNameLineInfoIconSize = "线性进度完成或状态图标尺寸。";
    public const string TokenNameLineInfoIconSizeSM = "线性进度小号完成或状态图标尺寸。";
    public const string TokenNameLineExtraInfoMargin = "线性进度轨道与附加信息之间的间距。";
    public const string TokenNameLineProgressPadding = "线性进度轨道的内部间距。";
    public const string TokenScopeComponent = "组件";
    public const string TokenStatusStable = "稳定";

    protected override Type GetResourceKindType() => typeof(ProgressBarShowCaseLangResourceKind);
}
