using AtomUI.Theme.Language;

namespace AtomUIGallery.ShowCases.ProgressBar;

[LanguageProvider(LanguageCode.zh_TW, ProgressBarShowCase.LanguageId)]
internal partial class zh_TW
{
    public const string ScenarioBasic = "基礎";
    public const string ScenarioAdvanced = "進階";
    public const string ScenarioLayout = "佈局";
    public const string ProgressBarTitle = "進度條";
    public const string ProgressBarDescription = "標準進度條。";
    public const string CircularProgressBarTitle = "環形進度條";
    public const string CircularProgressBarDescription = "環形進度條。";
    public const string MiniSizeTitle = "迷你尺寸進度條";
    public const string MiniSizeDescription = "適合較窄區域。";
    public const string SmallerCircularProgressBarTitle = "更小的環形進度條";
    public const string SmallerCircularProgressBarDescription = "更小的環形進度條。";
    public const string DynamicTitle = "動態進度";
    public const string DynamicDescription = "動態進度條效果更好。";
    public const string CustomTextFormatTitle = "自定義文本格式";
    public const string CustomTextFormatDescription = "可以通過設置 format 屬性自定義文本。";
    public const string DashboardTitle = "儀錶盤";
    public const string DashboardDescription = "設置 type=dashboard 可以輕鬆獲得儀錶盤樣式進度條。修改 gapDegree 可設置缺口角度。";
    public const string SuccessSegmentTitle = "帶成功分段的進度條";
    public const string SuccessSegmentDescription = "展示多個不同狀態的進度片段。";
    public const string StrokeLinecapTitle = "線帽樣式";
    public const string StrokeLinecapDescription = "設置 strokeLinecap='butt' 可以將線帽從 round 改為 butt，更多信息請參考 stroke-linecap。";
    public const string CustomLineGradientTitle = "自定義線性漸變";
    public const string CustomLineGradientDescription = "漸變封裝；設置漸變時 circle 和 dashboard 會忽略 strokeLinecap。";
    public const string StepsTitle = "步驟進度條";
    public const string StepsDescription = "帶步驟的進度條。";
    public const string CircularStepsTitle = "帶步驟的環形進度條";
    public const string CircularStepsDescription = "支持步驟和顏色分段的環形進度條，默認間隔為 2px。";
    public const string PercentPositionTitle = "調整進度值位置";
    public const string PercentPositionDescription = "改變進度值的位置，可使用 percentPosition 將進度值調整到進度條內部、外部或底部。";
    public const string StepsPercentPositionTitle = "調整步驟進度值位置";
    public const string StepsPercentPositionDescription = "改變步驟進度值的位置，可使用 percentPosition 將進度值調整到進度條內部、外部或底部。";
    public const string VerticalLinearTitle = "垂直線性進度條";
    public const string VerticalLinearDescription = "普通線性進度條，支持指定附加區域的位置。";
    public const string VerticalStepsTitle = "垂直步驟進度條";
    public const string VerticalStepsDescription = "普通步驟進度條，支持指定附加區域的位置。";
    public const string ToggleDisabledStatusTitle = "切換禁用狀態";
    public const string ToggleDisabledStatusDescription = "進度條處於禁用狀態並使用禁用樣式。";
    public const string P2ContentSub = "Sub";
    public const string P2ContentAdd = "Add";
    public const string PageSubtitle = "展示任務完成度與操作進度。";
    public const string PageDescription = "ProgressBar、StepsProgressBar、CircleProgress 和 DashboardProgress 覆蓋線性、步驟、環形與儀錶盤進度展示，並支持狀態、尺寸、漸變和佈局配置。";
    public const string ComponentCategory = "反饋";
    public const string ComponentStatusStable = ".NET 10";
    public const string ScenarioExamples = "示例";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "設計變量";
    public const string ApiColumnProperty = "屬性";
    public const string ApiColumnDescription = "說明";
    public const string ApiColumnType = "類型";
    public const string ApiColumnDefault = "默認值";
    public const string ApiPropertyValue = "當前進度值。";
    public const string ApiPropertyMinimum = "進度範圍的最小值。";
    public const string ApiPropertyMaximum = "進度範圍的最大值。";
    public const string ApiPropertyIsIndeterminate = "在進度未知時展示不確定進度狀態。";
    public const string ApiPropertyIsProgressInfoVisible = "控制進度文本或完成圖標是否可見。";
    public const string ApiPropertyProgressTextFormat = "用於渲染進度文本的格式字符串。";
    public const string ApiPropertyStrokeBrush = "已完成進度指示器使用的畫刷。";
    public const string ApiPropertyTrailColor = "剩餘進度軌道使用的顏色。";
    public const string ApiPropertyStrokeLineCap = "線性、環形和儀錶盤進度描邊使用的線帽。";
    public const string ApiPropertySizeType = "進度指示器的預設尺寸。";
    public const string ApiPropertyStatus = "進度指示器的視覺狀態。";
    public const string ApiPropertyIndicatorThickness = "進度指示器描邊的自定義厚度。";
    public const string ApiPropertySuccessThreshold = "進度軌道內展示的成功分段閾值。";
    public const string ApiPropertySuccessStrokeBrush = "渲染成功分段時使用的畫刷。";
    public const string ApiPropertyOrientation = "線性或步驟進度的方向。";
    public const string ApiPropertyPercentPosition = "控制進度文本顯示在指示器內部還是外部。";
    public const string ApiPropertySteps = "StepsProgressBar 的步驟數量。";
    public const string ApiPropertyStepsStrokeBrush = "用於為單個步驟著色的畫刷集合。";
    public const string ApiPropertyStepCount = "環形和儀錶盤進度的分段步驟數量。";
    public const string ApiPropertyStepGap = "環形或儀錶盤分段進度之間的間距。";
    public const string ApiPropertyDashboardGapPosition = "儀錶盤進度的缺口位置。";
    public const string ApiPropertyGapDegree = "儀錶盤進度的缺口角度。";
    public const string TokenColumnToken = "變量";
    public const string TokenColumnDescription = "說明";
    public const string TokenColumnScope = "範圍";
    public const string TokenColumnStatus = "狀態";
    public const string TokenNameDefaultColor = "默認已完成進度顏色。";
    public const string TokenNameRemainingColor = "剩餘軌道顏色。";
    public const string TokenNameCircleTextColor = "環形進度內部文本顏色。";
    public const string TokenNameLineBorderRadius = "線性進度軌道圓角。";
    public const string TokenNameCircleMinimumTextFontSize = "緊湊環形進度內部文本最小字號。";
    public const string TokenNameCircleMinimumIconSize = "緊湊環形進度內部完成圖標最小尺寸。";
    public const string TokenNameLineInfoIconSize = "線性進度完成或狀態圖標尺寸。";
    public const string TokenNameLineInfoIconSizeSM = "線性進度小號完成或狀態圖標尺寸。";
    public const string TokenNameLineExtraInfoMargin = "線性進度軌道與附加信息之間的間距。";
    public const string TokenNameLineProgressPadding = "線性進度軌道的內部間距。";
    public const string TokenScopeComponent = "組件";
    public const string TokenStatusStable = "穩定";

}
