using AtomUI.Theme.Language;

namespace AtomUIGallery.ShowCases.TimePicker;

[LanguageProvider(LanguageCode.en_US, TimePickerShowCase.LanguageId)]
internal partial class en_US
{
    public const string BasicTitle = "Basic";
    public const string BasicDescription = "Click TimePicker, and then we could select or input a time in panel.";
    public const string BindingTitle = "SelectedTime binding";
    public const string BindingDescription = "SelectedTime synchronizes with the ViewModel without explicitly setting Binding Mode=TwoWay.";
    public const string PickerDisplayTimeTitle = "Popup display time";
    public const string PickerDisplayTimeDescription = "Open the popup panel at a specific display time without committing a selected value.";
    public const string HourFormatsTitle = "12-hour and 24-hour formats";
    public const string HourFormatsDescription = "TimePicker supports two time types, 12-hour and 24-hour.";
    public const string ThreeSizesTitle = "Three Sizes";
    public const string ThreeSizesDescription = "The input box comes in three sizes: large, middle and small. Large is used in the form, while the medium size is the default.";
    public const string DisabledTitle = "Disabled";
    public const string DisabledDescription = "A disabled state of the TimePicker.";
    public const string IntervalOptionTitle = "Interval option";
    public const string IntervalOptionDescription = "Show stepped options by MinuteIncrement SecondIncrement.";
    public const string TwelveHoursTitle = "12 hours";
    public const string TwelveHoursDescription = "TimePicker of 12 hours format, with default format h:mm:ss a.";
    public const string VariantsTitle = "Variants";
    public const string VariantsDescription = "Bordered-less style component.";
    public const string StatusTitle = "Status";
    public const string StatusDescription = "Add status to TimePicker with status, which could be error or warning.";
    public const string TimeRangePickerTitle = "Time Range Picker";
    public const string TimeRangePickerDescription = "Use time range picker with RangeTimePicker.";
    public const string P2PlaceholderTextSelectTime = "Select time";
    public const string P2PlaceholderTextOutline = "Outline";
    public const string P2PlaceholderTextFilled = "Filled";
    public const string P2PlaceholderTextBorderless = "Borderless";
    public const string P2PlaceholderTextStartTime = "Start time";
    public const string P2SecondaryPlaceholderTextEndTime = "End time";
    public const string P2TextExpandDirection = "Picker size:";
    public const string P2ContentLarge = "Large";
    public const string P2ContentDefault = "Default";
    public const string P2ContentSmall = "Small";
    public const string P2ContentCustom = "Custom";
    public const string P2TextSelectedTime = "Selected value:";
    public const string P2ContentSetNoon = "Set noon";
    public const string P2ContentClear = "Clear";
    public const string PageSubtitle = "Select a time or a time range from a popup time panel.";
    public const string PageDescription = "TimePicker supports 12-hour and 24-hour clocks, size variants, disabled states, stepped minute and second options, visual variants, validation status, and range selection.";
    public const string ComponentCategory = "Data Entry";
    public const string ComponentStatusStable = "Stable";
    public const string ScenarioExamples = "Examples";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "Design Token";
    public const string ApiColumnProperty = "Property";
    public const string ApiColumnDescription = "Description";
    public const string ApiColumnType = "Type";
    public const string ApiColumnDefault = "Default";
    public const string ApiPropertySelectedTime = "Selected time value for TimePicker. The property binds TwoWay by default and supports Avalonia data validation.";
    public const string ApiPropertyDefaultTime = "Initial time used by TimePicker reset behavior.";
    public const string ApiPropertyPickerDisplayTime = "Popup panel display anchor; does not commit a selected value.";
    public const string ApiPropertyIsNeedConfirm = "Requires the user to confirm the selected time before committing.";
    public const string ApiPropertyIsShowNow = "Shows the Now shortcut in the popup panel.";
    public const string ApiPropertyMinuteIncrement = "Minute step used when generating minute options.";
    public const string ApiPropertySecondIncrement = "Second step used when generating second options.";
    public const string ApiPropertyClockIdentifier = "Chooses 12-hour or 24-hour clock display.";
    public const string ApiPropertyRangeStartSelectedTime = "Selected start time for RangeTimePicker.";
    public const string ApiPropertyRangeEndSelectedTime = "Selected end time for RangeTimePicker.";
    public const string ApiPropertyRangeStartDefaultTime = "Initial start time for RangeTimePicker reset behavior.";
    public const string ApiPropertyRangeEndDefaultTime = "Initial end time for RangeTimePicker reset behavior.";
    public const string TokenColumnToken = "Token";
    public const string TokenColumnDescription = "Description";
    public const string TokenColumnScope = "Scope";
    public const string TokenColumnStatus = "Status";
    public const string TokenScopeComponent = "Component";
    public const string TokenStatusStable = "Stable";
    public const string TokenNameItemHeight = "Height of each selectable time item.";
    public const string TokenNameItemWidth = "Width of each hour, minute, and second column.";
    public const string TokenNamePeriodHostWidth = "Width of the AM/PM period selector column.";
    public const string TokenNameItemPadding = "Padding inside each selectable time item.";
    public const string TokenNameButtonsMargin = "Top margin of the popup action button area.";
    public const string TokenNameRangePickerArrowMargin = "Margin around the arrow between range inputs.";
    public const string TokenNameRangePickerIndicatorThickness = "Thickness of the range selection indicator.";
    public const string TokenNameHeaderMargin = "Margin below the time panel header.";

}
