using AtomUI.Localization;

namespace AtomUIGallery.Localization;

[LanguageCatalog(ContractVersion = 1)]
public enum TimePickerShowCaseLangResourceKind
{
    BasicTitle = 1,
    BasicDescription = 2,
    BindingTitle = 3,
    BindingDescription = 4,
    PickerDisplayTimeTitle = 5,
    PickerDisplayTimeDescription = 6,
    HourFormatsTitle = 7,
    HourFormatsDescription = 8,
    ThreeSizesTitle = 9,
    ThreeSizesDescription = 10,
    DisabledTitle = 11,
    DisabledDescription = 12,
    IntervalOptionTitle = 13,
    IntervalOptionDescription = 14,
    TwelveHoursTitle = 15,
    TwelveHoursDescription = 16,
    VariantsTitle = 17,
    VariantsDescription = 18,
    StatusTitle = 19,
    StatusDescription = 20,
    TimeRangePickerTitle = 21,
    TimeRangePickerDescription = 22,
    P2PlaceholderTextSelectTime = 23,
    P2PlaceholderTextOutline = 24,
    P2PlaceholderTextFilled = 25,
    P2PlaceholderTextBorderless = 26,
    P2PlaceholderTextStartTime = 27,
    P2SecondaryPlaceholderTextEndTime = 28,
    P2TextExpandDirection = 29,
    P2ContentLarge = 30,
    P2ContentDefault = 31,
    P2ContentSmall = 32,
    P2ContentCustom = 33,
    P2TextSelectedTime = 34,
    P2TextSelectedTimeRange = 35,
    P2ContentSetNoon = 36,
    P2ContentSetWorkHours = 37,
    P2ContentClear = 38,
    PageSubtitle = 39,
    PageDescription = 40,
    ComponentCategory = 41,
    ComponentStatusStable = 42,
    ScenarioExamples = 43
}
