<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(AtomUIDevelopTargetFramework)</TargetFramework>
        <Nullable>enable</Nullable>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>GeneratedFiles</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets/**/*.*"/>
        <AdditionalFiles Include="ShowCases/**/*.axaml" />
        <AdditionalFiles Include="ShowCases/**/*.axaml.cs" />
        <AdditionalFiles Include="ShowCases/**/ViewModels/**/*.cs" />
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
            <_Parameter1>AtomUIVersion</_Parameter1>
            <_Parameter2>$(AtomUIVersion)</_Parameter2>
        </AssemblyAttribute>
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="$(CompilerGeneratedFilesOutputPath)/**/*.cs"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/AtomUI.Toolkits.GalleryBase/AtomUI.Toolkits.GalleryBase.csproj"/>
        <ProjectReference Include="../../src/AtomUI.Desktop.Controls/AtomUI.Desktop.Controls.csproj"/>
        <ProjectReference Include="../../src/AtomUI.Desktop.Controls.ColorPicker/AtomUI.Desktop.Controls.ColorPicker.csproj"/>
        <ProjectReference Include="../../src/AtomUI.Desktop.Controls.DataGrid/AtomUI.Desktop.Controls.DataGrid.csproj"/>
        <ProjectReference Include="../../src/AtomUI.Desktop.Controls.Extras/AtomUI.Desktop.Controls.Extras.csproj"/>
        <ProjectReference Include="../../src/AtomUI.Generator/AtomUI.Generator.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"
                          PrivateAssets="all" />
        <ProjectReference Include="../../src/AtomUI.Toolkits.GalleryBase.Generator/AtomUI.Toolkits.GalleryBase.Generator.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"
                          PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="AvaloniaUI.DiagnosticsSupport"/>
        <PackageReference Include="AsyncImageLoader.Avalonia" />
    </ItemGroup>

</Project>
