using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.Splitter;

[LanguageProvider(LanguageCode.en_US, SplitterShowCase.LanguageId)]
internal partial class en_US
{
    public const string ScenarioExamples = "Examples";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "Design Token";
    public const string ComponentCategory = "Layout";
    public const string ComponentStatusStable = ".NET 10";
    public const string PageSubtitle = "Resize adjacent panes with draggable handles, constraints, collapse controls, and lazy updates.";
    public const string PageDescription = "Splitter divides a region into resizable panels. It supports horizontal and vertical layouts, nested splitters, fixed or constrained panels, collapsible handles, multiple panels, and lazy resize feedback.";
    public const string ApiColumnProperty = "Property";
    public const string ApiColumnDescription = "Description";
    public const string ApiColumnType = "Type";
    public const string ApiColumnDefault = "Default";
    public const string ApiPropertyOrientation = "Controls whether panels are split left-right or top-bottom.";
    public const string ApiPropertyIsLazy = "Defers size updates until the drag operation completes.";
    public const string ApiPropertyHandleSize = "Overrides the splitter handle hit area size.";
    public const string ApiPropertyLineThickness = "Controls the visible divider line and grip thickness without changing the handle hit area.";
    public const string ApiPropertyLineCornerRadius = "Controls the corner radius applied to the visible divider line and grip.";
    public const string ApiPropertyCollapsePreviousIcon = "Icon template used by the previous-panel collapse action.";
    public const string ApiPropertyCollapseNextIcon = "Icon template used by the next-panel collapse action.";
    public const string ApiPropertyChildren = "Panel controls hosted by the splitter.";
    public const string ApiPropertySize = "Attached current size for an individual panel.";
    public const string ApiPropertyDefaultSize = "Attached initial size for an individual panel.";
    public const string ApiPropertyMinSize = "Attached minimum size constraint for an individual panel.";
    public const string ApiPropertyMaxSize = "Attached maximum size constraint for an individual panel.";
    public const string ApiPropertyIsResizable = "Attached flag that controls whether a panel edge can be resized.";
    public const string ApiPropertyCollapsible = "Attached collapse behavior configuration for a panel.";
    public const string ApiPropertyIsCollapsed = "Attached current collapsed state for a panel.";
    public const string ApiPropertyResizeStarted = "Raised when a handle drag starts.";
    public const string ApiPropertyResizeDelta = "Raised while a handle is being dragged.";
    public const string ApiPropertyResizeCompleted = "Raised when a handle drag completes.";
    public const string TokenColumnToken = "Token";
    public const string TokenColumnDescription = "Description";
    public const string TokenColumnScope = "Scope";
    public const string TokenColumnStatus = "Status";
    public const string TokenNameSplitBarDraggableSize = "Draggable area size around the split bar.";
    public const string TokenNameSplitBarSize = "Visible split bar thickness.";
    public const string TokenNameSplitTriggerSize = "Drag trigger size used by the handle.";
    public const string TokenNameSplitBarCollapseOffset = "Offset used to position collapse controls.";
    public const string TokenNameSplitBarCollapseOffsetNegative = "Negative offset used to position collapse controls.";
    public const string TokenNameSplitBarCollapseCrossOffset = "Cross-axis offset for collapse controls.";
    public const string TokenNameSplitBarHandleSize = "Overall handle size used by split bars.";
    public const string TokenNameHandleLineColor = "Handle line color.";
    public const string TokenNameHandleLineHoverColor = "Handle line color while hovering.";
    public const string TokenNameHandleLineDragColor = "Handle line color while dragging.";
    public const string TokenNameHandleIconColor = "Collapse icon color.";
    public const string TokenNameHandleIconHoverColor = "Collapse icon color while hovering.";
    public const string TokenNameHandleIconPressedColor = "Collapse icon color while pressed.";
    public const string TokenNameHandleLineThickness = "Handle line thickness.";
    public const string TokenNameHandleIconSize = "Collapse icon size.";
    public const string TokenScopeComponent = "Component";
    public const string TokenStatusStable = "Stable";
    public const string BasicTitle = "Basic";
    public const string BasicDescription = "Initial sizes with min/max constraints.";
    public const string HorizontalTitle = "Horizontal";
    public const string HorizontalDescription = "Top-bottom splitter with collapsible icons.";
    public const string CompositeTitle = "Composite";
    public const string CompositeDescription = "Nested horizontal splitter inside a vertical layout.";
    public const string ResizableDisabledTitle = "Resizable Disabled";
    public const string ResizableDisabledDescription = "If either side disables resizable, dragging is blocked.";
    public const string ShowCollapsibleIconTitle = "ShowCollapsibleIcon";
    public const string ShowCollapsibleIconDescription = "Three panels with hover and always-visible collapsible icons.";
    public const string MultiPanelsTitle = "Multi Panels";
    public const string MultiPanelsDescription = "Multiple panels in vertical layout.";
    public const string LazyTitle = "Lazy";
    public const string LazyDescription = "Lazy rendering mode: sizes update on drag release.";
    public const string LineStyleTitle = "Line Style";
    public const string LineStyleDescription = "Customize the root frame, visible divider thickness, and line corner radius.";
    public const string P2TextFirst = "First";
    public const string P2TextSecond = "Second";
    public const string P2TextTop = "Top";
    public const string P2TextBottom = "Bottom";
    public const string P2TextLeft = "Left";
    public const string P2TextResizable = "Resizable";
    public const string P2TextNotResizable = "Not Resizable";
    public const string P2TextShowcollapsibleicon = "ShowCollapsibleIcon:";
    public const string P2ContentHover = "Hover";
    public const string P2ContentTrue = "True";
    public const string P2ContentFalse = "False";
    public const string P2TextThird = "Third";
    public const string P2TextA = "A";
    public const string P2TextB = "B";
    public const string P2TextC = "C";
    public const string P2TextD = "D";

}
