using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.Splitter;

[LanguageProvider(LanguageCode.zh_CN, SplitterShowCase.LanguageId)]
internal partial class zh_CN
{
    public const string ScenarioExamples = "示例";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "设计变量";
    public const string ComponentCategory = "布局";
    public const string ComponentStatusStable = ".NET 10";
    public const string PageSubtitle = "通过可拖拽把手、约束、折叠控制和延迟更新调整相邻面板尺寸。";
    public const string PageDescription = "Splitter 将区域拆分为可调整大小的面板，支持水平和垂直布局、嵌套分割器、固定或受约束面板、可折叠把手、多面板和延迟拖拽反馈。";
    public const string ApiColumnProperty = "属性";
    public const string ApiColumnDescription = "说明";
    public const string ApiColumnType = "类型";
    public const string ApiColumnDefault = "默认值";
    public const string ApiPropertyOrientation = "控制面板按左右或上下方向分割。";
    public const string ApiPropertyIsLazy = "将尺寸更新延迟到拖拽操作完成后。";
    public const string ApiPropertyHandleSize = "覆盖分割把手的命中区域尺寸。";
    public const string ApiPropertyCollapsePreviousIcon = "上一个面板折叠操作使用的图标模板。";
    public const string ApiPropertyCollapseNextIcon = "下一个面板折叠操作使用的图标模板。";
    public const string ApiPropertyChildren = "Splitter 承载的面板控件集合。";
    public const string ApiPropertySize = "单个面板的当前尺寸附加属性。";
    public const string ApiPropertyDefaultSize = "单个面板的初始尺寸附加属性。";
    public const string ApiPropertyMinSize = "单个面板的最小尺寸约束附加属性。";
    public const string ApiPropertyMaxSize = "单个面板的最大尺寸约束附加属性。";
    public const string ApiPropertyIsResizable = "控制面板边缘是否可调整尺寸的附加标记。";
    public const string ApiPropertyCollapsible = "面板折叠行为配置附加属性。";
    public const string ApiPropertyIsCollapsed = "面板当前折叠状态附加属性。";
    public const string ApiPropertyResizeStarted = "把手拖拽开始时触发。";
    public const string ApiPropertyResizeDelta = "把手拖拽过程中触发。";
    public const string ApiPropertyResizeCompleted = "把手拖拽完成时触发。";
    public const string TokenColumnToken = "变量";
    public const string TokenColumnDescription = "说明";
    public const string TokenColumnScope = "范围";
    public const string TokenColumnStatus = "状态";
    public const string TokenNameSplitBarDraggableSize = "分割条周围的可拖拽区域尺寸。";
    public const string TokenNameSplitBarSize = "可见分割条厚度。";
    public const string TokenNameSplitTriggerSize = "把手使用的拖拽触发尺寸。";
    public const string TokenNameSplitBarCollapseOffset = "折叠控件定位使用的偏移量。";
    public const string TokenNameSplitBarCollapseOffsetNegative = "折叠控件定位使用的负向偏移量。";
    public const string TokenNameSplitBarCollapseCrossOffset = "折叠控件的交叉轴偏移量。";
    public const string TokenNameSplitBarHandleSize = "分割条使用的整体把手尺寸。";
    public const string TokenNameHandleLineColor = "把手线条颜色。";
    public const string TokenNameHandleLineHoverColor = "悬浮时的把手线条颜色。";
    public const string TokenNameHandleLineDragColor = "拖拽时的把手线条颜色。";
    public const string TokenNameHandleIconColor = "折叠图标颜色。";
    public const string TokenNameHandleIconHoverColor = "悬浮时的折叠图标颜色。";
    public const string TokenNameHandleIconPressedColor = "按下时的折叠图标颜色。";
    public const string TokenNameHandleLineThickness = "把手线条厚度。";
    public const string TokenNameHandleIconSize = "折叠图标尺寸。";
    public const string TokenScopeComponent = "组件";
    public const string TokenStatusStable = "稳定";
    public const string BasicTitle = "基础用法";
    public const string BasicDescription = "带最小/最大约束的初始尺寸。";
    public const string HorizontalTitle = "水平分割";
    public const string HorizontalDescription = "带可折叠图标的上下分割器。";
    public const string CompositeTitle = "组合布局";
    public const string CompositeDescription = "在垂直布局中嵌套水平分割器。";
    public const string ResizableDisabledTitle = "禁用拖拽调整";
    public const string ResizableDisabledDescription = "任意一侧禁用 resizable 时，拖拽会被阻止。";
    public const string ShowCollapsibleIconTitle = "显示折叠图标";
    public const string ShowCollapsibleIconDescription = "三个面板展示 hover 和始终可见的折叠图标。";
    public const string MultiPanelsTitle = "多个面板";
    public const string MultiPanelsDescription = "垂直布局中的多个面板。";
    public const string LazyTitle = "延迟模式";
    public const string LazyDescription = "延迟渲染模式：拖拽释放后更新尺寸。";
    public const string P2TextFirst = "第一项";
    public const string P2TextSecond = "第二项";
    public const string P2TextTop = "顶部";
    public const string P2TextBottom = "底部";
    public const string P2TextLeft = "左侧";
    public const string P2TextResizable = "Resizable";
    public const string P2TextNotResizable = "Not Resizable";
    public const string P2TextShowcollapsibleicon = "ShowCollapsibleIcon:";
    public const string P2ContentHover = "悬停";
    public const string P2ContentTrue = "True";
    public const string P2ContentFalse = "False";
    public const string P2TextThird = "第三项";
    public const string P2TextA = "A";
    public const string P2TextB = "B";
    public const string P2TextC = "C";
    public const string P2TextD = "D";

}
