using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.Splitter;

[LanguageProvider(LanguageCode.zh_TW, SplitterShowCase.LanguageId)]
internal partial class zh_TW : LanguageProvider
{
    public const string ScenarioExamples = "示例";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "設計變數";
    public const string ComponentCategory = "佈局";
    public const string ComponentStatusStable = ".NET 10";
    public const string PageSubtitle = "通過可拖拽把手、約束、折疊控制和延遲更新調整相鄰面板尺寸。";
    public const string PageDescription = "Splitter 將區域拆分為可調整大小的面板，支持水平和垂直佈局、嵌套分割器、固定或受約束面板、可折疊把手、多面板和延遲拖拽反饋。";
    public const string ApiColumnProperty = "屬性";
    public const string ApiColumnDescription = "說明";
    public const string ApiColumnType = "類型";
    public const string ApiColumnDefault = "默認值";
    public const string ApiPropertyOrientation = "控制面板按左右或上下方向分割。";
    public const string ApiPropertyIsLazy = "將尺寸更新延遲到拖拽操作完成後。";
    public const string ApiPropertyHandleSize = "覆蓋分割把手的命中區域尺寸。";
    public const string ApiPropertyCollapsePreviousIcon = "上一個面板折疊操作使用的圖標模板。";
    public const string ApiPropertyCollapseNextIcon = "下一個面板折疊操作使用的圖標模板。";
    public const string ApiPropertyChildren = "Splitter 承載的面板控件集合。";
    public const string ApiPropertySize = "單個面板的當前尺寸附加屬性。";
    public const string ApiPropertyDefaultSize = "單個面板的初始尺寸附加屬性。";
    public const string ApiPropertyMinSize = "單個面板的最小尺寸約束附加屬性。";
    public const string ApiPropertyMaxSize = "單個面板的最大尺寸約束附加屬性。";
    public const string ApiPropertyIsResizable = "控制面板邊緣是否可調整尺寸的附加標記。";
    public const string ApiPropertyCollapsible = "面板折疊行為配置附加屬性。";
    public const string ApiPropertyIsCollapsed = "面板當前折疊狀態附加屬性。";
    public const string ApiPropertyResizeStarted = "把手拖拽開始時觸發。";
    public const string ApiPropertyResizeDelta = "把手拖拽過程中觸發。";
    public const string ApiPropertyResizeCompleted = "把手拖拽完成時觸發。";
    public const string TokenColumnToken = "變數";
    public const string TokenColumnDescription = "說明";
    public const string TokenColumnScope = "範圍";
    public const string TokenColumnStatus = "狀態";
    public const string TokenNameSplitBarDraggableSize = "分割條周圍的可拖拽區域尺寸。";
    public const string TokenNameSplitBarSize = "可見分割條厚度。";
    public const string TokenNameSplitTriggerSize = "把手使用的拖拽觸發尺寸。";
    public const string TokenNameSplitBarCollapseOffset = "折疊控件定位使用的偏移量。";
    public const string TokenNameSplitBarCollapseOffsetNegative = "折疊控件定位使用的負向偏移量。";
    public const string TokenNameSplitBarCollapseCrossOffset = "折疊控件的交叉軸偏移量。";
    public const string TokenNameSplitBarHandleSize = "分割條使用的整體把手尺寸。";
    public const string TokenNameHandleLineColor = "把手線條顏色。";
    public const string TokenNameHandleLineHoverColor = "懸浮時的把手線條顏色。";
    public const string TokenNameHandleLineDragColor = "拖拽時的把手線條顏色。";
    public const string TokenNameHandleIconColor = "折疊圖標顏色。";
    public const string TokenNameHandleIconHoverColor = "懸浮時的折疊圖標顏色。";
    public const string TokenNameHandleIconPressedColor = "按下時的折疊圖標顏色。";
    public const string TokenNameHandleLineThickness = "把手線條厚度。";
    public const string TokenNameHandleIconSize = "折疊圖標尺寸。";
    public const string TokenScopeComponent = "組件";
    public const string TokenStatusStable = "穩定";
    public const string BasicTitle = "基礎用法";
    public const string BasicDescription = "帶最小/最大約束的初始尺寸。";
    public const string HorizontalTitle = "水平分割";
    public const string HorizontalDescription = "帶可折疊圖標的上下分割器。";
    public const string CompositeTitle = "組合佈局";
    public const string CompositeDescription = "在垂直佈局中嵌套水平分割器。";
    public const string ResizableDisabledTitle = "禁用拖拽調整";
    public const string ResizableDisabledDescription = "任意一側禁用 resizable 時，拖拽會被阻止。";
    public const string ShowCollapsibleIconTitle = "顯示折疊圖標";
    public const string ShowCollapsibleIconDescription = "三個面板展示 hover 和始終可見的折疊圖標。";
    public const string MultiPanelsTitle = "多個面板";
    public const string MultiPanelsDescription = "垂直佈局中的多個面板。";
    public const string LazyTitle = "延遲模式";
    public const string LazyDescription = "延遲渲染模式：拖拽釋放後更新尺寸。";
    public const string P2TextFirst = "第一項";
    public const string P2TextSecond = "第二項";
    public const string P2TextTop = "頂部";
    public const string P2TextBottom = "底部";
    public const string P2TextLeft = "左側";
    public const string P2TextResizable = "Resizable";
    public const string P2TextNotResizable = "Not Resizable";
    public const string P2TextShowcollapsibleicon = "ShowCollapsibleIcon:";
    public const string P2ContentHover = "懸停";
    public const string P2ContentTrue = "True";
    public const string P2ContentFalse = "False";
    public const string P2TextThird = "第三項";
    public const string P2TextA = "A";
    public const string P2TextB = "B";
    public const string P2TextC = "C";
    public const string P2TextD = "D";

    protected override Type GetResourceKindType() => typeof(SplitterShowCaseLangResourceKind);
}
