using AtomUI.Localization;

namespace AtomUIGallery.Localization;

[LanguageCatalog(ContractVersion = 1)]
public enum TooltipShowCaseLangResourceKind
{
    BasicTitle = 1,
    BasicDescription = 2,
    PlacementTitle = 3,
    PlacementDescription = 4,
    ArrowTitle = 5,
    ArrowDescription = 6,
    ColorfulTooltipTitle = 7,
    ColorfulTooltipDescription = 8,
    P2TextTooltipWillShowOnMouseEnter = 9,
    P2ContentShow = 10,
    P2ContentHide = 11,
    P2ContentCenter = 12,
    P2TextPresets = 13,
    P2TextCustom = 14,
    P2ToolTipTipPromptText = 15,
    P2ContentLT = 16,
    P2ContentLeft = 17,
    P2ContentLB = 18,
    P2ContentTL = 19,
    P2ContentTop = 20,
    P2ContentTR = 21,
    P2ContentRT = 22,
    P2ContentRight = 23,
    P2ContentRB = 24,
    P2ContentBL = 25,
    P2ContentBottom = 26,
    P2ContentBR = 27,
    P2ContentBlue = 28,
    P2ContentRed = 29,
    P2ContentVolcano = 30,
    P2ContentOrange = 31,
    P2ContentGold = 32,
    P2ContentYellow = 33,
    P2ContentLime = 34,
    P2ContentGreen = 35,
    P2ContentCyan = 36,
    P2ContentGeekBlue = 37,
    P2ContentPurple = 38,
    P2ContentPink = 39,
    P2ContentMagenta = 40,
    P2ContentGrey = 41,
    ScenarioExamples = 42,
    PageSubtitle = 43,
    PageDescription = 44,
    ComponentCategory = 45,
    ComponentStatusStable = 46
}
