using AtomUI.Localization;

namespace AtomUIGallery.Localization;

[LanguageCatalog]
public enum TooltipShowCaseLangResourceKind
{
    BasicTitle,
    BasicDescription,
    PlacementTitle,
    PlacementDescription,
    ArrowTitle,
    ArrowDescription,
    ColorfulTooltipTitle,
    ColorfulTooltipDescription,
    P2TextTooltipWillShowOnMouseEnter,
    P2ContentShow,
    P2ContentHide,
    P2ContentCenter,
    P2TextPresets,
    P2TextCustom,
    P2ToolTipTipPromptText,
    P2ContentLT,
    P2ContentLeft,
    P2ContentLB,
    P2ContentTL,
    P2ContentTop,
    P2ContentTR,
    P2ContentRT,
    P2ContentRight,
    P2ContentRB,
    P2ContentBL,
    P2ContentBottom,
    P2ContentBR,
    P2ContentBlue,
    P2ContentRed,
    P2ContentVolcano,
    P2ContentOrange,
    P2ContentGold,
    P2ContentYellow,
    P2ContentLime,
    P2ContentGreen,
    P2ContentCyan,
    P2ContentGeekBlue,
    P2ContentPurple,
    P2ContentPink,
    P2ContentMagenta,
    P2ContentGrey,
    ScenarioExamples,
    PageSubtitle,
    PageDescription,
    ComponentCategory,
    ComponentStatusStable
}
