using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.Upload;

[LanguageProvider(LanguageCode.en_US, UploadShowCase.LanguageId)]
internal partial class en_US : LanguageProvider
{
    public const string UploadByClickingTitle = "Upload by clicking";
    public const string UploadByClickingDescription = "Classic mode. File selection dialog pops up when upload button is clicked.";
    public const string ScenarioBasic = "Basic";
    public const string ScenarioPictures = "Pictures";
    public const string ScenarioConstraints = "Constraints";
    public const string AvatarTitle = "Avatar";
    public const string AvatarDescription = "Click to upload user's avatar, and validate size and format of picture with beforeUpload.";
    public const string DefaultFilesTitle = "Default Files";
    public const string DefaultFilesDescription = "Use defaultFileList for uploaded files when page init.";
    public const string PicturesWallTitle = "Pictures Wall";
    public const string PicturesWallDescription = "After users upload picture, the thumbnail will be shown in list. The upload button will disappear when count meets limitation.";
    public const string PictureCircleTypeTitle = "Pictures with picture-circle type";
    public const string PictureCircleTypeDescription = "Alternative display for picture-card.";
    public const string DragAndDropTitle = "Drag and Drop";
    public const string DragAndDropDescription = "You can drag files to a specific area, to upload. Alternatively, you can also upload by selecting.";
    public const string PicturesWithListStyleTitle = "Pictures with list style";
    public const string PicturesWithListStyleDescription = "If uploaded file is a picture, the thumbnail can be shown.";
    public const string MaxCountTitle = "Max Count";
    public const string MaxCountDescription = "Limit files with maxCount. Will replace current one when maxCount is 1.";
    public const string UploadDirectoryTitle = "Upload directory";
    public const string UploadDirectoryDescription = "You can select and upload a whole directory.";
    public const string UploadPngOnlyTitle = "Upload png file only";
    public const string UploadPngOnlyDescription = "beforeUpload only prevent upload behavior when return false or reject promise, the prevented file would still show in file list. Here is the example you can keep prevented files out of list by return UPLOAD.LIST_IGNORE.";
    public const string P2ContentClickToUpload = "Click to Upload";
    public const string P2TextUpload = "Upload";
    public const string P2ContentUploadMaxN1 = "Upload (Max: 1)";
    public const string P2ContentUploadMaxN3 = "Upload (Max: 3)";
    public const string P2ContentUploadDirectory = "Upload Directory";
    public const string P2ContentUploadPngOnly = "Upload PNG only";
    public const string P2ErrorServer500 = "Server Error 500";
    public const string P2ErrorUpload = "Upload error!";
    public const string P2CancelJpgPngOnly = "You can only upload JPG/PNG file!";
    public const string P2CancelImageSize = "Image must be smaller than 2MB!";
    public const string P2CancelPngOnly = "You can only upload PNG file!";
    public const string P2UploadSuccessFormat = "{0} uploaded successfully!";
    public const string PageSubtitle = "Select, validate, preview, and upload files with list and picture presentations.";
    public const string PageDescription = "Upload supports button selection, avatar validation, default file lists, picture walls, drag-and-drop areas, max-count constraints, directory upload, and file type filtering.";
    public const string ComponentCategory = "Data Entry";
    public const string ComponentStatusStable = "Stable";
    public const string ScenarioExamples = "Examples";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "Design Token";
    public const string ApiColumnProperty = "Property";
    public const string ApiColumnDescription = "Description";
    public const string ApiColumnType = "Type";
    public const string ApiColumnDefault = "Default";
    public const string ApiPropertyAccepts = "Accepted MIME types, extensions, or storage provider filters.";
    public const string ApiPropertyExtraContext = "Additional context passed to the upload transport.";
    public const string ApiPropertyMaxCount = "Maximum number of files allowed in the task list.";
    public const string ApiPropertyIsUploadDirectoryEnabled = "Enables directory selection and uploads all top-level files.";
    public const string ApiPropertyListType = "Visual presentation of the upload task list.";
    public const string ApiPropertyIsMultipleEnabled = "Allows selecting multiple files or directories.";
    public const string ApiPropertyIsOpenFileDialogOnClick = "Opens the platform file dialog when the trigger is clicked.";
    public const string ApiPropertyIsShowUploadList = "Controls whether uploaded tasks are rendered in the list.";
    public const string ApiPropertyIsShowUploadTrigger = "Controls whether the upload trigger remains visible.";
    public const string ApiPropertyDefaultTaskList = "Initial task list rendered when the component is created.";
    public const string ApiPropertyMaxConcurrentTasks = "Maximum number of concurrent upload tasks.";
    public const string ApiPropertyUploadTransport = "Transport implementation used to upload files.";
    public const string TokenColumnToken = "Token";
    public const string TokenColumnDescription = "Description";
    public const string TokenColumnScope = "Scope";
    public const string TokenColumnStatus = "Status";
    public const string TokenScopeComponent = "Component";
    public const string TokenStatusStable = "Stable";
    public const string TokenNameActionsColor = "Color used by upload list action icons.";
    public const string TokenNamePictureCardSize = "Size of picture-card and picture-circle list items.";
    public const string TokenNameTextListItemMargin = "Margin around text list items.";
    public const string TokenNameTextListNamePadding = "Padding around text list file names.";
    public const string TokenNameUploadThumbnailSize = "Size of the file type thumbnail icon.";
    public const string TokenNameDragIconSize = "Size of the drag upload area icon.";
    public const string TokenNameDragIconMargin = "Margin around the drag upload area icon.";
    public const string TokenNameDragHeaderMargin = "Margin below the drag upload area header.";
    public const string TokenNamePictureListItemMargin = "Margin around picture list items.";
    public const string TokenNamePictureListPreviewerSize = "Preview thumbnail size for picture list items.";

    protected override Type GetResourceKindType() => typeof(UploadShowCaseLangResourceKind);
}
