using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.Upload;

[LanguageProvider(LanguageCode.zh_CN, UploadShowCase.LanguageId)]
internal partial class zh_CN : LanguageProvider
{
    public const string UploadByClickingTitle = "点击上传";
    public const string UploadByClickingDescription = "经典模式。点击上传按钮时弹出文件选择对话框。";
    public const string ScenarioBasic = "基础";
    public const string ScenarioPictures = "图片";
    public const string ScenarioConstraints = "限制";
    public const string AvatarTitle = "头像";
    public const string AvatarDescription = "点击上传用户头像，并通过 beforeUpload 校验图片大小和格式。";
    public const string DefaultFilesTitle = "默认文件";
    public const string DefaultFilesDescription = "页面初始化时使用 defaultFileList 设置已上传文件。";
    public const string PicturesWallTitle = "图片墙";
    public const string PicturesWallDescription = "用户上传图片后，缩略图会显示在列表中。当数量达到限制时，上传按钮会消失。";
    public const string PictureCircleTypeTitle = "圆形图片卡片";
    public const string PictureCircleTypeDescription = "picture-card 的另一种展示形式。";
    public const string DragAndDropTitle = "拖拽上传";
    public const string DragAndDropDescription = "可以将文件拖拽到指定区域上传，也可以通过选择文件上传。";
    public const string PicturesWithListStyleTitle = "列表样式图片";
    public const string PicturesWithListStyleDescription = "如果上传文件是图片，可以显示缩略图。";
    public const string MaxCountTitle = "最大数量";
    public const string MaxCountDescription = "使用 maxCount 限制文件数量。当 maxCount 为 1 时会替换当前文件。";
    public const string UploadDirectoryTitle = "上传目录";
    public const string UploadDirectoryDescription = "可以选择并上传整个目录。";
    public const string UploadPngOnlyTitle = "仅上传 PNG 文件";
    public const string UploadPngOnlyDescription = "beforeUpload 返回 false 或拒绝 promise 时只会阻止上传行为，被阻止的文件仍会显示在文件列表中。本示例通过返回 UPLOAD.LIST_IGNORE 将被阻止的文件排除在列表外。";
    public const string P2ContentClickToUpload = "点击上传";
    public const string P2TextUpload = "上传";
    public const string P2ContentUploadMaxN1 = "上传（最多：1）";
    public const string P2ContentUploadMaxN3 = "上传（最多：3）";
    public const string P2ContentUploadDirectory = "上传目录";
    public const string P2ContentUploadPngOnly = "仅上传 PNG";
    public const string P2ErrorServer500 = "服务器错误 500";
    public const string P2ErrorUpload = "上传失败！";
    public const string P2CancelJpgPngOnly = "只能上传 JPG/PNG 文件！";
    public const string P2CancelImageSize = "图片必须小于 2MB！";
    public const string P2CancelPngOnly = "只能上传 PNG 文件！";
    public const string P2UploadSuccessFormat = "{0} 上传成功！";
    public const string PageSubtitle = "选择、校验、预览并上传文件，支持列表和图片展示方式。";
    public const string PageDescription = "Upload 支持按钮选择、头像校验、默认文件列表、图片墙、拖拽区域、最大数量限制、目录上传和文件类型过滤。";
    public const string ComponentCategory = "数据录入";
    public const string ComponentStatusStable = "稳定";
    public const string ScenarioExamples = "示例";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "设计变量";
    public const string ApiColumnProperty = "属性";
    public const string ApiColumnDescription = "说明";
    public const string ApiColumnType = "类型";
    public const string ApiColumnDefault = "默认值";
    public const string ApiPropertyAccepts = "允许的 MIME 类型、扩展名或存储提供程序过滤条件。";
    public const string ApiPropertyExtraContext = "传递给上传传输实现的附加上下文。";
    public const string ApiPropertyMaxCount = "任务列表中允许的最大文件数量。";
    public const string ApiPropertyIsUploadDirectoryEnabled = "启用目录选择，并上传目录顶层文件。";
    public const string ApiPropertyListType = "上传任务列表的视觉展示方式。";
    public const string ApiPropertyIsMultipleEnabled = "允许选择多个文件或目录。";
    public const string ApiPropertyIsOpenFileDialogOnClick = "点击触发器时打开平台文件对话框。";
    public const string ApiPropertyIsShowUploadList = "控制是否渲染上传任务列表。";
    public const string ApiPropertyIsShowUploadTrigger = "控制上传触发器是否保持可见。";
    public const string ApiPropertyDefaultTaskList = "组件创建时渲染的初始任务列表。";
    public const string ApiPropertyMaxConcurrentTasks = "最大并发上传任务数量。";
    public const string ApiPropertyUploadTransport = "用于上传文件的传输实现。";
    public const string TokenColumnToken = "变量";
    public const string TokenColumnDescription = "说明";
    public const string TokenColumnScope = "作用域";
    public const string TokenColumnStatus = "状态";
    public const string TokenScopeComponent = "组件";
    public const string TokenStatusStable = "稳定";
    public const string TokenNameActionsColor = "上传列表操作图标使用的颜色。";
    public const string TokenNamePictureCardSize = "picture-card 和 picture-circle 列表项尺寸。";
    public const string TokenNameTextListItemMargin = "文本列表项的外边距。";
    public const string TokenNameTextListNamePadding = "文本列表文件名的内边距。";
    public const string TokenNameUploadThumbnailSize = "文件类型缩略图图标大小。";
    public const string TokenNameDragIconSize = "拖拽上传区域图标大小。";
    public const string TokenNameDragIconMargin = "拖拽上传区域图标外边距。";
    public const string TokenNameDragHeaderMargin = "拖拽上传区域标题下方外边距。";
    public const string TokenNamePictureListItemMargin = "图片列表项外边距。";
    public const string TokenNamePictureListPreviewerSize = "图片列表项预览缩略图尺寸。";

    protected override Type GetResourceKindType() => typeof(UploadShowCaseLangResourceKind);
}
