using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.Upload;

[LanguageProvider(LanguageCode.zh_TW, UploadShowCase.LanguageId)]
internal partial class zh_TW
{
    public const string UploadByClickingTitle = "點擊上傳";
    public const string UploadByClickingDescription = "經典模式。點擊上傳按鈕時彈出文件選擇對話框。";
    public const string ScenarioBasic = "基礎";
    public const string ScenarioPictures = "圖片";
    public const string ScenarioConstraints = "限制";
    public const string AvatarTitle = "頭像";
    public const string AvatarDescription = "點擊上傳用戶頭像，並通過 beforeUpload 校驗圖片大小和格式。";
    public const string DefaultFilesTitle = "默認文件";
    public const string DefaultFilesDescription = "頁面初始化時使用 defaultFileList 設置已上傳文件。";
    public const string PicturesWallTitle = "圖片牆";
    public const string PicturesWallDescription = "用戶上傳圖片後，縮略圖會顯示在列表中。當數量達到限制時，上傳按鈕會消失。";
    public const string PictureCircleTypeTitle = "圓形圖片卡片";
    public const string PictureCircleTypeDescription = "picture-card 的另一種展示形式。";
    public const string DragAndDropTitle = "拖拽上傳";
    public const string DragAndDropDescription = "可以將文件拖拽到指定區域上傳，也可以通過選擇文件上傳。";
    public const string PicturesWithListStyleTitle = "列表樣式圖片";
    public const string PicturesWithListStyleDescription = "如果上傳文件是圖片，可以顯示縮略圖。";
    public const string MaxCountTitle = "最大數量";
    public const string MaxCountDescription = "使用 maxCount 限制文件數量。當 maxCount 為 1 時會替換當前文件。";
    public const string UploadDirectoryTitle = "上傳目錄";
    public const string UploadDirectoryDescription = "可以選擇並上傳整個目錄。";
    public const string UploadPngOnlyTitle = "僅上傳 PNG 文件";
    public const string UploadPngOnlyDescription = "beforeUpload 返回 false 或拒絕 promise 時只會阻止上傳行為，被阻止的文件仍會顯示在文件列表中。本示例通過返回 UPLOAD.LIST_IGNORE 將被阻止的文件排除在列表外。";
    public const string P2ContentClickToUpload = "點擊上傳";
    public const string P2TextUpload = "上傳";
    public const string P2ContentUploadMaxN1 = "上傳（最多：1）";
    public const string P2ContentUploadMaxN3 = "上傳（最多：3）";
    public const string P2ContentUploadDirectory = "上傳目錄";
    public const string P2ContentUploadPngOnly = "僅上傳 PNG";
    public const string P2ErrorServer500 = "服務器錯誤 500";
    public const string P2ErrorUpload = "上傳失敗！";
    public const string P2CancelJpgPngOnly = "只能上傳 JPG/PNG 文件！";
    public const string P2CancelImageSize = "圖片必須小於 2MB！";
    public const string P2CancelPngOnly = "只能上傳 PNG 文件！";
    public const string P2UploadSuccessFormat = "{0} 上傳成功！";
    public const string PageSubtitle = "選擇、校驗、預覽並上傳文件，支援列表和圖片展示方式。";
    public const string PageDescription = "Upload 支援按鈕選擇、頭像校驗、默認文件列表、圖片牆、拖拽區域、最大數量限制、目錄上傳和文件類型過濾。";
    public const string ComponentCategory = "資料錄入";
    public const string ComponentStatusStable = "穩定";
    public const string ScenarioExamples = "示例";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "設計變數";
    public const string ApiColumnProperty = "屬性";
    public const string ApiColumnDescription = "說明";
    public const string ApiColumnType = "類型";
    public const string ApiColumnDefault = "默認值";
    public const string ApiPropertyAccepts = "允許的 MIME 類型、擴展名或存儲提供程序過濾條件。";
    public const string ApiPropertyExtraContext = "傳遞給上傳傳輸實現的附加上下文。";
    public const string ApiPropertyMaxCount = "任務列表中允許的最大文件數量。";
    public const string ApiPropertyIsUploadDirectoryEnabled = "啟用目錄選擇，並上傳目錄頂層文件。";
    public const string ApiPropertyListType = "上傳任務列表的視覺展示方式。";
    public const string ApiPropertyIsMultipleEnabled = "允許選擇多個文件或目錄。";
    public const string ApiPropertyIsOpenFileDialogOnClick = "點擊觸發器時打開平台文件對話框。";
    public const string ApiPropertyIsShowUploadList = "控制是否渲染上傳任務列表。";
    public const string ApiPropertyIsShowUploadTrigger = "控制上傳觸發器是否保持可見。";
    public const string ApiPropertyDefaultTaskList = "組件創建時渲染的初始任務列表。";
    public const string ApiPropertyMaxConcurrentTasks = "最大並發上傳任務數量。";
    public const string ApiPropertyUploadTransport = "用於上傳文件的傳輸實現。";
    public const string TokenColumnToken = "變數";
    public const string TokenColumnDescription = "說明";
    public const string TokenColumnScope = "作用域";
    public const string TokenColumnStatus = "狀態";
    public const string TokenScopeComponent = "組件";
    public const string TokenStatusStable = "穩定";
    public const string TokenNameActionsColor = "上傳列表操作圖標使用的顏色。";
    public const string TokenNamePictureCardSize = "picture-card 和 picture-circle 列表項尺寸。";
    public const string TokenNameTextListItemMargin = "文本列表項的外邊距。";
    public const string TokenNameTextListNamePadding = "文本列表文件名的內邊距。";
    public const string TokenNameUploadThumbnailSize = "文件類型縮略圖圖標大小。";
    public const string TokenNameDragIconSize = "拖拽上傳區域圖標大小。";
    public const string TokenNameDragIconMargin = "拖拽上傳區域圖標外邊距。";
    public const string TokenNameDragHeaderMargin = "拖拽上傳區域標題下方外邊距。";
    public const string TokenNamePictureListItemMargin = "圖片列表項外邊距。";
    public const string TokenNamePictureListPreviewerSize = "圖片列表項預覽縮略圖尺寸。";

}
