using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.Tour;

[LanguageProvider(LanguageCode.en_US, TourShowCase.LanguageId)]
internal partial class en_US
{
    public const string PageSubtitle = "Guide users through important workflows with contextual overlays.";
    public const string PageDescription = "Tour combines step targets, masks, placement, indicators, and custom actions to build lightweight product guidance without leaving the current page.";
    public const string ComponentCategory = "Data Display";
    public const string ComponentStatusStable = ".NET 10";
    public const string ScenarioExamples = "Examples";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "Design Token";
    public const string BasicTitle = "Basic";
    public const string BasicDescription = "The most basic usage.";
    public const string NonModalTitle = "Non-modal";
    public const string NonModalDescription = "Use mask={false} to make Tour non-modal. At the meantime it is recommended to use with type=primary to emphasize the guide itself.";
    public const string PlacementTitle = "Placement";
    public const string PlacementDescription = "Change the placement of the guide relative to the target, there are 12 placements available. When target={null} the guide will show in the center.";
    public const string CustomIndicatorTitle = "Custom indicator";
    public const string CustomIndicatorDescription = "Custom indicator.";
    public const string CustomMaskTitle = "Custom mask";
    public const string CustomMaskDescription = "Custom mask color.";
    public const string CustomActionTitle = "Custom action";
    public const string CustomActionDescription = "Custom action.";
    public const string CustomHighlightedAreaStyleTitle = "Custom highlighted area style";
    public const string CustomHighlightedAreaStyleDescription = "Using gap to control the radius of highlight area and the offset between highlight area and the element.";
    public const string P2TitleUploadFile = "Upload File";
    public const string P2DescriptionPutYourFilesHere = "Put your files here.";
    public const string P2TitleSave = "Save";
    public const string P2DescriptionSaveYourChanges = "Save your changes.";
    public const string P2TitleOtherActions = "Other Actions";
    public const string P2DescriptionClickToSeeOtherActions = "Click to see other actions.";
    public const string P2TitleCenter = "Center";
    public const string P2DescriptionDisplayedInTheCenterOfScreen = "Displayed in the center of screen.";
    public const string P2TitleRight = "Right";
    public const string P2DescriptionOnTheRightOfTarget = "On the right of target.";
    public const string P2TitleTop = "Top";
    public const string P2DescriptionOnTheTopOfTarget = "On the top of target.";
    public const string P2TitleLeft = "Left";
    public const string P2DescriptionOnTheLeftOfTarget = "On the left of target.";
    public const string P2ContentBeginTour = "Begin Tour";
    public const string P2ContentUpload = "Upload";
    public const string P2ContentSave = "Save";
    public const string P2ContentBeginNonModalTour = "Begin non-modal Tour";
    public const string P2ContentSkip = "Skip";
    public const string P2TextRadius = "Radius:";
    public const string P2TextHorizontalOffset = "Horizontal offset:";
    public const string P2TextVerticalOffset = "Vertical offset:";
    public const string ApiColumnProperty = "Property";
    public const string ApiColumnDescription = "Description";
    public const string ApiColumnType = "Type";
    public const string ApiColumnDefault = "Default";
    public const string ApiPropertyStepsSource = "Provides step data when steps are generated from a collection.";
    public const string ApiPropertyItemTemplate = "Defines the template used to render each item from StepsSource.";
    public const string ApiPropertyIsOpen = "Controls whether the tour popup is open. Two-way binding is enabled by default.";
    public const string ApiPropertyCurrentIndex = "Gets or sets the current step index. Two-way binding is enabled by default.";
    public const string ApiPropertyStepCount = "Gets the total number of steps currently available.";
    public const string ApiPropertyPlacement = "Sets the default popup placement relative to the target.";
    public const string ApiPropertyIsShowMask = "Controls whether the page mask is shown.";
    public const string ApiPropertyMaskColor = "Sets the mask brush used by the tour or an individual step.";
    public const string ApiPropertyStyleType = "Switches the tour visual style between default and primary.";
    public const string ApiPropertyIsArrowVisible = "Controls whether the popup arrow is visible.";
    public const string ApiPropertyIsPointAtCenter = "Places the arrow at the target center when enabled.";
    public const string ApiPropertyCloseIcon = "Customizes the close icon template.";
    public const string ApiPropertyIndicator = "Replaces the default step indicator.";
    public const string ApiPropertyIsDisabledInteraction = "Prevents interaction with the highlighted target area.";
    public const string ApiPropertyIsScrollIntoView = "Scrolls the target into view when the step changes.";
    public const string ApiPropertyGapOffsetX = "Sets the horizontal offset around the highlighted target.";
    public const string ApiPropertyGapOffsetY = "Sets the vertical offset around the highlighted target.";
    public const string ApiPropertyGapRadius = "Sets the corner radius of the highlighted target area.";
    public const string ApiPropertyStepTarget = "Sets the control highlighted by this step.";
    public const string ApiPropertyStepTitle = "Sets the step title content.";
    public const string ApiPropertyStepDescription = "Sets the step body content.";
    public const string ApiPropertyStepCover = "Sets optional cover content above the step body.";
    public const string TokenColumnToken = "Token";
    public const string TokenColumnDescription = "Description";
    public const string TokenColumnScope = "Scope";
    public const string TokenColumnStatus = "Status";
    public const string TokenNameCloseBtnSize = "Close button size.";
    public const string TokenNamePrimaryPrevBtnBg = "Background color for the previous button in primary mode.";
    public const string TokenNamePrimaryNextBtnHoverBg = "Hover background color for the next button in primary mode.";
    public const string TokenNameTourViewMinWidth = "Minimum width of the tour popup view.";
    public const string TokenNameTourViewMinHeight = "Minimum height of the tour popup view.";
    public const string TokenNameHeaderColor = "Text color of the step title.";
    public const string TokenScopeComponent = "Component";
    public const string TokenStatusStable = "Stable";

}
