using AtomUI.Theme.Language;

namespace AtomUIGallery.ShowCases.Tour;

[LanguageProvider(LanguageCode.zh_CN, TourShowCase.LanguageId)]
internal partial class zh_CN
{
    public const string PageSubtitle = "通过上下文浮层引导用户完成关键流程。";
    public const string PageDescription = "Tour 组合步骤目标、遮罩、弹出位置、指示器和自定义操作，在不离开当前页面的情况下构建轻量级产品引导。";
    public const string ComponentCategory = "数据展示";
    public const string ComponentStatusStable = ".NET 10";
    public const string ScenarioExamples = "示例";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "设计变量";
    public const string BasicTitle = "基础用法";
    public const string BasicDescription = "最基础的用法。";
    public const string NonModalTitle = "非模态";
    public const string NonModalDescription = "使用 mask={false} 可以让 Tour 变为非模态。同时建议配合 type=primary 使用，以突出引导本身。";
    public const string PlacementTitle = "位置";
    public const string PlacementDescription = "改变引导相对于目标的位置，提供 12 种位置。当 target={null} 时，引导会显示在中心。";
    public const string CustomIndicatorTitle = "自定义指示器";
    public const string CustomIndicatorDescription = "自定义指示器。";
    public const string CustomMaskTitle = "自定义遮罩";
    public const string CustomMaskDescription = "自定义遮罩颜色。";
    public const string CustomActionTitle = "自定义操作";
    public const string CustomActionDescription = "自定义操作。";
    public const string CustomHighlightedAreaStyleTitle = "自定义高亮区域样式";
    public const string CustomHighlightedAreaStyleDescription = "使用 gap 控制高亮区域圆角半径，以及高亮区域和元素之间的偏移。";
    public const string P2TitleUploadFile = "上传文件";
    public const string P2DescriptionPutYourFilesHere = "在这里放置你的文件。";
    public const string P2TitleSave = "保存";
    public const string P2DescriptionSaveYourChanges = "保存你的更改。";
    public const string P2TitleOtherActions = "其他操作";
    public const string P2DescriptionClickToSeeOtherActions = "点击查看其他操作。";
    public const string P2TitleCenter = "居中";
    public const string P2DescriptionDisplayedInTheCenterOfScreen = "显示在屏幕中央。";
    public const string P2TitleRight = "右侧";
    public const string P2DescriptionOnTheRightOfTarget = "位于目标右侧。";
    public const string P2TitleTop = "顶部";
    public const string P2DescriptionOnTheTopOfTarget = "位于目标上方。";
    public const string P2TitleLeft = "左侧";
    public const string P2DescriptionOnTheLeftOfTarget = "位于目标左侧。";
    public const string P2ContentBeginTour = "开始引导";
    public const string P2ContentUpload = "上传";
    public const string P2ContentSave = "保存";
    public const string P2ContentBeginNonModalTour = "开始非模态引导";
    public const string P2ContentSkip = "跳过";
    public const string P2TextRadius = "圆角半径：";
    public const string P2TextHorizontalOffset = "水平偏移：";
    public const string P2TextVerticalOffset = "垂直偏移：";
    public const string ApiColumnProperty = "属性";
    public const string ApiColumnDescription = "说明";
    public const string ApiColumnType = "类型";
    public const string ApiColumnDefault = "默认值";
    public const string ApiPropertyStepsSource = "通过集合数据生成引导步骤。";
    public const string ApiPropertyItemTemplate = "定义 StepsSource 中每一项的渲染模板。";
    public const string ApiPropertyIsOpen = "控制引导浮层是否打开，默认支持双向绑定。";
    public const string ApiPropertyCurrentIndex = "获取或设置当前步骤索引，默认支持双向绑定。";
    public const string ApiPropertyStepCount = "获取当前可用步骤总数。";
    public const string ApiPropertyPlacement = "设置相对目标控件的默认弹出位置。";
    public const string ApiPropertyIsShowMask = "控制是否显示页面遮罩。";
    public const string ApiPropertyMaskColor = "设置 Tour 或单个步骤使用的遮罩画刷。";
    public const string ApiPropertyStyleType = "在默认和 Primary 两种视觉样式之间切换。";
    public const string ApiPropertyIsArrowVisible = "控制弹出层箭头是否可见。";
    public const string ApiPropertyIsPointAtCenter = "启用后箭头指向目标控件中心。";
    public const string ApiPropertyCloseIcon = "自定义关闭图标模板。";
    public const string ApiPropertyIndicator = "替换默认步骤指示器。";
    public const string ApiPropertyIsDisabledInteraction = "禁用与高亮目标区域的交互。";
    public const string ApiPropertyIsScrollIntoView = "步骤切换时将目标滚动到可视区域。";
    public const string ApiPropertyGapOffsetX = "设置高亮区域的水平外扩偏移。";
    public const string ApiPropertyGapOffsetY = "设置高亮区域的垂直外扩偏移。";
    public const string ApiPropertyGapRadius = "设置高亮目标区域的圆角半径。";
    public const string ApiPropertyStepTarget = "设置当前步骤高亮的控件。";
    public const string ApiPropertyStepTitle = "设置步骤标题内容。";
    public const string ApiPropertyStepDescription = "设置步骤正文内容。";
    public const string ApiPropertyStepCover = "设置展示在步骤正文上方的可选封面内容。";
    public const string TokenColumnToken = "变量";
    public const string TokenColumnDescription = "说明";
    public const string TokenColumnScope = "范围";
    public const string TokenColumnStatus = "状态";
    public const string TokenNameCloseBtnSize = "关闭按钮尺寸。";
    public const string TokenNamePrimaryPrevBtnBg = "Primary 模式下上一步按钮的背景色。";
    public const string TokenNamePrimaryNextBtnHoverBg = "Primary 模式下下一步按钮的悬浮背景色。";
    public const string TokenNameTourViewMinWidth = "Tour 弹出视图的最小宽度。";
    public const string TokenNameTourViewMinHeight = "Tour 弹出视图的最小高度。";
    public const string TokenNameHeaderColor = "步骤标题文本颜色。";
    public const string TokenScopeComponent = "组件";
    public const string TokenStatusStable = "稳定";

}
