using AtomUI.Generator.Diagnostics;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace AtomUI.Generator.ResourceHost;

[Generator]
public sealed class ScopedResourceHostGenerator : IIncrementalGenerator
{
    private const string AvaloniaObjectMetadataName = "Avalonia.AvaloniaObject";
    private const string ControlMetadataName = "Avalonia.Controls.Control";
    private const string StyledElementMetadataName = "Avalonia.Controls.StyledElement";
    private const string VisualMetadataName = "Avalonia.Visual";
    private const string ResourceHostMetadataName = "Avalonia.Controls.IResourceHost";
    private const string ThemeVariantHostMetadataName = "Avalonia.Styling.IThemeVariantHost";

    public void Initialize(IncrementalGeneratorInitializationContext initContext)
    {
        initContext.RegisterPostInitializationOutput(static context =>
        {
            context.AddSource("GenerateScopedResourceHostAttribute.g.cs", GeneratedSourceText.From("""
                // <auto-generated />
                #nullable enable

                namespace AtomUI.Controls
                {
                    [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false)]
                    internal sealed class GenerateScopedResourceHostAttribute : global::System.Attribute
                    {
                    }
                }
                """));
        });

        var targets = initContext.SyntaxProvider.ForAttributeWithMetadataName(
                TargetMarkConstants.GenerateScopedResourceHostAttribute,
                static (node, token) => node is ClassDeclarationSyntax,
                static (context, token) => CreateTypeInfo(context))
            .Collect();

        initContext.RegisterImplementationSourceOutput(targets, static (context, items) =>
        {
            foreach (var item in items)
            {
                if (item.Diagnostic is not null)
                {
                    context.ReportDiagnostic(item.Diagnostic);
                    continue;
                }

                if (item.TypeInfo is not null)
                {
                    var writer = new ScopedResourceHostSourceWriter(context, item.TypeInfo);
                    writer.Write();
                }
            }
        });
    }

    private static ScopedResourceHostGenerationItem CreateTypeInfo(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
        {
            return ScopedResourceHostGenerationItem.Empty;
        }

        var location = typeSymbol.Locations.FirstOrDefault();
        if (typeSymbol.TypeKind != TypeKind.Class ||
            typeSymbol.IsGenericType ||
            typeSymbol.ContainingType is not null ||
            !IsPartial(typeSymbol))
        {
            return CreateDiagnostic(
                AtomUIDiagnosticDescriptors.ScopedResourceHostInvalidClassShape,
                typeSymbol,
                location);
        }

        if (!IsOrInheritsFrom(typeSymbol, AvaloniaObjectMetadataName))
        {
            return CreateDiagnostic(
                AtomUIDiagnosticDescriptors.ScopedResourceHostRequiresAvaloniaObject,
                typeSymbol,
                location);
        }

        if (IsOrInheritsFrom(typeSymbol, ControlMetadataName) ||
            IsOrInheritsFrom(typeSymbol, StyledElementMetadataName) ||
            IsOrInheritsFrom(typeSymbol, VisualMetadataName))
        {
            return CreateDiagnostic(
                AtomUIDiagnosticDescriptors.ScopedResourceHostRejectsVisualTarget,
                typeSymbol,
                location);
        }

        if (ImplementsInterface(typeSymbol, ResourceHostMetadataName) ||
            ImplementsInterface(typeSymbol, ThemeVariantHostMetadataName))
        {
            return CreateDiagnostic(
                AtomUIDiagnosticDescriptors.ScopedResourceHostRejectsExistingResourceHost,
                typeSymbol,
                location);
        }

        return new ScopedResourceHostGenerationItem(
            new ScopedResourceHostTypeInfo(
                typeSymbol.ContainingNamespace.IsGlobalNamespace
                    ? null
                    : typeSymbol.ContainingNamespace.ToDisplayString(),
                GetAccessibility(typeSymbol),
                typeSymbol.Name),
            null);
    }

    private static ScopedResourceHostGenerationItem CreateDiagnostic(DiagnosticDescriptor descriptor,
                                                                     INamedTypeSymbol typeSymbol,
                                                                     Location? location)
    {
        return new ScopedResourceHostGenerationItem(
            null,
            Diagnostic.Create(descriptor,
                location,
                typeSymbol.ToDisplayString()));
    }

    private static bool IsPartial(INamedTypeSymbol typeSymbol)
    {
        foreach (var syntaxReference in typeSymbol.DeclaringSyntaxReferences)
        {
            if (syntaxReference.GetSyntax() is ClassDeclarationSyntax classDeclaration &&
                classDeclaration.Modifiers.Any(SyntaxKind.PartialKeyword))
            {
                return true;
            }
        }

        return false;
    }

    private static bool IsOrInheritsFrom(INamedTypeSymbol typeSymbol, string metadataName)
    {
        for (INamedTypeSymbol? current = typeSymbol; current is not null; current = current.BaseType)
        {
            if (current.ToDisplayString() == metadataName)
            {
                return true;
            }
        }

        return false;
    }

    private static bool ImplementsInterface(INamedTypeSymbol typeSymbol, string metadataName)
    {
        return typeSymbol.AllInterfaces.Any(interfaceSymbol => interfaceSymbol.ToDisplayString() == metadataName);
    }

    private static string GetAccessibility(INamedTypeSymbol typeSymbol)
    {
        return typeSymbol.DeclaredAccessibility switch
        {
            Accessibility.Public => "public",
            _ => "internal"
        };
    }
}

internal readonly struct ScopedResourceHostGenerationItem
{
    public ScopedResourceHostGenerationItem(ScopedResourceHostTypeInfo? typeInfo, Diagnostic? diagnostic)
    {
        TypeInfo   = typeInfo;
        Diagnostic = diagnostic;
    }

    public static ScopedResourceHostGenerationItem Empty { get; } = new(null, null);

    public ScopedResourceHostTypeInfo? TypeInfo { get; }

    public Diagnostic? Diagnostic { get; }
}
