using System.Text;
using Microsoft.CodeAnalysis;

namespace AtomUI.Generator.ResourceHost;

internal sealed class ScopedResourceHostSourceWriter
{
    private readonly SourceProductionContext _context;
    private readonly ScopedResourceHostTypeInfo _typeInfo;

    public ScopedResourceHostSourceWriter(SourceProductionContext context, ScopedResourceHostTypeInfo typeInfo)
    {
        _context  = context;
        _typeInfo = typeInfo;
    }

    public void Write()
    {
        _context.AddSource($"{_typeInfo.TypeName}.ScopedResourceHost.g.cs", GeneratedSourceText.From(BuildSource()));
    }

    private string BuildSource()
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine();

        if (_typeInfo.Namespace is not null)
        {
            source.AppendLine($"namespace {_typeInfo.Namespace}");
            source.AppendLine("{");
        }

        AppendClass(source);

        if (_typeInfo.Namespace is not null)
        {
            source.AppendLine("}");
        }

        return source.ToString();
    }

    private void AppendClass(StringBuilder source)
    {
        var indent = _typeInfo.Namespace is null ? string.Empty : "    ";
        source.Append(indent);
        source.Append(_typeInfo.Accessibility);
        source.Append(" partial class ");
        source.Append(_typeInfo.TypeName);
        source.AppendLine(" : global::Avalonia.Controls.IResourceHost, global::Avalonia.Styling.IThemeVariantHost");
        source.Append(indent);
        source.AppendLine("{");

        AppendMembers(source, indent + "    ");

        source.Append(indent);
        source.AppendLine("}");
    }

    private void AppendMembers(StringBuilder source, string indent)
    {
        source.Append(indent);
        source.AppendLine("private global::Avalonia.Controls.IResourceHost? __atomuiResourceHost;");
        source.Append(indent);
        source.AppendLine("private int __atomuiResourceHostAttachmentCount;");
        source.AppendLine();
        source.Append(indent);
        source.AppendLine("public event global::System.EventHandler<global::Avalonia.Controls.ResourcesChangedEventArgs>? ResourcesChanged;");
        source.Append(indent);
        source.AppendLine("public event global::System.EventHandler? ActualThemeVariantChanged;");
        source.AppendLine();
        source.Append(indent);
        source.AppendLine("public bool HasResources => true;");
        source.AppendLine();
        source.Append(indent);
        source.AppendLine("public global::Avalonia.Styling.ThemeVariant ActualThemeVariant =>");
        source.Append(indent);
        source.AppendLine("    (__atomuiResourceHost as global::Avalonia.Styling.IThemeVariantHost)?.ActualThemeVariant ??");
        source.Append(indent);
        source.AppendLine("    global::Avalonia.Application.Current?.ActualThemeVariant ??");
        source.Append(indent);
        source.AppendLine("    global::Avalonia.Styling.ThemeVariant.Default;");
        source.AppendLine();
        AppendTryGetResource(source, indent);
        AppendNotifyHostedResourcesChanged(source, indent);
        AppendAttachResourceHost(source, indent);
        AppendDetachResourceHost(source, indent);
        AppendDetachCurrentResourceHost(source, indent);
        AppendRegisterResourceHost(source, indent);
        AppendEventHandlers(source, indent);
        AppendAttachmentDisposable(source, indent);
    }

    private void AppendTryGetResource(StringBuilder source, string indent)
    {
        source.Append(indent);
        source.AppendLine("public bool TryGetResource(object key, global::Avalonia.Styling.ThemeVariant? theme, out object? value)");
        source.Append(indent);
        source.AppendLine("{");
        source.Append(indent);
        source.AppendLine("    if (__atomuiResourceHost is not null &&");
        source.Append(indent);
        source.AppendLine("        global::Avalonia.Controls.ResourceNodeExtensions.TryFindResource(__atomuiResourceHost, key, theme, out value))");
        source.Append(indent);
        source.AppendLine("    {");
        source.Append(indent);
        source.AppendLine("        return true;");
        source.Append(indent);
        source.AppendLine("    }");
        source.AppendLine();
        source.Append(indent);
        source.AppendLine("    if (global::Avalonia.Application.Current?.TryGetResource(key, theme, out value) == true)");
        source.Append(indent);
        source.AppendLine("    {");
        source.Append(indent);
        source.AppendLine("        return true;");
        source.Append(indent);
        source.AppendLine("    }");
        source.AppendLine();
        source.Append(indent);
        source.AppendLine("    value = null;");
        source.Append(indent);
        source.AppendLine("    return false;");
        source.Append(indent);
        source.AppendLine("}");
        source.AppendLine();
    }

    private static void AppendNotifyHostedResourcesChanged(StringBuilder source, string indent)
    {
        source.Append(indent);
        source.AppendLine("void global::Avalonia.Controls.IResourceHost.NotifyHostedResourcesChanged(global::Avalonia.Controls.ResourcesChangedEventArgs e)");
        source.Append(indent);
        source.AppendLine("{");
        source.Append(indent);
        source.AppendLine("    ResourcesChanged?.Invoke(this, e);");
        source.Append(indent);
        source.AppendLine("}");
        source.AppendLine();
    }

    private static void AppendAttachResourceHost(StringBuilder source, string indent)
    {
        source.Append(indent);
        source.AppendLine("internal global::System.IDisposable AttachResourceHost(global::Avalonia.Controls.IResourceHost resourceHost)");
        source.Append(indent);
        source.AppendLine("{");
        source.Append(indent);
        source.AppendLine("    if (global::System.Object.ReferenceEquals(__atomuiResourceHost, resourceHost))");
        source.Append(indent);
        source.AppendLine("    {");
        source.Append(indent);
        source.AppendLine("        __atomuiResourceHostAttachmentCount++;");
        source.Append(indent);
        source.AppendLine("    }");
        source.Append(indent);
        source.AppendLine("    else");
        source.Append(indent);
        source.AppendLine("    {");
        source.Append(indent);
        source.AppendLine("        AtomUIDetachCurrentResourceHost();");
        source.Append(indent);
        source.AppendLine("        __atomuiResourceHost = resourceHost;");
        source.Append(indent);
        source.AppendLine("        __atomuiResourceHostAttachmentCount = 1;");
        source.Append(indent);
        source.AppendLine("        AtomUIRegisterResourceHost(resourceHost);");
        source.Append(indent);
        source.AppendLine("    }");
        source.AppendLine();
        source.Append(indent);
        source.AppendLine("    return new AtomUIScopedResourceHostAttachment(this, resourceHost);");
        source.Append(indent);
        source.AppendLine("}");
        source.AppendLine();
    }

    private static void AppendDetachResourceHost(StringBuilder source, string indent)
    {
        source.Append(indent);
        source.AppendLine("private void AtomUIDetachResourceHost(global::Avalonia.Controls.IResourceHost resourceHost)");
        source.Append(indent);
        source.AppendLine("{");
        source.Append(indent);
        source.AppendLine("    if (!global::System.Object.ReferenceEquals(__atomuiResourceHost, resourceHost))");
        source.Append(indent);
        source.AppendLine("    {");
        source.Append(indent);
        source.AppendLine("        return;");
        source.Append(indent);
        source.AppendLine("    }");
        source.AppendLine();
        source.Append(indent);
        source.AppendLine("    __atomuiResourceHostAttachmentCount--;");
        source.Append(indent);
        source.AppendLine("    if (__atomuiResourceHostAttachmentCount > 0)");
        source.Append(indent);
        source.AppendLine("    {");
        source.Append(indent);
        source.AppendLine("        return;");
        source.Append(indent);
        source.AppendLine("    }");
        source.AppendLine();
        source.Append(indent);
        source.AppendLine("    AtomUIDetachCurrentResourceHost();");
        source.Append(indent);
        source.AppendLine("    AtomUIRaiseResourcesChanged();");
        source.Append(indent);
        source.AppendLine("    ActualThemeVariantChanged?.Invoke(this, global::System.EventArgs.Empty);");
        source.Append(indent);
        source.AppendLine("}");
        source.AppendLine();
    }

    private static void AppendDetachCurrentResourceHost(StringBuilder source, string indent)
    {
        source.Append(indent);
        source.AppendLine("private void AtomUIDetachCurrentResourceHost()");
        source.Append(indent);
        source.AppendLine("{");
        source.Append(indent);
        source.AppendLine("    if (__atomuiResourceHost is null)");
        source.Append(indent);
        source.AppendLine("    {");
        source.Append(indent);
        source.AppendLine("        __atomuiResourceHostAttachmentCount = 0;");
        source.Append(indent);
        source.AppendLine("        return;");
        source.Append(indent);
        source.AppendLine("    }");
        source.AppendLine();
        source.Append(indent);
        source.AppendLine("    __atomuiResourceHost.ResourcesChanged -= AtomUIHandleResourceHostResourcesChanged;");
        source.AppendLine();
        source.Append(indent);
        source.AppendLine("    if (__atomuiResourceHost is global::Avalonia.Styling.IThemeVariantHost themeVariantHost)");
        source.Append(indent);
        source.AppendLine("    {");
        source.Append(indent);
        source.AppendLine("        themeVariantHost.ActualThemeVariantChanged -= AtomUIHandleResourceHostActualThemeVariantChanged;");
        source.Append(indent);
        source.AppendLine("    }");
        source.AppendLine();
        source.Append(indent);
        source.AppendLine("    __atomuiResourceHost = null;");
        source.Append(indent);
        source.AppendLine("    __atomuiResourceHostAttachmentCount = 0;");
        source.Append(indent);
        source.AppendLine("}");
        source.AppendLine();
    }

    private static void AppendRegisterResourceHost(StringBuilder source, string indent)
    {
        source.Append(indent);
        source.AppendLine("private void AtomUIRegisterResourceHost(global::Avalonia.Controls.IResourceHost resourceHost)");
        source.Append(indent);
        source.AppendLine("{");
        source.Append(indent);
        source.AppendLine("    resourceHost.ResourcesChanged += AtomUIHandleResourceHostResourcesChanged;");
        source.AppendLine();
        source.Append(indent);
        source.AppendLine("    if (resourceHost is global::Avalonia.Styling.IThemeVariantHost themeVariantHost)");
        source.Append(indent);
        source.AppendLine("    {");
        source.Append(indent);
        source.AppendLine("        themeVariantHost.ActualThemeVariantChanged += AtomUIHandleResourceHostActualThemeVariantChanged;");
        source.Append(indent);
        source.AppendLine("    }");
        source.AppendLine();
        source.Append(indent);
        source.AppendLine("    AtomUIRaiseResourcesChanged();");
        source.Append(indent);
        source.AppendLine("    ActualThemeVariantChanged?.Invoke(this, global::System.EventArgs.Empty);");
        source.Append(indent);
        source.AppendLine("}");
        source.AppendLine();
    }

    private static void AppendEventHandlers(StringBuilder source, string indent)
    {
        source.Append(indent);
        source.AppendLine("private void AtomUIHandleResourceHostResourcesChanged(object? sender, global::Avalonia.Controls.ResourcesChangedEventArgs e)");
        source.Append(indent);
        source.AppendLine("{");
        source.Append(indent);
        source.AppendLine("    ResourcesChanged?.Invoke(this, e);");
        source.Append(indent);
        source.AppendLine("}");
        source.AppendLine();
        source.Append(indent);
        source.AppendLine("private void AtomUIHandleResourceHostActualThemeVariantChanged(object? sender, global::System.EventArgs e)");
        source.Append(indent);
        source.AppendLine("{");
        source.Append(indent);
        source.AppendLine("    ActualThemeVariantChanged?.Invoke(this, e);");
        source.Append(indent);
        source.AppendLine("}");
        source.AppendLine();
        source.Append(indent);
        source.AppendLine("private void AtomUIRaiseResourcesChanged()");
        source.Append(indent);
        source.AppendLine("{");
        source.Append(indent);
        source.AppendLine("    ResourcesChanged?.Invoke(this, global::Avalonia.Controls.ResourcesChangedEventArgs.Create());");
        source.Append(indent);
        source.AppendLine("}");
        source.AppendLine();
    }

    private void AppendAttachmentDisposable(StringBuilder source, string indent)
    {
        source.Append(indent);
        source.AppendLine("private sealed class AtomUIScopedResourceHostAttachment : global::System.IDisposable");
        source.Append(indent);
        source.AppendLine("{");
        source.Append(indent);
        source.Append("    private ");
        source.Append(_typeInfo.TypeName);
        source.AppendLine("? _item;");
        source.Append(indent);
        source.AppendLine("    private global::Avalonia.Controls.IResourceHost? _resourceHost;");
        source.AppendLine();
        source.Append(indent);
        source.Append("    public AtomUIScopedResourceHostAttachment(");
        source.Append(_typeInfo.TypeName);
        source.AppendLine(" item, global::Avalonia.Controls.IResourceHost resourceHost)");
        source.Append(indent);
        source.AppendLine("    {");
        source.Append(indent);
        source.AppendLine("        _item = item;");
        source.Append(indent);
        source.AppendLine("        _resourceHost = resourceHost;");
        source.Append(indent);
        source.AppendLine("    }");
        source.AppendLine();
        source.Append(indent);
        source.AppendLine("    public void Dispose()");
        source.Append(indent);
        source.AppendLine("    {");
        source.Append(indent);
        source.AppendLine("        if (_item is null || _resourceHost is null)");
        source.Append(indent);
        source.AppendLine("        {");
        source.Append(indent);
        source.AppendLine("            return;");
        source.Append(indent);
        source.AppendLine("        }");
        source.AppendLine();
        source.Append(indent);
        source.AppendLine("        var item = _item;");
        source.Append(indent);
        source.AppendLine("        var resourceHost = _resourceHost;");
        source.Append(indent);
        source.AppendLine("        _item = null;");
        source.Append(indent);
        source.AppendLine("        _resourceHost = null;");
        source.Append(indent);
        source.AppendLine("        item.AtomUIDetachResourceHost(resourceHost);");
        source.Append(indent);
        source.AppendLine("    }");
        source.Append(indent);
        source.AppendLine("}");
    }
}
