using AtomUI.Localization;

namespace AtomUIGallery.Localization;

[LanguageCatalog]
public enum InfoFlyoutShowCaseLangResourceKind
{
    BasicTitle,
    BasicDescription,
    TriggerWaysTitle,
    TriggerWaysDescription,
    PlacementTitle,
    PlacementDescription,
    ArrowTitle,
    ArrowDescription,
    P2TextTheMostBasicExample,
    P2ContentHoverMe,
    P2ContentFocusMe,
    P2ContentClickMe,
    P2ContentShow,
    P2ContentHide,
    P2ContentCenter,
    P2ContentLT,
    P2ContentLeft,
    P2ContentLB,
    P2ContentTL,
    P2ContentTop,
    P2ContentTR,
    P2ContentRT,
    P2ContentRight,
    P2ContentRB,
    P2ContentBL,
    P2ContentBottom,
    P2ContentBR,
    ScenarioExamples,
    PageSubtitle,
    PageDescription,
    ComponentCategory,
    ComponentStatusStable,
    StyleClassTitle,
    StyleClassDescription,
    SemanticRootDescription,
    SemanticPopupRootDescription,
    SemanticPopupContainerDescription,
    SemanticPopupContentDescription,
    SemanticPopupArrowDescription,
    SemanticPreviewContentText,
    SemanticPreviewTriggerContent,
    SemanticStyleObjectContent,
    SemanticStyleObjectTrigger,
    SemanticStyleFunctionContent,
    SemanticStyleFunctionTrigger
}
