<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>$(AtomUITargetFrameworks)</TargetFrameworks>
        <RootNamespace>AtomUI.Localization</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="AtomUI.Localization.Tests" />
    </ItemGroup>
</Project>
