using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.Slider;

[LanguageProvider(LanguageCode.en_US, SliderShowCase.LanguageId)]
internal partial class en_US
{
    public const string ScenarioExamples = "Examples";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "Design Token";
    public const string ComponentCategory = "Data Entry";
    public const string ComponentStatusStable = ".NET 10";
    public const string PageSubtitle = "Select a numeric value or range from a continuous or graduated track.";
    public const string PageDescription = "Slider supports single-value and range selection, horizontal or vertical orientation, snap-to-tick behavior, formatted tooltips, marks, included tracks, disabled states, and keyboard interaction.";
    public const string ApiColumnProperty = "Property";
    public const string ApiColumnDescription = "Description";
    public const string ApiColumnType = "Type";
    public const string ApiColumnDefault = "Default";
    public const string ApiPropertyMinimum = "Lowest value allowed by the slider.";
    public const string ApiPropertyMaximum = "Highest value allowed by the slider.";
    public const string ApiPropertyValue = "Current single-thumb value.";
    public const string ApiPropertySmallChange = "Small keyboard increment used by arrow key navigation.";
    public const string ApiPropertyLargeChange = "Large keyboard increment used by PageUp and PageDown.";
    public const string ApiPropertyOrientation = "Controls whether the slider is horizontal or vertical.";
    public const string ApiPropertyIsDirectionReversed = "Reverses the visual direction of value growth.";
    public const string ApiPropertyIsSnapToTickEnabled = "Snaps thumb movement to tick values.";
    public const string ApiPropertyTickFrequency = "Distance between tick values.";
    public const string ApiPropertyRangeValue = "Selected start and end values in range mode. Defaults to TwoWay binding and participates in Avalonia data validation.";
    public const string ApiPropertyIsRangeMode = "Enables dual-thumb range selection.";
    public const string ApiPropertyMarks = "Graduated mark labels displayed along the track.";
    public const string ApiPropertyValueFormatTemplate = "Format string used for tooltip values.";
    public const string ApiPropertyIsIncluded = "Controls whether the selected track is visually included between values.";
    public const string ApiPropertyIsMotionEnabled = "Enables or disables slider motion effects.";
    public const string ApiPropertyIsWaveSpiritEnabled = "Enables or disables wave feedback on the thumb.";
    public const string TokenColumnToken = "Token";
    public const string TokenColumnDescription = "Description";
    public const string TokenColumnScope = "Scope";
    public const string TokenColumnStatus = "Status";
    public const string TokenNameSliderTrackSize = "Reserved slider track thickness used for layout.";
    public const string TokenNameRailSize = "Base rail thickness.";
    public const string TokenNameMarkSize = "Mark dot size.";
    public const string TokenNameThumbSize = "Recommended thumb layout size.";
    public const string TokenNameThumbCircleSize = "Thumb circle size.";
    public const string TokenNameThumbCircleSizeHover = "Thumb circle size while hovering.";
    public const string TokenNameThumbCircleBorderThickness = "Thumb circle border thickness.";
    public const string TokenNameThumbCircleBorderThicknessHover = "Thumb circle border thickness while hovering.";
    public const string TokenNameRailBg = "Background color of the rail.";
    public const string TokenNameRailHoverBg = "Background color of the rail while hovering.";
    public const string TokenNameTrackBg = "Background color of the selected track.";
    public const string TokenNameTrackHoverBg = "Background color of the selected track while hovering.";
    public const string TokenNameMarkBorderColor = "Border color of inactive marks.";
    public const string TokenNameMarkBorderColorHover = "Border color of marks while hovering.";
    public const string TokenNameMarkBorderColorActive = "Border color of active marks.";
    public const string TokenNameThumbCircleBorderColor = "Thumb border color.";
    public const string TokenNameThumbCircleBorderHoverColor = "Thumb border color while hovering.";
    public const string TokenNameThumbCircleBorderActiveColor = "Thumb border color while active.";
    public const string TokenNameThumbCircleBorderColorDisabled = "Thumb border color when disabled.";
    public const string TokenNameThumbOutlineColor = "Color of the thumb outline ring.";
    public const string TokenNameThumbOutlineThickness = "Thickness of the thumb outline ring.";
    public const string TokenNameTrackBgDisabled = "Selected track background color when disabled.";
    public const string TokenNameSliderPaddingHorizontal = "Padding used by horizontal slider layout.";
    public const string TokenNameSliderPaddingVertical = "Padding used by vertical slider layout.";
    public const string TokenNameMarginPartWithMark = "Extra margin reserved when marks are shown.";
    public const string TokenScopeComponent = "Component";
    public const string TokenStatusStable = "Stable";
    public const string BasicTitle = "Basic";
    public const string BasicDescription = "Basic slider. When range is true, display as dual thumb mode. When disable is true, the slider will not be interactable.";
    public const string RangeValueBindingTitle = "RangeValue binding";
    public const string RangeValueBindingDescription = "RangeValue now defaults to TwoWay binding, so range changes update the ViewModel without an explicit binding mode.";
    public const string CustomizeTooltipTitle = "Customize tooltip";
    public const string CustomizeTooltipDescription = "Use tooltip.formatter to format content of Tooltip. If tooltip.formatter is null, hide it.";
    public const string VerticalTitle = "Vertical";
    public const string VerticalDescription = "The vertical Slider.";
    public const string GraduatedSliderTitle = "Graduated slider";
    public const string GraduatedSliderDescription = "Using marks property to mark a graduated slider, use value or defaultValue to specify the position of thumb. When included is false, means that different thumbs are coordinative. when step is null, users can only slide the thumbs onto marks.";
    public const string P2TextEnabled = "Enabled:";
    public const string P2TextIncludedTrue = "included=true";
    public const string P2TextIncludedFalse = "included=false";
    public const string P2TextBoundRangeValue = "Bound range:";
    public const string P2ContentSetRange = "Set 35-85";
    public const string P2ContentClear = "Clear";

}
