using AtomUI.Theme.Language;

namespace AtomUIGallery.ShowCases.Slider;

[LanguageProvider(LanguageCode.zh_CN, SliderShowCase.LanguageId)]
internal partial class zh_CN
{
    public const string ScenarioExamples = "示例";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "设计变量";
    public const string ComponentCategory = "数据录入";
    public const string ComponentStatusStable = ".NET 10";
    public const string PageSubtitle = "从连续或带刻度的轨道中选择数值或范围。";
    public const string PageDescription = "Slider 支持单值和范围选择、水平或垂直方向、按刻度吸附、格式化提示、刻度标记、包含轨道、禁用状态和键盘交互。";
    public const string ApiColumnProperty = "属性";
    public const string ApiColumnDescription = "说明";
    public const string ApiColumnType = "类型";
    public const string ApiColumnDefault = "默认值";
    public const string ApiPropertyMinimum = "滑块允许的最小值。";
    public const string ApiPropertyMaximum = "滑块允许的最大值。";
    public const string ApiPropertyValue = "当前单滑块数值。";
    public const string ApiPropertySmallChange = "方向键导航使用的小步进值。";
    public const string ApiPropertyLargeChange = "PageUp 和 PageDown 使用的大步进值。";
    public const string ApiPropertyOrientation = "控制滑块为水平或垂直方向。";
    public const string ApiPropertyIsDirectionReversed = "反转数值增长的视觉方向。";
    public const string ApiPropertyIsSnapToTickEnabled = "将滑块移动吸附到刻度值。";
    public const string ApiPropertyTickFrequency = "刻度值之间的间距。";
    public const string ApiPropertyRangeValue = "范围模式下选中的开始值和结束值，默认双向绑定，并接入 Avalonia 数据验证。";
    public const string ApiPropertyIsRangeMode = "启用双滑块范围选择。";
    public const string ApiPropertyMarks = "沿轨道显示的刻度标记文本。";
    public const string ApiPropertyValueFormatTemplate = "用于提示值的格式化字符串。";
    public const string ApiPropertyIsIncluded = "控制选中轨道是否在数值之间视觉填充。";
    public const string ApiPropertyIsMotionEnabled = "启用或禁用滑块动效。";
    public const string ApiPropertyIsWaveSpiritEnabled = "启用或禁用滑块上的波纹反馈。";
    public const string TokenColumnToken = "变量";
    public const string TokenColumnDescription = "说明";
    public const string TokenColumnScope = "范围";
    public const string TokenColumnStatus = "状态";
    public const string TokenNameSliderTrackSize = "用于布局的滑块轨道预留厚度。";
    public const string TokenNameRailSize = "基础轨道厚度。";
    public const string TokenNameMarkSize = "刻度点尺寸。";
    public const string TokenNameThumbSize = "推荐的滑块布局尺寸。";
    public const string TokenNameThumbCircleSize = "滑块圆点尺寸。";
    public const string TokenNameThumbCircleSizeHover = "悬浮时的滑块圆点尺寸。";
    public const string TokenNameThumbCircleBorderThickness = "滑块圆点边框厚度。";
    public const string TokenNameThumbCircleBorderThicknessHover = "悬浮时的滑块圆点边框厚度。";
    public const string TokenNameRailBg = "轨道背景色。";
    public const string TokenNameRailHoverBg = "悬浮时的轨道背景色。";
    public const string TokenNameTrackBg = "已选轨道背景色。";
    public const string TokenNameTrackHoverBg = "悬浮时的已选轨道背景色。";
    public const string TokenNameMarkBorderColor = "未激活刻度的边框色。";
    public const string TokenNameMarkBorderColorHover = "悬浮时刻度的边框色。";
    public const string TokenNameMarkBorderColorActive = "激活刻度的边框色。";
    public const string TokenNameThumbCircleBorderColor = "滑块边框色。";
    public const string TokenNameThumbCircleBorderHoverColor = "悬浮时的滑块边框色。";
    public const string TokenNameThumbCircleBorderActiveColor = "激活时的滑块边框色。";
    public const string TokenNameThumbCircleBorderColorDisabled = "禁用时的滑块边框色。";
    public const string TokenNameThumbOutlineColor = "滑块外轮廓环颜色。";
    public const string TokenNameThumbOutlineThickness = "滑块外轮廓环厚度。";
    public const string TokenNameTrackBgDisabled = "禁用时已选轨道背景色。";
    public const string TokenNameSliderPaddingHorizontal = "水平滑块布局使用的内边距。";
    public const string TokenNameSliderPaddingVertical = "垂直滑块布局使用的内边距。";
    public const string TokenNameMarginPartWithMark = "显示刻度标记时预留的额外外边距。";
    public const string TokenScopeComponent = "组件";
    public const string TokenStatusStable = "稳定";
    public const string BasicTitle = "基础用法";
    public const string BasicDescription = "基础滑块。range 为 true 时显示为双滑块模式；disable 为 true 时滑块不可交互。";
    public const string RangeValueBindingTitle = "RangeValue 绑定";
    public const string RangeValueBindingDescription = "RangeValue 现在默认双向绑定，拖动范围会直接更新 ViewModel，无需显式设置绑定模式。";
    public const string CustomizeTooltipTitle = "自定义提示";
    public const string CustomizeTooltipDescription = "使用 tooltip.formatter 格式化 Tooltip 内容；当 tooltip.formatter 为 null 时隐藏提示。";
    public const string VerticalTitle = "垂直方向";
    public const string VerticalDescription = "垂直滑块。";
    public const string GraduatedSliderTitle = "带刻度的滑块";
    public const string GraduatedSliderDescription = "使用 marks 属性标记带刻度滑块，使用 value 或 defaultValue 指定滑块位置。当 included 为 false 时，不同滑块相互独立；当 step 为 null 时，用户只能将滑块拖到刻度上。";
    public const string P2TextEnabled = "Enabled:";
    public const string P2TextIncludedTrue = "included=true";
    public const string P2TextIncludedFalse = "included=false";
    public const string P2TextBoundRangeValue = "绑定范围：";
    public const string P2ContentSetRange = "设为 35-85";
    public const string P2ContentClear = "清空";

}
