using AtomUI.Theme.Language;

namespace AtomUIGallery.ShowCases.Notification;

[LanguageProvider(LanguageCode.en_US, NotificationShowCase.LanguageId)]
internal partial class en_US
{
    public const string BasicTitle = "Basic";
    public const string BasicDescription = "The simplest usage for Notification.";
    public const string DurationTitle = "Duration after which the notification box is closed";
    public const string DurationDescription = "Duration can be used to specify how long the notification stays open. After the duration time elapses, the notification closes automatically. If not specified, default value is 4.5 seconds. If you set the value to TimeSpan.Zero, the notification box will never close automatically.";
    public const string WithIconTitle = "Notification with icon";
    public const string WithIconDescription = "A notification box with a icon at the left side.";
    public const string PlacementTitle = "Placement";
    public const string PlacementDescription = "A notification box can appear from the top bottom topLeft topRight bottomLeft or bottomRight of the viewport via placement.";
    public const string CustomizedIconTitle = "Customized Icon";
    public const string CustomizedIconDescription = "The icon can be customized to any icon node.";
    public const string ProgressTitle = "Show with progress";
    public const string ProgressDescription = "Show progress bar for auto-closing notification.";
    public const string ComponentCategory = "Feedback";
    public const string ComponentStatusStable = "Stable";
    public const string PageSubtitle = "Desktop notifications for longer feedback and non-blocking updates.";
    public const string PageDescription = "Notification displays rich feedback cards near the edge of the window. It supports semantic types, custom icons, placement, manual duration, hover pause, and auto-close progress.";
    public const string ScenarioExamples = "Examples";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "Design Token";
    public const string ApiColumnMember = "Member";
    public const string ApiColumnDescription = "Description";
    public const string ApiColumnType = "Type";
    public const string ApiColumnDefault = "Default";
    public const string ApiPropertyNotificationTitle = "Title text displayed in the notification card header.";
    public const string ApiPropertyNotificationContent = "Body content displayed below the title.";
    public const string ApiPropertyNotificationType = "Notification semantic type. Default shows no type icon; typed notifications use the matching status icon and color.";
    public const string ApiPropertyNotificationIcon = "Optional custom icon. When unset, typed notifications select the icon from the notification type.";
    public const string ApiPropertyNotificationExpiration = "Auto-close delay. Use TimeSpan.Zero to keep the notification open.";
    public const string ApiPropertyNotificationShowProgress = "Shows an auto-close progress bar at the bottom of the notification.";
    public const string ApiPropertyNotificationOnClick = "Callback invoked when the notification card is clicked.";
    public const string ApiPropertyNotificationOnClose = "Callback invoked after the notification card is closed.";
    public const string ApiPropertyManagerPosition = "Window edge position used by the notification manager.";
    public const string ApiPropertyManagerMaxItems = "Maximum number of visible notifications. Older notifications close when the limit is exceeded.";
    public const string ApiPropertyManagerIsPauseOnHover = "Pauses expiration countdown while the pointer is over the notification.";
    public const string ApiPropertyManagerIsMotionEnabled = "Enables notification enter and exit motion.";
    public const string ApiMethodManagerShow = "Shows an INotification instance and applies optional style classes.";
    public const string TokenColumnToken = "Token";
    public const string TokenColumnDescription = "Description";
    public const string TokenColumnScope = "Scope";
    public const string TokenColumnStatus = "Status";
    public const string TokenScopeComponent = "Component";
    public const string TokenStatusStable = "Stable";
    public const string TokenNameNotificationBg = "Background color of the notification card.";
    public const string TokenNameNotificationPadding = "Inner padding of the notification card.";
    public const string TokenNameNotificationIconSize = "Size of the notification semantic icon.";
    public const string TokenNameNotificationIconMargin = "Outer margin around the notification icon.";
    public const string TokenNameNotificationCloseButtonSize = "Size of the notification close button.";
    public const string TokenNameNotificationCloseButtonPadding = "Inner padding of the notification close button.";
    public const string TokenNameNotificationProgressHeight = "Height of the auto-close progress bar.";
    public const string TokenNameNotificationProgressBg = "Brush used by the auto-close progress bar.";
    public const string TokenNameNotificationProgressMargin = "Outer margin around the notification progress bar.";
    public const string TokenNameNotificationWidth = "Default width of the notification card.";
    public const string TokenNameNotificationTopMargin = "Outer margin used by top-positioned notification cards.";
    public const string TokenNameNotificationBottomMargin = "Outer margin used by bottom-positioned notification cards.";
    public const string P2ContentShowNotification = "Show Notification";
    public const string P2ContentOpenTheNotificationBox = "Open the notification box";
    public const string P2ContentSuccess = "Success";
    public const string P2ContentInfo = "Info";
    public const string P2ContentWarning = "Warning";
    public const string P2ContentError = "Error";
    public const string P2ContentTop = "Top";
    public const string P2ContentBottom = "Bottom";
    public const string P2ContentTopleft = "TopLeft";
    public const string P2ContentTopright = "TopRight";
    public const string P2ContentBottomleft = "BottomLeft";
    public const string P2ContentBottomright = "BottomRight";
    public const string P2ContentPauseOnHover = "Pause on hover";
    public const string P2ContentDonTPauseOnHover = "Don't pause on hover";
    public const string P2NotificationTitle = "Notification Title";
    public const string P2NotificationTopTitle = "Notification Top";
    public const string P2NotificationBottomTitle = "Notification Bottom";
    public const string P2NotificationTopLeftTitle = "Notification TopLeft";
    public const string P2NotificationTopRightTitle = "Notification TopRight";
    public const string P2NotificationBottomLeftTitle = "Notification BottomLeft";
    public const string P2NotificationBottomRightTitle = "Notification BottomRight";
    public const string P2NotificationHello = "Hello, AtomUI/Avalonia!";
    public const string P2NotificationContent = "This is the content of the notification. This is the content of the notification. This is the content of the notification.";
    public const string P2NotificationNeverCloseContent = "I will never close automatically. This is a purposely very very long description that has many many characters and words.";

}
