using AtomUI.Localization;

namespace AtomUIGallery.Localization;

[LanguageCatalog(ContractVersion = 1)]
public enum NotificationShowCaseLangResourceKind
{
    BasicTitle = 1,
    BasicDescription = 2,
    DurationTitle = 3,
    DurationDescription = 4,
    WithIconTitle = 5,
    WithIconDescription = 6,
    PlacementTitle = 7,
    PlacementDescription = 8,
    CustomizedIconTitle = 9,
    CustomizedIconDescription = 10,
    ProgressTitle = 11,
    ProgressDescription = 12,
    ComponentCategory = 13,
    ComponentStatusStable = 14,
    PageSubtitle = 15,
    PageDescription = 16,
    ScenarioExamples = 17,
    ApiMethodManagerShow = 18,
    P2ContentShowNotification = 19,
    P2ContentOpenTheNotificationBox = 20,
    P2ContentSuccess = 21,
    P2ContentInfo = 22,
    P2ContentWarning = 23,
    P2ContentError = 24,
    P2ContentTop = 25,
    P2ContentBottom = 26,
    P2ContentTopleft = 27,
    P2ContentTopright = 28,
    P2ContentBottomleft = 29,
    P2ContentBottomright = 30,
    P2ContentPauseOnHover = 31,
    P2ContentDonTPauseOnHover = 32,
    P2NotificationTitle = 33,
    P2NotificationTopTitle = 34,
    P2NotificationBottomTitle = 35,
    P2NotificationTopLeftTitle = 36,
    P2NotificationTopRightTitle = 37,
    P2NotificationBottomLeftTitle = 38,
    P2NotificationBottomRightTitle = 39,
    P2NotificationHello = 40,
    P2NotificationContent = 41,
    P2NotificationNeverCloseContent = 42
}
