using AtomUI.Theme.Language;

namespace AtomUIGallery.ShowCases.Notification;

[LanguageProvider(LanguageCode.zh_CN, NotificationShowCase.LanguageId)]
internal partial class zh_CN
{
    public const string BasicTitle = "基础用法";
    public const string BasicDescription = "Notification 的最简单用法。";
    public const string DurationTitle = "自动关闭时长";
    public const string DurationDescription = "Duration 可指定通知保持打开的时间。时间结束后通知会自动关闭。未指定时默认值为 4.5 秒；设置为 TimeSpan.Zero 时通知不会自动关闭。";
    public const string WithIconTitle = "带图标通知";
    public const string WithIconDescription = "左侧带图标的通知框。";
    public const string PlacementTitle = "弹出位置";
    public const string PlacementDescription = "通知框可通过 placement 从视口顶部、底部、左上、右上、左下或右下出现。";
    public const string CustomizedIconTitle = "自定义图标";
    public const string CustomizedIconDescription = "图标可以自定义为任意图标节点。";
    public const string ProgressTitle = "显示进度";
    public const string ProgressDescription = "为自动关闭的通知显示进度条。";
    public const string ComponentCategory = "反馈";
    public const string ComponentStatusStable = "稳定";
    public const string PageSubtitle = "用于较长反馈和非阻塞更新的桌面通知。";
    public const string PageDescription = "Notification 在窗口边缘显示信息更丰富的反馈卡片，支持语义类型、自定义图标、弹出位置、手动时长、悬停暂停和自动关闭进度。";
    public const string ScenarioExamples = "示例";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "设计变量";
    public const string ApiColumnMember = "成员";
    public const string ApiColumnDescription = "说明";
    public const string ApiColumnType = "类型";
    public const string ApiColumnDefault = "默认值";
    public const string ApiPropertyNotificationTitle = "显示在通知卡片头部的标题文本。";
    public const string ApiPropertyNotificationContent = "显示在标题下方的正文内容。";
    public const string ApiPropertyNotificationType = "通知语义类型；Default 不显示类型图标，带类型通知使用对应状态图标和颜色。";
    public const string ApiPropertyNotificationIcon = "可选自定义图标；未设置时带类型通知根据通知类型选择图标。";
    public const string ApiPropertyNotificationExpiration = "自动关闭延迟；使用 TimeSpan.Zero 可保持通知打开。";
    public const string ApiPropertyNotificationShowProgress = "在通知底部显示自动关闭进度条。";
    public const string ApiPropertyNotificationOnClick = "点击通知卡片时调用的回调。";
    public const string ApiPropertyNotificationOnClose = "通知卡片关闭后调用的回调。";
    public const string ApiPropertyManagerPosition = "通知管理器使用的窗口边缘位置。";
    public const string ApiPropertyManagerMaxItems = "可见通知最大数量；超过限制时较旧通知会关闭。";
    public const string ApiPropertyManagerIsPauseOnHover = "指针悬停在通知上时暂停过期倒计时。";
    public const string ApiPropertyManagerIsMotionEnabled = "启用通知进入和退出动效。";
    public const string ApiMethodManagerShow = "显示 INotification 实例并应用可选样式类。";
    public const string TokenColumnToken = "变量";
    public const string TokenColumnDescription = "说明";
    public const string TokenColumnScope = "范围";
    public const string TokenColumnStatus = "状态";
    public const string TokenScopeComponent = "组件";
    public const string TokenStatusStable = "稳定";
    public const string TokenNameNotificationBg = "通知卡片背景色。";
    public const string TokenNameNotificationPadding = "通知卡片内边距。";
    public const string TokenNameNotificationIconSize = "通知语义图标尺寸。";
    public const string TokenNameNotificationIconMargin = "通知图标外边距。";
    public const string TokenNameNotificationCloseButtonSize = "通知关闭按钮尺寸。";
    public const string TokenNameNotificationCloseButtonPadding = "通知关闭按钮内边距。";
    public const string TokenNameNotificationProgressHeight = "自动关闭进度条高度。";
    public const string TokenNameNotificationProgressBg = "自动关闭进度条使用的画刷。";
    public const string TokenNameNotificationProgressMargin = "通知进度条外边距。";
    public const string TokenNameNotificationWidth = "通知卡片默认宽度。";
    public const string TokenNameNotificationTopMargin = "顶部位置通知卡片使用的外边距。";
    public const string TokenNameNotificationBottomMargin = "底部位置通知卡片使用的外边距。";
    public const string P2ContentShowNotification = "显示通知";
    public const string P2ContentOpenTheNotificationBox = "打开通知框";
    public const string P2ContentSuccess = "成功";
    public const string P2ContentInfo = "信息";
    public const string P2ContentWarning = "警告";
    public const string P2ContentError = "错误";
    public const string P2ContentTop = "顶部";
    public const string P2ContentBottom = "底部";
    public const string P2ContentTopleft = "左上";
    public const string P2ContentTopright = "右上";
    public const string P2ContentBottomleft = "左下";
    public const string P2ContentBottomright = "右下";
    public const string P2ContentPauseOnHover = "悬停时暂停";
    public const string P2ContentDonTPauseOnHover = "悬停时不暂停";
    public const string P2NotificationTitle = "通知标题";
    public const string P2NotificationTopTitle = "顶部通知";
    public const string P2NotificationBottomTitle = "底部通知";
    public const string P2NotificationTopLeftTitle = "左上通知";
    public const string P2NotificationTopRightTitle = "右上通知";
    public const string P2NotificationBottomLeftTitle = "左下通知";
    public const string P2NotificationBottomRightTitle = "右下通知";
    public const string P2NotificationHello = "你好，AtomUI/Avalonia！";
    public const string P2NotificationContent = "这是通知内容。这是通知内容。这是通知内容。";
    public const string P2NotificationNeverCloseContent = "我不会自动关闭。这是一段特意写得很长的描述，包含很多字符和词语。";

}
