trigger: none
pr: none

variables:
   SourceDir: $(Build.SourcesDirectory)
   NativeLibSrcDir: '$(sourceDir)/nativelibs'
   BuildDir: $(Build.BinariesDirectory)
   BaseOutputDir: '$(Build.ArtifactStagingDirectory)/output'
   MacOutputDir: '$(baseOutputDir)/osx'
   WinOutputDir: '$(baseOutputDir)/windows'
   Win64Output: '$(winOutputDir)/win-x64'
   Win32Output: '$(winOutputDir)/win-x86'
parameters:
   -  name: IsNightlyBuild
      displayName: 'Is it a nightly build:'
      type: boolean
      default: false
   -  name: BuildConfiguration
      displayName: 'Build configuration:'
      type: string
      default: "Release"

stages:
   -  stage:
      jobs:
         -  job: BuildAtomUINativeMacOS
            displayName: "Build AtomUINative for macOS"
            pool:
               vmImage: 'macOS-latest'
            steps:
               -  pwsh: |
                     brew install xmake
                     xmake --version
                     clang --version
                     xmake config --project=$(nativeLibSrcDir) --builddir=$(buildDir) -p macosx -a arm64 -m ${{ parameters.BuildConfiguration }}
                     xmake build
                     xmake install --installdir=$(macOutputDir)
                     xmake config --project=$(nativeLibSrcDir) --builddir=$(buildDir) -p macosx -a x86_64 -m ${{ parameters.BuildConfiguration }}
                     xmake build
                     xmake install --installdir=$(macOutputDir)
                     Write-Output "generate universal binary"
                     New-Item -Path "$(macOutputDir)/lib" -ItemType Directory -Force
                     lipo -create $(macOutputDir)/arm64/lib/libAtomUINative.dylib $(macOutputDir)/x86_64/lib/libAtomUINative.dylib -output $(macOutputDir)/lib/libAtomUINative.dylib
                     dir "$(macOutputDir)" -File
                     lipo -info $(macOutputDir)/lib/libAtomUINative.dylib
                     Remove-Item -Path "$(macOutputDir)/arm64/lib/libAtomUINative.dylib"
                     Remove-Item -Path "$(macOutputDir)/x86_64/lib/libAtomUINative.dylib"
                  displayName: "Build AtomUINative"
               -  task: PublishPipelineArtifact@1
                  inputs:
                     targetPath: $(macOutputDir)
                     artifactName: AtomUINativeMac
                  displayName: "Push libAtomUINative.dylib to pipeline"
         -  job: BuildAtomUINuget
            displayName: "Build AtomUI nupkg"
            pool:
               vmImage: 'windows-latest'
            steps:
               -  task: DownloadPipelineArtifact@2
                  inputs:
                     artifact: AtomUINativeMac
                  displayName: "Download libAtomUINative.dylib to pipeline"
               -  pwsh: |
                     $msysPath = "C:/msys64"
                     $env:MSYSTEM = "CLANG64"
                     $env:MSYSTEM_CARCH = "x86_64"
                     $env:MSYSTEM_CHOST = "x86_64-w64-mingw32"
                     $env:MSYSTEM_PREFIX = "/clang64"
                     $env:CHERE_INVOKING = "1"
                     $env:PATH = "$msysPath/clang64/bin;$msysPath/usr/bin;$env:PATH"
                     Write-Host "##vso[task.setvariable variable=MSYSTEM]CLANG64"
                     Write-Host "##vso[task.setvariable variable=MSYSTEM_CARCH]x86_64"
                     Write-Host "##vso[task.setvariable variable=MSYSTEM_CHOST]x86_64-w64-mingw32"
                     Write-Host "##vso[task.setvariable variable=MSYSTEM_PREFIX]/clang64"
                     Write-Host "##vso[task.prependpath]$msysPath/clang64/bin"
                     Write-Host "##vso[task.prependpath]$msysPath/usr/bin"
                     C:/msys64/usr/bin/bash.exe -lc @"
                        pacman -Sy --noconfirm
                        pacman -S mingw-w64-clang-x86_64-xmake --noconfirm
                        pacman -S mingw-w64-clang-x86_64-clang --noconfirm
                     "@
                     xmake --version
                     clang --version
                  displayName: "Prepare Build environment"
               -  pwsh: |
                    dotnet build --configuration ${{ parameters.BuildConfiguration }} /p:IsNightlyBuild=${{ parameters.IsNightlyBuild }} $(SourceDir)/packages/AtomUI/AtomUI.csproj
                     $osxNativeLibDir = "$(SourceDir)/output/Bin/Release/runtimes/osx/native"
                     New-Item -ItemType Directory -Force -Path $osxNativeLibDir
                     Copy-Item -Path $(Pipeline.Workspace)/lib/libAtomUINative.dylib -Destination $osxNativeLibDir
                     dotnet build --configuration ${{ parameters.BuildConfiguration }} /p:IsNightlyBuild=${{ parameters.IsNightlyBuild }} $(SourceDir)/packages/AtomUI/AtomUI.csproj
                  displayName: "Build AtomUI projects"
               -  pwsh: |
                     $buildTimestamp = Get-Date -Format 'yyyyMMddHHmm'
                     dotnet pack --no-build --output $(Build.ArtifactStagingDirectory) --configuration ${{ parameters.BuildConfiguration }} /p:BuildTimestamp=$buildTimestamp /p:IsNightlyBuild=${{ parameters.IsNightlyBuild }} $(SourceDir)/packages/AtomUI/AtomUI.csproj
                     dotnet pack --no-build --output $(Build.ArtifactStagingDirectory) --configuration ${{ parameters.BuildConfiguration }} /p:BuildTimestamp=$buildTimestamp /p:IsNightlyBuild=${{ parameters.IsNightlyBuild }} $(SourceDir)/src/AtomUI.IconPkg.Generator/AtomUI.IconPkg.Generator.csproj
                     dotnet pack --no-build --output $(Build.ArtifactStagingDirectory) --configuration ${{ parameters.BuildConfiguration }} /p:BuildTimestamp=$buildTimestamp /p:IsNightlyBuild=${{ parameters.IsNightlyBuild }} $(SourceDir)/src/AtomUI.Generator/AtomUI.Generator.csproj
                  displayName: "Pack AtomUI Umbrella project"
               -  task: DotNetCoreCLI@2
                  displayName: "Publish AtomUI project"
                  inputs:
                     command: "push"
                     nuGetFeedType: "internal"
                     packagesToPush: "$(Build.ArtifactStagingDirectory)/*.nupkg"
                     publishVstsFeed: "$(NuGetFeed)"
               -  task: PublishBuildArtifacts@1
                  displayName: "Publish AtomUI project pipeline"
                  inputs:
                     PathtoPublish: "$(Build.ArtifactStagingDirectory)"
                     ArtifactName: "NuGetPackages"
                     TargetPath: "nugets"
            dependsOn: BuildAtomUINativeMacOS