trigger:
  - manual

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: cmake --version
- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: cmake --version
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: cmake --version