using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.DatePicker;

[LanguageProvider(LanguageCode.en_US, DatePickerShowCase.LanguageId)]
internal partial class en_US : LanguageProvider
{
    public const string BasicTitle = "Basic";
    public const string BasicDescription = "Click DatePicker, and then we could select or input a date in panel.";
    public const string RangePickerTitle = "Range Picker";
    public const string RangePickerDescription = "Set range picker type by picker prop.";
    public const string NeedConfirmTitle = "Need Confirm";
    public const string NeedConfirmDescription = "DatePicker will automatically determine whether to show a confirm button according to the picker property. You can also set the needConfirm property to determine whether to show a confirm button. When needConfirm is set, the user must click the confirm button to complete the selection. Otherwise, the selection will be submitted when the picker loses focus or selects a date.";
    public const string ChooseTimeTitle = "Choose Time";
    public const string ChooseTimeDescription = "This property provides an additional time selection. When showTime is an Object, its properties will be passed on to the built-in TimePicker.";
    public const string DisabledTitle = "Disabled";
    public const string DisabledDescription = "A disabled state of the DatePicker. You can also set as array to disable one of input.";
    public const string ThreeSizesTitle = "Three Sizes";
    public const string ThreeSizesDescription = "The input box comes in three sizes: small, middle and large. The middle size will be used if size is omitted.";
    public const string StatusTitle = "Status";
    public const string StatusDescription = "Add status to DatePicker with status, which could be error or warning.";
    public const string VariantsTitle = "Variants";
    public const string VariantsDescription = "Bordered-less style component.";
    public const string PlacementTitle = "Placement";
    public const string PlacementDescription = "You can manually specify the position of the popup via placement.";
    public const string P2PlaceholderTextSelectDate = "Select date";
    public const string P2PlaceholderTextSelectWeek = "Select week";
    public const string P2PlaceholderTextSelectMonth = "Select month";
    public const string P2PlaceholderTextSelectQuarter = "Select quarter";
    public const string P2PlaceholderTextSelectYear = "Select year";
    public const string P2SecondaryPlaceholderTextEndDate = "End date";
    public const string P2PlaceholderTextSelectTime = "Select time";
    public const string P2PlaceholderTextStartDate = "Start date";
    public const string P2PlaceholderTextOutline = "Outline";
    public const string P2PlaceholderTextFilled = "Filled";
    public const string P2PlaceholderTextBorderless = "Borderless";
    public const string P2TextExpandDirection = "Picker size:";
    public const string P2ContentLarge = "Large";
    public const string P2ContentDefault = "Default";
    public const string P2ContentSmall = "Small";
    public const string P2ContentCustom = "Custom";
    public const string P2TextPlacement = "Placement:";
    public const string P2ContentTopleft = "TopLeft";
    public const string P2ContentTopright = "TopRight";
    public const string P2ContentBottomleft = "BottomLeft";
    public const string P2ContentBottomright = "BottomRight";
    public const string PageSubtitle = "Select dates, ranges, and optional times from calendar panels.";
    public const string PageDescription = "DatePicker supports single and range selection, confirmation flows, time selection, disabled states, size variants, validation status, visual variants, and custom popup placement.";
    public const string ComponentCategory = "Data Entry";
    public const string ComponentStatusStable = "Stable";
    public const string ScenarioExamples = "Examples";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "Design Token";
    public const string ApiColumnProperty = "Property";
    public const string ApiColumnDescription = "Description";
    public const string ApiColumnType = "Type";
    public const string ApiColumnDefault = "Default";
    public const string ApiPropertySelectedDateTime = "Selected date and optional time for DatePicker.";
    public const string ApiPropertyDefaultDateTime = "Initial date and optional time used by DatePicker reset behavior.";
    public const string ApiPropertyRangeStartSelectedDate = "Selected start date for RangeDatePicker.";
    public const string ApiPropertyRangeEndSelectedDate = "Selected end date for RangeDatePicker.";
    public const string ApiPropertyFormat = "Custom date/time formatting string.";
    public const string ApiPropertyPickerMode = "Selection granularity: Date, Week, Month, Quarter, or Year.";
    public const string ApiPropertyIsShowTime = "Enables the time selection panel.";
    public const string ApiPropertyIsNeedConfirm = "Requires the user to confirm the selected value before committing.";
    public const string ApiPropertyClockIdentifier = "Chooses 12-hour or 24-hour clock display when time selection is enabled.";
    public const string ApiPropertyPickerPlacement = "Controls the popup placement relative to the input.";
    public const string ApiPropertySecondaryPlaceholderText = "Placeholder text for the end input of range pickers.";
    public const string TokenColumnToken = "Token";
    public const string TokenColumnDescription = "Description";
    public const string TokenColumnScope = "Scope";
    public const string TokenColumnStatus = "Status";
    public const string TokenScopeComponent = "Component";
    public const string TokenStatusStable = "Stable";
    public const string TokenNameCellHoverBg = "Background color for hovered date cells.";
    public const string TokenNameCellActiveWithRangeBg = "Background color for cells inside the selected range.";
    public const string TokenNameCellHoverWithRangeBg = "Hover background color for cells inside the selected range.";
    public const string TokenNameCellBgDisabled = "Background color for disabled date cells.";
    public const string TokenNameCellRangeBorderColor = "Border color used while selecting a date range.";
    public const string TokenNameCellWidth = "Width of each date cell.";
    public const string TokenNameCellHeight = "Height of each date cell.";
    public const string TokenNamePanelContentPadding = "Padding inside the calendar panel.";
    public const string TokenNameItemPanelMinWidth = "Minimum width of a calendar item panel.";
    public const string TokenNameRangeCalendarSpacing = "Spacing between range calendar panels.";

    protected override Type GetResourceKindType() => typeof(DatePickerShowCaseLangResourceKind);
}
