using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.DatePicker;

[LanguageProvider(LanguageCode.zh_CN, DatePickerShowCase.LanguageId)]
internal partial class zh_CN : LanguageProvider
{
    public const string BasicTitle = "基础用法";
    public const string BasicDescription = "点击 DatePicker 后，可以在面板中选择或输入日期。";
    public const string RangePickerTitle = "范围选择器";
    public const string RangePickerDescription = "通过 picker 属性设置范围选择器类型。";
    public const string NeedConfirmTitle = "需要确认";
    public const string NeedConfirmDescription = "DatePicker 会根据 picker 属性自动判断是否显示确认按钮，也可以通过 needConfirm 属性控制。设置 needConfirm 后，用户必须点击确认按钮完成选择；否则在选择器失去焦点或选择日期时提交选择。";
    public const string ChooseTimeTitle = "选择时间";
    public const string ChooseTimeDescription = "该属性提供额外的时间选择。当 showTime 为对象时，其属性会传递给内置 TimePicker。";
    public const string DisabledTitle = "禁用";
    public const string DisabledDescription = "DatePicker 的禁用状态。也可以设置为数组来禁用其中一个输入框。";
    public const string ThreeSizesTitle = "三种尺寸";
    public const string ThreeSizesDescription = "输入框提供小号、中号和大号三种尺寸。省略 size 时使用中号。";
    public const string StatusTitle = "状态";
    public const string StatusDescription = "通过 status 为 DatePicker 添加状态，可设置为错误或警告。";
    public const string VariantsTitle = "变体";
    public const string VariantsDescription = "无边框风格组件。";
    public const string PlacementTitle = "弹出位置";
    public const string PlacementDescription = "可以通过 placement 手动指定弹出层位置。";
    public const string P2PlaceholderTextSelectDate = "选择日期";
    public const string P2SecondaryPlaceholderTextEndDate = "结束日期";
    public const string P2PlaceholderTextSelectTime = "选择时间";
    public const string P2PlaceholderTextStartDate = "开始日期";
    public const string P2PlaceholderTextOutline = "描边风格";
    public const string P2PlaceholderTextFilled = "填充风格";
    public const string P2PlaceholderTextBorderless = "无边框";
    public const string P2TextExpandDirection = "选择器尺寸：";
    public const string P2ContentLarge = "大号";
    public const string P2ContentDefault = "默认";
    public const string P2ContentSmall = "小号";
    public const string P2ContentCustom = "自定义";
    public const string P2TextPlacement = "弹出位置：";
    public const string P2ContentTopleft = "左上";
    public const string P2ContentTopright = "右上";
    public const string P2ContentBottomleft = "左下";
    public const string P2ContentBottomright = "右下";
    public const string PageSubtitle = "从日历面板中选择日期、日期范围和可选时间。";
    public const string PageDescription = "DatePicker 支持单选与范围选择、确认流程、时间选择、禁用状态、尺寸变体、校验状态、视觉变体和自定义弹出位置。";
    public const string ComponentCategory = "数据录入";
    public const string ComponentStatusStable = "稳定";
    public const string InfoNamespaceLabel = "命名空间";
    public const string InfoPackageLabel = "包";
    public const string InfoBaseClassLabel = "基类";
    public const string ScenarioExamples = "示例";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "设计变量";
    public const string ApiColumnProperty = "属性";
    public const string ApiColumnDescription = "说明";
    public const string ApiColumnType = "类型";
    public const string ApiColumnDefault = "默认值";
    public const string ApiPropertySelectedDateTime = "DatePicker 当前选中的日期和可选时间。";
    public const string ApiPropertyDefaultDateTime = "DatePicker 重置行为使用的初始日期和可选时间。";
    public const string ApiPropertyRangeStartSelectedDate = "RangeDatePicker 当前选中的开始日期。";
    public const string ApiPropertyRangeEndSelectedDate = "RangeDatePicker 当前选中的结束日期。";
    public const string ApiPropertyFormat = "自定义日期/时间格式字符串。";
    public const string ApiPropertyIsShowTime = "启用时间选择面板。";
    public const string ApiPropertyIsNeedConfirm = "要求用户确认选中值后再提交。";
    public const string ApiPropertyClockIdentifier = "启用时间选择时，选择 12 小时制或 24 小时制显示。";
    public const string ApiPropertyPickerPlacement = "控制弹出层相对于输入框的位置。";
    public const string ApiPropertySecondaryPlaceholderText = "范围选择器结束输入框的占位文本。";
    public const string TokenColumnToken = "变量";
    public const string TokenColumnDescription = "说明";
    public const string TokenColumnScope = "作用域";
    public const string TokenColumnStatus = "状态";
    public const string TokenScopeComponent = "组件";
    public const string TokenStatusStable = "稳定";
    public const string TokenNameCellHoverBg = "日期单元格悬浮态背景色。";
    public const string TokenNameCellActiveWithRangeBg = "选中范围内单元格的背景色。";
    public const string TokenNameCellHoverWithRangeBg = "选中范围内单元格的悬浮态背景色。";
    public const string TokenNameCellBgDisabled = "禁用日期单元格背景色。";
    public const string TokenNameCellRangeBorderColor = "选择日期范围时使用的边框色。";
    public const string TokenNameCellWidth = "每个日期单元格宽度。";
    public const string TokenNameCellHeight = "每个日期单元格高度。";
    public const string TokenNamePanelContentPadding = "日历面板内容内边距。";
    public const string TokenNameItemPanelMinWidth = "日历项面板最小宽度。";
    public const string TokenNameRangeCalendarSpacing = "范围日历面板之间的间距。";

    protected override Type GetResourceKindType() => typeof(DatePickerShowCaseLangResourceKind);
}
