<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>$(AtomUITargetFrameworks)</TargetFrameworks>
        <RootNamespace>AtomUI</RootNamespace>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>GeneratedFiles</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <Compile Remove="$(CompilerGeneratedFilesOutputPath)/**/*.cs"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../AtomUI.Localization/AtomUI.Localization.csproj" />
        <ProjectReference Include="../AtomUI.Generator/AtomUI.Generator.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"
                          PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets/**/*.*"/>
        <EmbeddedResource Include="../../docs/reference/theming/schemas/atomui-theme-v1.xsd"
                          LogicalName="AtomUI.Theme.Definitions.Schemas.atomui-theme-v1.xsd" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.X11" />
        <PackageReference Include="Avalonia.Native" />
        <PackageReference Include="Avalonia.Win32" />
        <PackageReference Include="Avalonia"/>
        <PackageReference Include="ReactiveUI.Avalonia"/>
        <PackageReference Include="System.Reactive"/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="AtomUI.Controls"/>
        <InternalsVisibleTo Include="AtomUI.Controls.Shared"/>
        <InternalsVisibleTo Include="AtomUI.Desktop.Controls"/>
        <InternalsVisibleTo Include="AtomUI.Desktop.Controls.DataGrid"/>
        <InternalsVisibleTo Include="AtomUI.Desktop.Controls.ColorPicker"/>
        <InternalsVisibleTo Include="AtomUI.Desktop.Controls.Extras"/>
        <InternalsVisibleTo Include="AtomUI.Desktop.Controls.Tests"/>
        <InternalsVisibleTo Include="AtomUI.Core.Tests"/>
    </ItemGroup>

    <ItemGroup>
        <AssemblyMetadata Include="AvaloniaVersion" Value="$(AvaloniaVersion)" />
        <AssemblyMetadata Include="AtomUIVersion" Value="$(AtomUIVersion)" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="AvaloniaUI.DiagnosticsSupport"/>
    </ItemGroup>

</Project>
