<Project Sdk="Microsoft.NET.Sdk"
         TreatAsLocalProperty="IsAotCompatible;EnableAotAnalyzer;EnableTrimAnalyzer;EnableSingleFileAnalyzer;PublishAot;PublishTrimmed;PublishSingleFile;SelfContained;RuntimeIdentifier">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <Nullable>enable</Nullable>
        <RootNamespace>AtomUI.Toolkits.GalleryBase.Generator</RootNamespace>
        <IsRoslynComponent>true</IsRoslynComponent>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <IncludeInPublish>false</IncludeInPublish>
        <IsAotCompatible>false</IsAotCompatible>
        <EnableAotAnalyzer>false</EnableAotAnalyzer>
        <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
        <EnableSingleFileAnalyzer>false</EnableSingleFileAnalyzer>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <None Include="$(OutputPath)/$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
    </ItemGroup>
</Project>
