using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.Cascader;

[LanguageProvider(LanguageCode.en_US, CascaderShowCase.LanguageId)]
internal class en_US : LanguageProvider
{
    public const string BasicTitle = "Basic";
    public const string BasicDescription = "Cascade selection box for selecting province/city/district.";
    public const string DefaultValueTitle = "Default value";
    public const string DefaultValueDescription = "Specifies default value by an array.";
    public const string HoverTitle = "Hover";
    public const string HoverDescription = "Hover to expand sub menu, click to select option.";
    public const string DisabledOptionTitle = "Disabled option";
    public const string DisabledOptionDescription = "Disable option by specifying the disabled property in options.";
    public const string ChangeOnSelectTitle = "Change on select";
    public const string ChangeOnSelectDescription = "Allows the selection of only parent options.";
    public const string MultipleTitle = "Multiple";
    public const string MultipleDescription = "Select multiple options. Disable the checkbox by adding the disableCheckbox property and selecting a specific item. The style of the disable can be modified by the className.";
    public const string ShowCheckedStrategyTitle = "ShowCheckedStrategy";
    public const string ShowCheckedStrategyDescription = "Shows a selected item in a box using showCheckedStrategy.";
    public const string SearchTitle = "Search";
    public const string SearchDescription = "Search and select options directly.";
    public const string LoadOptionsLazilyTitle = "Load Options Lazily";
    public const string LoadOptionsLazilyDescription = "Load options lazily with loadData.";
    public const string PrefixAndSuffixTitle = "Prefix and Suffix";
    public const string PrefixAndSuffixDescription = "Use prefix to customize the prefix content, use suffixIcon to customize the selection box suffix icon, and use expandIcon to customize the current item expand icon.";
    public const string VariantsTitle = "Variants";
    public const string VariantsDescription = "Variants of Cascader, there are four variants: outlined filled borderless and underlined.";
    public const string PlacementTitle = "Placement";
    public const string PlacementDescription = "You can manually specify the position of the popup via placement.";
    public const string StatusTitle = "Status";
    public const string StatusDescription = "Add status to Cascader with status, which could be error or warning.";
    public const string SizeTitle = "Size";
    public const string SizeDescription = "Cascade selection box of different sizes.";
    public const string BasicCascaderViewTitle = "Basic CascaderView";
    public const string BasicCascaderViewDescription = "The most basic usage.";
    public const string GenerateByTemplateTitle = "Generate by template";
    public const string GenerateByTemplateDescription = "You can use the Template mechanism to generate tree nodes";
    public const string SearchableTitle = "Searchable";
    public const string SearchableDescription = "Searchable CascaderView.";
    public const string SearchableItemsSourceTitle = "Searchable";
    public const string SearchableItemsSourceDescription = "Searchable CascaderView with ItemsSource.";
    public const string DefaultExpandedTitle = "Default expanded";
    public const string DefaultExpandedDescription = "You can set the default expansion path..";
    public const string P2PlaceholderTextPleaseSelect = "Please select";
    public const string P2TitleShowcheckedstrategyAll = "ShowCheckedStrategy=All";
    public const string P2TitleShowcheckedstrategyShowparent = "ShowCheckedStrategy=ShowParent";
    public const string P2HeaderZhejiang = "Zhejiang";
    public const string P2HeaderHangzhou = "Hangzhou";
    public const string P2HeaderWestLake = "West Lake";
    public const string P2HeaderLingyinShi = "Lingyin shi";
    public const string P2HeaderHefangJie = "Hefang jie";
    public const string P2HeaderNingbo = "Ningbo";
    public const string P2HeaderTianyiPavilion = "Tianyi Pavilion";
    public const string P2HeaderMoonLake = "Moon Lake";
    public const string P2HeaderJiangsu = "Jiangsu";
    public const string P2HeaderNanjing = "Nanjing";
    public const string P2HeaderZhongHuaMen = "Zhong Hua Men";
    public const string P2HeaderSunYatSenMausoleum = "Sun Yat-sen Mausoleum";
    public const string P2HeaderSuzhou = "Suzhou";
    public const string P2HeaderHumbleAdministratorsGarden = "Humble Administrator's Garden";
    public const string P2HeaderLingeringGarden = "Lingering Garden";
    public const string P2PlaceholderTextSearch = "Search";
    public const string P2HeaderXisha = "Xisha";
    public const string P2HeaderLight = "Light";
    public const string P2HeaderBamboo = "Bamboo";
    public const string P2HeaderLittle = "Little";
    public const string P2HeaderBambooBoy = "Bamboo Boy";
    public const string P2HeaderTadpole = "Tadpole";
    public const string P2HeaderLittleTadpole = "Little Tadpole";
    public const string P2HeaderZhangSan = "Zhang San";
    public const string P2HeaderGreen = "Green";
    public const string P2HeaderWildWolf = "Wild Wolf";
    public const string P2HeaderGrayWolf = "Gray Wolf";
    public const string P2HeaderYellow = "Yellow";
    public const string P2HeaderJiaoTailang = "Jiao Tailang";
    public const string P2HeaderBanban = "Banban";
    public const string P2HeaderBig = "Big";
    public const string P2HeaderFeifei = "Feifei";
    public const string P2HeaderXiaoXingxing = "Xiao Xingxing";
    public const string P2HeaderXiaoHuihui = "Xiao Huihui";
    public const string P2HeaderDynamicOptionFormat = "{0} Dynamic {1}";
    public const string P2TitleByTemplate = "By template";
    public const string P2TextPlacement = "Placement:";
    public const string P2ContentTopleft = "TopLeft";
    public const string P2ContentTopright = "TopRight";
    public const string P2ContentBottomleft = "BottomLeft";
    public const string P2ContentBottomright = "BottomRight";

    protected override Type GetResourceKindType() => typeof(CascaderShowCaseLangResourceKind);
}
