using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.Cascader;

[LanguageProvider(LanguageCode.zh_CN, CascaderShowCase.LanguageId)]
internal partial class zh_CN : LanguageProvider
{
    public const string ScenarioBasic = "基础";
    public const string ScenarioMultiple = "多选";
    public const string ScenarioAdvanced = "高级";
    public const string ScenarioCascaderView = "级联视图";
    public const string BasicTitle = "基础用法";
    public const string BasicDescription = "用于选择省、市、区的级联选择框。";
    public const string DefaultValueTitle = "默认值";
    public const string DefaultValueDescription = "通过数组指定默认值。";
    public const string HoverTitle = "悬停展开";
    public const string HoverDescription = "悬停展开子菜单，点击选择选项。";
    public const string DisabledOptionTitle = "禁用选项";
    public const string DisabledOptionDescription = "通过在 options 中指定 disabled 属性禁用选项。";
    public const string ChangeOnSelectTitle = "选择即变化";
    public const string ChangeOnSelectDescription = "允许只选择父级选项。";
    public const string MultipleTitle = "多选";
    public const string MultipleDescription = "选择多个选项。可以通过添加 disableCheckbox 属性禁用复选框并选择特定项，禁用样式可通过 className 修改。";
    public const string ShowCheckedStrategyTitle = "显示选中策略";
    public const string ShowCheckedStrategyDescription = "使用 showCheckedStrategy 在选择框中展示选中项。";
    public const string SearchTitle = "搜索";
    public const string SearchDescription = "直接搜索并选择选项。";
    public const string LoadOptionsLazilyTitle = "懒加载选项";
    public const string LoadOptionsLazilyDescription = "使用 loadData 懒加载选项。";
    public const string PrefixAndSuffixTitle = "前缀和后缀";
    public const string PrefixAndSuffixDescription = "使用 prefix 自定义前缀内容，使用 suffixIcon 自定义选择框后缀图标，使用 expandIcon 自定义当前项展开图标。";
    public const string VariantsTitle = "变体";
    public const string VariantsDescription = "Cascader 提供四种变体：描边、填充、无边框和下划线。";
    public const string PlacementTitle = "弹出位置";
    public const string PlacementDescription = "可以通过 placement 手动指定弹出层位置。";
    public const string StatusTitle = "状态";
    public const string StatusDescription = "通过 status 为 Cascader 添加状态，可设置为错误或警告。";
    public const string SizeTitle = "尺寸";
    public const string SizeDescription = "不同尺寸的级联选择框。";
    public const string BasicCascaderViewTitle = "基础 CascaderView";
    public const string BasicCascaderViewDescription = "最基础的用法。";
    public const string GenerateByTemplateTitle = "使用模板生成";
    public const string GenerateByTemplateDescription = "可以使用 Template 机制生成树节点。";
    public const string SearchableTitle = "可搜索";
    public const string SearchableDescription = "可搜索的 CascaderView。";
    public const string SearchableItemsSourceTitle = "可搜索";
    public const string SearchableItemsSourceDescription = "使用 ItemsSource 的可搜索 CascaderView。";
    public const string DefaultExpandedTitle = "默认展开";
    public const string DefaultExpandedDescription = "可以设置默认展开路径。";
    public const string P2PlaceholderTextPleaseSelect = "请选择";
    public const string P2TitleShowcheckedstrategyAll = "ShowCheckedStrategy=All";
    public const string P2TitleShowcheckedstrategyShowparent = "ShowCheckedStrategy=ShowParent";
    public const string P2HeaderZhejiang = "浙江";
    public const string P2HeaderHangzhou = "杭州";
    public const string P2HeaderWestLake = "西湖";
    public const string P2HeaderLingyinShi = "灵隐寺";
    public const string P2HeaderHefangJie = "河坊街";
    public const string P2HeaderNingbo = "宁波";
    public const string P2HeaderTianyiPavilion = "天一阁";
    public const string P2HeaderMoonLake = "月湖";
    public const string P2HeaderJiangsu = "江苏";
    public const string P2HeaderNanjing = "南京";
    public const string P2HeaderZhongHuaMen = "中华门";
    public const string P2HeaderSunYatSenMausoleum = "中山陵";
    public const string P2HeaderSuzhou = "苏州";
    public const string P2HeaderHumbleAdministratorsGarden = "拙政园";
    public const string P2HeaderLingeringGarden = "留园";
    public const string P2PlaceholderTextSearch = "搜索";
    public const string P2HeaderXisha = "西沙";
    public const string P2HeaderLight = "浅色";
    public const string P2HeaderBamboo = "竹子";
    public const string P2HeaderLittle = "小";
    public const string P2HeaderBambooBoy = "竹子男孩";
    public const string P2HeaderTadpole = "蝌蚪";
    public const string P2HeaderLittleTadpole = "小蝌蚪";
    public const string P2HeaderZhangSan = "张三";
    public const string P2HeaderGreen = "绿色";
    public const string P2HeaderWildWolf = "野狼";
    public const string P2HeaderGrayWolf = "灰狼";
    public const string P2HeaderYellow = "黄色";
    public const string P2HeaderJiaoTailang = "蕉太狼";
    public const string P2HeaderBanban = "班班";
    public const string P2HeaderBig = "大";
    public const string P2HeaderFeifei = "飞飞";
    public const string P2HeaderXiaoXingxing = "小星星";
    public const string P2HeaderXiaoHuihui = "小灰灰";
    public const string P2HeaderDynamicOptionFormat = "{0} 动态 {1}";
    public const string P2TitleByTemplate = "通过模板";
    public const string P2TextPlacement = "弹出位置：";
    public const string P2ContentTopleft = "左上";
    public const string P2ContentTopright = "右上";
    public const string P2ContentBottomleft = "左下";
    public const string P2ContentBottomright = "右下";

    protected override Type GetResourceKindType() => typeof(CascaderShowCaseLangResourceKind);
}
