using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace AtomUI.Generator.DataMemberAccessors;

internal sealed class DataMemberAccessorSourceWriter
{
    private readonly SourceProductionContext _context;
    private readonly DataMemberAccessorTypeInfo _typeInfo;

    public DataMemberAccessorSourceWriter(SourceProductionContext context, DataMemberAccessorTypeInfo typeInfo)
    {
        _context  = context;
        _typeInfo = typeInfo;
    }

    public void Write()
    {
        _context.AddSource($"{_typeInfo.GeneratedClassName}.g.cs", SourceText.From(BuildSource(), Encoding.UTF8));
    }

    private string BuildSource()
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("using System.Runtime.CompilerServices;");
        source.AppendLine();
        source.AppendLine("namespace AtomUI.Controls.Data.Generated");
        source.AppendLine("{");
        source.AppendLine($"    internal static class {_typeInfo.GeneratedClassName}");
        source.AppendLine("    {");
        source.AppendLine("        [ModuleInitializer]");
        source.AppendLine("        internal static void Register()");
        source.AppendLine("        {");
        source.AppendLine("            global::AtomUI.Controls.Data.DataMemberAccessorRegistry.Register(");
        source.AppendLine($"                new global::AtomUI.Controls.Data.DataMemberAccessorDescriptor<{_typeInfo.TypeName}>(");
        source.Append("                    ");
        source.Append(BuildFactoryExpression());
        source.AppendLine(",");
        source.AppendLine("                    new global::AtomUI.Controls.Data.IDataMemberAccessor[]");
        source.AppendLine("                    {");

        foreach (var property in _typeInfo.Properties)
        {
            AppendPropertyAccessor(source, property);
        }

        source.AppendLine("                    },");
        source.Append("                    ");
        source.Append(ToBoolLiteral(_typeInfo.IsDataTypeReadOnly));
        source.AppendLine("));");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("}");
        return source.ToString();
    }

    private string BuildFactoryExpression()
    {
        if (!_typeInfo.CanCreateFactory)
        {
            return "null";
        }

        return $"static () => new {_typeInfo.TypeName}()";
    }

    private void AppendPropertyAccessor(StringBuilder source, DataMemberAccessorPropertyInfo property)
    {
        source.Append("                        new global::AtomUI.Controls.Data.DataMemberAccessor<");
        source.Append(_typeInfo.TypeName);
        source.Append(", ");
        source.Append(property.TypeName);
        source.Append(">(");
        source.Append(ToStringLiteral(property.Name));
        source.Append(", ");
        source.Append("static instance => instance.");
        source.Append(property.Name);

        if (property.CanWrite)
        {
            source.Append(", static (instance, value) => instance.");
            source.Append(property.Name);
            source.Append(" = value");
        }

        source.Append(", metadata: ");
        source.Append(BuildMetadataExpression(property));

        source.AppendLine("),");
    }

    private string BuildMetadataExpression(DataMemberAccessorPropertyInfo property)
    {
        if (property.DisplayName == null &&
            property.AutoGenerateField == null &&
            property.Order == null &&
            !property.IsReadOnly &&
            property.IsEditable)
        {
            return "global::AtomUI.Controls.Data.DataMemberAccessorMetadata.Default";
        }

        var source = new StringBuilder("new global::AtomUI.Controls.Data.DataMemberAccessorMetadata(");
        source.Append("displayName: ");
        source.Append(ToNullableStringLiteral(property.DisplayName));
        source.Append(", autoGenerateField: ");
        source.Append(ToNullableBoolLiteral(property.AutoGenerateField));
        source.Append(", order: ");
        source.Append(ToNullableIntLiteral(property.Order));
        source.Append(", isReadOnly: ");
        source.Append(ToBoolLiteral(property.IsReadOnly));
        source.Append(", isEditable: ");
        source.Append(ToBoolLiteral(property.IsEditable));
        source.Append(")");
        return source.ToString();
    }

    private static string ToNullableStringLiteral(string? value)
    {
        return value == null ? "null" : ToStringLiteral(value);
    }

    private static string ToNullableBoolLiteral(bool? value)
    {
        return value.HasValue ? ToBoolLiteral(value.Value) : "null";
    }

    private static string ToNullableIntLiteral(int? value)
    {
        return value.HasValue ? value.Value.ToString(System.Globalization.CultureInfo.InvariantCulture) : "null";
    }

    private static string ToBoolLiteral(bool value)
    {
        return value ? "true" : "false";
    }

    private static string ToStringLiteral(string value)
    {
        return SyntaxFactory.LiteralExpression(
                                SyntaxKind.StringLiteralExpression,
                                SyntaxFactory.Literal(value))
                            .ToFullString();
    }
}
