using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using System.Xml.Linq;
using AtomUI.Generator.Diagnostics;
using AtomUI.Generator.LinkedRegistration.Manifest;
using AtomUI.Generator.LinkedRegistration.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Operations;
using Microsoft.CodeAnalysis.Text;

namespace AtomUI.Generator.LinkedRegistration;

[Generator]
public sealed class LinkedRegistrationUsageGenerator : IIncrementalGenerator
{
    private const string AxamlUsageMetadata =
        "build_metadata.AdditionalFiles.AtomUIAxamlUsage";
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var input = context.CompilationProvider
                           .Combine(context.AdditionalTextsProvider.Collect())
                           .Combine(context.AnalyzerConfigOptionsProvider);
        context.RegisterSourceOutput(input, static (productionContext, value) =>
        {
            Generate(
                productionContext,
                value.Left.Left,
                value.Left.Right,
                value.Right);
        });
    }

    private static void Generate(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<AdditionalText> additionalTexts,
        AnalyzerConfigOptionsProvider optionsProvider)
    {
        var catalog = LinkedRegistrationManifestCatalog.Create(compilation, context.ReportDiagnostic);
        if (LinkedRegistrationOptions.GetDeclaredPackageId(optionsProvider).Length != 0)
        {
            ValidateMarkedAxamlInputs(
                context,
                additionalTexts,
                optionsProvider);
            context.AddSource(
                "LinkedRegistrationUsage.g.cs",
                GeneratedSourceText.From("// <auto-generated />\n#nullable enable\n"));
            return;
        }

        var collector = new UsageCollector(
            compilation,
            catalog,
            LinkedRegistrationOptions.IsLinkedPublish(optionsProvider) ||
            LinkedRegistrationOptions.IsRegistrationStrict(optionsProvider),
            LinkedRegistrationOptions.IsRegistrationStrict(optionsProvider),
            LinkedRegistrationOptions.GetProjectDirectory(optionsProvider),
            context.ReportDiagnostic);

        collector.CollectCSharp(context.CancellationToken);
        foreach (var text in additionalTexts.OrderBy(static item => item.Path, StringComparer.Ordinal))
        {
            if (optionsProvider.GetOptions(text).TryGetValue(AxamlUsageMetadata, out var enabled) &&
                string.Equals(enabled, "true", StringComparison.OrdinalIgnoreCase))
            {
                collector.CollectAxaml(text, context.CancellationToken);
            }
        }
        collector.CompleteFallbacks();

        if (LinkedRegistrationOptions.IsLinkedPublish(optionsProvider) &&
            LinkedRegistrationOptions.IsRegistrationPlanOwner(optionsProvider))
        {
            collector.ReportMissingEntries();
        }

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        foreach (var usage in collector.GetOrderedUsages())
        {
            LinkedRegistrationMetadataWriter.Write(source, usage.ToManifestRecord());
        }
        context.AddSource("LinkedRegistrationUsage.g.cs", GeneratedSourceText.From(source.ToString()));
    }

    internal static IReadOnlyList<LinkedUsageInfo> CollectApplicationUsages(
        Compilation compilation,
        LinkedRegistrationManifestCatalog catalog,
        ImmutableArray<AdditionalText> additionalTexts,
        AnalyzerConfigOptionsProvider optionsProvider,
        CancellationToken cancellationToken,
        Action<Diagnostic> reportDiagnostic)
    {
        var collector = new UsageCollector(
            compilation,
            catalog,
            LinkedRegistrationOptions.IsLinkedPublish(optionsProvider) ||
            LinkedRegistrationOptions.IsRegistrationStrict(optionsProvider),
            LinkedRegistrationOptions.IsRegistrationStrict(optionsProvider),
            LinkedRegistrationOptions.GetProjectDirectory(optionsProvider),
            reportDiagnostic);
        collector.CollectCSharp(cancellationToken);
        foreach (var text in additionalTexts.OrderBy(static item => item.Path, StringComparer.Ordinal))
        {
            if (optionsProvider.GetOptions(text).TryGetValue(AxamlUsageMetadata, out var enabled) &&
                string.Equals(enabled, "true", StringComparison.OrdinalIgnoreCase))
            {
                collector.CollectAxaml(text, cancellationToken);
            }
        }
        collector.CompleteFallbacks();
        return collector.GetOrderedUsages();
    }

    private static void ValidateMarkedAxamlInputs(
        SourceProductionContext context,
        ImmutableArray<AdditionalText> additionalTexts,
        AnalyzerConfigOptionsProvider optionsProvider)
    {
        foreach (var text in additionalTexts.OrderBy(static item => item.Path, StringComparer.Ordinal))
        {
            if (!optionsProvider.GetOptions(text).TryGetValue(AxamlUsageMetadata, out var enabled) ||
                !string.Equals(enabled, "true", StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            var content = text.GetText(context.CancellationToken)?.ToString();
            if (string.IsNullOrWhiteSpace(content))
            {
                ReportProtocolError(
                    context.ReportDiagnostic,
                    text.Path,
                    "marked AXAML usage input is empty");
            }
            else if (!LinkedAxamlUsageInput.TryParse(content!, out _, out var validationError))
            {
                ReportProtocolError(context.ReportDiagnostic, text.Path, validationError);
            }
        }
    }

    private sealed class UsageCollector
    {
        private readonly Compilation _compilation;
        private readonly LinkedRegistrationManifestCatalog _catalog;
        private readonly bool _reportFallbackDiagnostics;
        private readonly bool _strict;
        private readonly string _projectDirectory;
        private readonly Action<Diagnostic> _reportDiagnostic;
        private readonly Dictionary<string, LinkedUsageInfo> _usages =
            new(StringComparer.Ordinal);
        private readonly List<DynamicUse> _dynamicUses = [];
        private readonly List<AxamlUncertainty> _axamlUncertainties = [];
        private readonly HashSet<string> _invokedPackages = new(StringComparer.Ordinal);
        private readonly HashSet<string> _explicitPackageRoots = new(StringComparer.Ordinal);
        private readonly Dictionary<string, HashSet<string>> _axamlPackagesBySource =
            new(StringComparer.Ordinal);

        internal UsageCollector(
            Compilation compilation,
            LinkedRegistrationManifestCatalog catalog,
            bool reportFallbackDiagnostics,
            bool strict,
            string projectDirectory,
            Action<Diagnostic> reportDiagnostic)
        {
            _compilation = compilation;
            _catalog = catalog;
            _reportFallbackDiagnostics = reportFallbackDiagnostics;
            _strict = strict;
            _projectDirectory = projectDirectory;
            _reportDiagnostic = reportDiagnostic;
        }

        internal void CollectCSharp(CancellationToken cancellationToken)
        {
            CollectNamespace(_compilation.Assembly.GlobalNamespace);
            foreach (var tree in _compilation.SyntaxTrees.OrderBy(
                         static item => item.FilePath,
                         StringComparer.Ordinal))
            {
                cancellationToken.ThrowIfCancellationRequested();
                var model = _compilation.GetSemanticModel(tree);
                foreach (var node in tree.GetRoot(cancellationToken).DescendantNodes())
                {
                    switch (node)
                    {
                        case ObjectCreationExpressionSyntax objectCreation
                            when model.GetOperation(objectCreation, cancellationToken) is
                                IObjectCreationOperation operation:
                            AddType(operation.Type, operation.Syntax.GetLocation());
                            break;
                        case ImplicitObjectCreationExpressionSyntax implicitCreation
                            when model.GetOperation(implicitCreation, cancellationToken) is
                                IObjectCreationOperation operation:
                            AddType(operation.Type, operation.Syntax.GetLocation());
                            break;
                        case TypeOfExpressionSyntax typeOfExpression
                            when model.GetOperation(typeOfExpression, cancellationToken) is
                                ITypeOfOperation operation:
                            AddType(operation.TypeOperand, operation.Syntax.GetLocation());
                            break;
                        case InvocationExpressionSyntax invocationExpression
                            when model.GetOperation(invocationExpression, cancellationToken) is
                                IInvocationOperation operation:
                            CollectInvocation(operation);
                            break;
                    }
                }
            }
        }

        internal void CollectAxaml(AdditionalText text, CancellationToken cancellationToken)
        {
            var content = text.GetText(cancellationToken)?.ToString();
            if (string.IsNullOrWhiteSpace(content))
            {
                ReportProtocolError(text.Path, "marked AXAML usage input is empty");
                return;
            }

            if (!LinkedAxamlUsageInput.TryParse(content!, out var root, out var validationError))
            {
                ReportProtocolError(text.Path, validationError);
                return;
            }

            var elements = root!.Elements().ToArray();
            foreach (var element in elements.Where(IsExplicitRootUsage))
            {
                CollectAxamlUsage(element);
            }
            foreach (var element in elements.Where(static element =>
                         string.Equals(element.Name.LocalName, "Usage", StringComparison.Ordinal) &&
                         !IsExplicitRootUsage(element)))
            {
                CollectResolvedAxamlPackageEvidence(element);
            }
            foreach (var element in elements.Where(static element => !IsExplicitRootUsage(element)))
            {
                if (string.Equals(element.Name.LocalName, "Usage", StringComparison.Ordinal))
                {
                    CollectAxamlUsage(element);
                }
                else if (string.Equals(element.Name.LocalName, "Uncertainty", StringComparison.Ordinal))
                {
                    _axamlUncertainties.Add(new AxamlUncertainty(
                        LinkedAxamlUsageInput.GetAttribute(element, "Source"),
                        LinkedAxamlUsageInput.GetIntAttribute(element, "Line"),
                        LinkedAxamlUsageInput.GetIntAttribute(element, "Column"),
                        LinkedAxamlUsageInput.GetAttribute(element, "Reason"),
                        LinkedAxamlUsageInput.GetAttribute(element, "Value"),
                        LinkedAxamlUsageInput.GetAttribute(element, "PackageId")));
                }
            }
        }

        private static bool IsExplicitRootUsage(XElement element)
        {
            if (!string.Equals(element.Name.LocalName, "Usage", StringComparison.Ordinal))
            {
                return false;
            }
            var kind = LinkedAxamlUsageInput.GetAttribute(element, "Kind");
            return string.Equals(kind, "PackageRoot", StringComparison.Ordinal) ||
                   string.Equals(kind, "UnitRoot", StringComparison.Ordinal);
        }

        private void CollectResolvedAxamlPackageEvidence(XElement element)
        {
            var source = LinkedAxamlUsageInput.GetAttribute(element, "Source");
            var metadataName = LinkedAxamlUsageInput.GetAttribute(element, "TypeName");
            var namespaceUri = LinkedAxamlUsageInput.GetAttribute(element, "NamespaceUri");
            var localName = LinkedAxamlUsageInput.GetAttribute(element, "LocalName");
            if (metadataName.Length == 0)
            {
                metadataName = LinkedAxamlUsageInput.ResolveMetadataName(
                    _catalog,
                    namespaceUri,
                    localName);
            }
            if (_catalog.ControlMaps.TryGetValue(metadataName, out var controlMap))
            {
                AddAxamlPackage(source, controlMap.PackageId);
                return;
            }

            var knownType = LinkedAxamlUsageInput.ResolveKnownType(
                _compilation,
                _catalog,
                metadataName,
                namespaceUri,
                localName);
            if (knownType is not null &&
                IsControlType(knownType) &&
                _catalog.TryGetPackageId(knownType.ContainingAssembly, out var owningPackage))
            {
                AddAxamlPackage(source, owningPackage);
            }
        }

        internal void CompleteFallbacks()
        {
            foreach (var dynamicUse in _dynamicUses.OrderBy(
                         static item => item.Source,
                         StringComparer.Ordinal).ThenBy(static item => item.Line)
                                              .ThenBy(static item => item.Column))
            {
                if (_explicitPackageRoots.Count != 1)
                {
                    ReportInvalidScope("Package", dynamicUse.Identity, dynamicUse.Location);
                    continue;
                }

                var packageId = _explicitPackageRoots.Single();
                AddPackageFallback(
                    packageId,
                    dynamicUse.Source,
                    dynamicUse.Line,
                    dynamicUse.Column,
                    dynamicUse.Location,
                    AtomUIDiagnosticDescriptors.LinkedDynamicUsageWidened,
                    dynamicUse.Identity);
            }

            foreach (var uncertainty in _axamlUncertainties.OrderBy(
                         static item => item.Source,
                         StringComparer.Ordinal).ThenBy(static item => item.Line)
                                              .ThenBy(static item => item.Column)
                                              .ThenBy(static item => item.Reason, StringComparer.Ordinal)
                                              .ThenBy(static item => item.Value, StringComparer.Ordinal))
            {
                if (uncertainty.PackageId.Length != 0 &&
                    !_catalog.Packages.ContainsKey(uncertainty.PackageId))
                {
                    ReportInvalidScope(
                        "Package",
                        uncertainty.PackageId,
                        CreateLocation(uncertainty.Source, uncertainty.Line, uncertainty.Column));
                    continue;
                }
                var packages = ResolveAxamlUncertaintyPackages(uncertainty);
                if (packages.Count != 1)
                {
                    ReportInvalidScope(
                        "Package",
                        uncertainty.Source + ":" + uncertainty.Reason,
                        CreateLocation(uncertainty.Source, uncertainty.Line, uncertainty.Column));
                    continue;
                }

                var packageId = packages.Single();
                var descriptor = IsLooseOrDynamic(uncertainty.Reason)
                    ? AtomUIDiagnosticDescriptors.LinkedLooseAxamlWidened
                    : AtomUIDiagnosticDescriptors.LinkedDynamicUsageWidened;
                AddPackageFallback(
                    packageId,
                    uncertainty.Source,
                    uncertainty.Line,
                    uncertainty.Column,
                    CreateLocation(uncertainty.Source, uncertainty.Line, uncertainty.Column),
                    descriptor,
                    uncertainty.Value.Length == 0 ? uncertainty.Reason : uncertainty.Value);
            }
        }

        internal void ReportMissingEntries()
        {
            foreach (var entry in _catalog.ReferencedUsages.Where(static usage =>
                         usage.Kind == LinkedUsageKind.Entry))
            {
                _invokedPackages.Add(entry.Identity);
            }
            var usedPackages = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (var usage in _catalog.ReferencedUsages.Concat(_usages.Values))
            {
                var packageId = GetUsagePackage(usage);
                if (packageId.Length != 0 && !usedPackages.ContainsKey(packageId))
                {
                    usedPackages.Add(packageId, usage.Source);
                }
            }

            foreach (var package in usedPackages.OrderBy(static item => item.Key, StringComparer.Ordinal))
            {
                if (!_invokedPackages.Contains(package.Key))
                {
                    _reportDiagnostic(Diagnostic.Create(
                        AtomUIDiagnosticDescriptors.LinkedPackageEntryMissing,
                        Location.None,
                        package.Key,
                        package.Value));
                }
            }
        }

        internal IReadOnlyList<LinkedUsageInfo> GetOrderedUsages()
        {
            return _usages.Values.OrderBy(static item => item.Source, StringComparer.Ordinal)
                          .ThenBy(static item => item.Line)
                          .ThenBy(static item => item.Column)
                          .ThenBy(static item => item.Kind)
                          .ThenBy(static item => item.Identity, StringComparer.Ordinal)
                          .ToArray();
        }

        private void CollectNamespace(INamespaceSymbol namespaceSymbol)
        {
            foreach (var type in namespaceSymbol.GetTypeMembers().OrderBy(
                         static item => item.MetadataName,
                         StringComparer.Ordinal))
            {
                CollectNamedType(type);
            }
            foreach (var child in namespaceSymbol.GetNamespaceMembers().OrderBy(
                         static item => item.Name,
                         StringComparer.Ordinal))
            {
                CollectNamespace(child);
            }
        }

        private void CollectNamedType(INamedTypeSymbol type)
        {
            var location = GetSourceLocation(type);
            AddType(type.BaseType, location);
            foreach (var interfaceType in type.Interfaces)
            {
                AddType(interfaceType, location);
            }
            foreach (var member in type.GetMembers())
            {
                switch (member)
                {
                    case IFieldSymbol field:
                        AddType(field.Type, GetSourceLocation(field));
                        break;
                    case IPropertySymbol property:
                        AddType(property.Type, GetSourceLocation(property));
                        foreach (var parameter in property.Parameters)
                        {
                            AddType(parameter.Type, GetSourceLocation(parameter));
                        }
                        break;
                    case IEventSymbol eventSymbol:
                        AddType(eventSymbol.Type, GetSourceLocation(eventSymbol));
                        break;
                    case IMethodSymbol method:
                        AddType(method.ReturnType, GetSourceLocation(method));
                        foreach (var parameter in method.Parameters)
                        {
                            AddType(parameter.Type, GetSourceLocation(parameter));
                        }
                        break;
                    case INamedTypeSymbol nested:
                        CollectNamedType(nested);
                        break;
                }
            }
        }

        private void CollectInvocation(IInvocationOperation invocation)
        {
            var target = invocation.TargetMethod.OriginalDefinition;
            var methodName = GetMethodMetadataName(target);
            if (_catalog.PackageIdsByEntry.TryGetValue(methodName, out var entryPackageIds))
            {
                var location = GetLocationInfo(invocation.Syntax.GetLocation());
                foreach (var packageId in entryPackageIds.OrderBy(
                             static packageId => packageId,
                             StringComparer.Ordinal))
                {
                    _invokedPackages.Add(packageId);
                    AddUsage(new LinkedUsageInfo(
                        LinkedUsageKind.Entry,
                        packageId,
                        location.Source,
                        location.Line,
                        location.Column,
                        packageId,
                        invocation.Syntax.GetLocation()));
                }
            }

            if (!IsDynamicCreationMethod(target))
            {
                return;
            }

            if (invocation.TargetMethod.IsGenericMethod && invocation.TargetMethod.TypeArguments.Length != 0)
            {
                if (invocation.TargetMethod.TypeArguments.Any(ContainsTypeParameter))
                {
                    AddDynamicUse(invocation, methodName);
                    return;
                }
                foreach (var typeArgument in invocation.TargetMethod.TypeArguments)
                {
                    AddType(typeArgument, invocation.Syntax.GetLocation());
                }
                return;
            }

            var typeArgumentOperation = invocation.Arguments.FirstOrDefault()?.Value;
            var resolvedType = ResolveRuntimeTypeValue(
                typeArgumentOperation,
                new HashSet<ISymbol>(SymbolEqualityComparer.Default));
            if (resolvedType is not null)
            {
                if (ContainsTypeParameter(resolvedType))
                {
                    AddDynamicUse(invocation, methodName);
                    return;
                }
                AddType(resolvedType, invocation.Syntax.GetLocation());
                return;
            }

            AddDynamicUse(invocation, methodName);
        }

        private void AddDynamicUse(IInvocationOperation invocation, string methodName)
        {
            var location = GetLocationInfo(invocation.Syntax.GetLocation());
            _dynamicUses.Add(new DynamicUse(
                methodName,
                location.Source,
                location.Line,
                location.Column,
                invocation.Syntax.GetLocation()));
        }

        private ITypeSymbol? ResolveRuntimeTypeValue(
            IOperation? operation,
            ISet<ISymbol> visitedSymbols)
        {
            while (operation is IConversionOperation conversion)
            {
                operation = conversion.Operand;
            }
            if (operation is ITypeOfOperation typeOfOperation)
            {
                return typeOfOperation.TypeOperand;
            }
            if (operation is not ILocalReferenceOperation localReference ||
                !visitedSymbols.Add(localReference.Local))
            {
                return null;
            }

            foreach (var syntaxReference in localReference.Local.DeclaringSyntaxReferences)
            {
                var syntax = syntaxReference.GetSyntax();
                var semanticModel = _compilation.GetSemanticModel(syntax.SyntaxTree);
                if (semanticModel.GetOperation(syntax) is IVariableDeclaratorOperation declarator &&
                    declarator.Initializer is not null)
                {
                    var resolved = ResolveRuntimeTypeValue(
                        declarator.Initializer.Value,
                        visitedSymbols);
                    if (resolved is not null)
                    {
                        return resolved;
                    }
                }
            }
            return null;
        }

        private void CollectAxamlUsage(XElement element)
        {
            var source = LinkedAxamlUsageInput.GetAttribute(element, "Source");
            var line = LinkedAxamlUsageInput.GetIntAttribute(element, "Line");
            var column = LinkedAxamlUsageInput.GetIntAttribute(element, "Column");
            var kind = LinkedAxamlUsageInput.GetAttribute(element, "Kind");
            var identity = LinkedAxamlUsageInput.GetAttribute(element, "Identity");
            var location = CreateLocation(source, line, column);

            if (string.Equals(kind, "PackageRoot", StringComparison.Ordinal))
            {
                if (!_catalog.Packages.ContainsKey(identity))
                {
                    ReportInvalidScope("Package", identity, location);
                    return;
                }
                _explicitPackageRoots.Add(identity);
                AddUsage(new LinkedUsageInfo(
                    LinkedUsageKind.PackageRoot,
                    identity,
                    source,
                    line,
                    column,
                    identity,
                    location));
                return;
            }

            if (string.Equals(kind, "UnitRoot", StringComparison.Ordinal))
            {
                if (!_catalog.PackageByUnit.TryGetValue(identity, out var unitPackage))
                {
                    ReportInvalidScope("Unit", identity, location);
                    return;
                }
                AddUsage(new LinkedUsageInfo(
                    LinkedUsageKind.UnitRoot,
                    identity,
                    source,
                    line,
                    column,
                    unitPackage,
                    location));
                return;
            }

            var metadataName = LinkedAxamlUsageInput.GetAttribute(element, "TypeName");
            var namespaceUri = LinkedAxamlUsageInput.GetAttribute(element, "NamespaceUri");
            var localName = LinkedAxamlUsageInput.GetAttribute(element, "LocalName");
            if (metadataName.Length == 0)
            {
                metadataName = LinkedAxamlUsageInput.ResolveMetadataName(
                    _catalog,
                    namespaceUri,
                    localName);
            }
            if (_catalog.ControlMaps.TryGetValue(metadataName, out var controlMap))
            {
                AddControlUsage(controlMap, source, line, column, location);
                AddAxamlPackage(source, controlMap.PackageId);
                return;
            }

            var knownType = LinkedAxamlUsageInput.ResolveKnownType(
                _compilation,
                _catalog,
                metadataName,
                namespaceUri,
                localName);
            if (knownType is not null)
            {
                if (SymbolEqualityComparer.Default.Equals(
                        knownType.ContainingAssembly,
                        _compilation.Assembly) ||
                    !_catalog.TryGetPackageId(knownType.ContainingAssembly, out var owningPackage) ||
                    !IsControlType(knownType))
                {
                    return;
                }

                AddPackageFallback(
                    owningPackage,
                    source,
                    line,
                    column,
                    location,
                    AtomUIDiagnosticDescriptors.LinkedDynamicUsageWidened,
                    metadataName.Length == 0 ? localName : metadataName);
                AddAxamlPackage(source, owningPackage);
                return;
            }

            var candidatePackages = LinkedAxamlUsageInput.ResolveCandidatePackages(
                _catalog,
                metadataName,
                namespaceUri,
                localName);
            if (candidatePackages.Count > 1 &&
                _axamlPackagesBySource.TryGetValue(source, out var sourcePackages))
            {
                candidatePackages.IntersectWith(sourcePackages);
            }
            if (candidatePackages.Count == 0 &&
                _axamlPackagesBySource.TryGetValue(source, out sourcePackages))
            {
                candidatePackages.UnionWith(sourcePackages);
            }
            if (candidatePackages.Count == 0)
            {
                candidatePackages.UnionWith(_explicitPackageRoots);
            }
            if (candidatePackages.Count > 1)
            {
                candidatePackages.IntersectWith(_explicitPackageRoots);
            }
            if (candidatePackages.Count != 1)
            {
                ReportInvalidScope(
                    "Package",
                    metadataName.Length == 0 ? localName : metadataName,
                    location);
                return;
            }
            var packageId = candidatePackages.Single();
            AddPackageFallback(
                packageId,
                source,
                line,
                column,
                location,
                AtomUIDiagnosticDescriptors.LinkedDynamicUsageWidened,
                metadataName.Length == 0 ? localName : metadataName);
            AddAxamlPackage(source, packageId);
        }

        private HashSet<string> ResolveAxamlUncertaintyPackages(AxamlUncertainty uncertainty)
        {
            var packages = new HashSet<string>(StringComparer.Ordinal);
            if (uncertainty.PackageId.Length != 0 &&
                _catalog.Packages.ContainsKey(uncertainty.PackageId))
            {
                packages.Add(uncertainty.PackageId);
                return packages;
            }
            if (_axamlPackagesBySource.TryGetValue(uncertainty.Source, out var sourcePackages))
            {
                packages.UnionWith(sourcePackages);
            }
            if (packages.Count == 0)
            {
                packages.UnionWith(_explicitPackageRoots);
            }
            return packages;
        }

        private void AddType(ITypeSymbol? type, Location? location)
        {
            switch (type)
            {
                case null:
                    return;
                case IArrayTypeSymbol array:
                    AddType(array.ElementType, location);
                    return;
                case IPointerTypeSymbol pointer:
                    AddType(pointer.PointedAtType, location);
                    return;
                case INamedTypeSymbol named:
                    var definition = named.OriginalDefinition;
                    var metadataName = GetTypeMetadataName(definition);
                    if (_catalog.ControlMaps.TryGetValue(metadataName, out var controlMap))
                    {
                        var sourceLocation = GetLocationInfo(location);
                        AddControlUsage(
                            controlMap,
                            sourceLocation.Source,
                            sourceLocation.Line,
                            sourceLocation.Column,
                            location);
                    }
                    foreach (var typeArgument in named.TypeArguments)
                    {
                        AddType(typeArgument, location);
                    }
                    return;
            }
        }

        private void AddControlUsage(
            LinkedControlMapManifestRecord controlMap,
            string source,
            int line,
            int column,
            Location? location)
        {
            AddUsage(new LinkedUsageInfo(
                LinkedUsageKind.Control,
                controlMap.MetadataName,
                source,
                line,
                column,
                controlMap.PackageId,
                location));
        }

        private void AddPackageFallback(
            string packageId,
            string source,
            int line,
            int column,
            Location? location,
            DiagnosticDescriptor descriptor,
            string value)
        {
            if (!_catalog.Packages.ContainsKey(packageId))
            {
                ReportInvalidScope("Package", packageId, location);
                return;
            }

            AddUsage(new LinkedUsageInfo(
                LinkedUsageKind.PackageRoot,
                packageId,
                source,
                line,
                column,
                packageId,
                location));
            ReportFallback(descriptor, location, value, packageId);
        }

        private void AddUsage(LinkedUsageInfo usage)
        {
            var key = usage.Kind is LinkedUsageKind.PackageRoot or
                LinkedUsageKind.UnitRoot or LinkedUsageKind.Entry
                ? string.Join("\u001f", usage.Kind.ToString(), usage.Identity)
                : string.Join(
                    "\u001f",
                    usage.Kind.ToString(),
                    usage.Identity,
                    usage.Source,
                    usage.Line.ToString(CultureInfo.InvariantCulture),
                    usage.Column.ToString(CultureInfo.InvariantCulture));
            if (!_usages.ContainsKey(key))
            {
                _usages.Add(key, usage);
            }
        }

        private void AddAxamlPackage(string source, string packageId)
        {
            if (!_axamlPackagesBySource.TryGetValue(source, out var packages))
            {
                packages = new HashSet<string>(StringComparer.Ordinal);
                _axamlPackagesBySource.Add(source, packages);
            }
            packages.Add(packageId);
        }

        private string GetUsagePackage(LinkedUsageInfo usage)
        {
            if (usage.PackageId.Length != 0)
            {
                return usage.PackageId;
            }
            return usage.Kind switch
            {
                LinkedUsageKind.Control when _catalog.ControlMaps.TryGetValue(
                    usage.Identity,
                    out var control) => control.PackageId,
                LinkedUsageKind.UnitRoot when _catalog.PackageByUnit.TryGetValue(
                    usage.Identity,
                    out var packageId) => packageId,
                LinkedUsageKind.PackageRoot or LinkedUsageKind.Entry => usage.Identity,
                _ => string.Empty
            };
        }

        private void ReportFallback(
            DiagnosticDescriptor descriptor,
            Location? location,
            string value,
            string packageId)
        {
            if (!_reportFallbackDiagnostics)
            {
                return;
            }

            var effectiveDescriptor = _strict ? AsError(descriptor) : descriptor;
            _reportDiagnostic(Diagnostic.Create(
                effectiveDescriptor,
                location ?? Location.None,
                value,
                packageId));
        }

        private void ReportInvalidScope(string kind, string identity, Location? location)
        {
            _reportDiagnostic(Diagnostic.Create(
                AtomUIDiagnosticDescriptors.LinkedExplicitRootInvalid,
                location ?? Location.None,
                kind,
                identity));
        }

        private void ReportProtocolError(string input, string detail)
        {
            _reportDiagnostic(Diagnostic.Create(
                AtomUIDiagnosticDescriptors.LinkedManifestVersionMismatch,
                Location.None,
                input,
                detail));
        }

        private Location? GetSourceLocation(ISymbol symbol)
        {
            return symbol.Locations.Where(static location => location.IsInSource)
                         .OrderBy(location => NormalizeSourcePath(
                             location.GetLineSpan().Path,
                             _projectDirectory), StringComparer.Ordinal)
                         .ThenBy(static location => location.SourceSpan.Start)
                         .ThenBy(static location => location.SourceSpan.Length)
                         .FirstOrDefault();
        }

        private SourceLocation GetLocationInfo(Location? location)
        {
            if (location is null || !location.IsInSource)
            {
                return new SourceLocation("<Unknown>", 0, 0);
            }
            var span = location.GetLineSpan();
            return new SourceLocation(
                NormalizeSourcePath(span.Path, _projectDirectory),
                span.StartLinePosition.Line + 1,
                span.StartLinePosition.Character + 1);
        }
    }

    private static bool IsDynamicCreationMethod(IMethodSymbol method)
    {
        var containingType = GetTypeMetadataName(method.ContainingType.OriginalDefinition);
        return (containingType == "System.Activator" && method.Name == "CreateInstance") ||
               (containingType == "System.Runtime.CompilerServices.RuntimeHelpers" &&
                method.Name == "GetUninitializedObject") ||
               (containingType == "System.Runtime.Serialization.FormatterServices" &&
                method.Name == "GetUninitializedObject");
    }

    private static bool ContainsTypeParameter(ITypeSymbol type)
    {
        return type switch
        {
            ITypeParameterSymbol => true,
            IArrayTypeSymbol array => ContainsTypeParameter(array.ElementType),
            IPointerTypeSymbol pointer => ContainsTypeParameter(pointer.PointedAtType),
            INamedTypeSymbol named => named.TypeArguments.Any(ContainsTypeParameter) ||
                                     (named.ContainingType is not null &&
                                      ContainsTypeParameter(named.ContainingType)),
            _ => false
        };
    }

    private static bool IsControlType(INamedTypeSymbol type)
    {
        for (var current = type; current is not null; current = current.BaseType)
        {
            if (GetTypeMetadataName(current.OriginalDefinition) == "Avalonia.Controls.Control")
            {
                return true;
            }
        }
        return false;
    }

    private static string GetMethodMetadataName(IMethodSymbol method)
    {
        return GetTypeMetadataName(method.ContainingType.OriginalDefinition) + "." + method.Name;
    }

    private static string GetTypeMetadataName(INamedTypeSymbol type)
    {
        var names = new Stack<string>();
        for (var current = type; current is not null; current = current.ContainingType)
        {
            names.Push(current.MetadataName);
        }
        var typeName = string.Join("+", names);
        return type.ContainingNamespace is { IsGlobalNamespace: false } namespaceSymbol
            ? namespaceSymbol.ToDisplayString() + "." + typeName
            : typeName;
    }

    private static string NormalizeSourcePath(string path, string projectDirectory)
    {
        var normalized = path.Replace('\\', '/');
        var comparison = IsWindowsStylePath(normalized) && IsWindowsStylePath(projectDirectory)
            ? StringComparison.OrdinalIgnoreCase
            : StringComparison.Ordinal;
        if (projectDirectory.Length != 0 &&
            normalized.StartsWith(projectDirectory, comparison))
        {
            return normalized.Substring(projectDirectory.Length).TrimStart('/');
        }
        return normalized;
    }

    private static bool IsWindowsStylePath(string path)
    {
        return (path.Length >= 3 &&
                char.IsLetter(path[0]) &&
                path[1] == ':' &&
                path[2] == '/') ||
               path.StartsWith("//", StringComparison.Ordinal);
    }

    private static void ReportProtocolError(
        Action<Diagnostic> reportDiagnostic,
        string input,
        string detail)
    {
        reportDiagnostic(Diagnostic.Create(
            AtomUIDiagnosticDescriptors.LinkedManifestVersionMismatch,
            Location.None,
            input,
            detail));
    }

    private static Location CreateLocation(string source, int line, int column)
    {
        var position = new LinePosition(Math.Max(0, line - 1), Math.Max(0, column - 1));
        return Location.Create(
            source.Length == 0 ? "<Unknown>" : source,
            new TextSpan(0, 0),
            new LinePositionSpan(position, position));
    }

    private static bool IsLooseOrDynamic(string reason)
    {
        return string.Equals(reason, "LooseAxaml", StringComparison.Ordinal) ||
               string.Equals(reason, "DynamicResourceSource", StringComparison.Ordinal);
    }

    private static DiagnosticDescriptor AsError(DiagnosticDescriptor descriptor)
    {
        return new DiagnosticDescriptor(
            descriptor.Id,
            descriptor.Title,
            descriptor.MessageFormat,
            descriptor.Category,
            DiagnosticSeverity.Error,
            descriptor.IsEnabledByDefault,
            descriptor.Description,
            descriptor.HelpLinkUri,
            descriptor.CustomTags.ToArray());
    }

    private sealed class SourceLocation
    {
        internal SourceLocation(string source, int line, int column)
        {
            Source = source;
            Line = line;
            Column = column;
        }

        internal string Source { get; }
        internal int Line { get; }
        internal int Column { get; }
    }

    private sealed class DynamicUse
    {
        internal DynamicUse(
            string identity,
            string source,
            int line,
            int column,
            Location location)
        {
            Identity = identity;
            Source = source;
            Line = line;
            Column = column;
            Location = location;
        }

        internal string Identity { get; }
        internal string Source { get; }
        internal int Line { get; }
        internal int Column { get; }
        internal Location Location { get; }
    }

    private sealed class AxamlUncertainty
    {
        internal AxamlUncertainty(
            string source,
            int line,
            int column,
            string reason,
            string value,
            string packageId)
        {
            Source = source;
            Line = line;
            Column = column;
            Reason = reason;
            Value = value;
            PackageId = packageId;
        }

        internal string Source { get; }
        internal int Line { get; }
        internal int Column { get; }
        internal string Reason { get; }
        internal string Value { get; }
        internal string PackageId { get; }
    }
}
