using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using System.Xml.Linq;
using AtomUI.Generator.Diagnostics;
using AtomUI.Generator.LinkedRegistration.Manifest;
using AtomUI.Generator.LinkedRegistration.Model;
using AtomUI.LinkedRegistration.Protocol;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Operations;
using Microsoft.CodeAnalysis.Text;

namespace AtomUI.Generator.LinkedRegistration;

[Generator]
public sealed class LinkedRegistrationUsageGenerator : IIncrementalGenerator
{
    private const string AxamlUsageMetadata =
        "build_metadata.AdditionalFiles.AtomUIAxamlUsage";
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var csharpCandidates = LinkedCSharpUsageCandidateProvider.Create(context).Collect();
        var input = context.CompilationProvider
                           .Combine(csharpCandidates)
                           .Combine(context.AdditionalTextsProvider.Collect())
                           .Combine(context.AnalyzerConfigOptionsProvider);
        context.RegisterSourceOutput(input, static (productionContext, value) =>
        {
            Generate(
                productionContext,
                value.Left.Left.Left,
                value.Left.Left.Right,
                value.Left.Right,
                value.Right);
        });
    }

    private static void Generate(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<LinkedCSharpUsageCandidate> csharpCandidates,
        ImmutableArray<AdditionalText> additionalTexts,
        AnalyzerConfigOptionsProvider optionsProvider)
    {
        var catalog = LinkedRegistrationManifestCatalog.Create(
            compilation,
            additionalTexts,
            optionsProvider,
            context.ReportDiagnostic);
        if (LinkedRegistrationOptions.GetDeclaredPackageId(optionsProvider).Length != 0)
        {
            ValidateMarkedAxamlInputs(
                context,
                additionalTexts,
                optionsProvider);
            context.AddSource(
                "LinkedRegistrationUsage.g.cs",
                GeneratedSourceText.From("// <auto-generated />\n#nullable enable\n"));
            return;
        }

        var collector = new UsageCollector(
            compilation,
            catalog,
            LinkedRegistrationOptions.IsLinkedPublish(optionsProvider) ||
            LinkedRegistrationOptions.IsRegistrationStrict(optionsProvider),
            LinkedRegistrationOptions.IsRegistrationStrict(optionsProvider),
            LinkedRegistrationOptions.GetProjectDirectory(optionsProvider),
            context.ReportDiagnostic);

        collector.CollectCSharp(csharpCandidates, context.CancellationToken);
        foreach (var text in additionalTexts.OrderBy(static item => item.Path, StringComparer.Ordinal))
        {
            if (optionsProvider.GetOptions(text).TryGetValue(AxamlUsageMetadata, out var enabled) &&
                string.Equals(enabled, "true", StringComparison.OrdinalIgnoreCase))
            {
                collector.CollectAxaml(text, context.CancellationToken);
            }
        }
        collector.CompleteFallbacks();

        if (LinkedRegistrationOptions.IsLinkedPublish(optionsProvider) &&
            LinkedRegistrationOptions.IsRegistrationPlanOwner(optionsProvider))
        {
            collector.ReportMissingEntries();
        }

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        foreach (var usage in collector.GetOrderedUsages())
        {
            LinkedRegistrationMetadataWriter.Write(source, usage.ToManifestRecord());
        }
        if (collector.AnalysisBudgetExceeded)
        {
            LinkedRegistrationMetadataWriter.Write(
                source,
                new LinkedFallbackManifestRecord(
                    string.Empty,
                    "AnalysisBudgetExceeded",
                    compilation.AssemblyName ?? "<application>",
                    0,
                    0));
        }
        context.AddSource("LinkedRegistrationUsage.g.cs", GeneratedSourceText.From(source.ToString()));
    }

    internal static IReadOnlyList<LinkedUsageInfo> CollectApplicationUsages(
        Compilation compilation,
        LinkedRegistrationManifestCatalog catalog,
        ImmutableArray<LinkedCSharpUsageCandidate> csharpCandidates,
        ImmutableArray<AdditionalText> additionalTexts,
        AnalyzerConfigOptionsProvider optionsProvider,
        CancellationToken cancellationToken,
        Action<Diagnostic> reportDiagnostic,
        out bool analysisBudgetExceeded)
    {
        var collector = new UsageCollector(
            compilation,
            catalog,
            LinkedRegistrationOptions.IsLinkedPublish(optionsProvider) ||
            LinkedRegistrationOptions.IsRegistrationStrict(optionsProvider),
            LinkedRegistrationOptions.IsRegistrationStrict(optionsProvider),
            LinkedRegistrationOptions.GetProjectDirectory(optionsProvider),
            reportDiagnostic);
        collector.CollectCSharp(csharpCandidates, cancellationToken);
        foreach (var text in additionalTexts.OrderBy(static item => item.Path, StringComparer.Ordinal))
        {
            if (optionsProvider.GetOptions(text).TryGetValue(AxamlUsageMetadata, out var enabled) &&
                string.Equals(enabled, "true", StringComparison.OrdinalIgnoreCase))
            {
                collector.CollectAxaml(text, cancellationToken);
            }
        }
        collector.CompleteFallbacks();
        analysisBudgetExceeded = collector.AnalysisBudgetExceeded;
        return collector.GetOrderedUsages();
    }

    private static void ValidateMarkedAxamlInputs(
        SourceProductionContext context,
        ImmutableArray<AdditionalText> additionalTexts,
        AnalyzerConfigOptionsProvider optionsProvider)
    {
        foreach (var text in additionalTexts.OrderBy(static item => item.Path, StringComparer.Ordinal))
        {
            if (!optionsProvider.GetOptions(text).TryGetValue(AxamlUsageMetadata, out var enabled) ||
                !string.Equals(enabled, "true", StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            var content = text.GetText(context.CancellationToken)?.ToString();
            if (string.IsNullOrWhiteSpace(content))
            {
                ReportProtocolError(
                    context.ReportDiagnostic,
                    text.Path,
                    "marked AXAML usage input is empty");
            }
            else if (!LinkedAxamlUsageInput.TryParse(content!, out _, out var validationError))
            {
                ReportProtocolError(context.ReportDiagnostic, text.Path, validationError);
            }
        }
    }

    private sealed class UsageCollector
    {
        private readonly Compilation _compilation;
        private readonly LinkedRegistrationManifestCatalog _catalog;
        private readonly bool _reportFallbackDiagnostics;
        private readonly bool _strict;
        private readonly string _projectDirectory;
        private readonly Action<Diagnostic> _reportDiagnostic;
        private readonly Dictionary<string, LinkedUsageInfo> _usages =
            new(StringComparer.Ordinal);
        private readonly List<DynamicUse> _dynamicUses = [];
        private readonly List<AxamlUncertainty> _axamlUncertainties = [];
        private readonly HashSet<string> _invokedPackages = new(StringComparer.Ordinal);
        private readonly HashSet<string> _explicitPackageRoots = new(StringComparer.Ordinal);
        private readonly Dictionary<string, HashSet<string>> _axamlPackagesBySource =
            new(StringComparer.Ordinal);
        private int _axamlCandidateCount;

        internal bool AnalysisBudgetExceeded { get; private set; }

        internal UsageCollector(
            Compilation compilation,
            LinkedRegistrationManifestCatalog catalog,
            bool reportFallbackDiagnostics,
            bool strict,
            string projectDirectory,
            Action<Diagnostic> reportDiagnostic)
        {
            _compilation = compilation;
            _catalog = catalog;
            _reportFallbackDiagnostics = reportFallbackDiagnostics;
            _strict = strict;
            _projectDirectory = projectDirectory;
            _reportDiagnostic = reportDiagnostic;
        }

        internal void CollectCSharp(
            IReadOnlyList<LinkedCSharpUsageCandidate> candidates,
            CancellationToken cancellationToken)
        {
            if (candidates.Count > LinkedRegistrationAnalysisBudget.MaxSourceCandidates)
            {
                AnalysisBudgetExceeded = true;
                foreach (var candidate in candidates)
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    CollectBudgetCandidate(candidate);
                }
                return;
            }

            foreach (var candidate in candidates.OrderBy(
                         static item => item.Source,
                         StringComparer.Ordinal).ThenBy(static item => item.SpanStart)
                                              .ThenBy(static item => item.Kind)
                                              .ThenBy(static item => item.Identity, StringComparer.Ordinal))
            {
                cancellationToken.ThrowIfCancellationRequested();
                var location = candidate.CreateLocation();
                switch (candidate.Kind)
                {
                    case LinkedCSharpUsageCandidateKind.Type:
                        AddType(candidate.Identity, location);
                        break;
                    case LinkedCSharpUsageCandidateKind.Call:
                        CollectInvocation(candidate, location);
                        break;
                    case LinkedCSharpUsageCandidateKind.Dynamic:
                        AddDynamicUse(candidate.Identity, location);
                        break;
                }
            }
        }

        internal void CollectAxaml(AdditionalText text, CancellationToken cancellationToken)
        {
            var sourceText = text.GetText(cancellationToken);
            if (sourceText is null || sourceText.Length == 0)
            {
                ReportProtocolError(text.Path, "marked AXAML usage input is empty");
                return;
            }
            if (sourceText.Length > LinkedRegistrationAnalysisBudget.MaxAxamlUsageBytes)
            {
                AnalysisBudgetExceeded = true;
                return;
            }
            var content = sourceText.ToString();
            if (Encoding.UTF8.GetByteCount(content) > LinkedRegistrationAnalysisBudget.MaxAxamlUsageBytes)
            {
                AnalysisBudgetExceeded = true;
                return;
            }
            if (string.IsNullOrWhiteSpace(content))
            {
                ReportProtocolError(text.Path, "marked AXAML usage input is empty");
                return;
            }

            if (!LinkedAxamlUsageInput.TryParse(content!, out var root, out var validationError))
            {
                ReportProtocolError(text.Path, validationError);
                return;
            }

            var elements = root!.Elements()
                .Take(LinkedRegistrationAnalysisBudget.MaxAxamlCandidates + 1)
                .ToArray();
            _axamlCandidateCount += elements.Length;
            if (elements.Length > LinkedRegistrationAnalysisBudget.MaxAxamlCandidates ||
                _axamlCandidateCount > LinkedRegistrationAnalysisBudget.MaxAxamlCandidates)
            {
                AnalysisBudgetExceeded = true;
                return;
            }
            foreach (var element in elements.Where(IsExplicitRootUsage))
            {
                CollectAxamlUsage(element);
            }
            foreach (var element in elements.Where(static element =>
                         string.Equals(element.Name.LocalName, "Usage", StringComparison.Ordinal) &&
                         !IsExplicitRootUsage(element)))
            {
                CollectResolvedAxamlPackageEvidence(element);
            }
            foreach (var element in elements.Where(static element => !IsExplicitRootUsage(element)))
            {
                if (string.Equals(element.Name.LocalName, "Usage", StringComparison.Ordinal))
                {
                    CollectAxamlUsage(element);
                }
                else if (string.Equals(element.Name.LocalName, "Uncertainty", StringComparison.Ordinal))
                {
                    _axamlUncertainties.Add(new AxamlUncertainty(
                        LinkedAxamlUsageInput.GetAttribute(element, "Source"),
                        LinkedAxamlUsageInput.GetIntAttribute(element, "Line"),
                        LinkedAxamlUsageInput.GetIntAttribute(element, "Column"),
                        LinkedAxamlUsageInput.GetAttribute(element, "Reason"),
                        LinkedAxamlUsageInput.GetAttribute(element, "Value"),
                        LinkedAxamlUsageInput.GetAttribute(element, "PackageId")));
                }
            }
        }

        private static bool IsExplicitRootUsage(XElement element)
        {
            if (!string.Equals(element.Name.LocalName, "Usage", StringComparison.Ordinal))
            {
                return false;
            }
            var kind = LinkedAxamlUsageInput.GetAttribute(element, "Kind");
            return string.Equals(kind, "PackageRoot", StringComparison.Ordinal) ||
                   string.Equals(kind, "UnitRoot", StringComparison.Ordinal);
        }

        private void CollectResolvedAxamlPackageEvidence(XElement element)
        {
            var source = LinkedAxamlUsageInput.GetAttribute(element, "Source");
            var metadataName = LinkedAxamlUsageInput.GetAttribute(element, "TypeName");
            var namespaceUri = LinkedAxamlUsageInput.GetAttribute(element, "NamespaceUri");
            var localName = LinkedAxamlUsageInput.GetAttribute(element, "LocalName");
            if (LinkedAxamlUsageInput.IsXamlLanguageNamespace(namespaceUri))
            {
                return;
            }
            if (metadataName.Length == 0)
            {
                metadataName = LinkedAxamlUsageInput.ResolveMetadataName(
                    _catalog,
                    namespaceUri,
                    localName);
            }
            if (_catalog.ControlMaps.TryGetValue(metadataName, out var controlMap))
            {
                AddAxamlPackage(source, controlMap.PackageId);
                return;
            }

            var knownType = LinkedAxamlUsageInput.ResolveKnownType(
                _compilation,
                _catalog,
                metadataName,
                namespaceUri,
                localName);
            if (knownType is not null &&
                IsControlType(knownType) &&
                _catalog.TryGetPackageId(knownType.ContainingAssembly, out var owningPackage))
            {
                AddAxamlPackage(source, owningPackage);
            }
        }

        internal void CompleteFallbacks()
        {
            if (AnalysisBudgetExceeded)
            {
                return;
            }

            foreach (var dynamicUse in _dynamicUses.OrderBy(
                         static item => item.Source,
                         StringComparer.Ordinal).ThenBy(static item => item.Line)
                                              .ThenBy(static item => item.Column))
            {
                var packages = _explicitPackageRoots.Count != 0
                    ? _explicitPackageRoots
                    : _invokedPackages;
                if (packages.Count == 0)
                {
                    ReportInvalidScope(
                        "Package",
                        dynamicUse.Identity,
                        dynamicUse.Location);
                    continue;
                }
                foreach (var packageId in packages.OrderBy(
                             static packageId => packageId,
                             StringComparer.Ordinal))
                {
                    // C# dynamic creation sites no longer widen the package: controls declared
                    // in the application are already covered by base-type evidence, and purely
                    // string-driven creation is covered by explicit Unit/Package roots. Report
                    // guidance only.
                    ReportFallback(
                        AtomUIDiagnosticDescriptors.LinkedDynamicUsageUncovered,
                        dynamicUse.Location,
                        dynamicUse.Identity,
                        packageId);
                }
            }

            foreach (var uncertainty in _axamlUncertainties.OrderBy(
                         static item => item.Source,
                         StringComparer.Ordinal).ThenBy(static item => item.Line)
                                              .ThenBy(static item => item.Column)
                                              .ThenBy(static item => item.Reason, StringComparer.Ordinal)
                                              .ThenBy(static item => item.Value, StringComparer.Ordinal))
            {
                if (uncertainty.PackageId.Length != 0 &&
                    !_catalog.Packages.ContainsKey(uncertainty.PackageId))
                {
                    ReportInvalidScope(
                        "Package",
                        uncertainty.PackageId,
                        CreateLocation(uncertainty.Source, uncertainty.Line, uncertainty.Column));
                    continue;
                }
                var packages = ResolveAxamlUncertaintyPackages(uncertainty);
                if (packages.Count != 1)
                {
                    ReportInvalidScope(
                        "Package",
                        uncertainty.Source + ":" + uncertainty.Reason,
                        CreateLocation(uncertainty.Source, uncertainty.Line, uncertainty.Column));
                    continue;
                }

                var packageId = packages.Single();
                var descriptor = IsLooseOrDynamic(uncertainty.Reason)
                    ? AtomUIDiagnosticDescriptors.LinkedLooseAxamlWidened
                    : AtomUIDiagnosticDescriptors.LinkedDynamicUsageWidened;
                AddPackageFallback(
                    packageId,
                    uncertainty.Source,
                    uncertainty.Line,
                    uncertainty.Column,
                    CreateLocation(uncertainty.Source, uncertainty.Line, uncertainty.Column),
                    descriptor,
                    uncertainty.Value.Length == 0 ? uncertainty.Reason : uncertainty.Value);
            }
        }

        internal void ReportMissingEntries()
        {
            foreach (var entry in _catalog.ReferencedUsages.Where(static usage =>
                         usage.Kind == LinkedUsageKind.Entry))
            {
                _invokedPackages.Add(entry.Identity);
            }
            var usedPackages = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (var usage in _catalog.ReferencedUsages.Concat(_usages.Values))
            {
                var packageId = GetUsagePackage(usage);
                if (packageId.Length != 0 && !usedPackages.ContainsKey(packageId))
                {
                    usedPackages.Add(packageId, usage.Source);
                }
            }

            foreach (var package in usedPackages.OrderBy(static item => item.Key, StringComparer.Ordinal))
            {
                if (!_invokedPackages.Contains(package.Key))
                {
                    _reportDiagnostic(Diagnostic.Create(
                        AtomUIDiagnosticDescriptors.LinkedPackageEntryMissing,
                        Location.None,
                        package.Key,
                        package.Value));
                }
            }
        }

        internal IReadOnlyList<LinkedUsageInfo> GetOrderedUsages()
        {
            return _usages.Values.OrderBy(static item => item.Source, StringComparer.Ordinal)
                          .ThenBy(static item => item.Line)
                          .ThenBy(static item => item.Column)
                          .ThenBy(static item => item.Kind)
                          .ThenBy(static item => item.Identity, StringComparer.Ordinal)
                          .ToArray();
        }

        private void CollectInvocation(
            LinkedCSharpUsageCandidate invocation,
            Location location)
        {
            if (_catalog.ControlMaps.TryGetValue(
                    invocation.ContainingTypeIdentity,
                    out var controlMap))
            {
                var sourceLocation = GetLocationInfo(location);
                AddControlUsage(
                    controlMap,
                    sourceLocation.Source,
                    sourceLocation.Line,
                    sourceLocation.Column,
                    location);
            }

            if (_catalog.PackageIdsByEntry.TryGetValue(
                    invocation.Identity,
                    out var entryPackageIds))
            {
                var sourceLocation = GetLocationInfo(location);
                foreach (var packageId in entryPackageIds.OrderBy(
                             static packageId => packageId,
                             StringComparer.Ordinal))
                {
                    _invokedPackages.Add(packageId);
                    AddUsage(new LinkedUsageInfo(
                        LinkedUsageKind.Entry,
                        packageId,
                        sourceLocation.Source,
                        sourceLocation.Line,
                        sourceLocation.Column,
                        packageId,
                        location));
                }
            }
        }

        private void CollectBudgetCandidate(LinkedCSharpUsageCandidate candidate)
        {
            var location = candidate.CreateLocation();
            if (candidate.Kind == LinkedCSharpUsageCandidateKind.Dynamic)
            {
                return;
            }

            if (candidate.Kind == LinkedCSharpUsageCandidateKind.Type &&
                _catalog.ControlMaps.TryGetValue(candidate.Identity, out var typeControl))
            {
                AddPackageRootUsage(typeControl.PackageId, location);
            }
            else if (candidate.Kind == LinkedCSharpUsageCandidateKind.Call &&
                     _catalog.ControlMaps.TryGetValue(
                         candidate.ContainingTypeIdentity,
                         out var containingControl))
            {
                AddPackageRootUsage(containingControl.PackageId, location);
            }

            if (candidate.Kind == LinkedCSharpUsageCandidateKind.Call &&
                _catalog.PackageIdsByEntry.TryGetValue(candidate.Identity, out var packageIds))
            {
                var sourceLocation = GetLocationInfo(location);
                foreach (var packageId in packageIds)
                {
                    _invokedPackages.Add(packageId);
                    AddUsage(new LinkedUsageInfo(
                        LinkedUsageKind.Entry,
                        packageId,
                        sourceLocation.Source,
                        sourceLocation.Line,
                        sourceLocation.Column,
                        packageId,
                        location));
                }
            }
        }

        private void AddPackageRootUsage(string packageId, Location location)
        {
            AddUsage(new LinkedUsageInfo(
                LinkedUsageKind.PackageRoot,
                packageId,
                GetLocationInfo(location).Source,
                GetLocationInfo(location).Line,
                GetLocationInfo(location).Column,
                packageId,
                location));
        }

        private void AddDynamicUse(string identity, Location location)
        {
            var sourceLocation = GetLocationInfo(location);
            _dynamicUses.Add(new DynamicUse(
                identity,
                sourceLocation.Source,
                sourceLocation.Line,
                sourceLocation.Column,
                location));
        }

        private void CollectAxamlUsage(XElement element)
        {
            var source = LinkedAxamlUsageInput.GetAttribute(element, "Source");
            var line = LinkedAxamlUsageInput.GetIntAttribute(element, "Line");
            var column = LinkedAxamlUsageInput.GetIntAttribute(element, "Column");
            var kind = LinkedAxamlUsageInput.GetAttribute(element, "Kind");
            var identity = LinkedAxamlUsageInput.GetAttribute(element, "Identity");
            var location = CreateLocation(source, line, column);

            if (string.Equals(kind, "PackageRoot", StringComparison.Ordinal))
            {
                if (!_catalog.Packages.ContainsKey(identity))
                {
                    ReportInvalidScope("Package", identity, location);
                    return;
                }
                _explicitPackageRoots.Add(identity);
                AddUsage(new LinkedUsageInfo(
                    LinkedUsageKind.PackageRoot,
                    identity,
                    source,
                    line,
                    column,
                    identity,
                    location));
                return;
            }

            if (string.Equals(kind, "UnitRoot", StringComparison.Ordinal))
            {
                if (!_catalog.PackageByUnit.TryGetValue(identity, out var unitPackage))
                {
                    ReportInvalidScope("Unit", identity, location);
                    return;
                }
                AddUsage(new LinkedUsageInfo(
                    LinkedUsageKind.UnitRoot,
                    identity,
                    source,
                    line,
                    column,
                    unitPackage,
                    location));
                return;
            }

            var metadataName = LinkedAxamlUsageInput.GetAttribute(element, "TypeName");
            var namespaceUri = LinkedAxamlUsageInput.GetAttribute(element, "NamespaceUri");
            var localName = LinkedAxamlUsageInput.GetAttribute(element, "LocalName");
            if (LinkedAxamlUsageInput.IsXamlLanguageNamespace(namespaceUri))
            {
                return;
            }
            if (metadataName.Length == 0)
            {
                metadataName = LinkedAxamlUsageInput.ResolveMetadataName(
                    _catalog,
                    namespaceUri,
                    localName);
            }
            if (_catalog.ControlMaps.TryGetValue(metadataName, out var controlMap))
            {
                AddControlUsage(controlMap, source, line, column, location);
                AddAxamlPackage(source, controlMap.PackageId);
                return;
            }

            var knownType = LinkedAxamlUsageInput.ResolveKnownType(
                _compilation,
                _catalog,
                metadataName,
                namespaceUri,
                localName);
            if (knownType is not null)
            {
                if (SymbolEqualityComparer.Default.Equals(
                        knownType.ContainingAssembly,
                        _compilation.Assembly) ||
                    !_catalog.TryGetPackageId(knownType.ContainingAssembly, out var owningPackage) ||
                    !IsControlType(knownType))
                {
                    return;
                }

                AddPackageFallback(
                    owningPackage,
                    source,
                    line,
                    column,
                    location,
                    AtomUIDiagnosticDescriptors.LinkedDynamicUsageWidened,
                    metadataName.Length == 0 ? localName : metadataName);
                AddAxamlPackage(source, owningPackage);
                return;
            }

            var candidatePackages = LinkedAxamlUsageInput.ResolveCandidatePackages(
                _catalog,
                metadataName,
                namespaceUri,
                localName);
            if (candidatePackages.Count > 1 &&
                _axamlPackagesBySource.TryGetValue(source, out var sourcePackages))
            {
                candidatePackages.IntersectWith(sourcePackages);
            }
            if (candidatePackages.Count == 0 &&
                _axamlPackagesBySource.TryGetValue(source, out sourcePackages))
            {
                candidatePackages.UnionWith(sourcePackages);
            }
            if (candidatePackages.Count == 0)
            {
                candidatePackages.UnionWith(_explicitPackageRoots);
            }
            if (candidatePackages.Count > 1)
            {
                candidatePackages.IntersectWith(_explicitPackageRoots);
            }
            if (candidatePackages.Count != 1)
            {
                ReportInvalidScope(
                    "Package",
                    metadataName.Length == 0 ? localName : metadataName,
                    location);
                return;
            }
            var packageId = candidatePackages.Single();
            AddPackageFallback(
                packageId,
                source,
                line,
                column,
                location,
                AtomUIDiagnosticDescriptors.LinkedDynamicUsageWidened,
                metadataName.Length == 0 ? localName : metadataName);
            AddAxamlPackage(source, packageId);
        }

        private HashSet<string> ResolveAxamlUncertaintyPackages(AxamlUncertainty uncertainty)
        {
            var packages = new HashSet<string>(StringComparer.Ordinal);
            if (uncertainty.PackageId.Length != 0 &&
                _catalog.Packages.ContainsKey(uncertainty.PackageId))
            {
                packages.Add(uncertainty.PackageId);
                return packages;
            }
            if (_axamlPackagesBySource.TryGetValue(uncertainty.Source, out var sourcePackages))
            {
                packages.UnionWith(sourcePackages);
            }
            if (packages.Count == 0)
            {
                packages.UnionWith(_explicitPackageRoots);
            }
            return packages;
        }

        private void AddType(string metadataName, Location location)
        {
            if (_catalog.ControlMaps.TryGetValue(metadataName, out var controlMap))
            {
                var sourceLocation = GetLocationInfo(location);
                AddControlUsage(
                    controlMap,
                    sourceLocation.Source,
                    sourceLocation.Line,
                    sourceLocation.Column,
                    location);
            }
        }

        private void AddControlUsage(
            LinkedControlMapManifestRecord controlMap,
            string source,
            int line,
            int column,
            Location? location)
        {
            AddUsage(new LinkedUsageInfo(
                LinkedUsageKind.Control,
                controlMap.MetadataName,
                source,
                line,
                column,
                controlMap.PackageId,
                location));
        }

        private void AddPackageFallback(
            string packageId,
            string source,
            int line,
            int column,
            Location? location,
            DiagnosticDescriptor descriptor,
            string value)
        {
            if (!_catalog.Packages.ContainsKey(packageId))
            {
                ReportInvalidScope("Package", packageId, location);
                return;
            }

            AddUsage(new LinkedUsageInfo(
                LinkedUsageKind.PackageRoot,
                packageId,
                source,
                line,
                column,
                packageId,
                location));
            ReportFallback(descriptor, location, value, packageId);
        }

        private void AddUsage(LinkedUsageInfo usage)
        {
            if (AnalysisBudgetExceeded && usage.Kind is not (
                    LinkedUsageKind.PackageRoot or LinkedUsageKind.Entry))
            {
                var packageId = GetUsagePackage(usage);
                if (packageId.Length != 0)
                {
                    AddPackageRootUsage(packageId, usage.Location ?? Location.None);
                }
                return;
            }

            var key = usage.Kind is LinkedUsageKind.PackageRoot or
                LinkedUsageKind.UnitRoot or LinkedUsageKind.Entry
                ? string.Join("\u001f", usage.Kind.ToString(), usage.Identity)
                : string.Join(
                    "\u001f",
                    usage.Kind.ToString(),
                    usage.Identity,
                    usage.Source,
                    usage.Line.ToString(CultureInfo.InvariantCulture),
                    usage.Column.ToString(CultureInfo.InvariantCulture));
            if (!_usages.ContainsKey(key) && _usages.Count >= LinkedRegistrationAnalysisBudget.MaxUsages)
            {
                AnalysisBudgetExceeded = true;
                CompactUsagesToPackageRoots();
                if (usage.Kind is not (LinkedUsageKind.PackageRoot or LinkedUsageKind.Entry))
                {
                    var packageId = GetUsagePackage(usage);
                    if (packageId.Length != 0)
                    {
                        AddPackageRootUsage(packageId, usage.Location ?? Location.None);
                    }
                    return;
                }
            }
            if (!_usages.ContainsKey(key))
            {
                _usages.Add(key, usage);
            }
        }

        private void CompactUsagesToPackageRoots()
        {
            var compacted = _usages.Values
                .Where(usage => usage.Kind is LinkedUsageKind.PackageRoot or LinkedUsageKind.Entry)
                .ToArray();
            _usages.Clear();
            foreach (var usage in compacted)
            {
                _usages.Add(
                    usage.Kind + "\u001f" + usage.Identity,
                    usage);
            }
        }

        private void AddAxamlPackage(string source, string packageId)
        {
            if (!_axamlPackagesBySource.TryGetValue(source, out var packages))
            {
                packages = new HashSet<string>(StringComparer.Ordinal);
                _axamlPackagesBySource.Add(source, packages);
            }
            packages.Add(packageId);
        }

        private string GetUsagePackage(LinkedUsageInfo usage)
        {
            if (usage.PackageId.Length != 0)
            {
                return usage.PackageId;
            }
            return usage.Kind switch
            {
                LinkedUsageKind.Control when _catalog.ControlMaps.TryGetValue(
                    usage.Identity,
                    out var control) => control.PackageId,
                LinkedUsageKind.UnitRoot when _catalog.PackageByUnit.TryGetValue(
                    usage.Identity,
                    out var packageId) => packageId,
                LinkedUsageKind.PackageRoot or LinkedUsageKind.Entry => usage.Identity,
                _ => string.Empty
            };
        }

        private void ReportFallback(
            DiagnosticDescriptor descriptor,
            Location? location,
            string value,
            string packageId)
        {
            if (!_reportFallbackDiagnostics)
            {
                return;
            }

            var effectiveDescriptor = _strict ? AsError(descriptor) : descriptor;
            _reportDiagnostic(Diagnostic.Create(
                effectiveDescriptor,
                location ?? Location.None,
                value,
                packageId));
        }

        private void ReportInvalidScope(string kind, string identity, Location? location)
        {
            _reportDiagnostic(Diagnostic.Create(
                AtomUIDiagnosticDescriptors.LinkedExplicitRootInvalid,
                location ?? Location.None,
                kind,
                identity));
        }

        private void ReportProtocolError(string input, string detail)
        {
            _reportDiagnostic(Diagnostic.Create(
                AtomUIDiagnosticDescriptors.LinkedManifestVersionMismatch,
                Location.None,
                input,
                detail));
        }

        private SourceLocation GetLocationInfo(Location? location)
        {
            if (location is null)
            {
                return new SourceLocation("<Unknown>", 0, 0);
            }
            var span = location.GetLineSpan();
            if (span.Path.Length == 0)
            {
                return new SourceLocation("<Unknown>", 0, 0);
            }
            return new SourceLocation(
                NormalizeSourcePath(span.Path, _projectDirectory),
                span.StartLinePosition.Line + 1,
                span.StartLinePosition.Character + 1);
        }
    }

    private static bool IsControlType(INamedTypeSymbol type)
    {
        for (var current = type; current is not null; current = current.BaseType)
        {
            if (GetTypeMetadataName(current.OriginalDefinition) == "Avalonia.Controls.Control")
            {
                return true;
            }
        }
        return false;
    }

    private static string GetTypeMetadataName(INamedTypeSymbol type)
    {
        return LinkedRegistrationSymbolName.GetTypeMetadataName(type);
    }

    private static string NormalizeSourcePath(string path, string projectDirectory)
    {
        var normalized = path.Replace('\\', '/');
        var comparison = IsWindowsStylePath(normalized) && IsWindowsStylePath(projectDirectory)
            ? StringComparison.OrdinalIgnoreCase
            : StringComparison.Ordinal;
        if (projectDirectory.Length != 0 &&
            normalized.StartsWith(projectDirectory, comparison))
        {
            return normalized.Substring(projectDirectory.Length).TrimStart('/');
        }
        return normalized;
    }

    private static bool IsWindowsStylePath(string path)
    {
        return (path.Length >= 3 &&
                char.IsLetter(path[0]) &&
                path[1] == ':' &&
                path[2] == '/') ||
               path.StartsWith("//", StringComparison.Ordinal);
    }

    private static void ReportProtocolError(
        Action<Diagnostic> reportDiagnostic,
        string input,
        string detail)
    {
        reportDiagnostic(Diagnostic.Create(
            AtomUIDiagnosticDescriptors.LinkedManifestVersionMismatch,
            Location.None,
            input,
            detail));
    }

    private static Location CreateLocation(string source, int line, int column)
    {
        var position = new LinePosition(Math.Max(0, line - 1), Math.Max(0, column - 1));
        return Location.Create(
            source.Length == 0 ? "<Unknown>" : source,
            new TextSpan(0, 0),
            new LinePositionSpan(position, position));
    }

    private static bool IsLooseOrDynamic(string reason)
    {
        return string.Equals(reason, "LooseAxaml", StringComparison.Ordinal) ||
               string.Equals(reason, "DynamicResourceSource", StringComparison.Ordinal);
    }

    private static DiagnosticDescriptor AsError(DiagnosticDescriptor descriptor)
    {
        return new DiagnosticDescriptor(
            descriptor.Id,
            descriptor.Title,
            descriptor.MessageFormat,
            descriptor.Category,
            DiagnosticSeverity.Error,
            descriptor.IsEnabledByDefault,
            descriptor.Description,
            descriptor.HelpLinkUri,
            descriptor.CustomTags.ToArray());
    }

    private sealed class SourceLocation
    {
        internal SourceLocation(string source, int line, int column)
        {
            Source = source;
            Line = line;
            Column = column;
        }

        internal string Source { get; }
        internal int Line { get; }
        internal int Column { get; }
    }

    private sealed class DynamicUse
    {
        internal DynamicUse(
            string identity,
            string source,
            int line,
            int column,
            Location location)
        {
            Identity = identity;
            Source = source;
            Line = line;
            Column = column;
            Location = location;
        }

        internal string Identity { get; }
        internal string Source { get; }
        internal int Line { get; }
        internal int Column { get; }
        internal Location Location { get; }
    }

    private sealed class AxamlUncertainty
    {
        internal AxamlUncertainty(
            string source,
            int line,
            int column,
            string reason,
            string value,
            string packageId)
        {
            Source = source;
            Line = line;
            Column = column;
            Reason = reason;
            Value = value;
            PackageId = packageId;
        }

        internal string Source { get; }
        internal int Line { get; }
        internal int Column { get; }
        internal string Reason { get; }
        internal string Value { get; }
        internal string PackageId { get; }
    }
}
