using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.Splash;

[LanguageProvider(LanguageCode.en_US, SplashShowCase.LanguageId)]
internal partial class en_US : LanguageProvider
{
    public const string ScenarioExamples = "Examples";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "Design Token";
    public const string ComponentCategory = "Other";
    public const string ComponentStatusPreview = "Preview";
    public const string PageSubtitle = "Present desktop startup progress before the main workspace is ready.";
    public const string PageDescription = "Splash combines a compact branded surface, loading indicator, determinate progress, status copy, and optional footer. The service API can host it in a borderless startup window, while the visual control can be previewed directly in Gallery.";
    public const string InfoNamespaceLabel = "Namespace:";
    public const string InfoPackageLabel = "Package:";
    public const string InfoBaseClassLabel = "Base class:";
    public const string BasicTitle = "Basic";
    public const string BasicDescription = "Use the visual Splash control to show startup copy with an indeterminate loading indicator.";
    public const string DeterminateTitle = "Determinate progress";
    public const string DeterminateDescription = "Set Progress and disable IsIndeterminate when startup has measurable phases.";
    public const string StatusTitle = "Status";
    public const string StatusDescription = "Switch Status to Success or Error when the startup flow reaches a terminal state.";
    public const string ComposedTitle = "Logo, content and footer";
    public const string ComposedDescription = "Template the logo and footer when a product needs richer startup metadata.";
    public const string WindowServiceTitle = "Window service";
    public const string WindowServiceDescription = "Open a real desktop Splash window, run a five-second mock startup flow, then close it automatically.";
    public const string P2SubtitleDesktopBoot = "Desktop boot sequence";
    public const string P2MessagePreparingShell = "Preparing workspace";
    public const string P2DetailLoadingThemeAndResources = "Loading theme, language resources and cached state.";
    public const string P2MessageLoadingModules = "Loading modules";
    public const string P2DetailProgress = "Theme, icons and route catalog are ready. Optional packages are being initialized.";
    public const string P2MessageReady = "Workspace ready";
    public const string P2DetailReady = "The main window can be shown after the minimum splash duration.";
    public const string P2MessageError = "Startup failed";
    public const string P2DetailError = "Use SetErrorAsync to surface a blocking startup error before closing.";
    public const string P2FooterStaticPreview = "Static Gallery preview";
    public const string P2ContentModuleCore = "Core";
    public const string P2ContentModuleTheme = "Theme";
    public const string P2ContentModuleGallery = "Gallery";
    public const string P2FooterDesktopOnly = "Window service is intended for desktop startup.";
    public const string P2ContentShowWindowSplash = "Show window Splash";
    public const string P2WindowSplashSubtitle = "Desktop startup simulation";
    public const string P2WindowSplashMessageStarting = "Starting Gallery workspace";
    public const string P2WindowSplashDetailStarting = "A temporary Splash window is showing a mocked five-second startup.";
    public const string P2WindowSplashMessageLoadingTheme = "Loading theme resources";
    public const string P2WindowSplashMessageLoadingControls = "Registering control packages";
    public const string P2WindowSplashMessageLoadingRoutes = "Preparing route catalog";
    public const string P2WindowSplashMessageWarmingCache = "Warming Gallery cache";
    public const string P2WindowSplashMessageFinalizing = "Finalizing workspace";
    public const string P2WindowSplashDetailProgress = "This is a fake loading step for the Gallery demo.";
    public const string P2WindowSplashMessageComplete = "Gallery ready";
    public const string P2WindowSplashDetailComplete = "The fake startup flow has completed and the window will close.";
    public const string P2WindowSplashFooter = "Desktop Extras package / window-hosted startup surface";
    public const string ApiColumnMember = "Member";
    public const string ApiColumnDescription = "Description";
    public const string ApiColumnType = "Type";
    public const string ApiColumnDefault = "Default";
    public const string ApiPropertyLogo = "Logo data displayed above the title.";
    public const string ApiPropertyLogoTemplate = "Template used to render Logo.";
    public const string ApiPropertyTitle = "Primary product or application title.";
    public const string ApiPropertySubtitle = "Secondary caption shown below the title.";
    public const string ApiPropertyMessage = "Current startup message.";
    public const string ApiPropertyDetail = "Optional detail text for longer startup context.";
    public const string ApiPropertyProgress = "Determinate progress in the public 0-1 range.";
    public const string ApiPropertyIsIndeterminate = "Controls whether the spin indicator or progress bar is shown.";
    public const string ApiPropertyStatus = "Loading, Success or Error visual status.";
    public const string ApiPropertyIsMotionEnabled = "Controls splash fade and template transitions.";
    public const string ApiPropertyFooter = "Footer data displayed below the progress and message area.";
    public const string ApiStaticShowAsync = "Static convenience API that delegates to Splash.DefaultService.";
    public const string ApiServiceShowAsync = "Instance service API for applications that want dependency-injected startup flow control.";
    public const string ApiMethodSetProgress = "Updates progress, message and detail on the splash instance.";
    public const string ApiOptionMinimumShowDuration = "Minimum display time before the splash window may close.";
    public const string TokenColumnToken = "Token";
    public const string TokenColumnDescription = "Description";
    public const string TokenColumnScope = "Scope";
    public const string TokenColumnStatus = "Status";
    public const string TokenNameWindowWidth = "Default splash window width.";
    public const string TokenNameWindowMinHeight = "Default minimum height of the splash surface.";
    public const string TokenNameSurfaceCornerRadius = "Corner radius of the splash surface.";
    public const string TokenNameSurfaceBoxShadow = "Shadow used by the splash surface.";
    public const string TokenNameSurfaceBackground = "Background color of the splash surface.";
    public const string TokenNameContentPadding = "Internal content padding.";
    public const string TokenNameLogoSize = "Default logo presenter size.";
    public const string TokenNameTitleFontSize = "Title text size.";
    public const string TokenNameSubtitleFontSize = "Subtitle text size.";
    public const string TokenNameMessageFontSize = "Message text size.";
    public const string TokenNameDetailFontSize = "Detail text size.";
    public const string TokenNameIndicatorSize = "Default loading indicator size.";
    public const string TokenNameProgressBarHeight = "Height of the determinate progress bar.";
    public const string TokenNameSuccessColor = "Message color used by the success state.";
    public const string TokenNameErrorColor = "Message color used by the error state.";
    public const string TokenScopeComponent = "Component";
    public const string TokenStatusPreview = "Preview";

    protected override Type GetResourceKindType() => typeof(SplashShowCaseLangResourceKind);
}
