using AtomUI.Localization;

namespace AtomUIGallery.Localization;

[LanguageCatalog(ContractVersion = 1)]
public enum SplashShowCaseLangResourceKind
{
    ScenarioExamples = 1,
    ComponentCategory = 2,
    ComponentStatusPreview = 3,
    ComponentIntroducedVersion = 4,
    PageSubtitle = 5,
    PageDescription = 6,
    BasicTitle = 7,
    BasicDescription = 8,
    DeterminateTitle = 9,
    DeterminateDescription = 10,
    StatusTitle = 11,
    StatusDescription = 12,
    ComposedTitle = 13,
    ComposedDescription = 14,
    WindowServiceTitle = 15,
    WindowServiceDescription = 16,
    P2SubtitleDesktopBoot = 17,
    P2MessagePreparingShell = 18,
    P2DetailLoadingThemeAndResources = 19,
    P2MessageLoadingModules = 20,
    P2DetailProgress = 21,
    P2MessageReady = 22,
    P2DetailReady = 23,
    P2MessageError = 24,
    P2DetailError = 25,
    P2FooterStaticPreview = 26,
    P2ContentModuleCore = 27,
    P2ContentModuleTheme = 28,
    P2ContentModuleGallery = 29,
    P2FooterDesktopOnly = 30,
    P2ContentShowWindowSplash = 31,
    P2WindowSplashSubtitle = 32,
    P2WindowSplashMessageStarting = 33,
    P2WindowSplashDetailStarting = 34,
    P2WindowSplashMessageLoadingTheme = 35,
    P2WindowSplashMessageLoadingControls = 36,
    P2WindowSplashMessageLoadingRoutes = 37,
    P2WindowSplashMessageWarmingCache = 38,
    P2WindowSplashMessageFinalizing = 39,
    P2WindowSplashDetailProgress = 40,
    P2WindowSplashMessageComplete = 41,
    P2WindowSplashDetailComplete = 42,
    P2WindowSplashFooter = 43,
    ApiStaticShowAsync = 44,
    ApiServiceShowAsync = 45,
    ApiMethodSetProgress = 46,
    ApiOptionMinimumShowDuration = 47
}
