using AtomUI.Theme.Language;

namespace AtomUIGallery.ShowCases.Splash;

[LanguageProvider(LanguageCode.zh_CN, SplashShowCase.LanguageId)]
internal partial class zh_CN
{
    public const string ScenarioExamples = "示例";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "Design Token";
    public const string ComponentCategory = "其他";
    public const string ComponentStatusPreview = "预览";
    public const string ComponentIntroducedVersion = "v6.0.7";
    public const string PageSubtitle = "在主工作区准备完成前呈现桌面启动进度。";
    public const string PageDescription = "Splash 组合紧凑的品牌面板、加载指示、确定进度、状态文案和可选页脚。服务 API 可将它托管在无边框启动窗口中，视觉控件也可以直接在 Gallery 中预览。";
    public const string BasicTitle = "基础";
    public const string BasicDescription = "使用 Splash 视觉控件展示启动文案和不确定加载指示。";
    public const string DeterminateTitle = "确定进度";
    public const string DeterminateDescription = "当启动流程有可度量阶段时，设置 Progress 并关闭 IsIndeterminate。";
    public const string StatusTitle = "状态";
    public const string StatusDescription = "启动流程进入终态后，将 Status 切换为 Success 或 Error。";
    public const string ComposedTitle = "Logo、内容与页脚";
    public const string ComposedDescription = "当产品需要更丰富的启动元信息时，可以模板化 Logo 和页脚。";
    public const string WindowServiceTitle = "窗口服务";
    public const string WindowServiceDescription = "打开真实桌面 Splash 窗口，运行 5 秒模拟启动流程，然后自动关闭。";
    public const string P2SubtitleDesktopBoot = "桌面启动流程";
    public const string P2MessagePreparingShell = "正在准备工作区";
    public const string P2DetailLoadingThemeAndResources = "正在加载主题、语言资源和缓存状态。";
    public const string P2MessageLoadingModules = "正在加载模块";
    public const string P2DetailProgress = "主题、图标和路由目录已就绪，正在初始化可选包。";
    public const string P2MessageReady = "工作区已就绪";
    public const string P2DetailReady = "满足最短展示时长后即可显示主窗口。";
    public const string P2MessageError = "启动失败";
    public const string P2DetailError = "可通过 SetErrorAsync 在关闭前呈现阻塞型启动错误。";
    public const string P2FooterStaticPreview = "Gallery 静态预览";
    public const string P2ContentModuleCore = "核心";
    public const string P2ContentModuleTheme = "主题";
    public const string P2ContentModuleGallery = "Gallery";
    public const string P2FooterDesktopOnly = "窗口服务面向桌面启动流程。";
    public const string P2ContentShowWindowSplash = "显示窗口 Splash";
    public const string P2WindowSplashSubtitle = "桌面启动模拟";
    public const string P2WindowSplashMessageStarting = "正在启动 Gallery 工作区";
    public const string P2WindowSplashDetailStarting = "临时 Splash 窗口正在展示 5 秒模拟启动流程。";
    public const string P2WindowSplashMessageLoadingTheme = "正在加载主题资源";
    public const string P2WindowSplashMessageLoadingControls = "正在注册控件包";
    public const string P2WindowSplashMessageLoadingRoutes = "正在准备路由目录";
    public const string P2WindowSplashMessageWarmingCache = "正在预热 Gallery 缓存";
    public const string P2WindowSplashMessageFinalizing = "正在完成工作区准备";
    public const string P2WindowSplashDetailProgress = "这是 Gallery 示例里的模拟加载步骤。";
    public const string P2WindowSplashMessageComplete = "Gallery 已就绪";
    public const string P2WindowSplashDetailComplete = "模拟启动流程已完成，窗口即将关闭。";
    public const string P2WindowSplashFooter = "Desktop Extras 包 / 窗口托管启动面板";
    public const string ApiColumnMember = "成员";
    public const string ApiColumnDescription = "说明";
    public const string ApiColumnType = "类型";
    public const string ApiColumnDefault = "默认值";
    public const string ApiPropertyLogo = "显示在标题上方的 Logo 数据。";
    public const string ApiPropertyLogoTemplate = "用于渲染 Logo 的模板。";
    public const string ApiPropertyTitle = "产品或应用的主标题。";
    public const string ApiPropertySubtitle = "显示在标题下方的副标题。";
    public const string ApiPropertyMessage = "当前启动消息。";
    public const string ApiPropertyDetail = "用于更长启动上下文的可选详情文本。";
    public const string ApiPropertyProgress = "0 到 1 范围内的确定进度。";
    public const string ApiPropertyIsIndeterminate = "控制显示加载指示器还是进度条。";
    public const string ApiPropertyStatus = "Loading、Success 或 Error 视觉状态。";
    public const string ApiPropertyIsMotionEnabled = "控制 Splash 淡出和模板过渡。";
    public const string ApiPropertyFooter = "显示在进度和消息区域下方的页脚数据。";
    public const string ApiStaticShowAsync = "静态便捷 API，委托给 Splash.DefaultService。";
    public const string ApiServiceShowAsync = "实例服务 API，适用于希望通过依赖注入控制启动流程的应用。";
    public const string ApiMethodSetProgress = "更新 Splash 实例的进度、消息和详情。";
    public const string ApiOptionMinimumShowDuration = "Splash 窗口允许关闭前的最短展示时间。";
    public const string TokenColumnToken = "Token";
    public const string TokenColumnDescription = "说明";
    public const string TokenColumnScope = "范围";
    public const string TokenColumnStatus = "状态";
    public const string TokenNameWindowWidth = "Splash 窗口默认宽度。";
    public const string TokenNameWindowMinHeight = "Splash 面板默认最小高度。";
    public const string TokenNameSurfaceCornerRadius = "Splash 面板圆角。";
    public const string TokenNameSurfaceBoxShadow = "Splash 面板阴影。";
    public const string TokenNameSurfaceBackground = "Splash 面板背景色。";
    public const string TokenNameContentPadding = "内容内边距。";
    public const string TokenNameLogoSize = "Logo presenter 默认尺寸。";
    public const string TokenNameTitleFontSize = "标题字号。";
    public const string TokenNameSubtitleFontSize = "副标题字号。";
    public const string TokenNameMessageFontSize = "消息字号。";
    public const string TokenNameDetailFontSize = "详情字号。";
    public const string TokenNameIndicatorSize = "默认加载指示器尺寸。";
    public const string TokenNameProgressBarHeight = "确定进度条高度。";
    public const string TokenNameSuccessColor = "Success 状态下的消息颜色。";
    public const string TokenNameErrorColor = "Error 状态下的消息颜色。";
    public const string TokenScopeComponent = "组件";
    public const string TokenStatusPreview = "预览";

}
