<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(AtomUITargetFrameworks)</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>GeneratedFiles</CompilerGeneratedFilesOutputPath>
        <AtomUIGenerateControlThemeAssetResources>true</AtomUIGenerateControlThemeAssetResources>
        <AtomUIRegistrationPackageId>$(AssemblyName)</AtomUIRegistrationPackageId>
        <AtomUIRegistrationEntries>AtomUI.Desktop.Controls.ColorPickerThemeManagerBuilderExtensions.UseDesktopColorPicker</AtomUIRegistrationEntries>
        <RootNamespace>AtomUI.Desktop.Controls</RootNamespace>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaXaml Update="Themes/ColorSlider/AbstractColorPickerSliderTrackTheme.axaml;Themes/ColorSlider/ColorPickerSliderTrackTheme.axaml;Themes/ColorSlider/ColorSliderTrackButtonTheme.axaml;Themes/ColorSlider/GradientColorPickerTrackTheme.axaml;Themes/ColorView/ColorPickerInput.axaml"
                       AtomUIRegistrationUnit="ColorPicker" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Controls.ColorPicker" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../AtomUI.Generator/AtomUI.Generator.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"
                          PrivateAssets="all"/>
        <ProjectReference Include="../AtomUI.Desktop.Controls/AtomUI.Desktop.Controls.csproj" />
    </ItemGroup>

</Project>
