// <auto-generated />
#nullable enable

namespace AtomUI.Desktop.Controls
{
    public partial class DescriptionItem : global::Avalonia.Controls.IResourceHost, global::Avalonia.Styling.IThemeVariantHost
    {
        private global::Avalonia.Controls.IResourceHost? __atomuiResourceHost;
        private int __atomuiResourceHostAttachmentCount;

        public event global::System.EventHandler<global::Avalonia.Controls.ResourcesChangedEventArgs>? ResourcesChanged;
        public event global::System.EventHandler? ActualThemeVariantChanged;

        public bool HasResources => true;

        public global::Avalonia.Styling.ThemeVariant ActualThemeVariant =>
            (__atomuiResourceHost as global::Avalonia.Styling.IThemeVariantHost)?.ActualThemeVariant ??
            global::Avalonia.Application.Current?.ActualThemeVariant ??
            global::Avalonia.Styling.ThemeVariant.Default;

        public bool TryGetResource(object key, global::Avalonia.Styling.ThemeVariant? theme, out object? value)
        {
            if (__atomuiResourceHost is not null &&
                global::Avalonia.Controls.ResourceNodeExtensions.TryFindResource(__atomuiResourceHost, key, theme, out value))
            {
                return true;
            }

            if (global::Avalonia.Application.Current?.TryGetResource(key, theme, out value) == true)
            {
                return true;
            }

            value = null;
            return false;
        }

        void global::Avalonia.Controls.IResourceHost.NotifyHostedResourcesChanged(global::Avalonia.Controls.ResourcesChangedEventArgs e)
        {
            ResourcesChanged?.Invoke(this, e);
        }

        internal global::System.IDisposable AttachResourceHost(global::Avalonia.Controls.IResourceHost resourceHost)
        {
            if (global::System.Object.ReferenceEquals(__atomuiResourceHost, resourceHost))
            {
                __atomuiResourceHostAttachmentCount++;
            }
            else
            {
                AtomUIDetachCurrentResourceHost();
                __atomuiResourceHost = resourceHost;
                __atomuiResourceHostAttachmentCount = 1;
                AtomUIRegisterResourceHost(resourceHost);
            }

            return new AtomUIScopedResourceHostAttachment(this, resourceHost);
        }

        private void AtomUIDetachResourceHost(global::Avalonia.Controls.IResourceHost resourceHost)
        {
            if (!global::System.Object.ReferenceEquals(__atomuiResourceHost, resourceHost))
            {
                return;
            }

            __atomuiResourceHostAttachmentCount--;
            if (__atomuiResourceHostAttachmentCount > 0)
            {
                return;
            }

            AtomUIDetachCurrentResourceHost();
            AtomUIRaiseResourcesChanged();
            ActualThemeVariantChanged?.Invoke(this, global::System.EventArgs.Empty);
        }

        private void AtomUIDetachCurrentResourceHost()
        {
            if (__atomuiResourceHost is null)
            {
                __atomuiResourceHostAttachmentCount = 0;
                return;
            }

            __atomuiResourceHost.ResourcesChanged -= AtomUIHandleResourceHostResourcesChanged;

            if (__atomuiResourceHost is global::Avalonia.Styling.IThemeVariantHost themeVariantHost)
            {
                themeVariantHost.ActualThemeVariantChanged -= AtomUIHandleResourceHostActualThemeVariantChanged;
            }

            __atomuiResourceHost = null;
            __atomuiResourceHostAttachmentCount = 0;
        }

        private void AtomUIRegisterResourceHost(global::Avalonia.Controls.IResourceHost resourceHost)
        {
            resourceHost.ResourcesChanged += AtomUIHandleResourceHostResourcesChanged;

            if (resourceHost is global::Avalonia.Styling.IThemeVariantHost themeVariantHost)
            {
                themeVariantHost.ActualThemeVariantChanged += AtomUIHandleResourceHostActualThemeVariantChanged;
            }

            AtomUIRaiseResourcesChanged();
            ActualThemeVariantChanged?.Invoke(this, global::System.EventArgs.Empty);
        }

        private void AtomUIHandleResourceHostResourcesChanged(object? sender, global::Avalonia.Controls.ResourcesChangedEventArgs e)
        {
            ResourcesChanged?.Invoke(this, e);
        }

        private void AtomUIHandleResourceHostActualThemeVariantChanged(object? sender, global::System.EventArgs e)
        {
            ActualThemeVariantChanged?.Invoke(this, e);
        }

        private void AtomUIRaiseResourcesChanged()
        {
            ResourcesChanged?.Invoke(this, global::Avalonia.Controls.ResourcesChangedEventArgs.Create());
        }

        private sealed class AtomUIScopedResourceHostAttachment : global::System.IDisposable
        {
            private DescriptionItem? _item;
            private global::Avalonia.Controls.IResourceHost? _resourceHost;

            public AtomUIScopedResourceHostAttachment(DescriptionItem item, global::Avalonia.Controls.IResourceHost resourceHost)
            {
                _item = item;
                _resourceHost = resourceHost;
            }

            public void Dispose()
            {
                if (_item is null || _resourceHost is null)
                {
                    return;
                }

                var item = _item;
                var resourceHost = _resourceHost;
                _item = null;
                _resourceHost = null;
                item.AtomUIDetachResourceHost(resourceHost);
            }
        }
    }
}
