using AtomUI.Theme.Language;

namespace AtomUIGallery.ShowCases.Select;

[LanguageProvider(LanguageCode.en_US, SelectShowCase.LanguageId)]
internal partial class en_US
{
    public const string BasicTitle = "Basic";
    public const string BasicDescription = "Basic Usage.";
    public const string BindingTitle = "Two-way binding";
    public const string BindingDescription = "SelectedOption and SelectedOptions synchronize with the ViewModel without explicitly setting Binding Mode=TwoWay.";
    public const string BindingSingleLabel = "SelectedOption";
    public const string BindingMultipleLabel = "SelectedOptions";
    public const string BindingViewModelValueLabel = "ViewModel value";
    public const string BindingSetSingleButton = "Set Lucy";
    public const string BindingSetMultipleButton = "Set Jack + Yiminghe";
    public const string BindingClearButton = "Clear";
    public const string ScenarioBasic = "Basic";
    public const string ScenarioOptions = "Options";
    public const string ScenarioAppearance = "Appearance";
    public const string ScenarioExamples = "Examples";
    public const string PageSubtitle = "Single, multiple, searchable, and tag-based option selection.";
    public const string PageDescription = "Select lets users choose values from option lists with filtering, grouping, async loading, custom rendering, and multiple selection behaviors.";
    public const string ComponentCategory = "Data Entry";
    public const string ComponentStatusStable = "Stable";
    public const string SearchFieldTitle = "Select with search field";
    public const string SearchFieldDescription = "Search the options while expanded.";
    public const string CustomSearchTitle = "Custom Search";
    public const string CustomSearchDescription = "Customize search using filterOption, Case-sensitive search for Header.";
    public const string MultipleSelectionTitle = "multiple selection";
    public const string MultipleSelectionDescription = "Multiple selection, selecting from existing items.";
    public const string TagsTitle = "Tags";
    public const string TagsDescription = "Allow user to select tags from list or input custom tag.";
    public const string SizesTitle = "Sizes";
    public const string SizesDescription = "The height of the input field for the select defaults to 32px. If size is set to large, the height will be 40px, and if set to small, 24px. Custom can use local size properties.";
    public const string CustomDropdownOptionsTitle = "Custom dropdown options";
    public const string CustomDropdownOptionsDescription = "Use optionRender to customize the rendering dropdown options";
    public const string OptionGroupTitle = "Option Group";
    public const string OptionGroupDescription = "Using OptGroup to group the options.";
    public const string VariantsTitle = "Variants";
    public const string VariantsDescription = "Variants of Select, there are four variants: outlined filled borderless and underlined.";
    public const string HideAlreadySelectedTitle = "Hide Already Selected";
    public const string HideAlreadySelectedDescription = "Hide already selected options in the dropdown.";
    public const string StatusTitle = "Status";
    public const string StatusDescription = "Add status to Select with status, which could be error or warning.";
    public const string MaxCountTitle = "Max Count";
    public const string MaxCountDescription = "You can set the maxCount prop to control the max number of items can be selected. When the limit is exceeded, the options will become disabled.";
    public const string ResponsiveMaxTagCountTitle = "Responsive maxTagCount";
    public const string ResponsiveMaxTagCountDescription = "Auto collapse to tag with responsive case. Not recommend use in large form case since responsive calculation has a perf cost.";
    public const string PrefixAndSuffixTitle = "Prefix and Suffix";
    public const string PrefixAndSuffixDescription = "Custom prefix and suffixIcon.";
    public const string P2PlaceholderTextPleaseSelect = "Please select";
    public const string P2HeaderJack = "Jack";
    public const string P2HeaderLucy = "Lucy";
    public const string P2HeaderYiminghe = "Yiminghe";
    public const string P2HeaderDisabled = "Disabled";
    public const string P2HeaderTom = "Tom";
    public const string P2PlaceholderTextSelectAPerson = "Select a person";
    public const string P2PlaceholderTextTagsMode = "Tags Mode";
    public const string P2DescriptionChina = "China";
    public const string P2HeaderChina = "China";
    public const string P2DescriptionUsa = "United States";
    public const string P2HeaderUsa = "USA";
    public const string P2DescriptionJapan = "Japan";
    public const string P2HeaderJapan = "Japan";
    public const string P2DescriptionKorea = "Korea";
    public const string P2HeaderKorea = "Korea";
    public const string P2HeaderChloe = "Chloe";
    public const string P2HeaderLucas = "Lucas";
    public const string P2PlaceholderTextOutline = "Outline";
    public const string P2HeaderYiminghe2 = "yiminghe";
    public const string P2PlaceholderTextFilled = "Filled";
    public const string P2PlaceholderTextBorderless = "Borderless";
    public const string P2PlaceholderTextInsertedAreRemoved = "Inserted are removed";
    public const string P2HeaderApples = "Apples";
    public const string P2HeaderNails = "Nails";
    public const string P2HeaderBananas = "Bananas";
    public const string P2HeaderHelicopters = "Helicopters";
    public const string P2HeaderAvaSwift = "Ava Swift";
    public const string P2HeaderColeReed = "Cole Reed";
    public const string P2HeaderMiaBlake = "Mia Blake";
    public const string P2HeaderJakeStone = "Jake Stone";
    public const string P2HeaderLilyLane = "Lily Lane";
    public const string P2HeaderRyanChase = "Ryan Chase";
    public const string P2HeaderZoeFox = "Zoe Fox";
    public const string P2HeaderAlexGrey = "Alex Grey";
    public const string P2HeaderElleBlair = "Elle Blair";
    public const string P2PlaceholderTextSelectItem = "Select Item...";
    public const string P2ContentLarge = "Large";
    public const string P2ContentDefault = "Default";
    public const string P2ContentSmall = "Small";
    public const string P2ContentCustom = "Custom";
    public const string P2GroupManager = "Manager";
    public const string P2GroupEngineer = "Engineer";
    public const string P2ContentUser = "User";
    public const string P2TextLongLabelPrefix = "Long label: ";

}
