using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.Select;

[LanguageProvider(LanguageCode.zh_CN, SelectShowCase.LanguageId)]
internal partial class zh_CN : LanguageProvider
{
    public const string BasicTitle = "基础用法";
    public const string BasicDescription = "基础用法。";
    public const string ScenarioBasic = "基础";
    public const string ScenarioOptions = "选项";
    public const string ScenarioAppearance = "外观";
    public const string SearchFieldTitle = "带搜索框的选择器";
    public const string SearchFieldDescription = "展开时搜索选项。";
    public const string CustomSearchTitle = "自定义搜索";
    public const string CustomSearchDescription = "使用 filterOption 自定义搜索，对 Header 进行大小写敏感搜索。";
    public const string MultipleSelectionTitle = "多选";
    public const string MultipleSelectionDescription = "多选，从已有项中选择。";
    public const string TagsTitle = "标签";
    public const string TagsDescription = "允许用户从列表中选择标签或输入自定义标签。";
    public const string SizesTitle = "尺寸";
    public const string SizesDescription = "选择器输入区域默认高度为 32px。size 设置为 large 时高度为 40px，设置为 small 时高度为 24px。";
    public const string CustomDropdownOptionsTitle = "自定义下拉选项";
    public const string CustomDropdownOptionsDescription = "使用 optionRender 自定义下拉选项渲染。";
    public const string OptionGroupTitle = "选项分组";
    public const string OptionGroupDescription = "使用 OptGroup 对选项分组。";
    public const string VariantsTitle = "变体";
    public const string VariantsDescription = "Select 提供四种变体：描边、填充、无边框和下划线。";
    public const string HideAlreadySelectedTitle = "隐藏已选项";
    public const string HideAlreadySelectedDescription = "在下拉列表中隐藏已经选择的选项。";
    public const string StatusTitle = "状态";
    public const string StatusDescription = "通过 status 为 Select 添加状态，可设置为错误或警告。";
    public const string MaxCountTitle = "最大数量";
    public const string MaxCountDescription = "可以设置 maxCount 属性控制最多可选项数量。超过限制后，选项会变为禁用状态。";
    public const string ResponsiveMaxTagCountTitle = "响应式 maxTagCount";
    public const string ResponsiveMaxTagCountDescription = "在响应式场景中自动折叠为标签。由于响应式计算有性能成本，不建议在大型表单中使用。";
    public const string PrefixAndSuffixTitle = "前缀和后缀";
    public const string PrefixAndSuffixDescription = "自定义 prefix 和 suffixIcon。";
    public const string P2PlaceholderTextPleaseSelect = "请选择";
    public const string P2HeaderJack = "杰克";
    public const string P2HeaderLucy = "露西";
    public const string P2HeaderYiminghe = "一鸣鹤";
    public const string P2HeaderDisabled = "禁用";
    public const string P2HeaderTom = "汤姆";
    public const string P2PlaceholderTextSelectAPerson = "请选择人员";
    public const string P2PlaceholderTextTagsMode = "标签模式";
    public const string P2DescriptionChina = "中国";
    public const string P2HeaderChina = "中国";
    public const string P2DescriptionUsa = "美国";
    public const string P2HeaderUsa = "美国";
    public const string P2DescriptionJapan = "日本";
    public const string P2HeaderJapan = "日本";
    public const string P2DescriptionKorea = "韩国";
    public const string P2HeaderKorea = "韩国";
    public const string P2HeaderChloe = "克洛伊";
    public const string P2HeaderLucas = "卢卡斯";
    public const string P2PlaceholderTextOutline = "线框风格";
    public const string P2HeaderYiminghe2 = "一鸣鹤";
    public const string P2PlaceholderTextFilled = "填充风格";
    public const string P2PlaceholderTextBorderless = "无边框";
    public const string P2PlaceholderTextInsertedAreRemoved = "已插入项会被移除";
    public const string P2HeaderApples = "苹果";
    public const string P2HeaderNails = "钉子";
    public const string P2HeaderBananas = "香蕉";
    public const string P2HeaderHelicopters = "直升机";
    public const string P2HeaderAvaSwift = "艾娃·斯威夫特";
    public const string P2HeaderColeReed = "科尔·里德";
    public const string P2HeaderMiaBlake = "米娅·布莱克";
    public const string P2HeaderJakeStone = "杰克·斯通";
    public const string P2HeaderLilyLane = "莉莉·莱恩";
    public const string P2HeaderRyanChase = "瑞安·蔡斯";
    public const string P2HeaderZoeFox = "佐伊·福克斯";
    public const string P2HeaderAlexGrey = "亚历克斯·格雷";
    public const string P2HeaderElleBlair = "艾尔·布莱尔";
    public const string P2PlaceholderTextSelectItem = "选择项目...";
    public const string P2ContentLarge = "大号";
    public const string P2ContentDefault = "默认";
    public const string P2ContentSmall = "小号";
    public const string P2GroupManager = "经理";
    public const string P2GroupEngineer = "工程师";
    public const string P2ContentUser = "用户";
    public const string P2TextLongLabelPrefix = "长标签：";

    protected override Type GetResourceKindType() => typeof(SelectShowCaseLangResourceKind);
}
