using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace AtomUI.Generator;

internal static class ThemeControlCatalogMetadataWriter
{
    internal static void Write(
        SourceProductionContext context,
        string controlCatalog)
    {
        var catalog = SymbolDisplay.FormatLiteral(controlCatalog, quote: true);
        var key = SymbolDisplay.FormatLiteral(
            ThemeGeneratorOptions.ControlCatalogMetadataKey,
            quote: true);
        context.AddSource(
            "ThemeControlCatalogMetadata.g.cs",
            GeneratedSourceText.From($$"""
                // <auto-generated />
                [assembly: global::System.Reflection.AssemblyMetadata({{key}}, {{catalog}})]
                """));
    }
}
