namespace AtomUI.Theme
{
    internal class ControlTokenTypeRegister
    {
        internal static void Register()
        {
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.AddOnDecoratedBoxToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.AlertToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.ArrowDecoratedBoxToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.BadgeToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.ButtonToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.ButtonSpinnerToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.CalendarToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.CheckBoxToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.CollapseToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.ComboBoxToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.DatePickerToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.EmptyIndicatorToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.ExpanderToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.FlyoutPresenterToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.GroupBoxToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.LineEditToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.Internal.InfoPickerInputToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.ListBoxToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.LoadingIndicatorToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.MarqueeLabelToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.MenuToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.MessageToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.NavMenuToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.NotificationToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.NumericUpDownToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.OptionButtonToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.PopupConfirmToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.ProgressBarToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.RadioButtonToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.SegmentedToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.SeparatorToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.SliderToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.ToggleSwitchToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.TabControlToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.TagToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.TimelineToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.TimePickerToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.ToolTipToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.TreeViewToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.CaptionButtonToken));
            ThemeManager.Current.RegisterControlTokenType(typeof(AtomUI.Controls.WindowToken));
        }
    }
}