// <auto-generated />
using global::AtomUI.Theme.Schema;

namespace AtomUI.Generated.AtomUI_Controls;

internal static class GeneratedThemeSchema
{
    private static readonly TokenDescriptor[] s_globalTokens = new TokenDescriptor[]
    {
    };

    private static readonly ControlTokenDescriptor[] s_controls = new ControlTokenDescriptor[]
    {
        new ControlTokenDescriptor(
            new ControlTokenIdentity("AtomUI", "Icon"),
            new TokenDescriptor[]
            {
                new TokenDescriptor("FallbackColor", 0, TokenStage.Control, typeof(global::Avalonia.Media.Color), global::AtomUI.Controls.DesignTokens.IconTokenKind.FallbackColor,
                    static value => ThemeTokenValueParser.Parse<global::Avalonia.Media.Color>(value),
                    static value => ThemeTokenValueFormatter.Format((global::Avalonia.Media.Color)value!),
                    static token => ((global::AtomUI.Controls.IconToken)token).FallbackColor,
                    static (token, value) => ((global::AtomUI.Controls.IconToken)token).FallbackColor = (global::Avalonia.Media.Color)value!,
                    static token => ThemeResourceValue.Project(((global::AtomUI.Controls.IconToken)token).FallbackColor)),
                new TokenDescriptor("SecondaryFillColor", 1, TokenStage.Control, typeof(global::Avalonia.Media.Color), global::AtomUI.Controls.DesignTokens.IconTokenKind.SecondaryFillColor,
                    static value => ThemeTokenValueParser.Parse<global::Avalonia.Media.Color>(value),
                    static value => ThemeTokenValueFormatter.Format((global::Avalonia.Media.Color)value!),
                    static token => ((global::AtomUI.Controls.IconToken)token).SecondaryFillColor,
                    static (token, value) => ((global::AtomUI.Controls.IconToken)token).SecondaryFillColor = (global::Avalonia.Media.Color)value!,
                    static token => ThemeResourceValue.Project(((global::AtomUI.Controls.IconToken)token).SecondaryFillColor)),
                new TokenDescriptor("SecondaryStrokeColor", 2, TokenStage.Control, typeof(global::Avalonia.Media.Color), global::AtomUI.Controls.DesignTokens.IconTokenKind.SecondaryStrokeColor,
                    static value => ThemeTokenValueParser.Parse<global::Avalonia.Media.Color>(value),
                    static value => ThemeTokenValueFormatter.Format((global::Avalonia.Media.Color)value!),
                    static token => ((global::AtomUI.Controls.IconToken)token).SecondaryStrokeColor,
                    static (token, value) => ((global::AtomUI.Controls.IconToken)token).SecondaryStrokeColor = (global::Avalonia.Media.Color)value!,
                    static token => ThemeResourceValue.Project(((global::AtomUI.Controls.IconToken)token).SecondaryStrokeColor)),
                new TokenDescriptor("StrokeLineCap", 3, TokenStage.Control, typeof(global::Avalonia.Media.PenLineCap), global::AtomUI.Controls.DesignTokens.IconTokenKind.StrokeLineCap,
                    static value => ThemeTokenValueParser.Parse<global::Avalonia.Media.PenLineCap>(value),
                    static value => ThemeTokenValueFormatter.Format((global::Avalonia.Media.PenLineCap)value!),
                    static token => ((global::AtomUI.Controls.IconToken)token).StrokeLineCap,
                    static (token, value) => ((global::AtomUI.Controls.IconToken)token).StrokeLineCap = (global::Avalonia.Media.PenLineCap)value!,
                    static token => ThemeResourceValue.Project(((global::AtomUI.Controls.IconToken)token).StrokeLineCap)),
                new TokenDescriptor("StrokeLineJoin", 4, TokenStage.Control, typeof(global::Avalonia.Media.PenLineJoin), global::AtomUI.Controls.DesignTokens.IconTokenKind.StrokeLineJoin,
                    static value => ThemeTokenValueParser.Parse<global::Avalonia.Media.PenLineJoin>(value),
                    static value => ThemeTokenValueFormatter.Format((global::Avalonia.Media.PenLineJoin)value!),
                    static token => ((global::AtomUI.Controls.IconToken)token).StrokeLineJoin,
                    static (token, value) => ((global::AtomUI.Controls.IconToken)token).StrokeLineJoin = (global::Avalonia.Media.PenLineJoin)value!,
                    static token => ThemeResourceValue.Project(((global::AtomUI.Controls.IconToken)token).StrokeLineJoin)),
                new TokenDescriptor("StrokeWidth", 5, TokenStage.Control, typeof(global::System.Double), global::AtomUI.Controls.DesignTokens.IconTokenKind.StrokeWidth,
                    static value => ThemeTokenValueParser.Parse<global::System.Double>(value),
                    static value => ThemeTokenValueFormatter.Format((global::System.Double)value!),
                    static token => ((global::AtomUI.Controls.IconToken)token).StrokeWidth,
                    static (token, value) => ((global::AtomUI.Controls.IconToken)token).StrokeWidth = (global::System.Double)value!,
                    static token => ThemeResourceValue.Project(((global::AtomUI.Controls.IconToken)token).StrokeWidth)),
            },
            static () => new global::AtomUI.Controls.IconToken(),
            static (token, appearance) => ((global::AtomUI.Controls.IconToken)token).CalculateTokenValues(appearance == global::AtomUI.Theme.ThemeAppearance.Dark)),
    };

    private static readonly ThemeAlgorithmDescriptor[] s_algorithms = new ThemeAlgorithmDescriptor[]
    {
    };

    internal static global::System.Collections.Generic.IReadOnlyList<TokenDescriptor> GetGlobalTokens() => s_globalTokens;
    internal static global::System.Collections.Generic.IReadOnlyList<ControlTokenDescriptor> GetControls() => s_controls;
    internal static global::System.Collections.Generic.IReadOnlyList<ThemeAlgorithmDescriptor> GetAlgorithms() => s_algorithms;
}
