using AtomUI.Localization;

namespace AtomUIGallery.Localization;

[LanguageCatalog(ContractVersion = 1)]
public enum BadgeShowCaseLangResourceKind
{
    ScenarioExamples = 1,
    ComponentCategory = 2,
    ComponentStatusStable = 3,
    PageSubtitle = 4,
    PageDescription = 5,
    BasicTitle = 6,
    BasicDescription = 7,
    OverflowCountTitle = 8,
    OverflowCountDescription = 9,
    OffsetTitle = 10,
    OffsetDescription = 11,
    SizeTitle = 12,
    SizeDescription = 13,
    StandaloneTitle = 14,
    StandaloneDescription = 15,
    DynamicTitle = 16,
    DynamicDescription = 17,
    RedBadgeTitle = 18,
    RedBadgeDescription = 19,
    StatusTitle = 20,
    StatusDescription = 21,
    RibbonTitle = 22,
    RibbonDescription = 23,
    ColorfulBadgeTitle = 24,
    ColorfulBadgeDescription = 25,
    P2TextSuccess = 26,
    P2TextError = 27,
    P2TextDefault = 28,
    P2TextProcessing = 29,
    P2TextWarning = 30,
    P2TextPolishExperience = 31,
    P2TextJiachenPlan = 32,
    P2TextAvaloniaExcellent = 33,
    P2TextHippies = 34,
    P2TitlePresets = 35,
    P2TextPink = 36,
    P2TextRed = 37,
    P2TextYellow = 38,
    P2TextOrange = 39,
    P2TextCyan = 40,
    P2TextGreen = 41,
    P2TextBlue = 42,
    P2TextPurple = 43,
    P2TextGeekblue = 44,
    P2TextMagenta = 45,
    P2TextVolcano = 46,
    P2TextGold = 47,
    P2TextLime = 48,
    P2TitleCustom = 49,
    P2TextRgbN45N183N245 = 50,
    P2TextHslN102N53N61 = 51,
    P2TextRgbN15N141N230 = 52,
    P2ContentAdd = 53,
    P2ContentSub = 54,
    P2ContentRandom = 55,
    P2TextPushesOpenTheWindow = 56,
    P2TextAndRaisesTheSpyglass = 57,
    P2ContentLinkSomething = 58
}
