using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.Badge;

[LanguageProvider(LanguageCode.en_US, BadgeShowCase.LanguageId)]
internal partial class en_US
{
    public const string ScenarioExamples = "Examples";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "Design Token";
    public const string ComponentCategory = "Data Display";
    public const string ComponentStatusStable = "Stable";
    public const string PageSubtitle = "Highlight counts, statuses, and contextual labels near related content.";
    public const string PageDescription = "Badge draws attention to notifications, counts, status dots, and ribbon labels without interrupting the user's workflow.";
    public const string ApiColumnProperty = "Property";
    public const string ApiColumnDescription = "Description";
    public const string ApiColumnType = "Type";
    public const string ApiColumnDefault = "Default";
    public const string ApiPropertyCount = "Displays the numeric value inside a count badge.";
    public const string ApiPropertyOverflowCount = "Shows overflow text when Count is greater than the configured limit.";
    public const string ApiPropertyBadgeColor = "Overrides the badge color with a preset or CSS color string.";
    public const string ApiPropertyIsZeroVisible = "Keeps the count badge visible when Count is zero.";
    public const string ApiPropertyOffset = "Moves the badge from its default anchor position.";
    public const string ApiPropertySize = "Switches the count badge between middle and small visual sizes.";
    public const string ApiPropertyBadgeIsVisible = "Controls whether the badge indicator is rendered.";
    public const string ApiPropertyStatus = "Applies semantic status styling to dot badges.";
    public const string ApiPropertyDotColor = "Sets a preset or custom color for standalone dot badges.";
    public const string ApiPropertyText = "Displays text next to dot badges or inside ribbon badges.";
    public const string ApiPropertyRibbonColor = "Sets the ribbon badge color with a preset or custom value.";
    public const string ApiPropertyPlacement = "Places the ribbon badge at the start or end edge.";
    public const string TokenColumnToken = "Token";
    public const string TokenColumnDescription = "Description";
    public const string TokenColumnScope = "Scope";
    public const string TokenColumnStatus = "Status";
    public const string TokenNameBadgeColor = "Default color used by count and dot badge indicators.";
    public const string TokenNameIndicatorHeight = "Default count badge indicator height.";
    public const string TokenNameIndicatorHeightSM = "Small count badge indicator height.";
    public const string TokenNameDotSize = "Size of dot and status badge indicators.";
    public const string TokenNameTextFontSize = "Font size used by count badge text.";
    public const string TokenNameStatusSize = "Size used by standalone status dots.";
    public const string TokenScopeComponent = "Component";
    public const string TokenStatusStable = "Stable";
    public const string BasicTitle = "Basic";
    public const string BasicDescription = "Simplest Usage. Badge will be hidden when count is 0, but we can use showZero to show it.";
    public const string OverflowCountTitle = "Overflow Count";
    public const string OverflowCountDescription = "${overflowCount}+ is displayed when count is larger than overflowCount. The default value of overflowCount is 99.";
    public const string OffsetTitle = "Offset";
    public const string OffsetDescription = "Set offset of the badge dot, the format is [left, top], which represents the offset of the status dot from the left and top of the default position.";
    public const string SizeTitle = "Size";
    public const string SizeDescription = "Set size of numeral Badge.";
    public const string StandaloneTitle = "Standalone";
    public const string StandaloneDescription = "Used in standalone when children is empty.";
    public const string DynamicTitle = "Dynamic";
    public const string DynamicDescription = "The count will be animated as it changes.";
    public const string RedBadgeTitle = "Red badge";
    public const string RedBadgeDescription = "This will simply display a red badge, without a specific count. If count equals 0, it won't display the dot.";
    public const string StatusTitle = "Status";
    public const string StatusDescription = "Standalone badge with status.";
    public const string RibbonTitle = "Ribbon";
    public const string RibbonDescription = "Use ribbon badge.";
    public const string ColorfulBadgeTitle = "Colorful Badge";
    public const string ColorfulBadgeDescription = "We preset a series of colorful Badge styles for use in different situations. You can also set it to a hex color string for custom color.";
    public const string P2TextSuccess = "Success";
    public const string P2TextError = "Error";
    public const string P2TextDefault = "Default";
    public const string P2TextProcessing = "Processing";
    public const string P2TextWarning = "Warning";
    public const string P2TextPolishExperience = "Polish every detail for an excellent UI SDK experience";
    public const string P2TextJiachenPlan = "Jiachen Plan takes off";
    public const string P2TextAvaloniaExcellent = "Avalonia is excellent";
    public const string P2TextHippies = "Hippies";
    public const string P2TitlePresets = "Presets";
    public const string P2TextPink = "Pink";
    public const string P2TextRed = "Red";
    public const string P2TextYellow = "Yellow";
    public const string P2TextOrange = "Orange";
    public const string P2TextCyan = "Cyan";
    public const string P2TextGreen = "Green";
    public const string P2TextBlue = "Blue";
    public const string P2TextPurple = "Purple";
    public const string P2TextGeekblue = "GeekBlue";
    public const string P2TextMagenta = "Magenta";
    public const string P2TextVolcano = "Volcano";
    public const string P2TextGold = "Gold";
    public const string P2TextLime = "Lime";
    public const string P2TitleCustom = "Custom";
    public const string P2TextRgbN45N183N245 = "rgb(45, 183, 245)";
    public const string P2TextHslN102N53N61 = "hsl(102, 53%, 61%)";
    public const string P2TextRgbN15N141N230 = "rgb(15, 141, 230)";
    public const string P2ContentAdd = "Add";
    public const string P2ContentSub = "Sub";
    public const string P2ContentRandom = "Random";
    public const string P2TextPushesOpenTheWindow = "Pushes open the window";
    public const string P2TextAndRaisesTheSpyglass = "and raises the spyglass.";

    public const string P2ContentLinkSomething = "Link something";

}
