<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <IsPackable>true</IsPackable>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
        <PackageId>Acme.LocalizationComponent.I18n.JaJP</PackageId>
        <PackageVersion Condition="'$(PackageVersion)' == ''">1.0.0</PackageVersion>
        <AtomUIBuildLanguagePackage>true</AtomUIBuildLanguagePackage>
        <AtomUILanguageTag>ja-JP</AtomUILanguageTag>
        <AtomUILanguageModuleId>Acme.LocalizationComponent</AtomUILanguageModuleId>
        <AtomUIRequireVerifiedLanguageContract>true</AtomUIRequireVerifiedLanguageContract>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../../../src/AtomUI.Generator/AtomUI.Generator.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"
                          PrivateAssets="all" />
        <ProjectReference Include="../Module/Module.csproj" />
    </ItemGroup>
</Project>
