using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.ComboBox;

[LanguageProvider(LanguageCode.en_US, ComboBoxShowCase.LanguageId)]
internal partial class en_US
{
    public const string ComponentCategory = "Navigation";
    public const string ComponentStatusStable = "Stable";
    public const string PageSubtitle = "A selection input for choosing from a compact popup list.";
    public const string PageDescription = "ComboBox combines input-style layout with dropdown selection, supporting item templates, add-ons, prefixes, suffixes, validation status, and size variants.";
    public const string ScenarioExamples = "Examples";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "Design Token";

    public const string BasicTitle = "Basic";
    public const string BasicDescription = "Basic button spinner.";
    public const string ItemsSourceTitle = "Generate ComboBoxItem by ItemsSource";
    public const string ItemsSourceDescription = "Generate structure based on ItemsSource and template.";
    public const string BindingTitle = "SelectedItem binding";
    public const string BindingDescription = "SelectedItem synchronizes with the ViewModel and is also the value read and written by Form.";
    public const string BindingSelectedItemLabel = "SelectedItem";
    public const string BindingViewModelValueLabel = "ViewModel value";
    public const string BindingSetButton = "Set third line";
    public const string BindingClearButton = "Clear";
    public const string EditableFilterTitle = "Editable filtering";
    public const string EditableFilterDescription = "Type in the ComboBox input to filter popup candidates without replacing the source items.";
    public const string DisabledTitle = "Disabled";
    public const string DisabledDescription = "Disabled button spinner.";
    public const string ThreeSizesTitle = "Three sizes of Input";
    public const string ThreeSizesDescription = "ComboBox supports large (40px), default (32px), small (24px), and Custom sizes with local size properties.";
    public const string VariantsTitle = "Variants";
    public const string VariantsDescription = "Variants of Input.";
    public const string PrePostTabTitle = "Pre / Post tab";
    public const string PrePostTabDescription = "Using pre and post tabs example.";
    public const string PrefixSuffixTitle = "prefix and suffix";
    public const string PrefixSuffixDescription = "Add a prefix or suffix icons inside input.";
    public const string StatusTitle = "Status";
    public const string StatusDescription = "Add status to Input with status, which could be error or warning.";
    public const string P2PlaceholderTextPleaseSelect = "Please select";
    public const string P2PlaceholderTextTypeToFilter = "Type to filter";
    public const string P2PlaceholderSizeTypeLarge = "SizeType: Large";
    public const string P2PlaceholderSizeTypeMiddle = "SizeType: Middle";
    public const string P2PlaceholderSizeTypeSmall = "SizeType: Small";
    public const string P2PlaceholderSizeTypeCustom = "SizeType: Custom";
    public const string P2ContentPoemLine1 = "床前明月光";
    public const string P2ContentPoemLine2 = "疑是地上霜";
    public const string P2ContentPoemLine3 = "举头望明月";
    public const string P2ContentPoemLine4 = "低头思故乡";

    public const string ApiColumnProperty = "Property";
    public const string ApiColumnDescription = "Description";
    public const string ApiColumnType = "Type";
    public const string ApiColumnDefault = "Default";
    public const string ApiPropertyItemsSource = "Collection used to generate popup items.";
    public const string ApiPropertySelectedItem = "Currently selected item. This is the default Form value for ComboBox.";
    public const string ApiPropertySelectedIndex = "Index of the selected item.";
    public const string ApiPropertyPlaceholderText = "Placeholder shown when no item is selected.";
    public const string ApiPropertyIsEditable = "Allows text input in the ComboBox selection area.";
    public const string ApiPropertyText = "Editable input text. When filtering is enabled, it drives FilterValue.";
    public const string ApiPropertyIsFilterEnabled = "Enables filtering for editable ComboBox candidates.";
    public const string ApiPropertyIsShowOverflowTip = "Shows a tooltip with the full selected content when the non-editable selection text overflows.";
    public const string ApiPropertyOverflowTipDelay = "Delay in milliseconds before the overflow tooltip opens.";
    public const string ApiPropertyOverflowTipPlacement = "Placement of the overflow tooltip relative to the clipped selected content.";
    public const string ApiPropertyFilter = "Predicate used to match candidate values against FilterValue.";
    public const string ApiPropertyFilterValue = "Current filtering value, normally synchronized from Text in editable filtering mode.";
    public const string ApiPropertyFilterValueSelector = "Selects the comparable value from each candidate item before filtering.";
    public const string ApiPropertyLeftAddOn = "Content displayed outside the input area on the left.";
    public const string ApiPropertyRightAddOn = "Content displayed outside the input area on the right.";
    public const string ApiPropertyContentLeftAddOn = "Content displayed inside the input area before the selection.";
    public const string ApiPropertyContentRightAddOn = "Content displayed inside the input area after the selection.";
    public const string ApiPropertySizeType = "Controls the ComboBox size.";
    public const string ApiPropertyStyleVariant = "Controls outlined, filled, and borderless visual variants.";
    public const string ApiPropertyStatus = "Applies validation status styling.";
    public const string ApiPropertyIsAllowClear = "Allows the current selection to be cleared.";
    public const string ApiPropertyOptionFontSize = "Overrides popup option font size.";
    public const string ApiPropertyDropDownDisplayPageSize = "Controls how many options are shown before scrolling.";
    public const string ApiPropertyShouldUseOverlayPopup = "Controls whether the dropdown uses the overlay popup host.";
    public const string ApiPropertyIsMotionEnabled = "Enables control motion when the theme allows it.";

    public const string TokenColumnToken = "Token";
    public const string TokenColumnDescription = "Description";
    public const string TokenColumnScope = "Scope";
    public const string TokenColumnStatus = "Status";
    public const string TokenNameControlWidth = "Default control width inherited from ButtonSpinner.";
    public const string TokenNameHandleWidth = "Dropdown handle width.";
    public const string TokenNameHandleIconSize = "Dropdown handle icon size.";
    public const string TokenNameHandleBg = "Dropdown handle background color.";
    public const string TokenNameHandleActiveBg = "Dropdown handle active background color.";
    public const string TokenNameHandleHoverColor = "Dropdown handle hover foreground color.";
    public const string TokenNameHandleBorderColor = "Dropdown handle border color.";
    public const string TokenNameFilledHandleBg = "Dropdown handle background for filled variant.";
    public const string TokenNameInputFontSize = "Default input font size inherited from LineEdit.";
    public const string TokenNameInputFontSizeLG = "Large input font size inherited from LineEdit.";
    public const string TokenNameInputFontSizeSM = "Small input font size inherited from LineEdit.";
    public const string TokenNamePopupContentPadding = "Dropdown popup content padding.";
    public const string TokenNameItemColor = "Option text color.";
    public const string TokenNameItemHoverColor = "Option hover text color.";
    public const string TokenNameItemSelectedColor = "Selected option text color.";
    public const string TokenNameItemDisabledColor = "Disabled option text color.";
    public const string TokenNameItemBgColor = "Option background color.";
    public const string TokenNameItemHoverBgColor = "Option hover background color.";
    public const string TokenNameItemSelectedBgColor = "Selected option background color.";
    public const string TokenNameItemPadding = "Option content padding.";
    public const string TokenNameItemMargin = "Option margin.";
    public const string TokenScopeComponent = "Component";
    public const string TokenStatusStable = "Stable";

}
