using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.TreeView;

[LanguageProvider(LanguageCode.en_US, TreeViewShowCase.LanguageId)]
internal partial class en_US : LanguageProvider
{
    public const string ScenarioBasic = "Basic";
    public const string ScenarioAdvanced = "Advanced";
    public const string BasicTitle = "Basic";
    public const string BasicDescription = "The most basic usage, tell you how to use checkable, selectable, disabled, defaultExpandKeys, and etc.";
    public const string GenerateByTemplateTitle = "Generate by template";
    public const string GenerateByTemplateDescription = "You can use the Template mechanism to generate tree nodes";
    public const string BlockNodeTitle = "Block Node";
    public const string BlockNodeDescription = "Block Node.";
    public const string TreeWithLineTitle = "Tree with line";
    public const string TreeWithLineDescription = "Tree with connected line between nodes, turn on by showLine, customize the preset icon by switcherIcon.";
    public const string DraggableTitle = "draggable";
    public const string DraggableDescription = "Drag treeNode to insert after the other treeNode or insert into the other parent TreeNode.";
    public const string CustomizeExpandIconTitle = "Customize collapse/expand icon";
    public const string CustomizeExpandIconDescription = "customize collapse/expand icon of tree node";
    public const string AsyncLoadDataTitle = "load data asynchronously";
    public const string AsyncLoadDataDescription = "To load data asynchronously when click to expand a treeNode.";
    public const string SearchableByTemplateTitle = "Searchable by TreeDataTemplate";
    public const string SearchableByTemplateDescription = "Searchable Tree use ItemsSource datasource.";
    public const string SearchableTitle = "Searchable";
    public const string SearchableDescription = "Searchable Tree.";
    public const string ContextMenuTitle = "Context menu";
    public const string ContextMenuDescription = "Right-click any node to open a context menu. Toggle IsSelectOnRightClick to switch between following the right-clicked node (default) and keeping the existing selection untouched.";
    public const string P2HeaderParentN1 = "parent 1";
    public const string P2HeaderParentN1N0 = "parent 1-0";
    public const string P2HeaderLeaf = "leaf";
    public const string P2HeaderParentN1N1 = "parent 1-1";
    public const string P2HeaderSss = "sss";
    public const string P2HeaderCcc = "ccc";
    public const string P2HeaderXxx = "xxx";
    public const string P2HeaderAaaa = "aaaa";
    public const string P2HeaderParent = "parent";
    public const string P2HeaderChildN1 = "child 1";
    public const string P2HeaderChildN2 = "child 2";
    public const string P2HeaderLeafN1 = "leaf 1";
    public const string P2HeaderLeafN2 = "leaf 2";
    public const string P2HeaderParentN1N2 = "parent 1-2";
    public const string P2HeaderParentN2 = "parent 2";
    public const string P2HeaderParentN2N0 = "parent 2-0";
    public const string P2HeaderN0N0 = "0-0";
    public const string P2HeaderN0N0N0 = "0-0-0";
    public const string P2HeaderN0N0N0N0 = "0-0-0-0";
    public const string P2HeaderN0N0N0N1 = "0-0-0-1";
    public const string P2HeaderN0N0N0N2 = "0-0-0-2";
    public const string P2HeaderN0N0N1 = "0-0-1";
    public const string P2HeaderN0N0N1N0 = "0-0-1-0";
    public const string P2HeaderN0N0N1N1 = "0-0-1-1";
    public const string P2HeaderN0N0N1N2 = "0-0-1-2";
    public const string P2HeaderN0N0N2 = "0-0-2";
    public const string P2HeaderN0N1 = "0-1";
    public const string P2HeaderN0N1N0 = "0-1-0";
    public const string P2HeaderN0N1N0N0 = "0-1-0-0";
    public const string P2HeaderN0N1N0N1 = "0-1-0-1";
    public const string P2HeaderN0N1N0N2 = "0-1-0-2";
    public const string P2HeaderN0N1N1 = "0-1-1";
    public const string P2HeaderN0N1N1N0 = "0-1-1-0";
    public const string P2HeaderN0N1N1N1 = "0-1-1-1";
    public const string P2HeaderN0N1N1N2 = "0-1-1-2";
    public const string P2HeaderN0N1N2 = "0-1-2";
    public const string P2HeaderN0N2 = "0-2";
    public const string P2PlaceholderTextSearch = "Search";
    public const string P2HeaderNewNode = "New Node";
    public const string P2HeaderRename = "Rename";
    public const string P2HeaderDelete = "Delete";
    public const string P2TextShowline = "showLine:";
    public const string P2TextShowicon = "showIcon:";
    public const string P2TextShowleaficon = "ShowLeafIcon:";
    public const string P2TextNodeHoverMode = "Node hover mode:";
    public const string P2ContentDefault = "Default";
    public const string P2ContentBlock = "Block";
    public const string P2ContentWholeline = "WholeLine";
    public const string P2TextIsselectonrightclick = "IsSelectOnRightClick:";
    public const string P2HeaderExpandToLoad = "Expand to load";
    public const string P2HeaderTreeNode = "Tree Node";
    public const string P2HeaderChildNode = "Child Node";
    public const string P2HeaderNodeFallback = "node";
    public const string P2HeaderNewNodeFormat = "{0} / new ({1})";
    public const string P2HeaderRenamedFormat = "{0} (renamed)";

    protected override Type GetResourceKindType() => typeof(TreeViewShowCaseLangResourceKind);
}
