using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.TreeView;

[LanguageProvider(LanguageCode.zh_CN, TreeViewShowCase.LanguageId)]
internal class zh_CN : LanguageProvider
{
    public const string ScenarioBasic = "基础";
    public const string ScenarioAdvanced = "进阶";
    public const string BasicTitle = "基础用法";
    public const string BasicDescription = "最基础的用法，展示如何使用 checkable、selectable、disabled、defaultExpandKeys 等属性。";
    public const string GenerateByTemplateTitle = "使用模板生成";
    public const string GenerateByTemplateDescription = "可以使用 Template 机制生成树节点。";
    public const string BlockNodeTitle = "块级节点";
    public const string BlockNodeDescription = "块级节点。";
    public const string TreeWithLineTitle = "带连接线的树";
    public const string TreeWithLineDescription = "节点之间带连接线的树。通过 showLine 开启，并可通过 switcherIcon 自定义预设图标。";
    public const string DraggableTitle = "可拖拽";
    public const string DraggableDescription = "拖拽 treeNode 可将其插入到其他 treeNode 之后，或插入到其他父级 TreeNode 中。";
    public const string CustomizeExpandIconTitle = "自定义展开/折叠图标";
    public const string CustomizeExpandIconDescription = "自定义树节点的展开/折叠图标。";
    public const string AsyncLoadDataTitle = "异步加载数据";
    public const string AsyncLoadDataDescription = "点击展开 treeNode 时异步加载数据。";
    public const string SearchableByTemplateTitle = "通过 TreeDataTemplate 搜索";
    public const string SearchableByTemplateDescription = "使用 ItemsSource 数据源的可搜索树。";
    public const string SearchableTitle = "可搜索";
    public const string SearchableDescription = "可搜索的树。";
    public const string ContextMenuTitle = "上下文菜单";
    public const string ContextMenuDescription = "右键任意节点可打开上下文菜单。切换 IsSelectOnRightClick 可在跟随右键节点（默认）和保持现有选择不变之间切换。";
    public const string P2HeaderParentN1 = "父节点 1";
    public const string P2HeaderParentN1N0 = "父节点 1-0";
    public const string P2HeaderLeaf = "叶子节点";
    public const string P2HeaderParentN1N1 = "父节点 1-1";
    public const string P2HeaderSss = "示例一";
    public const string P2HeaderCcc = "示例二";
    public const string P2HeaderXxx = "示例三";
    public const string P2HeaderAaaa = "示例四";
    public const string P2HeaderParent = "父节点";
    public const string P2HeaderChildN1 = "子节点 1";
    public const string P2HeaderChildN2 = "子节点 2";
    public const string P2HeaderLeafN1 = "叶子节点 1";
    public const string P2HeaderLeafN2 = "叶子节点 2";
    public const string P2HeaderParentN1N2 = "父节点 1-2";
    public const string P2HeaderParentN2 = "父节点 2";
    public const string P2HeaderParentN2N0 = "父节点 2-0";
    public const string P2HeaderN0N0 = "0-0";
    public const string P2HeaderN0N0N0 = "0-0-0";
    public const string P2HeaderN0N0N0N0 = "0-0-0-0";
    public const string P2HeaderN0N0N0N1 = "0-0-0-1";
    public const string P2HeaderN0N0N0N2 = "0-0-0-2";
    public const string P2HeaderN0N0N1 = "0-0-1";
    public const string P2HeaderN0N0N1N0 = "0-0-1-0";
    public const string P2HeaderN0N0N1N1 = "0-0-1-1";
    public const string P2HeaderN0N0N1N2 = "0-0-1-2";
    public const string P2HeaderN0N0N2 = "0-0-2";
    public const string P2HeaderN0N1 = "0-1";
    public const string P2HeaderN0N1N0 = "0-1-0";
    public const string P2HeaderN0N1N0N0 = "0-1-0-0";
    public const string P2HeaderN0N1N0N1 = "0-1-0-1";
    public const string P2HeaderN0N1N0N2 = "0-1-0-2";
    public const string P2HeaderN0N1N1 = "0-1-1";
    public const string P2HeaderN0N1N1N0 = "0-1-1-0";
    public const string P2HeaderN0N1N1N1 = "0-1-1-1";
    public const string P2HeaderN0N1N1N2 = "0-1-1-2";
    public const string P2HeaderN0N1N2 = "0-1-2";
    public const string P2HeaderN0N2 = "0-2";
    public const string P2PlaceholderTextSearch = "搜索";
    public const string P2HeaderNewNode = "新节点";
    public const string P2HeaderRename = "重命名";
    public const string P2HeaderDelete = "删除";
    public const string P2TextShowline = "显示连接线：";
    public const string P2TextShowicon = "显示图标：";
    public const string P2TextShowleaficon = "显示叶子节点图标：";
    public const string P2TextNodeHoverMode = "节点悬停模式：";
    public const string P2ContentDefault = "默认";
    public const string P2ContentBlock = "块";
    public const string P2ContentWholeline = "整行";
    public const string P2TextIsselectonrightclick = "右键时选择节点：";
    public const string P2HeaderExpandToLoad = "展开加载";
    public const string P2HeaderTreeNode = "树节点";
    public const string P2HeaderChildNode = "子节点";
    public const string P2HeaderNodeFallback = "节点";
    public const string P2HeaderNewNodeFormat = "{0} / 新建 ({1})";
    public const string P2HeaderRenamedFormat = "{0}（已重命名）";

    protected override Type GetResourceKindType() => typeof(TreeViewShowCaseLangResourceKind);
}
