// <auto-generated />
#nullable enable

namespace AtomUI.Controls
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false)]
    internal sealed class GenerateScopedResourceHostAttribute : global::System.Attribute
    {
    }
}