using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.TabControl;

[LanguageProvider(LanguageCode.en_US, TabControlShowCase.LanguageId)]
internal partial class en_US : LanguageProvider
{
    public const string TabControlBasicTitle = "Basic";
    public const string TabControlBasicDescription = "Default activate first tab.";
    public const string TabControlItemsSourceTitle = "Items from ItemSource datasource";
    public const string TabControlItemsSourceDescription = "Add TabItem based on data source and item template.";
    public const string TabControlDisabledTitle = "Disabled";
    public const string TabControlDisabledDescription = "Disabled a tab.";
    public const string TabControlCenteredTitle = "Centered";
    public const string TabControlCenteredDescription = "Centered tabs.";
    public const string TabControlIconTitle = "Icon";
    public const string TabControlIconDescription = "The Tab with Icon.";
    public const string TabControlSlideTitle = "Slide";
    public const string TabControlSlideDescription = "In order to fit in more tabs, they can slide left and right (or up and down).";
    public const string TabControlCardTypeTitle = "Card type tab";
    public const string TabControlCardTypeDescription = "Another type of Tabs, which doesn't support vertical mode.";
    public const string TabControlClosableTitle = "Closable Tab";
    public const string TabControlClosableDescription = "We support closable tab settings.";
    public const string TabControlPositionTitle = "Position";
    public const string TabControlPositionDescription = "Tab's position: left, right, top or bottom. Will auto switch to top in mobile.";
    public const string TabControlCardShapePositionTitle = "Card Shape Position";
    public const string TabControlCardShapePositionDescription = "Tab's position: left, right, top or bottom. Will auto switch to top in mobile.";
    public const string TabControlSizeTitle = "Size";
    public const string TabControlSizeDescription = "Large size tabs are usually used in page header, and small size could be used in Modal.";
    public const string TabControlAddCloseTitle = "Add and close tab";
    public const string TabControlAddCloseDescription = "Hide default plus icon, and bind event for customized trigger.";
    public const string TabControlExtraContentTitle = "Extra content";
    public const string TabControlExtraContentDescription = "You can add extra actions to the right or left or even both side of Tabs.";
    public const string P2HeaderTabN1 = "Tab 1";
    public const string P2HeaderTabN2 = "Tab 2";
    public const string P2HeaderTabN3 = "Tab 3";
    public const string P2HeaderTabN4 = "Tab 4";
    public const string P2HeaderTabN5 = "Tab 5";
    public const string P2HeaderTabN6 = "Tab 6";
    public const string P2HeaderTabN7 = "Tab 7";
    public const string P2HeaderTabN8 = "Tab 8";
    public const string P2HeaderTabN9 = "Tab 9";
    public const string P2HeaderTabN10 = "Tab 10";
    public const string P2HeaderTabN11 = "Tab 11";
    public const string P2HeaderTabN12 = "Tab 12";
    public const string P2HeaderTabN13 = "Tab 13";
    public const string P2HeaderTabN14 = "Tab 14";
    public const string P2HeaderTabN15 = "Tab 15";
    public const string P2HeaderTabN16 = "Tab 16";
    public const string P2HeaderTabN17 = "Tab 17";
    public const string P2HeaderTabN18 = "Tab 18";
    public const string P2HeaderTabN19 = "Tab 19";
    public const string P2HeaderTabN20 = "Tab 20";
    public const string P2ContentContentOfTabPaneN1 = "Content of Tab Pane 1";
    public const string P2ContentContentOfTabPaneN2 = "Content of Tab Pane 2";
    public const string P2ContentContentOfTabPaneN3 = "Content of Tab Pane 3";
    public const string P2ContentContentOfTabPaneN4 = "Content of Tab Pane 4";
    public const string P2ContentContentOfTabPaneN5 = "Content of Tab Pane 5";
    public const string P2ContentContentOfTabPaneN6 = "Content of Tab Pane 6";
    public const string P2ContentContentOfTabPaneN7 = "Content of Tab Pane 7";
    public const string P2ContentContentOfTabPaneN8 = "Content of Tab Pane 8";
    public const string P2ContentContentOfTabPaneN9 = "Content of Tab Pane 9";
    public const string P2ContentContentOfTabPaneN10 = "Content of Tab Pane 10";
    public const string P2ContentContentOfTabPaneN11 = "Content of Tab Pane 11";
    public const string P2ContentContentOfTabPaneN12 = "Content of Tab Pane 12";
    public const string P2ContentContentOfTabPaneN13 = "Content of Tab Pane 13";
    public const string P2ContentContentOfTabPaneN14 = "Content of Tab Pane 14";
    public const string P2ContentContentOfTabPaneN15 = "Content of Tab Pane 15";
    public const string P2ContentContentOfTabPaneN16 = "Content of Tab Pane 16";
    public const string P2ContentContentOfTabPaneN17 = "Content of Tab Pane 17";
    public const string P2ContentContentOfTabPaneN18 = "Content of Tab Pane 18";
    public const string P2ContentContentOfTabPaneN19 = "Content of Tab Pane 19";
    public const string P2ContentContentOfTabPaneN20 = "Content of Tab Pane 20";
    public const string P2ContentDynamicTabContentN1 = "Tab Content 1";
    public const string P2ContentDynamicTabContentN2 = "Tab Content 2";
    public const string P2ContentNewTabContentFormat = "new tab content {0}";
    public const string P2TextTabPosition = "Tab position:";
    public const string P2ContentTop = "Top";
    public const string P2ContentBottom = "Bottom";
    public const string P2ContentLeft = "Left";
    public const string P2ContentRight = "Right";
    public const string P2ContentSmall = "Small";
    public const string P2ContentMiddle = "Middle";
    public const string P2ContentLarge = "Large";
    public const string P2ContentStartExtraAction = "Start extra action";
    public const string P2ContentEndExtraAction = "End extra action";
    public const string P2HeaderNewTabFormat = "new tab {0}";

    protected override Type GetResourceKindType() => typeof(TabControlShowCaseLangResourceKind);
}
