using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.TabControl;

[LanguageProvider(LanguageCode.zh_CN, TabControlShowCase.LanguageId)]
internal class zh_CN : LanguageProvider
{
    public const string TabControlBasicTitle = "基础用法";
    public const string TabControlBasicDescription = "默认激活第一个标签页。";
    public const string TabControlItemsSourceTitle = "通过 ItemSource 生成标签项";
    public const string TabControlItemsSourceDescription = "基于数据源和项目模板添加 TabItem。";
    public const string TabControlDisabledTitle = "禁用标签";
    public const string TabControlDisabledDescription = "禁用某个标签页。";
    public const string TabControlCenteredTitle = "居中显示";
    public const string TabControlCenteredDescription = "标签页居中显示。";
    public const string TabControlIconTitle = "带图标";
    public const string TabControlIconDescription = "带图标的标签页。";
    public const string TabControlSlideTitle = "滑动";
    public const string TabControlSlideDescription = "为了容纳更多标签，标签可以左右滑动（或上下滑动）。";
    public const string TabControlCardTypeTitle = "卡片式标签";
    public const string TabControlCardTypeDescription = "另一种标签页类型，不支持垂直模式。";
    public const string TabControlClosableTitle = "可关闭标签";
    public const string TabControlClosableDescription = "支持可关闭的标签页设置。";
    public const string TabControlPositionTitle = "位置";
    public const string TabControlPositionDescription = "标签位置可设为 left、right、top 或 bottom，在移动端会自动切换为 top。";
    public const string TabControlCardShapePositionTitle = "卡片形态位置";
    public const string TabControlCardShapePositionDescription = "标签位置可设为 left、right、top 或 bottom，在移动端会自动切换为 top。";
    public const string TabControlSizeTitle = "尺寸";
    public const string TabControlSizeDescription = "大尺寸标签通常用于页头，小尺寸可用于模态框。";
    public const string TabControlAddCloseTitle = "新增和关闭标签";
    public const string TabControlAddCloseDescription = "隐藏默认加号图标，并为自定义触发器绑定事件。";
    public const string TabControlExtraContentTitle = "额外内容";
    public const string TabControlExtraContentDescription = "可以在标签页右侧、左侧或两侧添加额外操作。";
    public const string P2HeaderTabN1 = "标签页 1";
    public const string P2HeaderTabN2 = "标签页 2";
    public const string P2HeaderTabN3 = "标签页 3";
    public const string P2HeaderTabN4 = "标签页 4";
    public const string P2HeaderTabN5 = "标签页 5";
    public const string P2HeaderTabN6 = "标签页 6";
    public const string P2HeaderTabN7 = "标签页 7";
    public const string P2HeaderTabN8 = "标签页 8";
    public const string P2HeaderTabN9 = "标签页 9";
    public const string P2HeaderTabN10 = "标签页 10";
    public const string P2HeaderTabN11 = "标签页 11";
    public const string P2HeaderTabN12 = "标签页 12";
    public const string P2HeaderTabN13 = "标签页 13";
    public const string P2HeaderTabN14 = "标签页 14";
    public const string P2HeaderTabN15 = "标签页 15";
    public const string P2HeaderTabN16 = "标签页 16";
    public const string P2HeaderTabN17 = "标签页 17";
    public const string P2HeaderTabN18 = "标签页 18";
    public const string P2HeaderTabN19 = "标签页 19";
    public const string P2HeaderTabN20 = "标签页 20";
    public const string P2ContentContentOfTabPaneN1 = "标签页内容 1";
    public const string P2ContentContentOfTabPaneN2 = "标签页内容 2";
    public const string P2ContentContentOfTabPaneN3 = "标签页内容 3";
    public const string P2ContentContentOfTabPaneN4 = "标签页内容 4";
    public const string P2ContentContentOfTabPaneN5 = "标签页内容 5";
    public const string P2ContentContentOfTabPaneN6 = "标签页内容 6";
    public const string P2ContentContentOfTabPaneN7 = "标签页内容 7";
    public const string P2ContentContentOfTabPaneN8 = "标签页内容 8";
    public const string P2ContentContentOfTabPaneN9 = "标签页内容 9";
    public const string P2ContentContentOfTabPaneN10 = "标签页内容 10";
    public const string P2ContentContentOfTabPaneN11 = "标签页内容 11";
    public const string P2ContentContentOfTabPaneN12 = "标签页内容 12";
    public const string P2ContentContentOfTabPaneN13 = "标签页内容 13";
    public const string P2ContentContentOfTabPaneN14 = "标签页内容 14";
    public const string P2ContentContentOfTabPaneN15 = "标签页内容 15";
    public const string P2ContentContentOfTabPaneN16 = "标签页内容 16";
    public const string P2ContentContentOfTabPaneN17 = "标签页内容 17";
    public const string P2ContentContentOfTabPaneN18 = "标签页内容 18";
    public const string P2ContentContentOfTabPaneN19 = "标签页内容 19";
    public const string P2ContentContentOfTabPaneN20 = "标签页内容 20";
    public const string P2ContentDynamicTabContentN1 = "标签内容 1";
    public const string P2ContentDynamicTabContentN2 = "标签内容 2";
    public const string P2ContentNewTabContentFormat = "新增标签内容 {0}";
    public const string P2TextTabPosition = "标签位置：";
    public const string P2ContentTop = "顶部";
    public const string P2ContentBottom = "底部";
    public const string P2ContentLeft = "左侧";
    public const string P2ContentRight = "右侧";
    public const string P2ContentSmall = "小号";
    public const string P2ContentMiddle = "中号";
    public const string P2ContentLarge = "大号";
    public const string P2ContentStartExtraAction = "左侧额外操作";
    public const string P2ContentEndExtraAction = "右侧额外操作";
    public const string P2HeaderNewTabFormat = "新增标签 {0}";

    protected override Type GetResourceKindType() => typeof(TabControlShowCaseLangResourceKind);
}
