using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.List;

[LanguageProvider(LanguageCode.zh_CN, ListShowCase.LanguageId)]
internal partial class zh_CN
{
    public const string ScenarioExamples = "示例";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "设计变量";
    public const string ComponentCategory = "数据展示";
    public const string ComponentStatusStable = ".NET 10";
    public const string PageSubtitle = "展示一组相关项目，并支持选择、分组、排序、筛选和分页。";
    public const string PageDescription = "List 用紧凑的纵向结构呈现重复信息。它支持 ListView 的分组、选择指示器、空状态、筛选、排序和分页，也覆盖简单的 ListBox 用法。";
    public const string ApiColumnProperty = "属性";
    public const string ApiColumnDescription = "说明";
    public const string ApiColumnType = "类型";
    public const string ApiColumnDefault = "默认值";
    public const string ApiPropertyIsSelectable = "控制列表项是否可以被选择。";
    public const string ApiPropertySizeType = "控制列表项密度。";
    public const string ApiPropertyIsBorderless = "移除列表表面边框。";
    public const string ApiPropertySelectionMode = "控制单选、多选或切换选择行为。";
    public const string ApiPropertySelectedItems = "选中项集合。默认使用 TwoWay 绑定，并参与 Avalonia 数据验证。";
    public const string ApiPropertyIsShowSelectedIndicator = "在选中项内部显示选中指示器。";
    public const string ApiPropertyIsShowEmptyIndicator = "无项目时显示空状态指示。";
    public const string ApiPropertyIsGroupEnabled = "根据项目的分组值对列表项分组。";
    public const string ApiPropertyGroupPropertySelector = "选择用于分组的值。";
    public const string ApiPropertySortDescriptions = "按一个或多个项目字段排序。";
    public const string ApiPropertyFilter = "用于判断项目是否保持可见的筛选器。";
    public const string ApiPropertyFilterValue = "传给筛选器的筛选条件。";
    public const string ApiPropertyFilterValueSelector = "选择筛选时使用的项目值。";
    public const string ApiPropertyPaginationVisibility = "控制顶部、底部、两侧或隐藏分页器。";
    public const string ApiPropertyPageSize = "每页显示的项目数量。";
    public const string ApiPropertyBottomPagination = "渲染在列表下方的自定义分页控件。";
    public const string ApiPropertyFilterHighlightStrategy = "ListBox 筛选文本使用的高亮策略。";
    public const string TokenColumnToken = "变量";
    public const string TokenColumnDescription = "说明";
    public const string TokenColumnScope = "范围";
    public const string TokenColumnStatus = "状态";
    public const string TokenNameContentPadding = "列表内容内边距。";
    public const string TokenNameItemColor = "列表项文本颜色。";
    public const string TokenNameItemHoverColor = "列表项悬浮文本颜色。";
    public const string TokenNameItemSelectedColor = "列表项选中文本颜色。";
    public const string TokenNameItemDisabledColor = "列表项禁用文本颜色。";
    public const string TokenNameItemBgColor = "列表项背景色。";
    public const string TokenNameItemHoverBgColor = "列表项悬浮背景色。";
    public const string TokenNameItemSelectedBgColor = "列表项选中背景色。";
    public const string TokenNameItemPadding = "默认列表项内边距。";
    public const string TokenNameItemPaddingSM = "小尺寸列表项内边距。";
    public const string TokenNameItemPaddingLG = "大尺寸列表项内边距。";
    public const string TokenNameItemMargin = "列表项外边距。";
    public const string TokenNamePaginationMargin = "ListView 分页器外边距。";
    public const string TokenNameGroupHeaderColor = "分组标题文本颜色。";
    public const string TokenNameSelectedIndicatorMargin = "选中指示器外边距。";
    public const string TokenNameFilterHighlightColor = "ListBox 筛选高亮颜色。";
    public const string TokenStatusStable = "稳定";
    public const string ScenarioBasic = "基础";
    public const string ScenarioAdvanced = "进阶";
    public const string BasicUsageTitle = "基础用法";
    public const string BasicUsageDescription = "基础用法示例。";
    public const string SelectionTitle = "选择";
    public const string SelectionDescription = "可以设置单选、多选或不可选择。";
    public const string SelectedItemsBindingTitle = "SelectedItems 绑定";
    public const string SelectedItemsBindingDescription = "SelectedItems 不需要显式设置 Mode=TwoWay；用户选择和集合变更都会保持同步。";
    public const string GroupTitle = "分组";
    public const string GroupDescription = "可以根据条件对数据分组。";
    public const string ItemDisabledTitle = "禁用项";
    public const string ItemDisabledDescription = "禁用列表项。";
    public const string EmptyTitle = "空状态";
    public const string EmptyDescription = "无数据时显示空状态指示。";
    public const string FilterTitle = "筛选";
    public const string FilterDescription = "可以按条件筛选数据；这里筛选包含“色”的项。";
    public const string OrderedTitle = "排序";
    public const string OrderedDescription = "可以根据指定属性排序。";
    public const string SimpleListBoxTitle = "简单列表框控件";
    public const string SimpleListBoxDescription = "基础用法示例。";
    public const string SimpleListBoxItemsSourceTitle = "简单列表框控件";
    public const string SimpleListBoxItemsSourceDescription = "基础 ItemsSource 和模板用法示例。";
    public const string SearchableTitle = "可搜索";
    public const string SearchableDescription = "可搜索的列表。";
    public const string PaginationListTitle = "分页列表";
    public const string PaginationListDescription = "分页列表。";
    public const string P2PlaceholderTextSearch = "搜索";
    public const string P2FilterValue = "色";
    public const string P2TextSelectionMode = "选择模式：";
    public const string P2ContentSingle = "单选";
    public const string P2ContentMultiple = "多选";
    public const string P2ContentToggle = "切换选择";
    public const string P2TextSelectedItems = "已选：";
    public const string P2TextNoSelection = "无";
    public const string P2ContentSelectColors = "选择绿色 / 黄色";
    public const string P2ContentClearSelection = "清空";
    public const string P2ColorBlue = "蓝色";
    public const string P2ColorGreen = "绿色";
    public const string P2ColorRed = "红色";
    public const string P2ColorYellow = "黄色";
    public const string P2ColorOrange = "橙色";
    public const string P2ColorPurple = "紫色";
    public const string P2ColorPink = "粉色";
    public const string P2ColorBrown = "棕色";
    public const string P2ColorWhite = "白色";
    public const string P2ColorBlack = "黑色";
    public const string P2ColorGray = "灰色";
    public const string P2ColorTurquoise = "青绿色";
    public const string P2ColorViolet = "紫罗兰色";
    public const string P2ColorMagenta = "品红色";
    public const string P2ColorMaroon = "栗色";
    public const string P2ColorNavy = "海军蓝";
    public const string P2ColorBeige = "米色";
    public const string P2ColorCyan = "青色";
    public const string P2ColorLavender = "薰衣草色";
    public const string P2ColorOlive = "橄榄色";
    public const string P2GroupBasicColors = "基础颜色";
    public const string P2GroupNeutralColors = "中性色";
    public const string P2GroupSpecificShades = "特定色调";
    public const string P2ContentRacingCarSpraysBurningFuelIntoCrowd = "赛车向人群喷出燃烧的燃料。";
    public const string P2ContentJapanesePrincessToWedCommoner = "日本公主将嫁给平民。";
    public const string P2ContentAustralianWalksN100kmAfterOutbackCrash = "澳大利亚人在内陆车祸后步行 100 公里。";
    public const string P2ContentManChargedOverMissingWeddingGirl = "男子因婚礼女孩失踪案被起诉。";
    public const string P2ContentLosAngelesBattlesHugeWildfires = "洛杉矶抗击大规模山火。";
    public const string P2ContentDynamicItem = "动态项";
    public const string P2ContentPaginationItemFormat = "内容 {0}";

    public const string P2ContentAddItem = "添加项";

    public const string P2ContentRemoveItem = "移除项";

}
