// <auto-generated />
namespace AtomUI.Generated.AtomUI_Controls;

public static class IconThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Icon");
}

internal static class GeneratedControlThemeAssetManifest
{
    internal static global::System.Collections.Generic.IReadOnlyList<global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor> GetDescriptors()
    {
        return new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor[]
        {
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Controls/Icon/Themes/IconPresenterTheme.axaml"), IconThemeAsset.Identity, 0x068D4DD16D9106D0UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Controls/Icon/Themes/IconTheme.axaml"), IconThemeAsset.Identity, 0xEDBF77196D932811UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Controls/Icon/Themes/PathIconTheme.axaml"), IconThemeAsset.Identity, 0x068D4DD16D9106D0UL),
        };
    }
}
