using AtomUI.Theme.Language;

namespace AtomUIGallery.ShowCases.Steps;

[LanguageProvider(LanguageCode.zh_TW, StepsShowCase.LanguageId)]
internal partial class zh_TW
{
    public const string ScenarioBasic = "基礎";
    public const string ScenarioInteractive = "交互";
    public const string ScenarioVertical = "垂直";
    public const string ScenarioDotClickable = "點狀與可點擊";
    public const string ScenarioNavigation = "導航";
    public const string ScenarioProgress = "進度";
    public const string ScenarioInline = "內聯";
    public const string ScenarioExamples = "示例";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "設計 Token";
    public const string PageSubtitle = "引導使用者理解有順序的任務和流程狀態。";
    public const string PageDescription = "Steps 用於展示任務序列、進度、導航狀態以及可選的步驟內容，適合需要清晰階段感的流程。";
    public const string ComponentCategory = "導航";
    public const string ComponentStatusStable = "穩定";
    public const string ApiColumnProperty = "屬性";
    public const string ApiColumnDescription = "說明";
    public const string ApiColumnType = "類型";
    public const string ApiColumnDefault = "預設值";
    public const string TokenColumnToken = "Token";
    public const string TokenColumnDescription = "說明";
    public const string TokenColumnScope = "範圍";
    public const string TokenColumnStatus = "狀態";
    public const string ApiPropertyCurrent = "受控的目前步驟編號；啟用步驟項不會自動寫入此屬性。";
    public const string ApiPropertyInitial = "第一個步驟項的編號偏移；不會初始化或重設 Current。";
    public const string ApiPropertyStatus = "套用到目前步驟的預設狀態。";
    public const string ApiPropertyPercent = "目前進行中步驟的可選進度百分比；null 表示不顯示進度。";
    public const string ApiPropertyType = "選擇完整的 Default、Dot、OutlineDot、Navigation 或 Inline 視覺類型。";
    public const string ApiPropertyOrientation = "控制水平或垂直步驟布局。";
    public const string ApiPropertyTitlePlacement = "在目前類型支援時要求水平或垂直標題布局。";
    public const string ApiPropertySizeType = "控制步驟條視覺尺寸。";
    public const string ApiPropertyIsItemClickable = "允許已啟用的步驟項要求變更 Current。";
    public const string ApiPropertyOffset = "內聯步驟前方保留的空步驟單元數量；其他類型忽略該屬性。";
    public const string ApiPropertyHorizontalContentAlignment = "垂直 Navigation 步驟項的水平對齊方式。";
    public const string ApiPropertyIsMotionEnabled = "是否啟用過渡和指標 Wave 動畫。";
    public const string ApiPropertyItems = "控制項持有的步驟項集合。";
    public const string ApiPropertyItemsSource = "用於產生步驟項容器的可選資料來源。";
    public const string ApiPropertyItemTemplate = "ItemsSource 資料項使用的樣板。";
    public const string ApiEventCurrentChangeRequested = "啟動已啟用且非目前的步驟項時觸發；呼叫方決定是否更新 Current。";
    public const string ApiPropertyStepsItemHeader = "步驟的主標題內容。";
    public const string ApiPropertyStepsItemHeaderTemplate = "顯示步驟主標題的樣板。";
    public const string ApiPropertyStepsItemSubHeader = "顯示在步驟標題附近的輔助標題內容。";
    public const string ApiPropertyStepsItemSubHeaderTemplate = "顯示輔助標題內容的樣板。";
    public const string ApiPropertyStepsItemContent = "顯示在步驟標題下方或旁邊的詳情內容。";
    public const string ApiPropertyStepsItemContentTemplate = "顯示步驟詳情內容的樣板。";
    public const string ApiPropertyStepsItemIcon = "顯示在步驟指示器中的自定義圖標。";
    public const string ApiPropertyStepsItemStatus = "步驟項的可選顯式狀態覆蓋；null 使用 Steps 推導的狀態。";
    public const string ApiPropertyStepsItemIsEnabled = "控制步驟項是否可以接收啟用輸入。";
    public const string TokenNameDescriptionMaxWidth = "步驟描述區域的最大寬度。";
    public const string TokenNameIconSize = "預設步驟指示器容器尺寸。";
    public const string TokenNameIconFontSize = "預設步驟指示器圖標字號。";
    public const string TokenNameIconSizeSM = "小號步驟指示器尺寸。";
    public const string TokenNameDotSize = "點狀指示器尺寸。";
    public const string TokenNameDotCurrentSize = "目前點狀指示器尺寸。";
    public const string TokenNameDotLineThickness = "點狀連接線粗細。";
    public const string TokenNameHorizontalHeaderMargin = "水平步驟的標題外間距。";
    public const string TokenNameSubHeaderMargin = "步驟輔助標題使用的左側外間距。";
    public const string TokenNameVerticalItemSpacing = "垂直步驟項之間的間距。";
    public const string TokenNameVerticalDescriptionPadding = "垂直步驟描述使用的內間距。";
    public const string TokenNameStepsNavActiveColor = "導航步驟使用的啟用色。";
    public const string TokenNameInlineDotSize = "內聯步驟使用的點狀尺寸。";
    public const string TokenNameInlineItemPadding = "內聯步驟項使用的內間距。";
    public const string TokenNameProcessIconBgColor = "進行中步驟指示器背景色。";
    public const string TokenNameFinishTailColor = "已完成步驟連接線顏色。";
    public const string TokenNameErrorIconBgColor = "錯誤步驟指示器背景色。";
    public const string TokenScopeComponent = "元件";
    public const string TokenStatusStable = "穩定";
    public const string BasicTitle = "基礎用法";
    public const string BasicDescription = "最基礎的步驟條。";
    public const string MiniVersionTitle = "迷你版本";
    public const string MiniVersionDescription = "將 SizeType 設置為 Small 可獲得迷你版本。";
    public const string WithIconTitle = "帶圖標";
    public const string WithIconDescription = "可以通過為項目設置 icon 屬性使用自定義圖標。";
    public const string SwitchStepTitle = "切換步驟";
    public const string SwitchStepDescription = "透過受控 Current 繫結、變更要求、外部內容和按鈕展示流程進度。";
    public const string VerticalTitle = "垂直方向";
    public const string VerticalDescription = "垂直方向的簡單步驟條。";
    public const string VerticalMiniVersionTitle = "垂直迷你版本";
    public const string VerticalMiniVersionDescription = "垂直方向的簡單迷你步驟條。";
    public const string ErrorStatusTitle = "錯誤狀態";
    public const string ErrorStatusDescription = "通過 Steps 的 status 可以指定當前步驟狀態。";
    public const string DotStyleTitle = "點狀樣式";
    public const string DotStyleDescription = "帶進度點樣式的步驟條。";
    public const string DotStyleVerticalTitle = "垂直點狀樣式";
    public const string DotStyleVerticalDescription = "垂直方向帶進度點樣式的步驟條。";
    public const string ClickableTitle = "可點擊";
    public const string ClickableDescription = "設置 IsItemClickable=true 可讓步驟項可點擊。";
    public const string NavigationStepsTitle = "導航步驟";
    public const string NavigationStepsDescription = "導航式步驟。";
    public const string StepsWithProgressTitle = "帶進度的步驟";
    public const string StepsWithProgressDescription = "帶進度的步驟條。";
    public const string TitlePlacementTitle = "標題位置";
    public const string TitlePlacementDescription = "對支援的步驟類型將 TitlePlacement 設置為 Vertical。";
    public const string InlineStepsTitle = "內聯步驟";
    public const string InlineStepsDescription = "內聯類型步驟，適合在列表內容場景中展示對象的流程和當前狀態。";
    public const string InlineStyleCombinationTitle = "內聯樣式組合";
    public const string InlineStyleCombinationDescription = "內聯步驟條修改樣式，透過 offset 進行對齊。";
    public const string P2DescriptionThisIsADescription = "這是一段描述。";
    public const string P2HeaderFinished = "已完成";
    public const string P2HeaderInProgress = "進行中";
    public const string P2HeaderWaiting = "等待中";
    public const string P2HeaderLogin = "登錄";
    public const string P2HeaderVerification = "驗證";
    public const string P2HeaderPay = "支付";
    public const string P2HeaderDone = "完成";
    public const string P2HeaderFirst = "第一項";
    public const string P2HeaderSecond = "第二項";
    public const string P2HeaderThird = "第三項";
    public const string P2HeaderStepN1 = "步驟 1";
    public const string P2HeaderStepN2 = "步驟 2";
    public const string P2HeaderStepN3 = "步驟 3";
    public const string P2HeaderStepN4 = "步驟 4";
    public const string P2HeaderStepN5 = "步驟 5";
    public const string P2ContentThisIsStepN1 = "這是步驟 1";
    public const string P2ContentThisIsStepN2 = "這是步驟 2";
    public const string P2ContentThisIsStepN3 = "這是步驟 3";
    public const string P2ContentThisIsStepN4 = "這是步驟 4";
    public const string P2ContentThisIsStepN5 = "這是步驟 5";
    public const string P2HeaderFinishN1 = "完成 1";
    public const string P2HeaderFinishN2 = "完成 2";
    public const string P2HeaderCurrentProcess = "當前進行中";
    public const string P2HeaderWait = "等待";
    public const string P2SubHeaderSubTitle = "子標題";
    public const string P2SubHeaderLeftTime = "剩餘 00:00:08";
    public const string P2SubHeaderWaitingForLongTime = "等待較長時間";
    public const string P2TextAntDesignTitleN1 = "Ant Design 標題 1";
    public const string P2TextAntDesignADesignLanguageForBackgroundApplications = "Ant Design 是由 Ant UED 團隊提煉的後台應用設計語言";
    public const string P2TextAntDesignTitleN2 = "Ant Design 標題 2";
    public const string P2TextAntDesignTitleN3 = "Ant Design 標題 3";
    public const string P2TextAntDesignTitleN4 = "Ant Design 標題 4";
    public const string P2TextCurrent = "Current：";

    public const string P2ContentFirstContent = "第一步內容";

    public const string P2ContentSecondContent = "第二步內容";

    public const string P2ContentLastContent = "最後一步內容";

    public const string P2ContentNext = "下一步";

    public const string P2ContentPrevious = "上一步";

    public const string P2ContentDone = "完成";

}
