using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.Menu;

[LanguageProvider(LanguageCode.en_US, MenuShowCase.LanguageId)]
internal class en_US : LanguageProvider
{
    public const string BasicTitle = "Basic";
    public const string BasicDescription = "Simplest Usage.";
    public const string MenuItemItemsSourceTitle = "Generate MenuItem by ItemsSource";
    public const string MenuItemItemsSourceDescription = "Generate structure based on ItemsSource and template.";
    public const string InlineNavMenuItemsSourceTitle = "Inline NavMenu by ItemsSource";
    public const string InlineNavMenuItemsSourceDescription = "Generate inline NavMenu structure based on ItemsSource and template.";
    public const string IconAndSubmenuTitle = "Icon and submenu";
    public const string IconAndSubmenuDescription = "With icon and submenu.";
    public const string ToggleTypeTitle = "Menu item with ToggleType";
    public const string ToggleTypeDescription = "Renders a checkbox or radio button on a menu.";
    public const string ScrollableTitle = "Scrollable menu";
    public const string ScrollableDescription = "When there are too many menu items, up and down scroll buttons will appear.";
    public const string ContextMenuTitle = "Context menu";
    public const string ContextMenuDescription = "Right click to bring up the context menu.";
    public const string ContextMenuItemsSourceTitle = "Context menu, Generate MenuItem by ItemsSource";
    public const string ContextMenuItemsSourceDescription = "Right click to bring up the context menu.";
    public const string MenuFlyoutTitle = "Menu Flyout";
    public const string MenuFlyoutDescription = "Right Click to show Context Flyout";
    public const string VerticalNavMenuTitle = "Vertical nav menu";
    public const string VerticalNavMenuDescription = "Submenus open as pop-ups.";
    public const string InlineMenuTitle = "Inline menu";
    public const string InlineMenuDescription = "Vertical menu with inline submenus.";
    public const string TopNavigationTitle = "Top Navigation";
    public const string TopNavigationDescription = "Horizontal top navigation menu.";
    public const string SwitchMenuTypeTitle = "Switch the menu type";
    public const string SwitchMenuTypeDescription = "Show the dynamic switching mode (between inline and vertical).";
    public const string DefaultOpenedPathsTitle = "Default Opened paths";
    public const string DefaultOpenedPathsDescription = "You can open or select the path by default.";
    public const string NavMenuItemItemsSourceTitle = "Generate NavMenuItem by ItemsSource";
    public const string NavMenuItemItemsSourceDescription = "Generate structure based on ItemsSource and template.";
    public const string P2HeaderFile = "_File";
    public const string P2HeaderNewTextFile = "New Text File";
    public const string P2HeaderNewFile = "New File";
    public const string P2HeaderNewWindow = "New Window";
    public const string P2HeaderEdit = "_Edit";
    public const string P2HeaderUndo = "Undo";
    public const string P2HeaderCut = "Cut";
    public const string P2HeaderDisabledItem = "Disabled Item";
    public const string P2HeaderSave = "Save";
    public const string P2HeaderSaveAs = "Save As...";
    public const string P2HeaderSaveAll = "Save All";
    public const string P2HeaderExit = "Exit";
    public const string P2HeaderCopy = "Copy";
    public const string P2HeaderDelete = "Delete";
    public const string P2HeaderPaste = "Paste";
    public const string P2HeaderPasteFromHistory = "Paste from History";
    public const string P2HeaderMenuA = "_Menu A";
    public const string P2HeaderDisabled = "Disabled";
    public const string P2HeaderMenu = "_Menu";
    public const string P2HeaderMenuItem = "Menu Item";
    public const string P2TextRightClickToShowContextMenu = "Right Click to show Context Menu";
    public const string P2TitleNormal = "Normal";
    public const string P2TextRightClickToShowContextFlyout = "Right Click to show Context Flyout";
    public const string P2TitleGeneratedByTemplate = "Generated by template";
    public const string P2HeaderNavigationOne = "Navigation One";
    public const string P2HeaderNavigationTwo = "Navigation Two";
    public const string P2HeaderNavigationThreeSubmenu = "Navigation Three - Submenu";
    public const string P2HeaderItemN1 = "Item 1";
    public const string P2HeaderOptionN1 = "Option 1";
    public const string P2HeaderOptionN2 = "Option 2";
    public const string P2HeaderItemN2 = "Item 2";
    public const string P2HeaderOptionN3 = "Option 3";
    public const string P2HeaderOptionN4 = "Option 4";
    public const string P2HeaderNavigationFour = "Navigation Four";
    public const string P2TextChangeMode = "Change Mode";
    public const string P2TextChangeStyle = "Change Style";

    protected override Type GetResourceKindType() => typeof(MenuShowCaseLangResourceKind);
}
