// <auto-generated />
namespace AtomUI.Generated.AtomUI_Desktop_Controls_ColorPicker;

public static class ColorPickerThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "ColorPicker");
}

internal static class GeneratedControlThemeAssetManifest
{
    internal static global::System.Collections.Generic.IReadOnlyList<global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor> GetDescriptors()
    {
        return new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor[]
        {
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls.ColorPicker/Themes/AbstractColorPickerTheme.axaml"), ColorPickerThemeAsset.Identity, 0xA0C30E28D0D6EF21UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls.ColorPicker/Themes/ColorBlockTheme.axaml"), ColorPickerThemeAsset.Identity, 0x125667EE08300F27UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls.ColorPicker/Themes/ColorPickerPaletteGroupTheme.axaml"), ColorPickerThemeAsset.Identity, 0x125667EE08300F27UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls.ColorPicker/Themes/ColorSlider/ColorSliderTheme.axaml"), ColorPickerThemeAsset.Identity, 0x125667EE08300F27UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls.ColorPicker/Themes/ColorSlider/ColorSliderThumbTheme.axaml"), ColorPickerThemeAsset.Identity, 0x125667EE08300F27UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls.ColorPicker/Themes/ColorSlider/GradientColorSliderTheme.axaml"), ColorPickerThemeAsset.Identity, 0x125667EE08300F27UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls.ColorPicker/Themes/ColorView/AbstractColorPickerViewTheme.axaml"), ColorPickerThemeAsset.Identity, 0x125667EE08300F27UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls.ColorPicker/Themes/ColorView/ColorPickerViewTheme.axaml"), ColorPickerThemeAsset.Identity, 0xA1704322AFE37A0AUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls.ColorPicker/Themes/ColorView/ColorSpectrumTheme.axaml"), ColorPickerThemeAsset.Identity, 0x125667EE08300F27UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls.ColorPicker/Themes/ColorView/GradientColorPickerViewTheme.axaml"), ColorPickerThemeAsset.Identity, 0xA1704322AFE37A0AUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls.ColorPicker/Themes/GradientColorPickerTheme.axaml"), ColorPickerThemeAsset.Identity, 0x125667EE08300F27UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls.ColorPicker/Themes/PaletteColorItemTheme.axaml"), ColorPickerThemeAsset.Identity, 0x125667EE08300F27UL),
        };
    }
}
