using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace AtomUI.Generator;

internal sealed class ThemeAssetManifestWriter
{
    private readonly SourceProductionContext _context;
    private readonly string _assemblyName;
    private readonly IReadOnlyList<ThemeAssetInfo> _assets;

    internal ThemeAssetManifestWriter(
        SourceProductionContext context,
        string assemblyName,
        IReadOnlyList<ThemeAssetInfo> assets)
    {
        _context      = context;
        _assemblyName = assemblyName;
        _assets       = assets;
    }

    internal void Write()
    {
        var ns = $"AtomUI.Generated.{ToIdentifier(_assemblyName)}";
        var identities = _assets.Select(static asset => asset.Identities[0])
                                .Distinct(StringComparer.Ordinal)
                                .OrderBy(static identity => identity, StringComparer.Ordinal)
                                .ToArray();
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.Append("namespace ").Append(ns).AppendLine(";");
        builder.AppendLine();
        foreach (var identity in identities)
        {
            builder.Append("public static class ").Append(identity).AppendLine("ThemeAsset");
            builder.AppendLine("{");
            builder.Append("    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity(\"AtomUI\", \"")
                   .Append(identity)
                   .AppendLine("\");");
            builder.AppendLine("}");
            builder.AppendLine();
        }

        builder.AppendLine("internal static class GeneratedControlThemeAssetManifest");
        builder.AppendLine("{");
        builder.AppendLine("    internal static global::System.Collections.Generic.IReadOnlyList<global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor> GetDescriptors()");
        builder.AppendLine("    {");
        builder.AppendLine("        return new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor[]");
        builder.AppendLine("        {");
        foreach (var asset in _assets.OrderBy(static asset => asset.AssetPath, StringComparer.Ordinal))
        {
            var identity = asset.Identities[0];
            builder.Append("            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri(\"avares://")
                   .Append(Escape(_assemblyName))
                   .Append('/')
                   .Append(Escape(asset.AssetPath))
                   .Append("\"), ")
                   .Append(identity)
                   .Append("ThemeAsset.Identity, 0x")
                   .Append(ComputeFingerprint(asset).ToString("X16", System.Globalization.CultureInfo.InvariantCulture))
                   .AppendLine("UL),");
        }
        builder.AppendLine("        };");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        _context.AddSource(
            "GeneratedControlThemeAssetManifest.g.cs",
            SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    private static ulong ComputeFingerprint(ThemeAssetInfo asset)
    {
        var hash = 14695981039346656037UL;
        Add(ref hash, asset.Identities[0]);
        foreach (var family in asset.ControlTokenFamilies)
        {
            Add(ref hash, family);
        }
        return hash;
    }

    private static void Add(ref ulong hash, string value)
    {
        foreach (var character in value)
        {
            hash ^= character;
            hash *= 1099511628211UL;
        }
    }

    private static string ToIdentifier(string value)
    {
        var builder = new StringBuilder(value.Length);
        foreach (var character in value)
        {
            builder.Append(char.IsLetterOrDigit(character) || character == '_' ? character : '_');
        }
        if (builder.Length == 0 || char.IsDigit(builder[0]))
        {
            builder.Insert(0, '_');
        }
        return builder.ToString();
    }

    private static string Escape(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
