using System.Text;
using AtomUI.SourceGeneration;
using Microsoft.CodeAnalysis;

namespace AtomUI.Generator;

internal sealed class ThemeAssetManifestWriter
{
    private readonly SourceProductionContext _context;
    private readonly string _assemblyName;
    private readonly string _packageId;
    private readonly IReadOnlyList<ResolvedThemeAssetInfo> _assets;
    private readonly IReadOnlyList<UnitOwnedThemeAssetInfo> _unitOwnedAssets;
    private readonly IReadOnlyList<ThemeAssetInfo> _packageSharedAssets;
    private readonly IReadOnlyList<ThemeAssetInfo> _unknownAssets;
    private readonly IReadOnlyList<string> _globalTokenNames;
    private readonly bool _emitLinkedRegistration;

    internal ThemeAssetManifestWriter(
        SourceProductionContext context,
        string assemblyName,
        string packageId,
        IReadOnlyList<ResolvedThemeAssetInfo> assets,
        IReadOnlyList<UnitOwnedThemeAssetInfo> unitOwnedAssets,
        IReadOnlyList<ThemeAssetInfo> packageSharedAssets,
        IReadOnlyList<ThemeAssetInfo> unknownAssets,
        IReadOnlyList<string> globalTokenNames,
        bool emitLinkedRegistration)
    {
        _context = context;
        _assemblyName = assemblyName;
        _packageId = packageId;
        _assets = assets;
        _unitOwnedAssets = unitOwnedAssets;
        _packageSharedAssets = packageSharedAssets;
        _unknownAssets = unknownAssets;
        _globalTokenNames = globalTokenNames;
        _emitLinkedRegistration = emitLinkedRegistration;
    }

    internal void Write()
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.Append("namespace ").Append(GeneratedCodeNamespace.ForAssembly(_assemblyName)).AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("internal static class GeneratedControlThemeAssetManifest");
        builder.AppendLine("{");
        builder.AppendLine("    internal static global::System.Collections.Generic.IReadOnlyList<global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor> GetDescriptors()");
        builder.AppendLine("    {");
        if (_assets.Count == 0)
        {
            builder.AppendLine("        return global::System.Array.Empty<global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor>();");
        }
        else
        {
            builder.AppendLine("        return new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor[]");
            builder.AppendLine("        {");
            foreach (var asset in _assets.OrderBy(static item => item.Asset.AssetPath, StringComparer.Ordinal))
            {
                WriteAsset(builder, asset, "            ", ",");
            }
            builder.AppendLine("        };");
        }
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine();
        WriteResourceLoader(builder);
        _context.AddSource(
            "GeneratedControlThemeAssetManifest.g.cs",
            GeneratedSourceText.From(builder.ToString()));
        if (_emitLinkedRegistration)
        {
            WriteFragments();
        }
    }

    private void WriteFragments()
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        foreach (var asset in _unknownAssets.OrderBy(static item => item.AssetPath, StringComparer.Ordinal))
        {
            LinkedRegistration.Manifest.LinkedRegistrationMetadataWriter.Write(
                builder,
                new LinkedRegistration.Manifest.LinkedFallbackManifestRecord(
                    _packageId,
                    "UnresolvedAxaml",
                    asset.AssetPath,
                    0,
                    0));
        }
        foreach (var edge in _assets.SelectMany(static asset => asset.ReferencedUnitIds.Select(
                     dependencyUnitId => new
                     {
                         SourceUnitId = asset.OwnerUnitId,
                         TargetUnitId = dependencyUnitId
                     }))
                     .Where(static edge => !string.Equals(
                         edge.SourceUnitId,
                         edge.TargetUnitId,
                         StringComparison.Ordinal))
                     .Distinct()
                     .OrderBy(static edge => edge.SourceUnitId, StringComparer.Ordinal)
                     .ThenBy(static edge => edge.TargetUnitId, StringComparer.Ordinal))
        {
            LinkedRegistration.Manifest.LinkedRegistrationMetadataWriter.Write(
                builder,
                new LinkedRegistration.Manifest.LinkedUnitEdgeManifestRecord(
                    _packageId,
                    edge.SourceUnitId,
                    edge.TargetUnitId,
                    LinkedRegistration.Manifest.LinkedUnitEdgeEvidenceKind.AxamlType));
        }
        builder.AppendLine();
        builder.Append("namespace ").Append(GeneratedCodeNamespace.ForAssembly(_assemblyName))
               .AppendLine(".LinkedRegistrationV1;");
        builder.AppendLine();

        var packageSharedFragmentName = LinkedRegistration.LinkedRegistrationFragmentName
            .ForPackageShared(_packageId);
        builder.AppendLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        builder.Append("public static class ").Append(packageSharedFragmentName).AppendLine();
        builder.AppendLine("{");
        builder.AppendLine("    public static void Add(");
        builder.AppendLine("        global::AtomUI.Registration.AotTrimControlPackageRegistrationBuilder builder)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(builder);");
        foreach (var asset in _packageSharedAssets
                     .Where(static item => item.IsResourceDictionary || item.IsDefaultTypedControlTheme)
                     .OrderBy(static item => item.AssetPath, StringComparer.Ordinal))
        {
            builder.AppendLine("        builder.AddPackageSharedThemeAsset(");
            WriteResourceFactory(builder, asset, loadable: true, "            ");
        }
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine();

        var unitIds = _assets.Select(static asset => asset.OwnerUnitId)
                             .Concat(_unitOwnedAssets.Select(static asset => asset.UnitId))
                             .Distinct(StringComparer.Ordinal)
                             .OrderBy(static unitId => unitId, StringComparer.Ordinal)
                             .ToArray();
        foreach (var unitId in unitIds)
        {
            var unitAssets = _assets.Where(asset =>
                                       string.Equals(asset.OwnerUnitId, unitId, StringComparison.Ordinal))
                                   .OrderBy(static asset => asset.Asset.AssetPath, StringComparer.Ordinal)
                                   .ToArray();
            var unitResources = _unitOwnedAssets.Where(asset =>
                                                     string.Equals(asset.UnitId, unitId, StringComparison.Ordinal))
                                                .OrderBy(static asset => asset.Asset.AssetPath, StringComparer.Ordinal)
                                                .ToArray();
            var fragmentName = LinkedRegistration.LinkedRegistrationFragmentName.ForUnit(unitId);
            builder.Append("public static partial class ").Append(fragmentName).AppendLine();
            builder.AppendLine("{");
            builder.AppendLine("    static partial void AddThemes(");
            builder.AppendLine("        global::AtomUI.Registration.AotTrimControlPackageRegistrationBuilder builder)");
            builder.AppendLine("    {");
            foreach (var asset in unitAssets)
            {
                builder.AppendLine("        builder.AddThemeAsset(");
                WriteAsset(builder, asset, "            ", ",");
                WriteResourceFactory(builder, asset.Asset, IsLoadable(asset), "            ");
            }
            foreach (var resource in unitResources.Where(static resource =>
                         resource.Asset.HasGeneratedResourceWrapper))
            {
                builder.AppendLine("        builder.AddUnitThemeResource(");
                WriteResourceFactory(builder, resource.Asset, loadable: true, "            ");
            }
            builder.AppendLine("    }");
            builder.AppendLine("}");
            builder.AppendLine();
        }

        _context.AddSource(
            "GeneratedControlThemeAssetFragments.g.cs",
            GeneratedSourceText.From(builder.ToString()));
    }

    private void WriteResourceFactory(
        StringBuilder builder,
        ThemeAssetInfo asset,
        bool loadable,
        string indentation)
    {
        if (!loadable)
        {
            builder.Append(indentation).AppendLine("static _ => { });");
            return;
        }

        var generatedNamespace = "global::" + GeneratedCodeNamespace.ForAssembly(_assemblyName);
        var className = ThemeAssetInfo.GetGeneratedResourceClassName(asset.AssetPath);
        builder.Append(indentation).AppendLine("static provider =>");
        builder.Append(indentation).AppendLine("{");
        builder.Append(indentation).Append("    provider.ControlThemes.Add(new ")
               .Append(generatedNamespace).Append('.').Append(className).AppendLine("());");
        builder.Append(indentation).AppendLine("});");
    }

    private static bool IsLoadable(ResolvedThemeAssetInfo asset)
    {
        return asset.Asset.IsResourceDictionary ||
               (asset.SemanticPart is null && asset.Asset.IsDefaultTypedControlTheme);
    }

    private void WriteResourceLoader(StringBuilder builder)
    {
        builder.AppendLine("internal static class GeneratedControlThemeAssetResources");
        builder.AppendLine("{");
        builder.AppendLine("    internal static void AddResources(");
        builder.AppendLine("        global::AtomUI.Theme.Resources.IControlThemesProvider provider,");
        builder.AppendLine("        global::System.Collections.Generic.IReadOnlyList<global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor> assets)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(provider);");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(assets);");
        var loadableAssets = _assets.Where(static item =>
                                        item.Asset.IsResourceDictionary ||
                                        (item.SemanticPart is null && item.Asset.IsDefaultTypedControlTheme))
                                    .OrderBy(static item => item.Asset.AssetPath, StringComparer.Ordinal)
                                    .ToArray();
        var loadablePackageCoreAssets = _packageSharedAssets
                                      .Concat(_unknownAssets)
                                      .Concat(_unitOwnedAssets.Select(static asset => asset.Asset))
                                      .Where(static asset => asset.HasGeneratedResourceWrapper)
                                      .OrderBy(static asset => asset.AssetPath, StringComparer.Ordinal)
                                      .ToArray();
        if (loadableAssets.Length != 0 || loadablePackageCoreAssets.Length != 0)
        {
            builder.AppendLine("        var controlThemes = provider.ControlThemes;");
            foreach (var asset in loadablePackageCoreAssets)
            {
                WriteLoadAsset(builder, asset, "        ");
            }
        }
        if (loadableAssets.Length != 0)
        {
            builder.AppendLine("        foreach (var asset in assets)");
            builder.AppendLine("        {");
            builder.AppendLine("            switch (asset.AssetUri.AbsoluteUri)");
            builder.AppendLine("            {");
            foreach (var asset in loadableAssets)
            {
                builder.Append("                case \"avares://")
                       .Append(Escape(_assemblyName)).Append('/')
                       .Append(Escape(asset.Asset.AssetPath)).AppendLine("\":");
                builder.AppendLine("                {");
                WriteLoadAsset(builder, asset.Asset, "                    ");
                builder.AppendLine("                    break;");
                builder.AppendLine("                }");
            }
            builder.AppendLine("            }");
            builder.AppendLine("        }");
        }
        builder.AppendLine("    }");
        builder.AppendLine("}");
    }

    private static void WriteLoadAsset(StringBuilder builder, ThemeAssetInfo asset, string indentation)
    {
        var className = ThemeAssetInfo.GetGeneratedResourceClassName(asset.AssetPath);
        builder.Append(indentation).Append("controlThemes.Add(new ").Append(className).AppendLine("());");
    }

    private void WriteAsset(
        StringBuilder builder,
        ResolvedThemeAssetInfo asset,
        string indentation,
        string suffix)
    {
        builder.Append(indentation).Append("new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(")
               .Append("new global::System.Uri(\"avares://")
               .Append(Escape(_assemblyName))
               .Append('/')
               .Append(Escape(asset.Asset.AssetPath))
               .Append("\"), ")
               .Append("new global::AtomUI.Theme.Schema.ControlTokenIdentity(\"")
               .Append(Escape(asset.OwnerIdentity.Catalog))
               .Append("\", \"")
               .Append(Escape(asset.OwnerIdentity.Id))
               .Append("\"), new global::AtomUI.Theme.Schema.ControlTokenIdentity[] { ");
        foreach (var identity in asset.ReferencedControlIdentities)
        {
            builder.Append("new global::AtomUI.Theme.Schema.ControlTokenIdentity(\"")
                   .Append(Escape(identity.Catalog))
                   .Append("\", \"")
                   .Append(Escape(identity.Id))
                   .Append("\"), ");
        }
        builder.Append("}, ");
        if (asset.SemanticPart is null)
        {
            builder.Append("null, ");
        }
        else
        {
            builder.Append("new global::AtomUI.Theme.Schema.ControlThemeSemanticPartDescriptor(\"")
                   .Append(Escape(asset.SemanticPart.PropertyName))
                   .Append("\", \"")
                   .Append(Escape(asset.SemanticPart.TargetTypeName))
                   .Append("\"), ");
        }
        builder.Append("0x")
               .Append(ComputeFingerprint(asset).ToString("X16", System.Globalization.CultureInfo.InvariantCulture))
               .Append("UL)")
               .AppendLine(suffix);
    }

    private ulong ComputeFingerprint(ResolvedThemeAssetInfo asset)
    {
        var hash = 14695981039346656037UL;
        Add(ref hash, asset.OwnerIdentity.Catalog);
        Add(ref hash, asset.OwnerIdentity.Id);
        foreach (var identity in asset.ReferencedControlIdentities)
        {
            Add(ref hash, identity.Catalog);
            Add(ref hash, identity.Id);
        }
        foreach (var tokenName in _globalTokenNames)
        {
            Add(ref hash, tokenName);
        }
        if (asset.SemanticPart is not null)
        {
            Add(ref hash, asset.SemanticPart.PropertyName);
            Add(ref hash, asset.SemanticPart.TargetTypeName);
        }
        return hash;
    }

    private static void Add(ref ulong hash, string value)
    {
        foreach (var character in value)
        {
            hash ^= character;
            hash *= 1099511628211UL;
        }
    }

    private static string Escape(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
