using System.Text;
using Microsoft.CodeAnalysis;

namespace AtomUI.Generator;

internal sealed class ThemeAssetManifestWriter
{
    private readonly SourceProductionContext _context;
    private readonly string _assemblyName;
    private readonly IReadOnlyList<ResolvedThemeAssetInfo> _assets;
    private readonly IReadOnlyList<ThemeAssetInfo> _auxiliaryAssets;
    private readonly IReadOnlyList<string> _globalTokenNames;

    internal ThemeAssetManifestWriter(
        SourceProductionContext context,
        string assemblyName,
        IReadOnlyList<ResolvedThemeAssetInfo> assets,
        IReadOnlyList<ThemeAssetInfo> auxiliaryAssets,
        IReadOnlyList<string> globalTokenNames)
    {
        _context = context;
        _assemblyName = assemblyName;
        _assets = assets;
        _auxiliaryAssets = auxiliaryAssets;
        _globalTokenNames = globalTokenNames;
    }

    internal void Write()
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.Append("namespace AtomUI.Generated.").Append(ToIdentifier(_assemblyName)).AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("internal static class GeneratedControlThemeAssetManifest");
        builder.AppendLine("{");
        builder.AppendLine("    internal static global::System.Collections.Generic.IReadOnlyList<global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor> GetDescriptors()");
        builder.AppendLine("    {");
        if (_assets.Count == 0)
        {
            builder.AppendLine("        return global::System.Array.Empty<global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor>();");
        }
        else
        {
            builder.AppendLine("        return new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor[]");
            builder.AppendLine("        {");
            foreach (var asset in _assets.OrderBy(static item => item.Asset.AssetPath, StringComparer.Ordinal))
            {
                WriteAsset(builder, asset);
            }
            builder.AppendLine("        };");
        }
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine();
        WriteResourceLoader(builder);
        _context.AddSource(
            "GeneratedControlThemeAssetManifest.g.cs",
            GeneratedSourceText.From(builder.ToString()));
    }

    private void WriteResourceLoader(StringBuilder builder)
    {
        builder.AppendLine("internal static class GeneratedControlThemeAssetResources");
        builder.AppendLine("{");
        builder.AppendLine("    internal static void AddResources(");
        builder.AppendLine("        global::AtomUI.Theme.Resources.IControlThemesProvider provider,");
        builder.AppendLine("        global::System.Collections.Generic.IReadOnlyList<global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor> assets)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(provider);");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(assets);");
        var loadableAssets = _assets.Where(static item =>
                                        item.Asset.IsResourceDictionary ||
                                        (item.SemanticPart is null && item.Asset.IsDefaultTypedControlTheme))
                                    .OrderBy(static item => item.Asset.AssetPath, StringComparer.Ordinal)
                                    .ToArray();
        var loadableAuxiliaryAssets = _auxiliaryAssets
                                      .Where(static asset =>
                                          asset.IsResourceDictionary || asset.IsDefaultTypedControlTheme)
                                      .OrderBy(static asset => asset.AssetPath, StringComparer.Ordinal)
                                      .ToArray();
        if (loadableAssets.Length != 0 || loadableAuxiliaryAssets.Length != 0)
        {
            builder.AppendLine("        var controlThemes = provider.ControlThemes;");
            foreach (var asset in loadableAuxiliaryAssets)
            {
                WriteLoadAsset(builder, asset, "        ");
            }
        }
        if (loadableAssets.Length != 0)
        {
            builder.AppendLine("        foreach (var asset in assets)");
            builder.AppendLine("        {");
            builder.AppendLine("            switch (asset.AssetUri.AbsoluteUri)");
            builder.AppendLine("            {");
            foreach (var asset in loadableAssets)
            {
                builder.Append("                case \"avares://")
                       .Append(Escape(_assemblyName)).Append('/')
                       .Append(Escape(asset.Asset.AssetPath)).AppendLine("\":");
                builder.AppendLine("                {");
                WriteLoadAsset(builder, asset.Asset, "                    ");
                builder.AppendLine("                    break;");
                builder.AppendLine("                }");
            }
            builder.AppendLine("            }");
            builder.AppendLine("        }");
        }
        builder.AppendLine("    }");
        builder.AppendLine("}");
    }

    private static void WriteLoadAsset(StringBuilder builder, ThemeAssetInfo asset, string indentation)
    {
        var className = ThemeAssetInfo.GetGeneratedResourceClassName(asset.AssetPath);
        builder.Append(indentation).Append("controlThemes.Add(new ").Append(className).AppendLine("());");
    }

    private void WriteAsset(StringBuilder builder, ResolvedThemeAssetInfo asset)
    {
        builder.Append("            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(")
               .Append("new global::System.Uri(\"avares://")
               .Append(Escape(_assemblyName))
               .Append('/')
               .Append(Escape(asset.Asset.AssetPath))
               .Append("\"), ")
               .Append("new global::AtomUI.Theme.Schema.ControlTokenIdentity(\"")
               .Append(Escape(asset.OwnerIdentity.Catalog))
               .Append("\", \"")
               .Append(Escape(asset.OwnerIdentity.Id))
               .Append("\"), new global::AtomUI.Theme.Schema.ControlTokenIdentity[] { ");
        foreach (var identity in asset.ReferencedControlIdentities)
        {
            builder.Append("new global::AtomUI.Theme.Schema.ControlTokenIdentity(\"")
                   .Append(Escape(identity.Catalog))
                   .Append("\", \"")
                   .Append(Escape(identity.Id))
                   .Append("\"), ");
        }
        builder.Append("}, ");
        if (asset.SemanticPart is null)
        {
            builder.Append("null, ");
        }
        else
        {
            builder.Append("new global::AtomUI.Theme.Schema.ControlThemeSemanticPartDescriptor(\"")
                   .Append(Escape(asset.SemanticPart.PropertyName))
                   .Append("\", \"")
                   .Append(Escape(asset.SemanticPart.TargetTypeName))
                   .Append("\"), ");
        }
        builder.Append("0x")
               .Append(ComputeFingerprint(asset).ToString("X16", System.Globalization.CultureInfo.InvariantCulture))
               .AppendLine("UL),");
    }

    private ulong ComputeFingerprint(ResolvedThemeAssetInfo asset)
    {
        var hash = 14695981039346656037UL;
        Add(ref hash, asset.OwnerIdentity.Catalog);
        Add(ref hash, asset.OwnerIdentity.Id);
        foreach (var identity in asset.ReferencedControlIdentities)
        {
            Add(ref hash, identity.Catalog);
            Add(ref hash, identity.Id);
        }
        foreach (var tokenName in _globalTokenNames)
        {
            Add(ref hash, tokenName);
        }
        if (asset.SemanticPart is not null)
        {
            Add(ref hash, asset.SemanticPart.PropertyName);
            Add(ref hash, asset.SemanticPart.TargetTypeName);
        }
        return hash;
    }

    private static void Add(ref ulong hash, string value)
    {
        foreach (var character in value)
        {
            hash ^= character;
            hash *= 1099511628211UL;
        }
    }

    private static string ToIdentifier(string value)
    {
        var builder = new StringBuilder(value.Length);
        foreach (var character in value)
        {
            builder.Append(char.IsLetterOrDigit(character) || character == '_' ? character : '_');
        }
        if (builder.Length == 0 || char.IsDigit(builder[0]))
        {
            builder.Insert(0, '_');
        }
        return builder.ToString();
    }

    private static string Escape(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
