using AtomUI.Theme.Language;

namespace AtomUIGallery.ShowCases.Drawer;

[LanguageProvider(LanguageCode.en_US, DrawerShowCase.LanguageId)]
internal partial class en_US
{
    public const string PageSubtitle = "A slide-out panel for contextual tasks.";
    public const string PageDescription = "Drawer opens from the edge of the window or a local container, keeping users in the current workflow while exposing secondary actions, forms, or details.";
    public const string ComponentCategory = "Feedback";
    public const string ComponentStatusStable = "Stable";
    public const string ScenarioExamples = "Examples";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "Design Token";
    public const string ApiColumnProperty = "Property";
    public const string ApiColumnDescription = "Description";
    public const string ApiColumnType = "Type";
    public const string ApiColumnDefault = "Default";
    public const string TokenColumnToken = "Token";
    public const string TokenColumnDescription = "Description";
    public const string TokenColumnScope = "Scope";
    public const string TokenColumnStatus = "Status";
    public const string ApiPropertyDrawerContent = "Drawer body content.";
    public const string ApiPropertyDrawerContentTemplate = "Template used to render drawer body content.";
    public const string ApiPropertyDrawerContentPadding = "Overrides padding around drawer body content.";
    public const string ApiPropertyDrawerIsOpen = "Controls whether the drawer is open.";
    public const string ApiPropertyDrawerPlacement = "Specifies which edge the drawer appears from.";
    public const string ApiPropertyDrawerOpenOn = "Sets the host control where the drawer is rendered.";
    public const string ApiPropertyDrawerIsShowMask = "Controls whether the modal mask is displayed.";
    public const string ApiPropertyDrawerIsShowCloseButton = "Controls whether the close button is displayed in the header.";
    public const string ApiPropertyDrawerIsCloseOnMaskClick = "Controls whether clicking the mask closes the drawer.";
    public const string ApiPropertyDrawerTitle = "Header title text.";
    public const string ApiPropertyDrawerExtra = "Additional content displayed in the header action area.";
    public const string ApiPropertyDrawerFooter = "Footer content displayed at the bottom of the drawer.";
    public const string ApiPropertyDrawerSizeType = "Preset size token used by the drawer.";
    public const string ApiPropertyDrawerDialogSize = "Explicit drawer width or height when using custom size.";
    public const string ApiPropertyDrawerPushOffsetPercent = "Offset ratio used when a child drawer pushes its parent.";
    public const string ApiPropertyDrawerIsMotionEnabled = "Controls whether drawer transition motion is enabled.";
    public const string TokenNameDrawerHeaderMargin = "Header margin inside the drawer panel.";
    public const string TokenNameDrawerBodyPadding = "Padding applied to drawer body content.";
    public const string TokenNameDrawerFooterPadding = "Padding applied to the drawer footer.";
    public const string TokenNameDrawerCloseIconPadding = "Padding around the close icon button.";
    public const string TokenNameDrawerCloseIconMargin = "Margin around the close icon button.";
    public const string TokenNameDrawerSmallSize = "Small drawer preset size.";
    public const string TokenNameDrawerMiddleSize = "Middle drawer preset size.";
    public const string TokenNameDrawerLargeSize = "Large drawer preset size.";
    public const string TokenNameDrawerPushOffsetPercent = "Default push offset ratio for nested drawers.";
    public const string TokenNameDrawerBoxShadowLeft = "Shadow used when the drawer opens from the left.";
    public const string TokenNameDrawerBoxShadowRight = "Shadow used when the drawer opens from the right.";
    public const string TokenNameDrawerBoxShadowUp = "Shadow used when the drawer opens from the top.";
    public const string TokenNameDrawerBoxShadowDown = "Shadow used when the drawer opens from the bottom.";
    public const string TokenScopeComponent = "Component";
    public const string TokenStatusStable = "Stable";
    public const string BasicTitle = "Basic";
    public const string BasicDescription = "Basic drawer.";
    public const string MultiLevelTitle = "Multi-level drawer";
    public const string MultiLevelDescription = "Open a new drawer on top of an existing drawer to handle multi branch tasks.";
    public const string ExtraAndFooterTitle = "Extra and Footer";
    public const string ExtraAndFooterDescription = "Set the header extra area and footer area.";
    public const string NoMaskTitle = "No Mask";
    public const string NoMaskDescription = "Without a mask.";
    public const string CustomPlacementTitle = "Custom Placement";
    public const string CustomPlacementDescription = "The Drawer can appear from any edge of the screen.";
    public const string RenderInCurrentAreaTitle = "Render in current area";
    public const string RenderInCurrentAreaDescription = "Render in current area.";
    public const string PresetSizeTitle = "Preset size";
    public const string PresetSizeDescription = "The default width (or height) of Drawer is 378px, and there is a preset large size 736px.";
    public const string P2TitleBasicDrawer = "Basic Drawer";
    public const string P2TextSomeContents = "Some contents...";
    public const string P2TitleFirstLevelDrawer = "First-level Drawer";
    public const string P2TitleTwoLevelDrawer = "Two-level Drawer";
    public const string P2TextPlacement = "Placement:";
    public const string P2ContentLeft = "Left";
    public const string P2ContentTop = "Top";
    public const string P2ContentRight = "Right";
    public const string P2ContentBottom = "Bottom";
    public const string P2ContentTwoLevelDrawer = "Two-level drawer";
    public const string P2ContentCancel = "Cancel";
    public const string P2ContentOk = "Ok";
    public const string P2ContentEdit = "Edit";
    public const string P2ContentUpload = "Upload";
    public const string P2ContentDelete = "Delete";
    public const string P2TextRenderInThis = "Render in this";
    public const string P2ContentOpenDefaultSizeN378px = "Open Default Size (378px)";
    public const string P2ContentOpenLargeSizeN736px = "Open Large Size (736px)";
    public const string P2ContentOpenCustomSizeN400px = "Open Custom Size (400px)";
    public const string P2ContentOpenCustomSizeN50 = "Open Custom Size (50%)";

    public const string P2ContentOpen = "Open";

}
