using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.Drawer;

[LanguageProvider(LanguageCode.zh_CN, DrawerShowCase.LanguageId)]
internal partial class zh_CN
{
    public const string PageSubtitle = "用于上下文任务的滑出式面板。";
    public const string PageDescription = "Drawer 从窗口边缘或局部容器边缘滑出，在不打断当前流程的情况下展示次级操作、表单或详情。";
    public const string ComponentCategory = "反馈";
    public const string ComponentStatusStable = "稳定";
    public const string ScenarioExamples = "示例";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "设计变量";
    public const string ApiColumnProperty = "属性";
    public const string ApiColumnDescription = "说明";
    public const string ApiColumnType = "类型";
    public const string ApiColumnDefault = "默认值";
    public const string TokenColumnToken = "变量";
    public const string TokenColumnDescription = "说明";
    public const string TokenColumnScope = "作用域";
    public const string TokenColumnStatus = "状态";
    public const string ApiPropertyDrawerContent = "抽屉主体内容。";
    public const string ApiPropertyDrawerContentTemplate = "用于渲染抽屉主体内容的模板。";
    public const string ApiPropertyDrawerContentPadding = "覆盖抽屉主体内容区域的内边距。";
    public const string ApiPropertyDrawerIsOpen = "控制抽屉是否打开。";
    public const string ApiPropertyDrawerPlacement = "指定抽屉从哪一侧弹出。";
    public const string ApiPropertyDrawerOpenOn = "设置抽屉渲染所在的宿主控件。";
    public const string ApiPropertyDrawerIsShowMask = "控制是否显示模态遮罩。";
    public const string ApiPropertyDrawerIsShowCloseButton = "控制头部是否显示关闭按钮。";
    public const string ApiPropertyDrawerIsCloseOnMaskClick = "控制点击遮罩时是否关闭抽屉。";
    public const string ApiPropertyDrawerTitle = "头部标题文本。";
    public const string ApiPropertyDrawerExtra = "显示在头部操作区的额外内容。";
    public const string ApiPropertyDrawerFooter = "显示在抽屉底部的页脚内容。";
    public const string ApiPropertyDrawerSizeType = "抽屉使用的预设尺寸。";
    public const string ApiPropertyDrawerDialogSize = "使用自定义尺寸时的抽屉宽度或高度。";
    public const string ApiPropertyDrawerPushOffsetPercent = "子抽屉推动父抽屉时使用的偏移比例。";
    public const string ApiPropertyDrawerIsMotionEnabled = "控制是否启用抽屉过渡动效。";
    public const string TokenNameDrawerHeaderMargin = "抽屉面板内的头部外间距。";
    public const string TokenNameDrawerBodyPadding = "抽屉主体内容的内间距。";
    public const string TokenNameDrawerFooterPadding = "抽屉页脚的内间距。";
    public const string TokenNameDrawerCloseIconPadding = "关闭图标按钮的内间距。";
    public const string TokenNameDrawerCloseIconMargin = "关闭图标按钮的外间距。";
    public const string TokenNameDrawerSmallSize = "小号抽屉预设尺寸。";
    public const string TokenNameDrawerMiddleSize = "中号抽屉预设尺寸。";
    public const string TokenNameDrawerLargeSize = "大号抽屉预设尺寸。";
    public const string TokenNameDrawerPushOffsetPercent = "嵌套抽屉的默认推动偏移比例。";
    public const string TokenNameDrawerBoxShadowLeft = "从左侧打开时使用的阴影。";
    public const string TokenNameDrawerBoxShadowRight = "从右侧打开时使用的阴影。";
    public const string TokenNameDrawerBoxShadowUp = "从顶部打开时使用的阴影。";
    public const string TokenNameDrawerBoxShadowDown = "从底部打开时使用的阴影。";
    public const string TokenScopeComponent = "组件";
    public const string TokenStatusStable = "稳定";
    public const string BasicTitle = "基础用法";
    public const string BasicDescription = "基础抽屉。";
    public const string MultiLevelTitle = "多层抽屉";
    public const string MultiLevelDescription = "在已有抽屉上打开新的抽屉，用于处理多分支任务。";
    public const string ExtraAndFooterTitle = "额外区域和页脚";
    public const string ExtraAndFooterDescription = "设置头部额外区域和页脚区域。";
    public const string NoMaskTitle = "无遮罩";
    public const string NoMaskDescription = "不显示遮罩。";
    public const string CustomPlacementTitle = "自定义位置";
    public const string CustomPlacementDescription = "抽屉可以从屏幕任意边缘弹出。";
    public const string RenderInCurrentAreaTitle = "在当前区域渲染";
    public const string RenderInCurrentAreaDescription = "在当前区域中渲染。";
    public const string PresetSizeTitle = "预设尺寸";
    public const string PresetSizeDescription = "抽屉默认宽度（或高度）为 378px，并提供 736px 的大尺寸预设。";
    public const string P2TitleBasicDrawer = "基础抽屉";
    public const string P2TextSomeContents = "一些内容...";
    public const string P2TitleFirstLevelDrawer = "一级抽屉";
    public const string P2TitleTwoLevelDrawer = "二级抽屉";
    public const string P2TextPlacement = "弹出位置：";
    public const string P2ContentLeft = "左侧";
    public const string P2ContentTop = "顶部";
    public const string P2ContentRight = "右侧";
    public const string P2ContentBottom = "底部";
    public const string P2ContentTwoLevelDrawer = "二级抽屉";
    public const string P2ContentCancel = "取消";
    public const string P2ContentOk = "确定";
    public const string P2ContentEdit = "编辑";
    public const string P2ContentUpload = "上传";
    public const string P2ContentDelete = "删除";
    public const string P2TextRenderInThis = "在此区域渲染";
    public const string P2ContentOpenDefaultSizeN378px = "打开默认尺寸 (378px)";
    public const string P2ContentOpenLargeSizeN736px = "打开大尺寸 (736px)";
    public const string P2ContentOpenCustomSizeN400px = "打开自定义尺寸 (400px)";
    public const string P2ContentOpenCustomSizeN50 = "打开自定义尺寸 (50%)";

    public const string P2ContentOpen = "打开";

}
