using AtomUI.Theme.Language;

namespace AtomUIGallery.ShowCases.Drawer;

[LanguageProvider(LanguageCode.zh_TW, DrawerShowCase.LanguageId)]
internal partial class zh_TW
{
    public const string PageSubtitle = "用於上下文任務的滑出式面板。";
    public const string PageDescription = "Drawer 從視窗邊緣或局部容器邊緣滑出，在不打斷目前流程的情況下展示次級操作、表單或詳情。";
    public const string ComponentCategory = "反饋";
    public const string ComponentStatusStable = "穩定";
    public const string ScenarioExamples = "示例";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "設計變量";
    public const string ApiColumnProperty = "屬性";
    public const string ApiColumnDescription = "說明";
    public const string ApiColumnType = "類型";
    public const string ApiColumnDefault = "默認值";
    public const string TokenColumnToken = "變量";
    public const string TokenColumnDescription = "說明";
    public const string TokenColumnScope = "作用域";
    public const string TokenColumnStatus = "狀態";
    public const string ApiPropertyDrawerContent = "抽屜主體內容。";
    public const string ApiPropertyDrawerContentTemplate = "用於渲染抽屜主體內容的模板。";
    public const string ApiPropertyDrawerContentPadding = "覆蓋抽屜主體內容區域的內邊距。";
    public const string ApiPropertyDrawerIsOpen = "控制抽屜是否打開。";
    public const string ApiPropertyDrawerPlacement = "指定抽屜從哪一側彈出。";
    public const string ApiPropertyDrawerOpenOn = "設置抽屜渲染所在的宿主控件。";
    public const string ApiPropertyDrawerIsShowMask = "控制是否顯示模態遮罩。";
    public const string ApiPropertyDrawerIsShowCloseButton = "控制頭部是否顯示關閉按鈕。";
    public const string ApiPropertyDrawerIsCloseOnMaskClick = "控制點擊遮罩時是否關閉抽屜。";
    public const string ApiPropertyDrawerTitle = "頭部標題文本。";
    public const string ApiPropertyDrawerExtra = "顯示在頭部操作區的額外內容。";
    public const string ApiPropertyDrawerFooter = "顯示在抽屜底部的頁腳內容。";
    public const string ApiPropertyDrawerSizeType = "抽屜使用的預設尺寸。";
    public const string ApiPropertyDrawerDialogSize = "使用自定義尺寸時的抽屜寬度或高度。";
    public const string ApiPropertyDrawerPushOffsetPercent = "子抽屜推動父抽屜時使用的偏移比例。";
    public const string ApiPropertyDrawerIsMotionEnabled = "控制是否啟用抽屜過渡動效。";
    public const string TokenNameDrawerHeaderMargin = "抽屜面板內的頭部外間距。";
    public const string TokenNameDrawerBodyPadding = "抽屜主體內容的內間距。";
    public const string TokenNameDrawerFooterPadding = "抽屜頁腳的內間距。";
    public const string TokenNameDrawerCloseIconPadding = "關閉圖標按鈕的內間距。";
    public const string TokenNameDrawerCloseIconMargin = "關閉圖標按鈕的外間距。";
    public const string TokenNameDrawerSmallSize = "小號抽屜預設尺寸。";
    public const string TokenNameDrawerMiddleSize = "中號抽屜預設尺寸。";
    public const string TokenNameDrawerLargeSize = "大號抽屜預設尺寸。";
    public const string TokenNameDrawerPushOffsetPercent = "嵌套抽屜的默認推動偏移比例。";
    public const string TokenNameDrawerBoxShadowLeft = "從左側打開時使用的陰影。";
    public const string TokenNameDrawerBoxShadowRight = "從右側打開時使用的陰影。";
    public const string TokenNameDrawerBoxShadowUp = "從頂部打開時使用的陰影。";
    public const string TokenNameDrawerBoxShadowDown = "從底部打開時使用的陰影。";
    public const string TokenScopeComponent = "組件";
    public const string TokenStatusStable = "穩定";
    public const string BasicTitle = "基礎用法";
    public const string BasicDescription = "基礎抽屜。";
    public const string MultiLevelTitle = "多層抽屜";
    public const string MultiLevelDescription = "在已有抽屜上打開新的抽屜，用於處理多分支任務。";
    public const string ExtraAndFooterTitle = "額外區域和頁腳";
    public const string ExtraAndFooterDescription = "設置頭部額外區域和頁腳區域。";
    public const string NoMaskTitle = "無遮罩";
    public const string NoMaskDescription = "不顯示遮罩。";
    public const string CustomPlacementTitle = "自定義位置";
    public const string CustomPlacementDescription = "抽屜可以從屏幕任意邊緣彈出。";
    public const string RenderInCurrentAreaTitle = "在當前區域渲染";
    public const string RenderInCurrentAreaDescription = "在當前區域中渲染。";
    public const string PresetSizeTitle = "預設尺寸";
    public const string PresetSizeDescription = "抽屜默認寬度（或高度）為 378px，並提供 736px 的大尺寸預設。";
    public const string P2TitleBasicDrawer = "基礎抽屜";
    public const string P2TextSomeContents = "一些內容...";
    public const string P2TitleFirstLevelDrawer = "一級抽屜";
    public const string P2TitleTwoLevelDrawer = "二級抽屜";
    public const string P2TextPlacement = "彈出位置：";
    public const string P2ContentLeft = "左側";
    public const string P2ContentTop = "頂部";
    public const string P2ContentRight = "右側";
    public const string P2ContentBottom = "底部";
    public const string P2ContentTwoLevelDrawer = "二級抽屜";
    public const string P2ContentCancel = "取消";
    public const string P2ContentOk = "確定";
    public const string P2ContentEdit = "編輯";
    public const string P2ContentUpload = "上傳";
    public const string P2ContentDelete = "刪除";
    public const string P2TextRenderInThis = "在此區域渲染";
    public const string P2ContentOpenDefaultSizeN378px = "打開默認尺寸 (378px)";
    public const string P2ContentOpenLargeSizeN736px = "打開大尺寸 (736px)";
    public const string P2ContentOpenCustomSizeN400px = "打開自定義尺寸 (400px)";
    public const string P2ContentOpenCustomSizeN50 = "打開自定義尺寸 (50%)";

    public const string P2ContentOpen = "打開";

}
