using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace AtomUI.Generator;

internal sealed class ResourceKeyClassWriter
{
    private readonly SourceProductionContext _context;
    private readonly TokenInfo _tokenInfo;
    private readonly string _controlCatalog;

    internal ResourceKeyClassWriter(
        SourceProductionContext context,
        TokenInfo tokenInfo,
        string controlCatalog)
    {
        _context = context;
        _tokenInfo = tokenInfo;
        _controlCatalog = controlCatalog;
    }

    internal void Write()
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("using AtomUI.Theme.Resources;");
        source.AppendLine("using AtomUI.Theme.Schema;");
        source.AppendLine();

        if (_tokenInfo.Tokens.Count != 0)
        {
            WriteGlobalTokenKeys(source);
        }

        foreach (var group in _tokenInfo.ControlThemeInfos
                                        .GroupBy(static info => $"{info.ControlNamespace}.DesignTokens", StringComparer.Ordinal)
                                        .OrderBy(static group => group.Key, StringComparer.Ordinal))
        {
            source.Append("namespace ").Append(group.Key).AppendLine();
            source.AppendLine("{");
            foreach (var control in group.OrderBy(static info => info.ControlName, StringComparer.Ordinal))
            {
                WriteControl(source, control);
            }
            source.AppendLine("}");
        }

        _context.AddSource("TokenResourceConst.g.cs", GeneratedSourceText.From(source.ToString()));
    }

    private void WriteGlobalTokenKeys(StringBuilder source)
    {
        source.AppendLine("namespace AtomUI.Theme.Resources");
        source.AppendLine("{");
        source.AppendLine("    public enum SharedTokenKind");
        source.AppendLine("    {");
        foreach (var token in _tokenInfo.Tokens.OrderBy(static token => token.Name, StringComparer.Ordinal))
        {
            source.Append("        ").Append(token.Name).AppendLine(",");
        }
        source.AppendLine("    }");
        source.AppendLine("}");
        source.AppendLine();
    }

    private void WriteControl(StringBuilder source, ControlThemeInfo control)
    {
        var ownNames = control.OwnTokens.Select(static token => token.Name)
                              .OrderBy(static name => name, StringComparer.Ordinal)
                              .ToArray();
        var globalNames = _tokenInfo.AvailableGlobalTokenNames
                                    .OrderBy(static name => name, StringComparer.Ordinal)
                                    .ToArray();
        var tokenKindType = control.TokenKindType;
        var tokenKeyType = control.TokenKeyType;
        var tokensType = control.TokensType;
        var extensionType = control.ResourceExtensionType;

        if (control.HasOwnToken)
        {
            source.Append("    public enum ").Append(tokenKindType).AppendLine();
            source.AppendLine("    {");
            foreach (var name in ownNames)
            {
                source.Append("        ").Append(name).AppendLine(",");
            }
            source.AppendLine("    }");
            source.AppendLine();
        }

        source.Append("    public enum ").Append(tokenKeyType).AppendLine();
        source.AppendLine("    {");
        foreach (var name in globalNames)
        {
            source.Append("        ").Append(name).Append(" = (int)SharedTokenKind.").Append(name).AppendLine(",");
        }
        for (var ownSlot = 0; ownSlot < ownNames.Length; ownSlot++)
        {
            source.Append("        ").Append(ownNames[ownSlot]).Append(" = ").Append(-1 - ownSlot).AppendLine(",");
        }
        source.AppendLine("    }");
        source.AppendLine();

        source.Append("    public static class ").Append(tokensType).AppendLine();
        source.AppendLine("    {");
        source.Append("        public static readonly ControlTokenIdentity Identity = new ControlTokenIdentity(")
              .Append(SymbolDisplay.FormatLiteral(_controlCatalog, quote: true)).Append(", ")
              .Append(SymbolDisplay.FormatLiteral(control.ControlName, quote: true)).AppendLine(");");
        source.AppendLine("    }");
        source.AppendLine();

        source.Append("    public class ").Append(extensionType)
              .Append(" : TokenResourceExtension<").Append(tokenKeyType).AppendLine(">");
        source.AppendLine("    {");
        source.Append("        public ").Append(extensionType).AppendLine("()");
        source.AppendLine("        {");
        source.AppendLine("        }");
        source.AppendLine();
        source.Append("        public ").Append(extensionType).Append('(').Append(tokenKeyType).AppendLine(" kind)");
        source.AppendLine("            : base(kind)");
        source.AppendLine("        {");
        source.AppendLine("        }");
        source.AppendLine();
        source.Append("        protected override object GetResourceKey(").Append(tokenKeyType).AppendLine(" kind)");
        source.AppendLine("        {");
        source.AppendLine("            var slot = (int)kind;");
        source.AppendLine("            if (slot >= 0)");
        source.AppendLine("            {");
        source.Append("                if ((uint)slot >= ").Append(globalNames.Length).AppendLine("u)");
        source.AppendLine("                {");
        source.AppendLine("                    throw new global::System.ArgumentOutOfRangeException(nameof(kind));");
        source.AppendLine("                }");
        source.Append("                return ControlTokenResourceKey.Global(").Append(tokensType).Append(".Identity, (SharedTokenKind)slot);").AppendLine();
        source.AppendLine("            }");
        source.AppendLine("            var ownSlot = -1 - slot;");
        if (control.HasOwnToken)
        {
            source.Append("            if ((uint)ownSlot < ").Append(ownNames.Length).AppendLine("u)");
            source.AppendLine("            {");
            source.Append("                return (").Append(tokenKindType).Append(")ownSlot;").AppendLine();
            source.AppendLine("            }");
        }
        source.AppendLine("            throw new global::System.ArgumentOutOfRangeException(nameof(kind));");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine();
    }
}
