// <auto-generated />

using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace AtomUIGallery.ShowCases.Views
{
    partial class BoxPanelShowCase
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton Vertical;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton Horizontal;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.BoxPanel BasicBoxPanel;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton Vertical1;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton Horizontal1;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.BoxPanel FlexBoxPanel;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.Slider SpaceSlider;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.Button AddSpaceButton;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.Button ChangFlexButton;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.BoxPanel ChangeSpaceBoxPanel;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.Button AddFlexButton;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.BoxPanel AddPlaceholderBoxPanel;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton JustifyFlexStart;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton JustifyFlexEnd;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton JustifyCenter;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton JustifySpaceBetween;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton JustifySpaceAround;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton JustifySpaceEvenly;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.BoxPanel JustifyContentBoxPanel;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton AlignFlexStart;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton AlignFlexEnd;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton AlignCenter;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton AlignStretch;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.BoxPanel AlignItemsBoxPanel;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton NoWrap;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton Wrap;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton WrapReverse;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.BoxPanel WrapBoxPanel;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton ContentFlexStart;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton ContentFlexEnd;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton ContentCenter;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton ContentStretch;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton ContentSpaceBetween;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton ContentSpaceAround;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton ContentSpaceEvenly;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.BoxPanel AlignContentBoxPanel;

        /// <summary>
        /// Wires up the controls and optionally loads XAML markup and attaches dev tools (if Avalonia.Diagnostics package is referenced).
        /// </summary>
        /// <param name="loadXaml">Should the XAML be loaded into the component.</param>

        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public void InitializeComponent(bool loadXaml = true)
        {
            if (loadXaml)
            {
                AvaloniaXamlLoader.Load(this);
            }

            var __thisNameScope__ = this.FindNameScope();
            Vertical = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("Vertical");
            Horizontal = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("Horizontal");
            BasicBoxPanel = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.BoxPanel>("BasicBoxPanel");
            Vertical1 = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("Vertical1");
            Horizontal1 = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("Horizontal1");
            FlexBoxPanel = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.BoxPanel>("FlexBoxPanel");
            SpaceSlider = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Slider>("SpaceSlider");
            AddSpaceButton = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Button>("AddSpaceButton");
            ChangFlexButton = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Button>("ChangFlexButton");
            ChangeSpaceBoxPanel = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.BoxPanel>("ChangeSpaceBoxPanel");
            AddFlexButton = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Button>("AddFlexButton");
            AddPlaceholderBoxPanel = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.BoxPanel>("AddPlaceholderBoxPanel");
            JustifyFlexStart = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("JustifyFlexStart");
            JustifyFlexEnd = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("JustifyFlexEnd");
            JustifyCenter = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("JustifyCenter");
            JustifySpaceBetween = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("JustifySpaceBetween");
            JustifySpaceAround = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("JustifySpaceAround");
            JustifySpaceEvenly = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("JustifySpaceEvenly");
            JustifyContentBoxPanel = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.BoxPanel>("JustifyContentBoxPanel");
            AlignFlexStart = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("AlignFlexStart");
            AlignFlexEnd = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("AlignFlexEnd");
            AlignCenter = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("AlignCenter");
            AlignStretch = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("AlignStretch");
            AlignItemsBoxPanel = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.BoxPanel>("AlignItemsBoxPanel");
            NoWrap = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("NoWrap");
            Wrap = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("Wrap");
            WrapReverse = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("WrapReverse");
            WrapBoxPanel = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.BoxPanel>("WrapBoxPanel");
            ContentFlexStart = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("ContentFlexStart");
            ContentFlexEnd = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("ContentFlexEnd");
            ContentCenter = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("ContentCenter");
            ContentStretch = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("ContentStretch");
            ContentSpaceBetween = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("ContentSpaceBetween");
            ContentSpaceAround = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("ContentSpaceAround");
            ContentSpaceEvenly = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("ContentSpaceEvenly");
            AlignContentBoxPanel = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.BoxPanel>("AlignContentBoxPanel");
        }
    }
}
