// <auto-generated />

using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace AtomUIGallery.ShowCases.Views
{
    partial class ModalShowCase
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.Button BasicOpenModalButton;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.Button BasicWindowOpenModalButton;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.Button AsyncDialogOpenModalButton;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.ToggleSwitch StyleCaseHostTypeSwitch;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.Button ConfirmMsgBoxBtn;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.Button InformationMsgBoxBtn;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.Button SuccessMsgBoxBtn;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.Button ErrorMsgBoxBtn;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.Button WarningMsgBoxBtn;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.Button LoadingDialogOpenModalButton;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.Button CustomFooterDialogOpenButton;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.Button CustomFooterMsgBoxOpenButton;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.Button DraggableDialogOpenButton;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.Button DelayedCloseMsgBoxOpenButton;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.Button ConfigureButtonsDialogOpenButton;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.Dialog ConfigureButtonPropertiesDialog;

        /// <summary>
        /// Wires up the controls and optionally loads XAML markup and attaches dev tools (if Avalonia.Diagnostics package is referenced).
        /// </summary>
        /// <param name="loadXaml">Should the XAML be loaded into the component.</param>

        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public void InitializeComponent(bool loadXaml = true)
        {
            if (loadXaml)
            {
                AvaloniaXamlLoader.Load(this);
            }

            var __thisNameScope__ = this.FindNameScope();
            BasicOpenModalButton = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Button>("BasicOpenModalButton");
            BasicWindowOpenModalButton = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Button>("BasicWindowOpenModalButton");
            AsyncDialogOpenModalButton = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Button>("AsyncDialogOpenModalButton");
            StyleCaseHostTypeSwitch = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.ToggleSwitch>("StyleCaseHostTypeSwitch");
            ConfirmMsgBoxBtn = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Button>("ConfirmMsgBoxBtn");
            InformationMsgBoxBtn = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Button>("InformationMsgBoxBtn");
            SuccessMsgBoxBtn = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Button>("SuccessMsgBoxBtn");
            ErrorMsgBoxBtn = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Button>("ErrorMsgBoxBtn");
            WarningMsgBoxBtn = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Button>("WarningMsgBoxBtn");
            LoadingDialogOpenModalButton = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Button>("LoadingDialogOpenModalButton");
            CustomFooterDialogOpenButton = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Button>("CustomFooterDialogOpenButton");
            CustomFooterMsgBoxOpenButton = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Button>("CustomFooterMsgBoxOpenButton");
            DraggableDialogOpenButton = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Button>("DraggableDialogOpenButton");
            DelayedCloseMsgBoxOpenButton = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Button>("DelayedCloseMsgBoxOpenButton");
            ConfigureButtonsDialogOpenButton = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Button>("ConfigureButtonsDialogOpenButton");
            ConfigureButtonPropertiesDialog = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Dialog>("ConfigureButtonPropertiesDialog");
        }
    }
}
