// <auto-generated />

using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace AtomUIGallery.ShowCases.Views
{
    partial class DataGridShowCase
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.DataGrid BasicCaseGrid;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton ExtendedSelection;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.RadioButton SingleSelection;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.DataGrid SelectionDataGrid;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.DataGrid FilterAndSortGrid;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.DataGrid DragResizeColumn;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.DataGrid FilterInTreeGrid;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.DataGrid MultiSorterDataGrid;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.Button SortAgeBtn;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.Button ClearFiltersBtn;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.Button ClearFiltersAndSortersBtn;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.DataGrid ResetFilterAndSortGrid;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.DataGrid LargeSizeDataGrid;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.DataGrid MiddleSizeDataGrid;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.DataGrid SmallSizeDataGrid;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.DataGrid CustomHeaderAndFooterDataGrid;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.DataGrid ExpandableDataGrid;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.DataGrid OrderSpecificColumnDataGrid;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.DataGrid RowAndColumnHeaderDataGrid;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.DataGrid GroupHeaderDataGrid;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.CheckBox ColumnCheckBox1;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.CheckBox ColumnCheckBox2;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.CheckBox ColumnCheckBox3;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.CheckBox ColumnCheckBox4;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.CheckBox ColumnCheckBox5;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.CheckBox ColumnCheckBox6;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.DataGrid HideColumnDataGrid;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.DataGrid FixedHeaderDataGrid;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.DataGrid FixedColumnsDataGrid1;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.DataGrid FixedColumnsDataGrid2;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.DataGrid FixedColumnsAndHeadersDataGrid;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.DataGrid DragColumnDataGrid1;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.DataGrid DragColumnDataGrid2;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.DataGrid DragColumnDataGrid3;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.DataGrid DragRowDataGrid1;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.DataGrid DragRowDataGrid2;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.DataGrid CustomEmptyDataGrid;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.DataGrid EditableCellsDataGrid;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.CheckBox ShowTopPaginationCheckBox;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.CheckBox ShowBottomPaginationCheckBox;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.OptionButtonGroup TopPaginationOptionGroup;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.OptionButtonGroup BottomPaginationOptionGroup;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.DataGrid BasicPagingCaseGrid;

        /// <summary>
        /// Wires up the controls and optionally loads XAML markup and attaches dev tools (if Avalonia.Diagnostics package is referenced).
        /// </summary>
        /// <param name="loadXaml">Should the XAML be loaded into the component.</param>

        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public void InitializeComponent(bool loadXaml = true)
        {
            if (loadXaml)
            {
                AvaloniaXamlLoader.Load(this);
            }

            var __thisNameScope__ = this.FindNameScope();
            BasicCaseGrid = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.DataGrid>("BasicCaseGrid");
            ExtendedSelection = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("ExtendedSelection");
            SingleSelection = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.RadioButton>("SingleSelection");
            SelectionDataGrid = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.DataGrid>("SelectionDataGrid");
            FilterAndSortGrid = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.DataGrid>("FilterAndSortGrid");
            DragResizeColumn = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.DataGrid>("DragResizeColumn");
            FilterInTreeGrid = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.DataGrid>("FilterInTreeGrid");
            MultiSorterDataGrid = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.DataGrid>("MultiSorterDataGrid");
            SortAgeBtn = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Button>("SortAgeBtn");
            ClearFiltersBtn = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Button>("ClearFiltersBtn");
            ClearFiltersAndSortersBtn = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Button>("ClearFiltersAndSortersBtn");
            ResetFilterAndSortGrid = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.DataGrid>("ResetFilterAndSortGrid");
            LargeSizeDataGrid = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.DataGrid>("LargeSizeDataGrid");
            MiddleSizeDataGrid = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.DataGrid>("MiddleSizeDataGrid");
            SmallSizeDataGrid = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.DataGrid>("SmallSizeDataGrid");
            CustomHeaderAndFooterDataGrid = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.DataGrid>("CustomHeaderAndFooterDataGrid");
            ExpandableDataGrid = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.DataGrid>("ExpandableDataGrid");
            OrderSpecificColumnDataGrid = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.DataGrid>("OrderSpecificColumnDataGrid");
            RowAndColumnHeaderDataGrid = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.DataGrid>("RowAndColumnHeaderDataGrid");
            GroupHeaderDataGrid = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.DataGrid>("GroupHeaderDataGrid");
            ColumnCheckBox1 = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.CheckBox>("ColumnCheckBox1");
            ColumnCheckBox2 = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.CheckBox>("ColumnCheckBox2");
            ColumnCheckBox3 = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.CheckBox>("ColumnCheckBox3");
            ColumnCheckBox4 = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.CheckBox>("ColumnCheckBox4");
            ColumnCheckBox5 = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.CheckBox>("ColumnCheckBox5");
            ColumnCheckBox6 = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.CheckBox>("ColumnCheckBox6");
            HideColumnDataGrid = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.DataGrid>("HideColumnDataGrid");
            FixedHeaderDataGrid = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.DataGrid>("FixedHeaderDataGrid");
            FixedColumnsDataGrid1 = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.DataGrid>("FixedColumnsDataGrid1");
            FixedColumnsDataGrid2 = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.DataGrid>("FixedColumnsDataGrid2");
            FixedColumnsAndHeadersDataGrid = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.DataGrid>("FixedColumnsAndHeadersDataGrid");
            DragColumnDataGrid1 = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.DataGrid>("DragColumnDataGrid1");
            DragColumnDataGrid2 = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.DataGrid>("DragColumnDataGrid2");
            DragColumnDataGrid3 = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.DataGrid>("DragColumnDataGrid3");
            DragRowDataGrid1 = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.DataGrid>("DragRowDataGrid1");
            DragRowDataGrid2 = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.DataGrid>("DragRowDataGrid2");
            CustomEmptyDataGrid = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.DataGrid>("CustomEmptyDataGrid");
            EditableCellsDataGrid = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.DataGrid>("EditableCellsDataGrid");
            ShowTopPaginationCheckBox = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.CheckBox>("ShowTopPaginationCheckBox");
            ShowBottomPaginationCheckBox = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.CheckBox>("ShowBottomPaginationCheckBox");
            TopPaginationOptionGroup = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.OptionButtonGroup>("TopPaginationOptionGroup");
            BottomPaginationOptionGroup = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.OptionButtonGroup>("BottomPaginationOptionGroup");
            BasicPagingCaseGrid = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.DataGrid>("BasicPagingCaseGrid");
        }
    }
}
