// <auto-generated />

using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace AtomUIGallery.ShowCases.Views
{
    partial class DrawerShowCase
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.Drawer MultiLevelDrawerLevelTwo;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::Avalonia.Controls.ListBox ExtraAndFooter;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::Avalonia.Controls.ListBox CustomPlacement;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.Drawer PresetSizeDrawer;

        /// <summary>
        /// Wires up the controls and optionally loads XAML markup and attaches dev tools (if Avalonia.Diagnostics package is referenced).
        /// </summary>
        /// <param name="loadXaml">Should the XAML be loaded into the component.</param>

        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public void InitializeComponent(bool loadXaml = true)
        {
            if (loadXaml)
            {
                AvaloniaXamlLoader.Load(this);
            }

            var __thisNameScope__ = this.FindNameScope();
            MultiLevelDrawerLevelTwo = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Drawer>("MultiLevelDrawerLevelTwo");
            ExtraAndFooter = __thisNameScope__?.Find<global::Avalonia.Controls.ListBox>("ExtraAndFooter");
            CustomPlacement = __thisNameScope__?.Find<global::Avalonia.Controls.ListBox>("CustomPlacement");
            PresetSizeDrawer = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Drawer>("PresetSizeDrawer");
        }
    }
}
