// <auto-generated />

using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace AtomUIGallery.ShowCases.Views
{
    partial class MenuShowCase
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::Avalonia.Controls.Border ContextMenuContainer;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::Avalonia.Controls.Border ItemSourcesContextMenuContainer;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.ToggleSwitch ChangeModeSwitch;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.ToggleSwitch ChangeStyleSwitch;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.NavMenu ItemsSourceDemoNavMenu;

        /// <summary>
        /// Wires up the controls and optionally loads XAML markup and attaches dev tools (if Avalonia.Diagnostics package is referenced).
        /// </summary>
        /// <param name="loadXaml">Should the XAML be loaded into the component.</param>

        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public void InitializeComponent(bool loadXaml = true)
        {
            if (loadXaml)
            {
                AvaloniaXamlLoader.Load(this);
            }

            var __thisNameScope__ = this.FindNameScope();
            ContextMenuContainer = __thisNameScope__?.Find<global::Avalonia.Controls.Border>("ContextMenuContainer");
            ItemSourcesContextMenuContainer = __thisNameScope__?.Find<global::Avalonia.Controls.Border>("ItemSourcesContextMenuContainer");
            ChangeModeSwitch = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.ToggleSwitch>("ChangeModeSwitch");
            ChangeStyleSwitch = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.ToggleSwitch>("ChangeStyleSwitch");
            ItemsSourceDemoNavMenu = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.NavMenu>("ItemsSourceDemoNavMenu");
        }
    }
}
