// <auto-generated />

using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace AtomUIGallery.ShowCases.Views
{
    partial class StepsShowCase
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::Avalonia.Controls.UserControl StepsShowCaseName;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.Steps CurrentStepContentSteps;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.Button NextStepButton;
        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        internal global::AtomUI.Desktop.Controls.Button PreviousButton;

        /// <summary>
        /// Wires up the controls and optionally loads XAML markup and attaches dev tools (if Avalonia.Diagnostics package is referenced).
        /// </summary>
        /// <param name="loadXaml">Should the XAML be loaded into the component.</param>

        [global::System.CodeDom.Compiler.GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.3.9.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public void InitializeComponent(bool loadXaml = true)
        {
            if (loadXaml)
            {
                AvaloniaXamlLoader.Load(this);
            }

            var __thisNameScope__ = this.FindNameScope();
            StepsShowCaseName = __thisNameScope__?.Find<global::Avalonia.Controls.UserControl>("StepsShowCaseName");
            CurrentStepContentSteps = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Steps>("CurrentStepContentSteps");
            NextStepButton = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Button>("NextStepButton");
            PreviousButton = __thisNameScope__?.Find<global::AtomUI.Desktop.Controls.Button>("PreviousButton");
        }
    }
}
