using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.Expander;

[LanguageProvider(LanguageCode.en_US, ExpanderShowCase.LanguageId)]
internal partial class en_US : LanguageProvider
{
    public const string ScenarioExamples = "Examples";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "Design Token";
    public const string ComponentCategory = "Data Display";
    public const string ComponentStatusStable = ".NET 10";
    public const string PageSubtitle = "Show or hide a single section of supporting content.";
    public const string PageDescription = "Expander reveals content on demand without leaving the current context. It supports multiple expansion directions, size variants, icon placement, icon-only triggers, nested panels, ghost style, and custom spacing.";
    public const string ApiColumnProperty = "Property";
    public const string ApiColumnDescription = "Description";
    public const string ApiColumnType = "Type";
    public const string ApiColumnDefault = "Default";
    public const string ApiPropertySizeType = "Controls header and content density.";
    public const string ApiPropertyExpandDirection = "Controls the direction in which the content opens.";
    public const string ApiPropertyIsShowExpandIcon = "Controls whether the expand icon is visible.";
    public const string ApiPropertyExpandIcon = "Custom expand icon shown in the header.";
    public const string ApiPropertyAddOnContent = "Additional content rendered in the header.";
    public const string ApiPropertyAddOnContentTemplate = "Template used to render add-on content.";
    public const string ApiPropertyIsGhostStyle = "Removes the panel surface background for a ghost presentation.";
    public const string ApiPropertyIsBorderless = "Removes the outer panel border.";
    public const string ApiPropertyTriggerType = "Controls whether the header or only the icon toggles expansion.";
    public const string ApiPropertyExpandIconPosition = "Places the expand icon before or after the header content.";
    public const string ApiPropertyHeaderPadding = "Overrides header padding.";
    public const string ApiPropertyContentPadding = "Overrides content padding.";
    public const string ApiPropertyIsMotionEnabled = "Controls expand and collapse motion.";
    public const string TokenColumnToken = "Token";
    public const string TokenColumnDescription = "Description";
    public const string TokenColumnScope = "Scope";
    public const string TokenColumnStatus = "Status";
    public const string TokenNameHeaderPadding = "Default expander header padding.";
    public const string TokenNameHeaderPaddingSM = "Small size expander header padding.";
    public const string TokenNameHeaderPaddingLG = "Large size expander header padding.";
    public const string TokenNameHeaderBg = "Default expander header background.";
    public const string TokenNameContentPadding = "Default expander content padding.";
    public const string TokenNameContentPaddingSM = "Small size expander content padding.";
    public const string TokenNameContentPaddingLG = "Large size expander content padding.";
    public const string TokenNameContentBg = "Default expander content background.";
    public const string TokenNameExpanderBorderRadius = "Expander panel border radius.";
    public const string TokenNameLeftExpandButtonHMargin = "Horizontal margin when the expand icon is on the left.";
    public const string TokenNameRightExpandButtonHMargin = "Horizontal margin when the expand icon is on the right.";
    public const string TokenNameLeftExpandButtonVMargin = "Vertical margin when the expand icon is on the left.";
    public const string TokenNameRightExpandButtonVMargin = "Vertical margin when the expand icon is on the right.";
    public const string TokenScopeComponent = "Component";
    public const string TokenStatusStable = "Stable";
    public const string ScenarioBasic = "Basic";
    public const string ScenarioAppearance = "Appearance";
    public const string ScenarioBehavior = "Behavior";
    public const string ExpanderTitle = "Expander";
    public const string ExpanderDescription = "By default, The simplest usage is to expand downward.";
    public const string SizeTitle = "Size";
    public const string SizeDescription = "Ant Design supports a default Expander size as well as a large and small size. If a large or small Expander is desired, set the size property to either large or small respectively. Omit the size property for a Expander with the default size.";
    public const string ExpandingDirectionTitle = "Expanding Direction";
    public const string ExpandingDirectionDescription = "The content area supports expansion in four directions.";
    public const string NestedPanelTitle = "Nested panel";
    public const string NestedPanelDescription = "Expander is nested inside the Collapse.";
    public const string BorderlessTitle = "Borderless";
    public const string BorderlessDescription = "A borderless style of Expander.";
    public const string NoArrowTitle = "No Arrow";
    public const string NoArrowDescription = "You can hide the arrow icon by passing IsShowExpandIcon={False} to CollapsePanel component.";
    public const string ExpandIconLocationTitle = "Expand icon location";
    public const string ExpandIconLocationDescription = "The expand icon can be placed in front or in the back.";
    public const string GhostCollapseTitle = "Ghost Collapse";
    public const string GhostCollapseDescription = "Making collapse's background to transparent.";
    public const string CollapsibleTitle = "Collapsible";
    public const string CollapsibleDescription = "Specify the trigger area of collapsible by collapsible.";
    public const string CustomPaddingTitle = "Custom Header And Content Padding";
    public const string CustomPaddingDescription = "Please set custom header margins and content spacing.";
    public const string P2HeaderThisIsPanelHeaderN1 = "This is panel header 1";
    public const string P2TitleDefaultSize = "Default Size";
    public const string P2HeaderThisIsDefaultSizePanelHeader = "This is default size panel header";
    public const string P2TitleSmallSize = "Small Size";
    public const string P2HeaderThisIsSmallSizePanelHeader = "This is small size panel header";
    public const string P2TitleLargeSize = "Large Size";
    public const string P2HeaderThisIsLargeSizePanelHeader = "This is large size panel header";
    public const string P2HeaderThisIsPanelHeader = "This is panel header";
    public const string P2HeaderThisIsNestedPanelHeader = "This is nested panel header";
    public const string P2HeaderThisPanelCanOnlyBeCollapsedByClicking = "This panel can only be collapsed by clicking text";
    public const string P2HeaderThisPanelCanOnlyBeCollapsedByClicking2 = "This panel can only be collapsed by clicking icon";
    public const string P2HeaderThisPanelCanTBeCollapsed = "This panel can't be collapsed";
    public const string P2TextADogIsATypeOfDomesticatedAnimal = "A dog is a type of domesticated animal. Known for its loyalty and faithfulness, it can be found as a welcome guest in many households across the world.";
    public const string P2TextExpandDirection = "Expand direction:";
    public const string P2ContentDown = "Down";
    public const string P2ContentUp = "Up";
    public const string P2ContentLeft = "Left";
    public const string P2ContentRight = "Right";
    public const string P2TextExpandIconPosition = "Expand Icon Position:";
    public const string P2ContentStart = "Start";
    public const string P2ContentEnd = "End";

    protected override Type GetResourceKindType() => typeof(ExpanderShowCaseLangResourceKind);
}
