using AtomUI.Localization;

namespace AtomUIGallery.Localization;

[LanguageCatalog(ContractVersion = 1)]
public enum ExpanderShowCaseLangResourceKind
{
    ScenarioExamples = 1,
    ComponentCategory = 2,
    ComponentStatusStable = 3,
    PageSubtitle = 4,
    PageDescription = 5,
    ScenarioBasic = 6,
    ScenarioAppearance = 7,
    ScenarioBehavior = 8,
    ExpanderTitle = 9,
    ExpanderDescription = 10,
    SizeTitle = 11,
    SizeDescription = 12,
    ExpandingDirectionTitle = 13,
    ExpandingDirectionDescription = 14,
    NestedPanelTitle = 15,
    NestedPanelDescription = 16,
    BorderlessTitle = 17,
    BorderlessDescription = 18,
    NoArrowTitle = 19,
    NoArrowDescription = 20,
    ExpandIconLocationTitle = 21,
    ExpandIconLocationDescription = 22,
    GhostCollapseTitle = 23,
    GhostCollapseDescription = 24,
    CollapsibleTitle = 25,
    CollapsibleDescription = 26,
    CustomPaddingTitle = 27,
    CustomPaddingDescription = 28,
    P2HeaderThisIsPanelHeaderN1 = 29,
    P2TitleDefaultSize = 30,
    P2HeaderThisIsDefaultSizePanelHeader = 31,
    P2TitleSmallSize = 32,
    P2HeaderThisIsSmallSizePanelHeader = 33,
    P2TitleLargeSize = 34,
    P2HeaderThisIsLargeSizePanelHeader = 35,
    P2HeaderThisIsPanelHeader = 36,
    P2HeaderThisIsNestedPanelHeader = 37,
    P2HeaderThisPanelCanOnlyBeCollapsedByClicking = 38,
    P2HeaderThisPanelCanOnlyBeCollapsedByClicking2 = 39,
    P2HeaderThisPanelCanTBeCollapsed = 40,
    P2TextADogIsATypeOfDomesticatedAnimal = 41,
    P2TextExpandDirection = 42,
    P2ContentDown = 43,
    P2ContentUp = 44,
    P2ContentLeft = 45,
    P2ContentRight = 46,
    P2TextExpandIconPosition = 47,
    P2ContentStart = 48,
    P2ContentEnd = 49
}
