using AtomUI.Localization;

namespace AtomUIGallery.Localization;

[LanguageCatalog]
public enum ExpanderShowCaseLangResourceKind
{
    ScenarioExamples,
    ComponentCategory,
    ComponentStatusStable,
    PageSubtitle,
    PageDescription,
    ScenarioBasic,
    ScenarioAppearance,
    ScenarioBehavior,
    ExpanderTitle,
    ExpanderDescription,
    SizeTitle,
    SizeDescription,
    ExpandingDirectionTitle,
    ExpandingDirectionDescription,
    NestedPanelTitle,
    NestedPanelDescription,
    BorderlessTitle,
    BorderlessDescription,
    NoArrowTitle,
    NoArrowDescription,
    ExpandIconLocationTitle,
    ExpandIconLocationDescription,
    GhostCollapseTitle,
    GhostCollapseDescription,
    CollapsibleTitle,
    CollapsibleDescription,
    CustomPaddingTitle,
    CustomPaddingDescription,
    P2HeaderThisIsPanelHeaderN1,
    P2TitleDefaultSize,
    P2HeaderThisIsDefaultSizePanelHeader,
    P2TitleSmallSize,
    P2HeaderThisIsSmallSizePanelHeader,
    P2TitleLargeSize,
    P2HeaderThisIsLargeSizePanelHeader,
    P2HeaderThisIsPanelHeader,
    P2HeaderThisIsNestedPanelHeader,
    P2HeaderThisPanelCanOnlyBeCollapsedByClicking,
    P2HeaderThisPanelCanOnlyBeCollapsedByClicking2,
    P2HeaderThisPanelCanTBeCollapsed,
    P2TextADogIsATypeOfDomesticatedAnimal,
    P2TextExpandDirection,
    P2ContentDown,
    P2ContentUp,
    P2ContentLeft,
    P2ContentRight,
    P2TextExpandIconPosition,
    P2ContentStart,
    P2ContentEnd
}
