using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.Expander;

[LanguageProvider(LanguageCode.zh_TW, ExpanderShowCase.LanguageId)]
internal partial class zh_TW : LanguageProvider
{
    public const string ScenarioExamples = "示例";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "設計變數";
    public const string ComponentCategory = "資料展示";
    public const string ComponentStatusStable = ".NET 10";
    public const string PageSubtitle = "展示或隱藏一段可折疊的輔助內容。";
    public const string PageDescription = "Expander 用於在當前上下文中按需展開內容。它支持多種展開方向、尺寸、圖標位置、僅圖標觸發、嵌套面板、幽靈樣式和自定義間距。";
    public const string InfoNamespaceLabel = "命名空間:";
    public const string InfoPackageLabel = "包:";
    public const string InfoBaseClassLabel = "基類:";
    public const string ApiColumnProperty = "屬性";
    public const string ApiColumnDescription = "說明";
    public const string ApiColumnType = "類型";
    public const string ApiColumnDefault = "默認值";
    public const string ApiPropertySizeType = "控制頭部和內容區域的密度。";
    public const string ApiPropertyExpandDirection = "控制內容展開的方向。";
    public const string ApiPropertyIsShowExpandIcon = "控制是否顯示展開圖標。";
    public const string ApiPropertyExpandIcon = "自定義頭部中的展開圖標。";
    public const string ApiPropertyAddOnContent = "渲染在頭部中的附加內容。";
    public const string ApiPropertyAddOnContentTemplate = "用於渲染附加內容的模板。";
    public const string ApiPropertyIsGhostStyle = "移除面板表面背景，形成幽靈樣式。";
    public const string ApiPropertyIsBorderless = "移除外層面板邊框。";
    public const string ApiPropertyTriggerType = "控制點擊頭部或僅點擊圖標時觸發展開。";
    public const string ApiPropertyExpandIconPosition = "控制展開圖標位於頭部內容前側或後側。";
    public const string ApiPropertyHeaderPadding = "覆蓋頭部內邊距。";
    public const string ApiPropertyContentPadding = "覆蓋內容區域內邊距。";
    public const string ApiPropertyIsMotionEnabled = "控制展開和收起動效。";
    public const string TokenColumnToken = "變數";
    public const string TokenColumnDescription = "說明";
    public const string TokenColumnScope = "範圍";
    public const string TokenColumnStatus = "狀態";
    public const string TokenNameHeaderPadding = "默認展開器頭部內邊距。";
    public const string TokenNameHeaderPaddingSM = "小尺寸展開器頭部內邊距。";
    public const string TokenNameHeaderPaddingLG = "大尺寸展開器頭部內邊距。";
    public const string TokenNameHeaderBg = "默認展開器頭部背景。";
    public const string TokenNameContentPadding = "默認展開器內容內邊距。";
    public const string TokenNameContentPaddingSM = "小尺寸展開器內容內邊距。";
    public const string TokenNameContentPaddingLG = "大尺寸展開器內容內邊距。";
    public const string TokenNameContentBg = "默認展開器內容背景。";
    public const string TokenNameExpanderBorderRadius = "展開器面板圓角。";
    public const string TokenNameLeftExpandButtonHMargin = "展開圖標位於左側時的水平外邊距。";
    public const string TokenNameRightExpandButtonHMargin = "展開圖標位於右側時的水平外邊距。";
    public const string TokenNameLeftExpandButtonVMargin = "展開圖標位於左側時的垂直外邊距。";
    public const string TokenNameRightExpandButtonVMargin = "展開圖標位於右側時的垂直外邊距。";
    public const string TokenScopeComponent = "組件";
    public const string TokenStatusStable = "穩定";
    public const string ScenarioBasic = "基礎";
    public const string ScenarioAppearance = "外觀";
    public const string ScenarioBehavior = "行為";
    public const string ExpanderTitle = "展開器";
    public const string ExpanderDescription = "默認情況下，最簡單的用法是向下展開。";
    public const string SizeTitle = "尺寸";
    public const string SizeDescription = "Ant Design 支持默認、大號和小號三種 Expander 尺寸。需要大號或小號時分別設置 size 屬性；省略 size 屬性時使用默認尺寸。";
    public const string ExpandingDirectionTitle = "展開方向";
    public const string ExpandingDirectionDescription = "內容區域支持四個方向展開。";
    public const string NestedPanelTitle = "嵌套面板";
    public const string NestedPanelDescription = "在 Collapse 中嵌套 Expander。";
    public const string BorderlessTitle = "無邊框";
    public const string BorderlessDescription = "無邊框樣式的 Expander。";
    public const string NoArrowTitle = "隱藏箭頭";
    public const string NoArrowDescription = "可以向 CollapsePanel 傳入 IsShowExpandIcon={False} 來隱藏箭頭圖標。";
    public const string ExpandIconLocationTitle = "展開圖標位置";
    public const string ExpandIconLocationDescription = "展開圖標可以放在前方或後方。";
    public const string GhostCollapseTitle = "幽靈展開器";
    public const string GhostCollapseDescription = "讓背景透明。";
    public const string CollapsibleTitle = "可折疊觸發區域";
    public const string CollapsibleDescription = "通過 collapsible 指定折疊觸發區域。";
    public const string CustomPaddingTitle = "自定義標題和內容間距";
    public const string CustomPaddingDescription = "請設置自定義標題邊距和內容間距。";
    public const string P2HeaderThisIsPanelHeaderN1 = "這是面板標題 1";
    public const string P2TitleDefaultSize = "默認尺寸";
    public const string P2HeaderThisIsDefaultSizePanelHeader = "這是默認尺寸面板標題";
    public const string P2TitleSmallSize = "小尺寸";
    public const string P2HeaderThisIsSmallSizePanelHeader = "這是小尺寸面板標題";
    public const string P2TitleLargeSize = "大尺寸";
    public const string P2HeaderThisIsLargeSizePanelHeader = "這是大尺寸面板標題";
    public const string P2HeaderThisIsPanelHeader = "這是面板標題";
    public const string P2HeaderThisIsNestedPanelHeader = "這是嵌套面板標題";
    public const string P2HeaderThisPanelCanOnlyBeCollapsedByClicking = "只能點擊文字折疊此面板";
    public const string P2HeaderThisPanelCanOnlyBeCollapsedByClicking2 = "只能點擊圖標折疊此面板";
    public const string P2HeaderThisPanelCanTBeCollapsed = "此面板不能折疊";
    public const string P2TextADogIsATypeOfDomesticatedAnimal = "狗是一種被馴養的動物。它以忠誠和可靠著稱，在世界各地許多家庭中都是受歡迎的成員。";
    public const string P2TextExpandDirection = "展開方向：";
    public const string P2ContentDown = "向下";
    public const string P2ContentUp = "向上";
    public const string P2ContentLeft = "向左";
    public const string P2ContentRight = "向右";
    public const string P2TextExpandIconPosition = "展開圖標位置：";
    public const string P2ContentStart = "開始";
    public const string P2ContentEnd = "結束";

    protected override Type GetResourceKindType() => typeof(ExpanderShowCaseLangResourceKind);
}
