using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.FlexPanel;

[LanguageProvider(LanguageCode.en_US, FlexPanelShowCase.LanguageId)]
internal class en_US : LanguageProvider
{
    public const string ScenarioBasic = "Basic";
    public const string ScenarioAlignment = "Alignment";
    public const string ScenarioItem = "Item";
    public const string ScenarioCombination = "Combination";
    public const string ScenarioPlayground = "Playground";

    public const string BasicLayoutTitle = "Basic Layout";
    public const string BasicLayoutDescription = "The basic usage.";
    public const string AlignmentTitle = "Alignment";
    public const string AlignmentDescription = "Set justify and align.";
    public const string GapTitle = "Gap";
    public const string GapDescription = "Set spacing between items.";
    public const string AlignSelfTitle = "Align Self";
    public const string AlignSelfDescription = "Override alignment per item with Flex.AlignSelf.";
    public const string AutoWrapTitle = "Auto Wrap";
    public const string AutoWrapDescription = "Items wrap automatically.";
    public const string OrderTitle = "Order";
    public const string OrderDescription = "Change item order with Flex.Order.";
    public const string BasisTitle = "Basis";
    public const string BasisDescription = "Control initial size with Flex.Basis.";
    public const string FlexGrowTitle = "Flex Grow";
    public const string FlexGrowDescription = "Distribute free space with Flex.Grow.";
    public const string FlexShrinkTitle = "Flex Shrink (Weighted)";
    public const string FlexShrinkDescription = "Shrink is weighted by each item's base size.";
    public const string CombinationTitle = "Combination";
    public const string CombinationDescription = "Nested flex panels for complex layouts.";
    public const string PlaygroundTitle = "Flex Playground";
    public const string PlaygroundDescription = "Adjust all flex properties.";
    public const string P2TextItemA = "Item A";
    public const string P2TextA = "A";
    public const string P2TextB = "B";
    public const string P2TextC = "C";
    public const string P2TextD = "D";
    public const string P2TextPx = "px";
    public const string P2TextGrow = "Grow";
    public const string P2TextItemB = "Item B";
    public const string P2TextBasisN200 = "Basis 200";
    public const string P2TextBasisN100 = "Basis 100";
    public const string P2TextAtomuiIsAnEnterpriseClassUiDesignLanguage = "\"AtomUI is an enterprise-class UI design language and Avalonia UI library.\"";
    public const string P2ContentHorizontal = "horizontal";
    public const string P2ContentVertical = "vertical";
    public const string P2TextSelectJustify = "Select justify:";
    public const string P2ContentFlexStart = "flex-start";
    public const string P2ContentCenter = "center";
    public const string P2ContentFlexEnd = "flex-end";
    public const string P2ContentSpaceBetween = "space-between";
    public const string P2ContentSpaceAround = "space-around";
    public const string P2ContentSpaceEvenly = "space-evenly";
    public const string P2TextSelectAlign = "Select align:";
    public const string P2ContentStretch = "stretch";
    public const string P2ContentPrimary = "Primary";
    public const string P2ContentSmall = "small";
    public const string P2ContentMiddle = "middle";
    public const string P2ContentLarge = "large";
    public const string P2ContentCustomize = "customize";
    public const string P2TextCustomGap = "Custom gap:";
    public const string P2ContentDefault = "Default";
    public const string P2ContentDashed = "Dashed";
    public const string P2ContentLink = "Link";
    public const string P2ContentWrap = "wrap";
    public const string P2ContentNowrap = "nowrap";
    public const string P2ContentButton = "Button";
    public const string P2ContentDefault2 = "default";
    public const string P2ContentReverse = "reverse";
    public const string P2ContentCustom = "custom";
    public const string P2ContentAuto = "auto";
    public const string P2ContentAbsolute = "absolute";
    public const string P2ContentRelative = "relative";
    public const string P2TextValue = "Value:";
    public const string P2TextPercent = "Percent:";
    public const string P2TextItemA2 = "Item A:";
    public const string P2TextItemB2 = "Item B:";
    public const string P2TextContainerWidth = "Container width:";
    public const string P2ContentGetStarted = "Get Started";
    public const string P2TextPanel = "Panel";
    public const string P2TextDirection = "Direction:";
    public const string P2ContentRow = "row";
    public const string P2ContentColumn = "column";
    public const string P2ContentRowReverse = "row-reverse";
    public const string P2ContentColumnReverse = "column-reverse";
    public const string P2TextWrap = "Wrap:";
    public const string P2ContentWrapReverse = "wrap-reverse";
    public const string P2TextJustify = "Justify:";
    public const string P2TextAlignItems = "Align items:";
    public const string P2TextAlignContent = "Align content:";
    public const string P2TextColumnGap = "Column gap:";
    public const string P2TextRowGap = "Row gap:";
    public const string P2TextWidth = "Width:";
    public const string P2TextHeight = "Height:";
    public const string P2TextItem = "Item";
    public const string P2TextSelect = "Select:";
    public const string P2ContentA = "A";
    public const string P2ContentB = "B";
    public const string P2ContentC = "C";
    public const string P2TextAlignSelf = "Align self:";
    public const string P2TextBasis = "Basis:";
    public const string P2TextGrow2 = "Grow:";
    public const string P2TextShrink = "Shrink:";
    public const string P2TextOrder = "Order:";

    protected override Type GetResourceKindType() => typeof(FlexPanelShowCaseLangResourceKind);
}
