using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.FlexPanel;

[LanguageProvider(LanguageCode.zh_TW, FlexPanelShowCase.LanguageId)]
internal partial class zh_TW : LanguageProvider
{
    public const string ScenarioBasic = "基礎";
    public const string ScenarioAlignment = "對齊";
    public const string ScenarioItem = "項目";
    public const string ScenarioCombination = "組合";
    public const string ScenarioPlayground = "演練場";

    public const string BasicLayoutTitle = "基礎佈局";
    public const string BasicLayoutDescription = "基礎用法。";
    public const string AlignmentTitle = "對齊";
    public const string AlignmentDescription = "設置 justify 和 align。";
    public const string GapTitle = "間距";
    public const string GapDescription = "設置項目之間的間距。";
    public const string AlignSelfTitle = "單項對齊";
    public const string AlignSelfDescription = "使用 Flex.AlignSelf 覆蓋單個項目的對齊方式。";
    public const string AutoWrapTitle = "自動換行";
    public const string AutoWrapDescription = "項目會自動換行。";
    public const string OrderTitle = "排序";
    public const string OrderDescription = "使用 Flex.Order 改變項目順序。";
    public const string BasisTitle = "基礎尺寸";
    public const string BasisDescription = "使用 Flex.Basis 控制初始尺寸。";
    public const string FlexGrowTitle = "Flex 增長";
    public const string FlexGrowDescription = "使用 Flex.Grow 分配剩餘空間。";
    public const string FlexShrinkTitle = "Flex 收縮（加權）";
    public const string FlexShrinkDescription = "收縮量按每個項目的基礎尺寸加權。";
    public const string CombinationTitle = "組合佈局";
    public const string CombinationDescription = "使用嵌套 FlexPanel 構建複雜佈局。";
    public const string PlaygroundTitle = "Flex 演練場";
    public const string PlaygroundDescription = "調整所有 flex 屬性。";
    public const string P2TextItemA = "項目 A";
    public const string P2TextA = "A";
    public const string P2TextB = "B";
    public const string P2TextC = "C";
    public const string P2TextD = "D";
    public const string P2TextPx = "px";
    public const string P2TextGrow = "增長";
    public const string P2TextItemB = "項目 B";
    public const string P2TextBasisN200 = "Basis 200";
    public const string P2TextBasisN100 = "Basis 100";
    public const string P2TextAtomuiIsAnEnterpriseClassUiDesignLanguage = "\"AtomUI is an enterprise-class UI design language and Avalonia UI library.\"";
    public const string P2ContentHorizontal = "horizontal";
    public const string P2ContentVertical = "vertical";
    public const string P2TextSelectJustify = "選擇 justify：";
    public const string P2ContentFlexStart = "flex-start";
    public const string P2ContentCenter = "center";
    public const string P2ContentFlexEnd = "flex-end";
    public const string P2ContentSpaceBetween = "space-between";
    public const string P2ContentSpaceAround = "space-around";
    public const string P2ContentSpaceEvenly = "space-evenly";
    public const string P2TextSelectAlign = "選擇 align：";
    public const string P2ContentStretch = "stretch";
    public const string P2ContentPrimary = "主要";
    public const string P2ContentSmall = "small";
    public const string P2ContentMiddle = "middle";
    public const string P2ContentLarge = "large";
    public const string P2ContentCustomize = "customize";
    public const string P2TextCustomGap = "自定義間距：";
    public const string P2ContentDefault = "默認";
    public const string P2ContentDashed = "虛線";
    public const string P2ContentLink = "鏈接";
    public const string P2ContentWrap = "wrap";
    public const string P2ContentNowrap = "nowrap";
    public const string P2ContentButton = "按鈕";
    public const string P2ContentDefault2 = "default";
    public const string P2ContentReverse = "reverse";
    public const string P2ContentCustom = "custom";
    public const string P2ContentAuto = "auto";
    public const string P2ContentAbsolute = "absolute";
    public const string P2ContentRelative = "relative";
    public const string P2TextValue = "值：";
    public const string P2TextPercent = "百分比：";
    public const string P2TextItemA2 = "項目 A：";
    public const string P2TextItemB2 = "項目 B：";
    public const string P2TextContainerWidth = "容器寬度：";
    public const string P2ContentGetStarted = "Get Started";
    public const string P2TextPanel = "Panel";
    public const string P2TextDirection = "Direction:";
    public const string P2ContentRow = "row";
    public const string P2ContentColumn = "column";
    public const string P2ContentRowReverse = "row-reverse";
    public const string P2ContentColumnReverse = "column-reverse";
    public const string P2TextWrap = "Wrap:";
    public const string P2ContentWrapReverse = "wrap-reverse";
    public const string P2TextJustify = "Justify:";
    public const string P2TextAlignItems = "Align items:";
    public const string P2TextAlignContent = "Align content:";
    public const string P2TextColumnGap = "Column gap:";
    public const string P2TextRowGap = "Row gap:";
    public const string P2TextWidth = "Width:";
    public const string P2TextHeight = "Height:";
    public const string P2TextItem = "Item";
    public const string P2TextSelect = "Select:";
    public const string P2ContentA = "A";
    public const string P2ContentB = "B";
    public const string P2ContentC = "C";
    public const string P2TextAlignSelf = "Align self:";
    public const string P2TextBasis = "Basis:";
    public const string P2TextGrow2 = "Grow:";
    public const string P2TextShrink = "Shrink:";
    public const string P2TextOrder = "Order:";

    protected override Type GetResourceKindType() => typeof(FlexPanelShowCaseLangResourceKind);
}

