// <auto-generated />
namespace AtomUI.Generated.AtomUI_Desktop_Controls_Extras;

public static class SplashThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Splash");
}

internal static class GeneratedControlThemeAssetManifest
{
    internal static global::System.Collections.Generic.IReadOnlyList<global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor> GetDescriptors()
    {
        return new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor[]
        {
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls.Extras/Splash/Themes/SplashTheme.axaml"), SplashThemeAsset.Identity, 0x75229D1552323075UL),
        };
    }
}
