using System.Text;
using AtomUI.SourceGeneration;
using Microsoft.CodeAnalysis;

namespace AtomUI.Generator;

internal sealed class ControlPackageRegistrationWriter
{
    private readonly SourceProductionContext _context;
    private readonly string _generatedNamespace;
    private readonly string _assemblyName;
    private readonly string _packageId;
    private readonly string _registrationEntries;

    internal ControlPackageRegistrationWriter(
        SourceProductionContext context,
        string? assemblyName,
        string packageId,
        string registrationEntries)
    {
        _context = context;
        _assemblyName = assemblyName ?? "AtomUI";
        _generatedNamespace = GeneratedCodeNamespace.ForAssembly(assemblyName);
        _packageId = packageId;
        _registrationEntries = registrationEntries;
    }

    internal void Write()
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.Append("namespace ").Append(_generatedNamespace).AppendLine(";");
        source.AppendLine();
        source.AppendLine("internal static class GeneratedControlPackageRegistration");
        source.AppendLine("{");
        source.AppendLine("    internal static void Register(");
        source.AppendLine("        global::AtomUI.Theme.IThemeManagerBuilder themeManagerBuilder,");
        source.AppendLine("        global::AtomUI.Theme.Resources.IControlThemesProvider controlThemesProvider,");
        source.AppendLine("        global::System.Func<global::AtomUI.Theme.Schema.ControlTokenIdentity, bool>? includeIdentity = null,");
        source.AppendLine("        global::System.Func<global::System.Collections.Generic.IReadOnlyList<global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor>, global::System.Collections.Generic.IReadOnlyList<global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor>>? selectAssets = null)");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(themeManagerBuilder);");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(controlThemesProvider);");
        source.AppendLine("        var controls = GeneratedThemeSchema.GetControls();");
        source.AppendLine("        var selectedControls = new global::System.Collections.Generic.List<global::AtomUI.Theme.Schema.ControlTokenDescriptor>(controls.Count);");
        source.AppendLine("        foreach (var control in controls)");
        source.AppendLine("        {");
        source.AppendLine("            if (includeIdentity is null || includeIdentity(control.Identity))");
        source.AppendLine("            {");
        source.AppendLine("                selectedControls.Add(control);");
        source.AppendLine("            }");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        var assets = GeneratedControlThemeAssetManifest.GetDescriptors();");
        source.AppendLine("        var selectedAssets = new global::System.Collections.Generic.List<global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor>(assets.Count);");
        source.AppendLine("        foreach (var asset in assets)");
        source.AppendLine("        {");
        source.AppendLine("            var includeAsset = includeIdentity is null || includeIdentity(asset.OwnerIdentity);");
        source.AppendLine("            if (includeAsset && includeIdentity is not null)");
        source.AppendLine("            {");
        source.AppendLine("                foreach (var referencedIdentity in asset.ReferencedControlIdentities)");
        source.AppendLine("                {");
        source.AppendLine("                    if (!includeIdentity(referencedIdentity))");
        source.AppendLine("                    {");
        source.AppendLine("                        includeAsset = false;");
        source.AppendLine("                        break;");
        source.AppendLine("                    }");
        source.AppendLine("                }");
        source.AppendLine("            }");
        source.AppendLine("            if (includeAsset)");
        source.AppendLine("            {");
        source.AppendLine("                selectedAssets.Add(asset);");
        source.AppendLine("            }");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        var packageAssets = selectAssets is null ? selectedAssets : selectAssets(selectedAssets);");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(packageAssets);");
        source.AppendLine("        GeneratedControlThemeAssetResources.AddResources(controlThemesProvider, packageAssets);");
        source.AppendLine();
        source.AppendLine("        var package = new global::AtomUI.Theme.ControlPackageRegistration(");
        source.AppendLine("            controlThemesProvider.Id,");
        source.AppendLine("            selectedControls,");
        source.AppendLine("            packageAssets,");
        source.AppendLine("            controlThemesProvider);");
        source.AppendLine("        themeManagerBuilder.AddControlPackage(package);");
        source.AppendLine("    }");
        source.AppendLine("}");

        _context.AddSource(
            "GeneratedControlPackageRegistration.g.cs",
            GeneratedSourceText.From(source.ToString()));
        WriteFullFragment();
    }

    private void WriteFullFragment()
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        LinkedRegistration.Manifest.LinkedRegistrationMetadataWriter.Write(
            source,
            new LinkedRegistration.Manifest.LinkedPackageManifestRecord(
                _packageId,
                _assemblyName,
                _registrationEntries,
                _generatedNamespace + ".LinkedRegistrationV1.GeneratedFullControlPackageRegistrationFragment",
                "Register",
                _generatedNamespace + ".LinkedRegistrationV1." +
                LinkedRegistration.LinkedRegistrationFragmentName.ForPackageShared(_packageId),
                "Add"));
        source.AppendLine();
        source.Append("namespace ").Append(_generatedNamespace).AppendLine(".LinkedRegistrationV1;");
        source.AppendLine();
        source.AppendLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        source.AppendLine("public static class GeneratedFullControlPackageRegistrationFragment");
        source.AppendLine("{");
        source.AppendLine("    public static void Register(");
        source.AppendLine("        global::AtomUI.Theme.IThemeManagerBuilder themeManagerBuilder,");
        source.AppendLine("        global::AtomUI.Theme.Resources.IControlThemesProvider controlThemesProvider,");
        source.AppendLine("        global::System.Func<global::AtomUI.Theme.Schema.ControlTokenIdentity, bool>? includeIdentity = null,");
        source.AppendLine("        global::System.Func<global::System.Collections.Generic.IReadOnlyList<global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor>, global::System.Collections.Generic.IReadOnlyList<global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor>>? selectAssets = null)");
        source.AppendLine("    {");
        source.Append("        global::").Append(_generatedNamespace)
              .AppendLine(".GeneratedControlPackageRegistration.Register(");
        source.AppendLine("            themeManagerBuilder,");
        source.AppendLine("            controlThemesProvider,");
        source.AppendLine("            includeIdentity,");
        source.AppendLine("            selectAssets);");
        source.AppendLine("    }");
        source.AppendLine("}");

        _context.AddSource(
            "GeneratedFullControlPackageRegistrationFragment.g.cs",
            GeneratedSourceText.From(source.ToString()));
    }
}
