using AtomUI.Theme.Language;

namespace AtomUIGallery.ShowCases.Skeleton;

[LanguageProvider(LanguageCode.en_US, SkeletonShowCase.LanguageId)]
internal partial class en_US
{
    public const string BasicTitle = "Basic";
    public const string BasicDescription = "Simplest Skeleton usage.";
    public const string ComplexCombinationTitle = "Complex combination";
    public const string ComplexCombinationDescription = "Complex combination with avatar and multiple paragraphs.";
    public const string ActiveAnimationTitle = "Active Animation";
    public const string ActiveAnimationDescription = "Display active animation.";
    public const string ButtonAvatarInputImageNodeTitle = "Button/Avatar/Input/Image/Node";
    public const string ButtonAvatarInputImageNodeDescription = "Skeleton Button, Avatar, Input, Image and Node.";
    public const string ContainsSubComponentTitle = "Contains sub component";
    public const string ContainsSubComponentDescription = "Skeleton contains sub component.";
    public const string PageSubtitle = "Placeholder blocks for loading content.";
    public const string PageDescription = "Skeleton provides lightweight visual placeholders before content is available, covering text, avatar, image, input, button, and custom node states.";
    public const string ComponentCategory = "Feedback";
    public const string ComponentStatusStable = ".NET 10";
    public const string ScenarioExamples = "Examples";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "Design Token";
    public const string ApiColumnProperty = "Property";
    public const string ApiColumnDescription = "Description";
    public const string ApiColumnType = "Type";
    public const string ApiColumnDefault = "Default";
    public const string ApiPropertyIsLoading = "Controls whether Skeleton shows placeholder content or real content.";
    public const string ApiPropertyIsShowAvatar = "Shows the avatar placeholder in the composite Skeleton.";
    public const string ApiPropertyIsShowParagraph = "Shows the paragraph placeholder lines.";
    public const string ApiPropertyIsShowTitle = "Shows the title placeholder line.";
    public const string ApiPropertyIsRound = "Uses rounded paragraph and title placeholder lines.";
    public const string ApiPropertyTitleWidth = "Width of the title placeholder.";
    public const string ApiPropertyParagraphRows = "Number of paragraph placeholder lines.";
    public const string ApiPropertyParagraphLastLineWidth = "Width of the final paragraph line.";
    public const string ApiPropertyParagraphLineWidths = "Custom widths for paragraph placeholder lines.";
    public const string ApiPropertyAvatarShape = "Shape of the avatar placeholder in Skeleton.";
    public const string ApiPropertyAvatarSizeType = "Preset size of the avatar placeholder in Skeleton.";
    public const string ApiPropertyAvatarSize = "Custom size of the avatar placeholder in Skeleton.";
    public const string ApiPropertyContent = "Actual content displayed when Skeleton is not loading.";
    public const string ApiPropertyContentTemplate = "Template used to render actual content.";
    public const string ApiPropertyIsActive = "Enables the active loading animation.";
    public const string ApiPropertyMotionDuration = "Duration of the active loading animation.";
    public const string ApiPropertyMotionEasingCurve = "Easing curve used by the active loading animation.";
    public const string ApiPropertySizeType = "Preset size for Skeleton button and input elements.";
    public const string ApiPropertyIsBlock = "Makes Skeleton button and input elements stretch horizontally.";
    public const string ApiPropertyButtonShape = "Shape of the Skeleton button placeholder.";
    public const string ApiPropertyAvatarElementShape = "Shape of the standalone Skeleton avatar placeholder.";
    public const string ApiPropertyAvatarElementSize = "Custom size of the standalone Skeleton avatar placeholder.";
    public const string ApiPropertyNodeContent = "Custom content rendered inside SkeletonNode.";
    public const string TokenColumnToken = "Token";
    public const string TokenColumnDescription = "Description";
    public const string TokenColumnScope = "Scope";
    public const string TokenColumnStatus = "Status";
    public const string TokenNameGradientFromColor = "Start color of the loading gradient.";
    public const string TokenNameGradientToColor = "End color of the loading gradient.";
    public const string TokenNameTitleHeight = "Height of the title placeholder.";
    public const string TokenNameBlockRadius = "Border radius of skeleton blocks.";
    public const string TokenNameParagraphMarginTop = "Top margin before paragraph placeholder lines.";
    public const string TokenNameAvatarMarginRight = "Right margin after the avatar placeholder.";
    public const string TokenNameParagraphLineHeight = "Height of each paragraph placeholder line.";
    public const string TokenNameParagraphLineRoundCornerRadius = "Corner radius of rounded paragraph lines.";
    public const string TokenNameLoadingMotionDuration = "Default duration of the active loading animation.";
    public const string TokenNameLoadingBackgroundStart = "Gradient brush at the start of loading animation.";
    public const string TokenNameLoadingBackgroundMiddle = "Gradient brush at the middle of loading animation.";
    public const string TokenNameLoadingBackgroundEnd = "Gradient brush at the end of loading animation.";
    public const string TokenNameImageSize = "Size of the image placeholder icon.";
    public const string TokenNameImageContainerSize = "Default size of the image placeholder container.";
    public const string TokenNameImageContainerMaxSize = "Maximum size of the image placeholder container.";
    public const string TokenScopeComponent = "Component";
    public const string TokenStatusStable = "Stable";
    public const string P2TextActive = "Active:";
    public const string P2TextButtonAndInputBlock = "Button and Input Block:";
    public const string P2TextSize = "Size:";
    public const string P2ContentDefault = "Default";
    public const string P2ContentLarge = "Large";
    public const string P2ContentSmall = "Small";
    public const string P2TextButtonShape = "Button Shape:";
    public const string P2ContentSquare = "Square";
    public const string P2ContentRound = "Round";
    public const string P2ContentCircle = "Circle";
    public const string P2TextAvatarShape = "Avatar Shape:";
    public const string P2TextAntDesignADesignLanguage = "Ant Design, a design language";
    public const string P2TextWeSupplyASeriesOfDesignPrinciplesPractical = "We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently.";
    public const string P2ContentShowSkeleton = "Show Skeleton";

}
