using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.Skeleton;

[LanguageProvider(LanguageCode.zh_CN, SkeletonShowCase.LanguageId)]
internal partial class zh_CN : LanguageProvider
{
    public const string BasicTitle = "基础用法";
    public const string BasicDescription = "最简单的 Skeleton 用法。";
    public const string ComplexCombinationTitle = "复杂组合";
    public const string ComplexCombinationDescription = "包含头像和多段文本的复杂组合。";
    public const string ActiveAnimationTitle = "动态效果";
    public const string ActiveAnimationDescription = "显示动态加载效果。";
    public const string ButtonAvatarInputImageNodeTitle = "按钮/头像/输入框/图片/节点";
    public const string ButtonAvatarInputImageNodeDescription = "Skeleton Button、Avatar、Input、Image 和 Node。";
    public const string ContainsSubComponentTitle = "包含子组件";
    public const string ContainsSubComponentDescription = "Skeleton 包含子组件。";
    public const string PageSubtitle = "用于内容加载中的占位块。";
    public const string PageDescription = "Skeleton 在内容可用前提供轻量占位展示，覆盖文本、头像、图片、输入框、按钮和自定义节点状态。";
    public const string ComponentCategory = "反馈";
    public const string ComponentStatusStable = ".NET 10";
    public const string ScenarioExamples = "示例";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "Design Token";
    public const string InfoNamespaceLabel = "命名空间";
    public const string InfoPackageLabel = "包";
    public const string InfoBaseClassLabel = "基类";
    public const string ApiColumnProperty = "属性";
    public const string ApiColumnDescription = "说明";
    public const string ApiColumnType = "类型";
    public const string ApiColumnDefault = "默认值";
    public const string ApiPropertyIsLoading = "控制 Skeleton 显示占位内容还是真实内容。";
    public const string ApiPropertyIsShowAvatar = "在组合 Skeleton 中显示头像占位。";
    public const string ApiPropertyIsShowParagraph = "显示段落占位行。";
    public const string ApiPropertyIsShowTitle = "显示标题占位行。";
    public const string ApiPropertyIsRound = "使用圆角标题和段落占位行。";
    public const string ApiPropertyTitleWidth = "标题占位的宽度。";
    public const string ApiPropertyParagraphRows = "段落占位行数量。";
    public const string ApiPropertyParagraphLastLineWidth = "最后一行段落占位的宽度。";
    public const string ApiPropertyParagraphLineWidths = "段落占位行的自定义宽度。";
    public const string ApiPropertyAvatarShape = "Skeleton 中头像占位的形状。";
    public const string ApiPropertyAvatarSizeType = "Skeleton 中头像占位的预设尺寸。";
    public const string ApiPropertyAvatarSize = "Skeleton 中头像占位的自定义尺寸。";
    public const string ApiPropertyContent = "Skeleton 非加载状态下显示的真实内容。";
    public const string ApiPropertyContentTemplate = "用于渲染真实内容的模板。";
    public const string ApiPropertyIsActive = "启用动态加载动画。";
    public const string ApiPropertyMotionDuration = "动态加载动画的持续时间。";
    public const string ApiPropertyMotionEasingCurve = "动态加载动画使用的缓动曲线。";
    public const string ApiPropertySizeType = "Skeleton 按钮和输入框元素的预设尺寸。";
    public const string ApiPropertyIsBlock = "让 Skeleton 按钮和输入框元素水平铺满。";
    public const string ApiPropertyButtonShape = "Skeleton 按钮占位的形状。";
    public const string ApiPropertyAvatarElementShape = "独立 Skeleton 头像占位的形状。";
    public const string ApiPropertyAvatarElementSize = "独立 Skeleton 头像占位的自定义尺寸。";
    public const string ApiPropertyNodeContent = "SkeletonNode 内部渲染的自定义内容。";
    public const string TokenColumnToken = "Token";
    public const string TokenColumnDescription = "说明";
    public const string TokenColumnScope = "范围";
    public const string TokenColumnStatus = "状态";
    public const string TokenNameGradientFromColor = "加载渐变的起始颜色。";
    public const string TokenNameGradientToColor = "加载渐变的结束颜色。";
    public const string TokenNameTitleHeight = "标题占位的高度。";
    public const string TokenNameBlockRadius = "骨架屏块的圆角。";
    public const string TokenNameParagraphMarginTop = "段落占位行前的顶部间距。";
    public const string TokenNameAvatarMarginRight = "头像占位右侧间距。";
    public const string TokenNameParagraphLineHeight = "每一行段落占位的高度。";
    public const string TokenNameParagraphLineRoundCornerRadius = "圆角段落占位行的圆角。";
    public const string TokenNameLoadingMotionDuration = "默认动态加载动画时长。";
    public const string TokenNameLoadingBackgroundStart = "加载动画开始位置的渐变画刷。";
    public const string TokenNameLoadingBackgroundMiddle = "加载动画中间位置的渐变画刷。";
    public const string TokenNameLoadingBackgroundEnd = "加载动画结束位置的渐变画刷。";
    public const string TokenNameImageSize = "图片占位图标的尺寸。";
    public const string TokenNameImageContainerSize = "图片占位容器的默认尺寸。";
    public const string TokenNameImageContainerMaxSize = "图片占位容器的最大尺寸。";
    public const string TokenScopeComponent = "组件";
    public const string TokenStatusStable = "稳定";
    public const string P2TextActive = "动态效果：";
    public const string P2TextButtonAndInputBlock = "按钮和输入框块：";
    public const string P2TextSize = "尺寸：";
    public const string P2ContentDefault = "默认";
    public const string P2ContentLarge = "大号";
    public const string P2ContentSmall = "小号";
    public const string P2TextButtonShape = "按钮形状：";
    public const string P2ContentSquare = "方形";
    public const string P2ContentRound = "圆角";
    public const string P2ContentCircle = "圆形";
    public const string P2TextAvatarShape = "头像形状：";
    public const string P2TextAntDesignADesignLanguage = "Ant Design，一套设计语言";
    public const string P2TextWeSupplyASeriesOfDesignPrinciplesPractical = "我们提供一系列设计原则、实用模式和高质量设计资源（Sketch 和 Axure），帮助人们高效而优雅地创建产品原型。";
    public const string P2ContentShowSkeleton = "显示骨架屏";

    protected override Type GetResourceKindType() => typeof(SkeletonShowCaseLangResourceKind);
}
