using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.Skeleton;

[LanguageProvider(LanguageCode.zh_TW, SkeletonShowCase.LanguageId)]
internal partial class zh_TW : LanguageProvider
{
    public const string BasicTitle = "基礎用法";
    public const string BasicDescription = "最簡單的 Skeleton 用法。";
    public const string ComplexCombinationTitle = "複雜組合";
    public const string ComplexCombinationDescription = "包含頭像和多段文本的複雜組合。";
    public const string ActiveAnimationTitle = "動態效果";
    public const string ActiveAnimationDescription = "顯示動態加載效果。";
    public const string ButtonAvatarInputImageNodeTitle = "按鈕/頭像/輸入框/圖片/節點";
    public const string ButtonAvatarInputImageNodeDescription = "Skeleton Button、Avatar、Input、Image 和 Node。";
    public const string ContainsSubComponentTitle = "包含子組件";
    public const string ContainsSubComponentDescription = "Skeleton 包含子組件。";
    public const string PageSubtitle = "用於內容加載中的佔位塊。";
    public const string PageDescription = "Skeleton 在內容可用前提供輕量佔位展示，覆蓋文本、頭像、圖片、輸入框、按鈕和自定義節點狀態。";
    public const string ComponentCategory = "反饋";
    public const string ComponentStatusStable = ".NET 10";
    public const string ScenarioExamples = "示例";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "Design Token";
    public const string InfoNamespaceLabel = "命名空間";
    public const string InfoPackageLabel = "包";
    public const string InfoBaseClassLabel = "基類";
    public const string ApiColumnProperty = "屬性";
    public const string ApiColumnDescription = "說明";
    public const string ApiColumnType = "類型";
    public const string ApiColumnDefault = "默認值";
    public const string ApiPropertyIsLoading = "控制 Skeleton 顯示佔位內容還是真實內容。";
    public const string ApiPropertyIsShowAvatar = "在組合 Skeleton 中顯示頭像佔位。";
    public const string ApiPropertyIsShowParagraph = "顯示段落佔位行。";
    public const string ApiPropertyIsShowTitle = "顯示標題佔位行。";
    public const string ApiPropertyIsRound = "使用圓角標題和段落佔位行。";
    public const string ApiPropertyTitleWidth = "標題佔位的寬度。";
    public const string ApiPropertyParagraphRows = "段落佔位行數量。";
    public const string ApiPropertyParagraphLastLineWidth = "最後一行段落佔位的寬度。";
    public const string ApiPropertyParagraphLineWidths = "段落佔位行的自定義寬度。";
    public const string ApiPropertyAvatarShape = "Skeleton 中頭像佔位的形狀。";
    public const string ApiPropertyAvatarSizeType = "Skeleton 中頭像佔位的預設尺寸。";
    public const string ApiPropertyAvatarSize = "Skeleton 中頭像佔位的自定義尺寸。";
    public const string ApiPropertyContent = "Skeleton 非加載狀態下顯示的真實內容。";
    public const string ApiPropertyContentTemplate = "用於渲染真實內容的模板。";
    public const string ApiPropertyIsActive = "啟用動態加載動畫。";
    public const string ApiPropertyMotionDuration = "動態加載動畫的持續時間。";
    public const string ApiPropertyMotionEasingCurve = "動態加載動畫使用的緩動曲線。";
    public const string ApiPropertySizeType = "Skeleton 按鈕和輸入框元素的預設尺寸。";
    public const string ApiPropertyIsBlock = "讓 Skeleton 按鈕和輸入框元素水平鋪滿。";
    public const string ApiPropertyButtonShape = "Skeleton 按鈕佔位的形狀。";
    public const string ApiPropertyAvatarElementShape = "獨立 Skeleton 頭像佔位的形狀。";
    public const string ApiPropertyAvatarElementSize = "獨立 Skeleton 頭像佔位的自定義尺寸。";
    public const string ApiPropertyNodeContent = "SkeletonNode 內部渲染的自定義內容。";
    public const string TokenColumnToken = "Token";
    public const string TokenColumnDescription = "說明";
    public const string TokenColumnScope = "範圍";
    public const string TokenColumnStatus = "狀態";
    public const string TokenNameGradientFromColor = "加載漸變的起始顏色。";
    public const string TokenNameGradientToColor = "加載漸變的結束顏色。";
    public const string TokenNameTitleHeight = "標題佔位的高度。";
    public const string TokenNameBlockRadius = "骨架屏塊的圓角。";
    public const string TokenNameParagraphMarginTop = "段落佔位行前的頂部間距。";
    public const string TokenNameAvatarMarginRight = "頭像佔位右側間距。";
    public const string TokenNameParagraphLineHeight = "每一行段落佔位的高度。";
    public const string TokenNameParagraphLineRoundCornerRadius = "圓角段落佔位行的圓角。";
    public const string TokenNameLoadingMotionDuration = "默認動態加載動畫時長。";
    public const string TokenNameLoadingBackgroundStart = "加載動畫開始位置的漸變畫刷。";
    public const string TokenNameLoadingBackgroundMiddle = "加載動畫中間位置的漸變畫刷。";
    public const string TokenNameLoadingBackgroundEnd = "加載動畫結束位置的漸變畫刷。";
    public const string TokenNameImageSize = "圖片佔位圖標的尺寸。";
    public const string TokenNameImageContainerSize = "圖片佔位容器的默認尺寸。";
    public const string TokenNameImageContainerMaxSize = "圖片佔位容器的最大尺寸。";
    public const string TokenScopeComponent = "組件";
    public const string TokenStatusStable = "穩定";
    public const string P2TextActive = "動態效果：";
    public const string P2TextButtonAndInputBlock = "按鈕和輸入框塊：";
    public const string P2TextSize = "尺寸：";
    public const string P2ContentDefault = "默認";
    public const string P2ContentLarge = "大號";
    public const string P2ContentSmall = "小號";
    public const string P2TextButtonShape = "按鈕形狀：";
    public const string P2ContentSquare = "方形";
    public const string P2ContentRound = "圓角";
    public const string P2ContentCircle = "圓形";
    public const string P2TextAvatarShape = "頭像形狀：";
    public const string P2TextAntDesignADesignLanguage = "Ant Design，一套設計語言";
    public const string P2TextWeSupplyASeriesOfDesignPrinciplesPractical = "我們提供一系列設計原則、實用模式和高質量設計資源（Sketch 和 Axure），幫助人們高效而優雅地創建產品原型。";
    public const string P2ContentShowSkeleton = "顯示骨架屏";

    protected override Type GetResourceKindType() => typeof(SkeletonShowCaseLangResourceKind);
}
