// <auto-generated />
namespace AtomUI.Generated.AtomUI_Desktop_Controls;

public static class AddOnDecoratedBoxThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "AddOnDecoratedBox");
}

public static class AdornerLayerThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "AdornerLayer");
}

public static class AlertThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Alert");
}

public static class ArrowDecoratedBoxThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "ArrowDecoratedBox");
}

public static class AutoCompleteThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "AutoComplete");
}

public static class AvatarThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Avatar");
}

public static class BadgeThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Badge");
}

public static class BorderBeamThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "BorderBeam");
}

public static class BreadcrumbThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Breadcrumb");
}

public static class ButtonThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Button");
}

public static class ButtonSpinnerThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "ButtonSpinner");
}

public static class CalendarThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Calendar");
}

public static class CardThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Card");
}

public static class CarouselThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Carousel");
}

public static class CascaderThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Cascader");
}

public static class CheckBoxThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "CheckBox");
}

public static class CollapseThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Collapse");
}

public static class ComboBoxThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "ComboBox");
}

public static class DatePickerThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "DatePicker");
}

public static class DescriptionsThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Descriptions");
}

public static class DialogThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Dialog");
}

public static class DrawerThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Drawer");
}

public static class EmptyThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Empty");
}

public static class ExpanderThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Expander");
}

public static class FloatButtonThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "FloatButton");
}

public static class FlyoutHostThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "FlyoutHost");
}

public static class FormThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Form");
}

public static class GroupBoxThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "GroupBox");
}

public static class ImagePreviewerThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "ImagePreviewer");
}

public static class IndicatorScrollViewerThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "IndicatorScrollViewer");
}

public static class InfoPickerInputThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "InfoPickerInput");
}

public static class LineEditThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "LineEdit");
}

public static class ListBoxThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "ListBox");
}

public static class ListViewThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "ListView");
}

public static class MentionsThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Mentions");
}

public static class MenuThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Menu");
}

public static class MessageThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Message");
}

public static class MessageBoxThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "MessageBox");
}

public static class NavMenuThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "NavMenu");
}

public static class NotificationThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Notification");
}

public static class NumericUpDownThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "NumericUpDown");
}

public static class OptionButtonThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "OptionButton");
}

public static class OtpLineEditThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "OtpLineEdit");
}

public static class PaginationThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Pagination");
}

public static class PopupConfirmThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "PopupConfirm");
}

public static class PopupHostThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "PopupHost");
}

public static class ProgressBarThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "ProgressBar");
}

public static class QRCodeThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "QRCode");
}

public static class RadioButtonThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "RadioButton");
}

public static class RateThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Rate");
}

public static class ResultThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Result");
}

public static class ScrollViewerThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "ScrollViewer");
}

public static class SegmentedThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Segmented");
}

public static class SelectThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Select");
}

public static class SeparatorThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Separator");
}

public static class SkeletonThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Skeleton");
}

public static class SliderThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Slider");
}

public static class SpaceThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Space");
}

public static class SpinThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Spin");
}

public static class SplitViewThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "SplitView");
}

public static class SplitterThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Splitter");
}

public static class StatisticThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Statistic");
}

public static class StepsThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Steps");
}

public static class TabControlThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "TabControl");
}

public static class TagThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Tag");
}

public static class TextAreaThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "TextArea");
}

public static class TextBoxThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "TextBox");
}

public static class TimePickerThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "TimePicker");
}

public static class TimelineThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Timeline");
}

public static class ToggleSwitchThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "ToggleSwitch");
}

public static class ToolTipThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "ToolTip");
}

public static class TourThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Tour");
}

public static class TransferThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Transfer");
}

public static class TreeFlyoutThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "TreeFlyout");
}

public static class TreeSelectThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "TreeSelect");
}

public static class TreeViewThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "TreeView");
}

public static class UploadThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Upload");
}

public static class WindowThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "Window");
}

public static class WindowTitleBarThemeAsset
{
    public static readonly global::AtomUI.Theme.Schema.ControlTokenIdentity Identity = new global::AtomUI.Theme.Schema.ControlTokenIdentity("AtomUI", "WindowTitleBar");
}

internal static class GeneratedControlThemeAssetManifest
{
    internal static global::System.Collections.Generic.IReadOnlyList<global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor> GetDescriptors()
    {
        return new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor[]
        {
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/AdornerLayer/Themes/AdornerLayerTheme.axaml"), AdornerLayerThemeAsset.Identity, 0x78BC14D64EE84905UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Alert/Themes/AlertTheme.axaml"), AlertThemeAsset.Identity, 0x3DBA3952C564D41DUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/AutoComplete/Themes/AbstractAutoCompleteTheme.axaml"), AutoCompleteThemeAsset.Identity, 0x1C9FD8AFA3947F17UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Avatar/Themes/AvatarGroupTheme.axaml"), AvatarThemeAsset.Identity, 0x3BBEB9DD7B9BF18DUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Avatar/Themes/AvatarTheme.axaml"), AvatarThemeAsset.Identity, 0x3BBEB9DD7B9BF18DUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Badge/Themes/CountBadgeAdornerTheme.axaml"), BadgeThemeAsset.Identity, 0x8B2AD4107988CAA3UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Badge/Themes/DotBadgeAdornerTheme.axaml"), BadgeThemeAsset.Identity, 0x8B2AD4107988CAA3UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Badge/Themes/RibbonBadgeAdornerTheme.axaml"), BadgeThemeAsset.Identity, 0x8B2AD4107988CAA3UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/BorderBeam/Themes/BorderBeamTheme.axaml"), BorderBeamThemeAsset.Identity, 0x01C74E38C91C7DB1UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Breadcrumb/Themes/BreadcrumbItemTheme.axaml"), BreadcrumbThemeAsset.Identity, 0x193C2AB64E809CADUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Breadcrumb/Themes/BreadcrumbTheme.axaml"), BreadcrumbThemeAsset.Identity, 0x193C2AB64E809CADUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/ButtonSpinner/Themes/ButtonSpinnerDecoratedBoxTheme.axaml"), ButtonSpinnerThemeAsset.Identity, 0x261DD89CB2317413UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/ButtonSpinner/Themes/ButtonSpinnerHandleTheme.axaml"), ButtonSpinnerThemeAsset.Identity, 0x30E3C63DBC159333UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/ButtonSpinner/Themes/ButtonSpinnerTheme.axaml"), ButtonSpinnerThemeAsset.Identity, 0x30E3C63DBC159333UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Buttons/Themes/BrowserButtonThemes.axaml"), ButtonThemeAsset.Identity, 0xC04059B1F687FBE7UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Buttons/Themes/ButtonTheme.axaml"), ButtonThemeAsset.Identity, 0x842CEA97311DA065UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Buttons/Themes/DropdownButtonTheme.axaml"), ButtonThemeAsset.Identity, 0xC04059B1F687FBE7UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Buttons/Themes/HyperLinkButtonTheme.axaml"), ButtonThemeAsset.Identity, 0x842CEA97311DA065UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Buttons/Themes/IconButtonTheme.axaml"), ButtonThemeAsset.Identity, 0x0312976FE9DA5951UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Buttons/Themes/SplitButtonTheme.axaml"), ButtonThemeAsset.Identity, 0x842CEA97311DA065UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Buttons/Themes/ToggleIconButtonTheme.axaml"), ButtonThemeAsset.Identity, 0x0312976FE9DA5951UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Calendar/Themes/BaseCalendarButtonTheme.axaml"), CalendarThemeAsset.Identity, 0xB60970009B72020DUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Calendar/Themes/BaseCalendarDayButtonTheme.axaml"), CalendarThemeAsset.Identity, 0xB60970009B72020DUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Calendar/Themes/CalendarItemTheme.axaml"), CalendarThemeAsset.Identity, 0xB60970009B72020DUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Calendar/Themes/CalendarTheme.axaml"), CalendarThemeAsset.Identity, 0xB60970009B72020DUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Calendar/Themes/HeadTextButtonTheme.axaml"), CalendarThemeAsset.Identity, 0xBB980B38227E171FUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Card/Themes/CardActionButtonTheme.axaml"), CardThemeAsset.Identity, 0xBAEC18A74A61F2F9UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Card/Themes/CardActionPanelTheme.axaml"), CardThemeAsset.Identity, 0xBAEC18A74A61F2F9UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Card/Themes/CardMetaContentTheme.axaml"), CardThemeAsset.Identity, 0xDFEF4F9CE9EBB93FUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Card/Themes/CardTabsContentTheme.axaml"), CardThemeAsset.Identity, 0xBAEC18A74A61F2F9UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Card/Themes/CardTheme.axaml"), CardThemeAsset.Identity, 0xBAEC18A74A61F2F9UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Carousel/Themes/CarouselNavButtonTheme.axaml"), CarouselThemeAsset.Identity, 0xB69F851E3125BDD9UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Carousel/Themes/CarouselPageIndicatorTheme.axaml"), CarouselThemeAsset.Identity, 0xB69F851E3125BDD9UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Carousel/Themes/CarouselTheme.axaml"), CarouselThemeAsset.Identity, 0xB69F851E3125BDD9UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Cascader/Themes/CascaderAddOnDecoratedBoxTheme.axaml"), CascaderThemeAsset.Identity, 0x6D700C86E129E1BBUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Cascader/Themes/CascaderTheme.axaml"), CascaderThemeAsset.Identity, 0x493DF233CC683A27UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Cascader/Themes/CascaderViewItemTheme.axaml"), CascaderThemeAsset.Identity, 0x5E5108E2547E39A5UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Cascader/Themes/CascaderViewTheme.axaml"), CascaderThemeAsset.Identity, 0x5E5108E2547E39A5UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/CheckBox/Themes/CheckBoxGroupTheme.axaml"), CheckBoxThemeAsset.Identity, 0xC4DD29FA4978DBD8UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/CheckBox/Themes/CheckBoxIndicatorTheme.axaml"), CheckBoxThemeAsset.Identity, 0x8087E7F677F296C9UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/CheckBox/Themes/CheckBoxItemsControlTheme.axaml"), CheckBoxThemeAsset.Identity, 0xC4DD29FA4978DBD8UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/CheckBox/Themes/CheckBoxTheme.axaml"), CheckBoxThemeAsset.Identity, 0x8087E7F677F296C9UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Collapse/Themes/CollapseItemTheme.axaml"), CollapseThemeAsset.Identity, 0xBE7695FF5D48A391UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Collapse/Themes/CollapseTheme.axaml"), CollapseThemeAsset.Identity, 0xBE7695FF5D48A391UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/ComboBox/Themes/ComboBoxHandleTheme.axaml"), ComboBoxThemeAsset.Identity, 0x7993CE9A5896E2B7UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/ComboBox/Themes/ComboBoxItemTheme.axaml"), ComboBoxThemeAsset.Identity, 0x73266117F7DC2191UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/ComboBox/Themes/ComboBoxTheme.axaml"), ComboBoxThemeAsset.Identity, 0xB3C18E68A752946BUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/DatePicker/Themes/CalendarView/CalendarButtonTheme.axaml"), DatePickerThemeAsset.Identity, 0x8A0229618C925A4FUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/DatePicker/Themes/CalendarView/CalendarDayButtonTheme.axaml"), DatePickerThemeAsset.Identity, 0x37091366C0F975A9UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/DatePicker/Themes/CalendarView/CalendarItemTheme.axaml"), DatePickerThemeAsset.Identity, 0x90F244DAF369BD45UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/DatePicker/Themes/CalendarView/CalendarTheme.axaml"), DatePickerThemeAsset.Identity, 0xC273D40EF9C503EBUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/DatePicker/Themes/CalendarView/DualMonthCalendarItemTheme.axaml"), DatePickerThemeAsset.Identity, 0x8A0229618C925A4FUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/DatePicker/Themes/DatePickerPresenterTheme.axaml"), DatePickerThemeAsset.Identity, 0x90F244DAF369BD45UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/DatePicker/Themes/RangeDatePickerTheme.axaml"), DatePickerThemeAsset.Identity, 0xC273D40EF9C503EBUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Descriptions/Themes/DescriptionBorderedItemContentTheme.axaml"), DescriptionsThemeAsset.Identity, 0x867A3B2E8A286079UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Descriptions/Themes/DescriptionBorderedItemLabelTheme.axaml"), DescriptionsThemeAsset.Identity, 0x867A3B2E8A286079UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Descriptions/Themes/DescriptionDefaultItemTheme.axaml"), DescriptionsThemeAsset.Identity, 0x867A3B2E8A286079UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Descriptions/Themes/DescriptionsTheme.axaml"), DescriptionsThemeAsset.Identity, 0x867A3B2E8A286079UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Dialog/Themes/DialogButtonBoxTheme.axaml"), DialogThemeAsset.Identity, 0x28153908CA2445CDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Dialog/Themes/DialogCaptionButtonTheme.axaml"), DialogThemeAsset.Identity, 0xC50D09EDF9325339UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Dialog/Themes/DialogSurfaceTheme.axaml"), DialogThemeAsset.Identity, 0x28153908CA2445CDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Dialog/Themes/DialogTheme.axaml"), DialogThemeAsset.Identity, 0xC50D09EDF9325339UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Dialog/Themes/OverlayDialogHeaderTheme.axaml"), DialogThemeAsset.Identity, 0x28153908CA2445CDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Dialog/Themes/OverlayDialogMaskTheme.axaml"), DialogThemeAsset.Identity, 0xC50D09EDF9325339UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Dialog/Themes/OverlayDialogPresenterTheme.axaml"), DialogThemeAsset.Identity, 0xC50D09EDF9325339UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Drawer/Themes/DrawerContainerTheme.axaml"), DrawerThemeAsset.Identity, 0xCD0DDAB5A7A0F930UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Drawer/Themes/DrawerInfoContainerTheme.axaml"), DrawerThemeAsset.Identity, 0x4FFC23C0997C0C85UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Empty/Themes/EmptyTheme.axaml"), EmptyThemeAsset.Identity, 0xA21C0A20786362C3UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Expander/Themes/ExpanderTheme.axaml"), ExpanderThemeAsset.Identity, 0x5EF1FDE0713BDDF9UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/FloatButton/Themes/AbstractFloatButtonTheme.axaml"), FloatButtonThemeAsset.Identity, 0x070BD0155F778D22UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/FloatButton/Themes/BackTopFloatButtonHostTheme.axaml"), FloatButtonThemeAsset.Identity, 0xB12D9A01D95276FDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/FloatButton/Themes/BackTopFloatButtonTheme.axaml"), FloatButtonThemeAsset.Identity, 0xB285F1A19EB81D31UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/FloatButton/Themes/FloatButtonGroupHostTheme.axaml"), FloatButtonThemeAsset.Identity, 0xB12D9A01D95276FDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/FloatButton/Themes/FloatButtonGroupTheme.axaml"), FloatButtonThemeAsset.Identity, 0xB12D9A01D95276FDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/FloatButton/Themes/FloatButtonHostTheme.axaml"), FloatButtonThemeAsset.Identity, 0xB12D9A01D95276FDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/FloatButton/Themes/FloatButtonItemsControlTheme.axaml"), FloatButtonThemeAsset.Identity, 0xB285F1A19EB81D31UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Flyouts/Themes/FlyoutHostTheme.axaml"), FlyoutHostThemeAsset.Identity, 0x6D5444929A9DDCBDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Flyouts/Themes/MenuFlyoutPresenterTheme.axaml"), MenuThemeAsset.Identity, 0xE67B3F255D84409FUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Flyouts/Themes/TreeViewFlyoutPresenterTheme.axaml"), TreeFlyoutThemeAsset.Identity, 0x633C7D01534E9031UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Form/Themes/FormItemDecoratorTheme.axaml"), FormThemeAsset.Identity, 0x07AA10850D9DDCC7UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Form/Themes/FormItemTheme.axaml"), FormThemeAsset.Identity, 0xAE2C472769B1524DUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Form/Themes/FormTheme.axaml"), FormThemeAsset.Identity, 0xAE2C472769B1524DUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/GroupBox/Themes/GroupBoxTheme.axaml"), GroupBoxThemeAsset.Identity, 0x616F6CB19C537925UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/ImagePreviewer/Themes/ImageGroupPreviewerTheme.axaml"), ImagePreviewerThemeAsset.Identity, 0x91A1EE504C179CDDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/ImagePreviewer/Themes/ImagePreviewFloatToolbarTheme.axaml"), ImagePreviewerThemeAsset.Identity, 0x91A1EE504C179CDDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/ImagePreviewer/Themes/ImagePreviewNavButtonTheme.axaml"), ImagePreviewerThemeAsset.Identity, 0x91A1EE504C179CDDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/ImagePreviewer/Themes/ImagePreviewToolbarTheme.axaml"), ImagePreviewerThemeAsset.Identity, 0x508252ED2AE47A81UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/ImagePreviewer/Themes/ImagePreviewerCoverTheme.axaml"), ImagePreviewerThemeAsset.Identity, 0x91A1EE504C179CDDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/ImagePreviewer/Themes/ImagePreviewerDialogTheme.axaml"), ImagePreviewerThemeAsset.Identity, 0x91A1EE504C179CDDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/ImagePreviewer/Themes/ImagePreviewerTheme.axaml"), ImagePreviewerThemeAsset.Identity, 0x508252ED2AE47A81UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/ImagePreviewer/Themes/ImagePreviewerThemes.axaml"), ImagePreviewerThemeAsset.Identity, 0x91A1EE504C179CDDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/ImagePreviewer/Themes/ImagePreviewerTitleBarTheme.axaml"), ImagePreviewerThemeAsset.Identity, 0x9D081C8ADAD0AB46UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/ImagePreviewer/Themes/ImageViewerTheme.axaml"), ImagePreviewerThemeAsset.Identity, 0x508252ED2AE47A81UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Input/Themes/InputClearIconButtonTheme.axaml"), LineEditThemeAsset.Identity, 0x9FA2F7ADA3F83AABUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Input/Themes/LineEditTheme.axaml"), LineEditThemeAsset.Identity, 0xC0C77DA5322C6B01UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Input/Themes/RevealButtonTheme.axaml"), LineEditThemeAsset.Identity, 0x9FA2F7ADA3F83AABUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Input/Themes/SearchButtonTheme.axaml"), LineEditThemeAsset.Identity, 0x89580BEA5F558D53UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Input/Themes/SearchEditTheme.axaml"), LineEditThemeAsset.Identity, 0xC0C77DA5322C6B01UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Input/Themes/TextAreaTheme.axaml"), TextAreaThemeAsset.Identity, 0xC62CF9FB2D614767UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Input/Themes/TextBoxTheme.axaml"), TextBoxThemeAsset.Identity, 0x237899A90F089DE5UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/ListBox/Themes/ListBoxItemTheme.axaml"), ListBoxThemeAsset.Identity, 0x5CA6C28841FB4047UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/ListBox/Themes/ListBoxTheme.axaml"), ListBoxThemeAsset.Identity, 0x5CA6C28841FB4047UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/ListView/Themes/ListViewItemTheme.axaml"), ListViewThemeAsset.Identity, 0x6FAEE86DED65C37DUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/ListView/Themes/ListViewTheme.axaml"), ListViewThemeAsset.Identity, 0x6FAEE86DED65C37DUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Mentions/Themes/MentionsTheme.axaml"), MentionsThemeAsset.Identity, 0x340C9E0B3FAC0C3FUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Menu/Themes/ContextMenuTheme.axaml"), MenuThemeAsset.Identity, 0xE67B3F255D84409FUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Menu/Themes/MenuItemTheme.axaml"), MenuThemeAsset.Identity, 0xE67B3F255D84409FUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Menu/Themes/MenuSeparatorTheme.axaml"), MenuThemeAsset.Identity, 0xA171CE14BEF01DBDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Menu/Themes/MenuTheme.axaml"), MenuThemeAsset.Identity, 0x6D8C02AEE480AF7AUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Menu/Themes/TopLevelMenuItemTheme.axaml"), MenuThemeAsset.Identity, 0xE67B3F255D84409FUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Message/Themes/MessageCardTheme.axaml"), MessageThemeAsset.Identity, 0xD67ABC8EA8C305A3UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Message/Themes/WindowMessageManagerTheme.axaml"), MessageThemeAsset.Identity, 0x79E8CC71A5975B04UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/MessageBox/Themes/MessageBoxContentTheme.axaml"), MessageBoxThemeAsset.Identity, 0x6637389B30CC34C5UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/MessageBox/Themes/MessageBoxTheme.axaml"), MessageBoxThemeAsset.Identity, 0x6637389B30CC34C5UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/NavMenu/Themes/HorizontalNavMenuItemHeaderTheme.axaml"), NavMenuThemeAsset.Identity, 0xD77A170A994A68E5UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/NavMenu/Themes/NavMenuItemTheme.axaml"), NavMenuThemeAsset.Identity, 0xC92F71B85785DD67UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/NavMenu/Themes/NavMenuTheme.axaml"), NavMenuThemeAsset.Identity, 0xD77A170A994A68E5UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Notifications/Themes/NotificationCardTheme.axaml"), NotificationThemeAsset.Identity, 0xA5A098BEC2F1538DUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Notifications/Themes/WindowNotificationManagerTheme.axaml"), NotificationThemeAsset.Identity, 0xCB832FC8958BF9E6UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/NumericUpDown/Themes/NumericUpDownTheme.axaml"), NumericUpDownThemeAsset.Identity, 0xC5ECBA9DDBB85BE0UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/OptionButtonGroup/Themes/OptionButtonGroupTheme.axaml"), OptionButtonThemeAsset.Identity, 0x0256B7E325F3F2B0UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/OptionButtonGroup/Themes/OptionButtonTheme.axaml"), OptionButtonThemeAsset.Identity, 0x45BDD64C141C69DDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/OtpLineEdit/Themes/OtpLineEditCellTheme.axaml"), OtpLineEditThemeAsset.Identity, 0x29501E15ECDB4365UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/OtpLineEdit/Themes/OtpLineEditTheme.axaml"), OtpLineEditThemeAsset.Identity, 0xEEF36DD78538C79BUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Pagination/Themes/PaginationNavItemTheme.axaml"), PaginationThemeAsset.Identity, 0xDBC7F28C5495BCC5UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Pagination/Themes/PaginationNavTheme.axaml"), PaginationThemeAsset.Identity, 0x3DC14A4B8129F989UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Pagination/Themes/PaginationTheme.axaml"), PaginationThemeAsset.Identity, 0xDBC7F28C5495BCC5UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Pagination/Themes/SimplePaginationTheme.axaml"), PaginationThemeAsset.Identity, 0xDBC7F28C5495BCC5UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Popup/Themes/OverlayPopupHostTheme.axaml"), PopupHostThemeAsset.Identity, 0xE764C73D4EF38EA7UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Popup/Themes/PopupRootTheme.axaml"), PopupHostThemeAsset.Identity, 0xE764C73D4EF38EA7UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Popup/Themes/PopupTheme.axaml"), PopupHostThemeAsset.Identity, 0x545EB7DBA0DE65A1UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/PopupConfirm/Themes/PopupConfirmContainerTheme.axaml"), PopupConfirmThemeAsset.Identity, 0xE757250325C8D301UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/PopupConfirm/Themes/PopupConfirmTheme.axaml"), PopupConfirmThemeAsset.Identity, 0xC9A98686ACFF8946UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Primitives/AddOnDecoratedBox/Themes/AddOnDecoratedBoxTheme.axaml"), AddOnDecoratedBoxThemeAsset.Identity, 0x55422EA160981C31UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Primitives/ArrowDecoratedBox/Themes/ArrowDecoratedBoxTheme.axaml"), ArrowDecoratedBoxThemeAsset.Identity, 0x1B3997BEAB73D487UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Primitives/IndicatorScrollViewer/Themes/IndicatorScrollBarThumbTheme.axaml"), IndicatorScrollViewerThemeAsset.Identity, 0x9AE2DB1FC19D84C5UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Primitives/IndicatorScrollViewer/Themes/IndicatorScrollViewerTheme.axaml"), IndicatorScrollViewerThemeAsset.Identity, 0x178D693DE4C30CFDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Primitives/InfoPickerInput/Themes/InfoPickerInputTheme.axaml"), InfoPickerInputThemeAsset.Identity, 0x455CEE7B0C017DDFUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Primitives/InfoPickerInput/Themes/PickerClearUpButtonTheme.axaml"), InfoPickerInputThemeAsset.Identity, 0xD549DBB68FC249FDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Primitives/InfoPickerInput/Themes/RangeInfoPickerInputTheme.axaml"), InfoPickerInputThemeAsset.Identity, 0x6B8CE1631B0C3C35UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/ProgressBar/Themes/AbstractCircleProgressTheme.axaml"), ProgressBarThemeAsset.Identity, 0xFD0E5138CC835D75UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/ProgressBar/Themes/AbstractLineProgressTheme.axaml"), ProgressBarThemeAsset.Identity, 0xFD0E5138CC835D75UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/ProgressBar/Themes/AbstractProgressBarTheme.axaml"), ProgressBarThemeAsset.Identity, 0xFD0E5138CC835D75UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/ProgressBar/Themes/ProgressBarTheme.axaml"), ProgressBarThemeAsset.Identity, 0x8F062308D608209FUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/QRCode/Themes/QRCodeTheme.axaml"), QRCodeThemeAsset.Identity, 0x6B3BA35D409D57A5UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/RadioButton/Themes/RadioButtonGroupTheme.axaml"), RadioButtonThemeAsset.Identity, 0xC2830DC78D2BEBF0UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/RadioButton/Themes/RadioButtonTheme.axaml"), RadioButtonThemeAsset.Identity, 0x75A657B93FA915DBUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/RadioButton/Themes/RadioIndicatorTheme.axaml"), RadioButtonThemeAsset.Identity, 0xC2830DC78D2BEBF0UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Rate/Themes/RateItemsControlTheme.axaml"), RateThemeAsset.Identity, 0x981F232BD33EC927UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Rate/Themes/RateTheme.axaml"), RateThemeAsset.Identity, 0x1BEBD8492469966DUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Result/Themes/ResultTheme.axaml"), ResultThemeAsset.Identity, 0x15E87F5595A64CBDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/ScrollViewer/Themes/AvaScrollViewerTheme.axaml"), ScrollViewerThemeAsset.Identity, 0xFC4935233097FF86UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/ScrollViewer/Themes/ScrollBarTheme.axaml"), ScrollViewerThemeAsset.Identity, 0x3347D95B82AF4C25UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/ScrollViewer/Themes/ScrollViewerTheme.axaml"), ScrollViewerThemeAsset.Identity, 0xFC4935233097FF86UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Segmented/Themes/SegmentedItemTheme.axaml"), SegmentedThemeAsset.Identity, 0x2539EF4A0C693599UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Segmented/Themes/SegmentedTheme.axaml"), SegmentedThemeAsset.Identity, 0x2539EF4A0C693599UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Select/Themes/SelectAddOnDecoratedBoxTheme.axaml"), SelectThemeAsset.Identity, 0x4C34B9B7AF8CEF93UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Select/Themes/SelectHandleTheme.axaml"), SelectThemeAsset.Identity, 0xFC63E31AC7C956EDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Select/Themes/SelectMaxCountIndicatorTheme.axaml"), SelectThemeAsset.Identity, 0xFC63E31AC7C956EDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Select/Themes/SelectResultOptionsBoxTheme.axaml"), SelectThemeAsset.Identity, 0xFC63E31AC7C956EDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Select/Themes/SelectTagAwareTextBoxTheme.axaml"), SelectThemeAsset.Identity, 0xFC63E31AC7C956EDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Select/Themes/SelectTheme.axaml"), SelectThemeAsset.Identity, 0x18214CD79865D29FUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Separator/Themes/SeparatorTheme.axaml"), SeparatorThemeAsset.Identity, 0xCD8EAC02A20E14B3UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Skeleton/Themes/SkeletonAvatarTheme.axaml"), SkeletonThemeAsset.Identity, 0x79C231EC316F4F6DUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Skeleton/Themes/SkeletonButtonTheme.axaml"), SkeletonThemeAsset.Identity, 0x73C6AD85B7235B4EUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Skeleton/Themes/SkeletonElementTheme.axaml"), SkeletonThemeAsset.Identity, 0x73C6AD85B7235B4EUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Skeleton/Themes/SkeletonImageTheme.axaml"), SkeletonThemeAsset.Identity, 0x79C231EC316F4F6DUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Skeleton/Themes/SkeletonParagraphTheme.axaml"), SkeletonThemeAsset.Identity, 0x73C6AD85B7235B4EUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Slider/Themes/SliderTheme.axaml"), SliderThemeAsset.Identity, 0x5D573B1950FAD179UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Slider/Themes/SliderThumbTheme.axaml"), SliderThemeAsset.Identity, 0x5D573B1950FAD179UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Slider/Themes/SliderTrackTheme.axaml"), SliderThemeAsset.Identity, 0x5D573B1950FAD179UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Space/Themes/CompactSpaceAddOnTheme.axaml"), SpaceThemeAsset.Identity, 0x8048627F02B71F25UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Spin/Themes/SpinIndicatorTheme.axaml"), SpinThemeAsset.Identity, 0x08A42CBB731DCED5UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Spin/Themes/SpinTheme.axaml"), SpinThemeAsset.Identity, 0x08A42CBB731DCED5UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/SplitView/Themes/SplitViewTheme.axaml"), SplitViewThemeAsset.Identity, 0x7BE2773149A11D0FUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Splitter/Themes/SplitterDragBarTheme.axaml"), SplitterThemeAsset.Identity, 0xE74A056EDBC53559UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Splitter/Themes/SplitterHandleTheme.axaml"), SplitterThemeAsset.Identity, 0xE74A056EDBC53559UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Splitter/Themes/SplitterTheme.axaml"), SplitterThemeAsset.Identity, 0xE74A056EDBC53559UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Statistic/Themes/AbstractStatisticTheme.axaml"), StatisticThemeAsset.Identity, 0x4AD1502283D77605UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Statistic/Themes/StatisticCountUpTheme.axaml"), StatisticThemeAsset.Identity, 0x4AD1502283D77605UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Statistic/Themes/StatisticTheme.axaml"), StatisticThemeAsset.Identity, 0x79454494F711E05DUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Steps/Themes/StepsItemIndicatorTheme.axaml"), StepsThemeAsset.Identity, 0xE5CBE72E7D3636CFUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Steps/Themes/StepsItemTheme.axaml"), StepsThemeAsset.Identity, 0xE5CBE72E7D3636CFUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Steps/Themes/StepsTheme.axaml"), StepsThemeAsset.Identity, 0xD2023813CC70BF74UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Switch/Themes/ToggleSwitchTheme.axaml"), ToggleSwitchThemeAsset.Identity, 0x6D071244B8C72AFDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/TabControl/Themes/BaseOverflowMenuItemTheme.axaml"), TabControlThemeAsset.Identity, 0x6081BC4CA9243726UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/TabControl/Themes/BaseTabControlTheme.axaml"), TabControlThemeAsset.Identity, 0x6A448E3CA8E93EDDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/TabControl/Themes/BaseTabItemTheme.axaml"), TabControlThemeAsset.Identity, 0x6A448E3CA8E93EDDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/TabControl/Themes/BaseTabScrollViewerTheme.axaml"), TabControlThemeAsset.Identity, 0x6A448E3CA8E93EDDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/TabControl/Themes/CardTabControlTheme.axaml"), TabControlThemeAsset.Identity, 0x6A448E3CA8E93EDDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/TabControl/Themes/CardTabItemTheme.axaml"), TabControlThemeAsset.Identity, 0x6A448E3CA8E93EDDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/TabControl/Themes/TabControlTheme.axaml"), TabControlThemeAsset.Identity, 0x6A448E3CA8E93EDDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/TabControl/Themes/TabStrip/BaseTabStripItemTheme.axaml"), TabControlThemeAsset.Identity, 0x6A448E3CA8E93EDDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/TabControl/Themes/TabStrip/BaseTabStripTheme.axaml"), TabControlThemeAsset.Identity, 0xDD41855FA62999D1UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/TabControl/Themes/TabStrip/CardTabStripItemTheme.axaml"), TabControlThemeAsset.Identity, 0x6A448E3CA8E93EDDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/TabControl/Themes/TabStrip/CardTabStripTheme.axaml"), TabControlThemeAsset.Identity, 0x6A448E3CA8E93EDDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/TabControl/Themes/TabStrip/TabStripTheme.axaml"), TabControlThemeAsset.Identity, 0x6A448E3CA8E93EDDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Tag/Themes/TagTheme.axaml"), TagThemeAsset.Identity, 0x53F1E4D27CFEE711UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/TimePicker/Themes/TimePickerPresenterTheme.axaml"), TimePickerThemeAsset.Identity, 0x411EF088B10B9328UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/TimePicker/Themes/TimeViewCellTheme.axaml"), TimePickerThemeAsset.Identity, 0x3C22A3A58BF8D338UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/TimePicker/Themes/TimeViewTheme.axaml"), TimePickerThemeAsset.Identity, 0x6070AAC009B121CDUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Timeline/Themes/TimelineIndicatorTheme.axaml"), TimelineThemeAsset.Identity, 0x7F1926D110F0CC8DUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Timeline/Themes/TimelineTheme.axaml"), TimelineThemeAsset.Identity, 0x680FC90489553ED6UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Tooltip/Themes/ToolTipTheme.axaml"), ToolTipThemeAsset.Identity, 0x807D950E68DBDFDBUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Tour/Themes/DefaultTourIndicatorTheme.axaml"), TourThemeAsset.Identity, 0xBF115A49E57C51E9UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Tour/Themes/TourStepTheme.axaml"), TourThemeAsset.Identity, 0xBF115A49E57C51E9UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Tour/Themes/TourStepsViewTheme.axaml"), TourThemeAsset.Identity, 0xBF115A49E57C51E9UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Tour/Themes/TourTheme.axaml"), TourThemeAsset.Identity, 0xBF115A49E57C51E9UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Transfer/Themes/AbstractTransferTheme.axaml"), TransferThemeAsset.Identity, 0xC35F2DC54DAD4BADUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Transfer/Themes/TransferItemDecoratorTheme.axaml"), TransferThemeAsset.Identity, 0xC35F2DC54DAD4BADUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Transfer/Themes/TransferListItemTheme.axaml"), TransferThemeAsset.Identity, 0x30A8E41782BC06C6UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Transfer/Themes/TransferSelectDropdownTheme.axaml"), TransferThemeAsset.Identity, 0x30A8E41782BC06C6UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Transfer/Themes/TransferTreeViewItemHeaderTheme.axaml"), TransferThemeAsset.Identity, 0x30A8E41782BC06C6UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/TreeSelect/Themes/TreeSelectAddOnDecoratedBoxTheme.axaml"), TreeSelectThemeAsset.Identity, 0x6438BE353533BAE3UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/TreeSelect/Themes/TreeSelectTheme.axaml"), TreeSelectThemeAsset.Identity, 0x8BFDFED602895FE3UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/TreeView/Themes/NodeSwitcherButtonTheme.axaml"), TreeViewThemeAsset.Identity, 0x6B484FF59B5859A1UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/TreeView/Themes/TreeViewItemHeaderTheme.axaml"), TreeViewThemeAsset.Identity, 0x6B484FF59B5859A1UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/TreeView/Themes/TreeViewItemTheme.axaml"), TreeViewThemeAsset.Identity, 0xD111C7D9BD54ABC8UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/TreeView/Themes/TreeViewTheme.axaml"), TreeViewThemeAsset.Identity, 0x6B484FF59B5859A1UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Upload/Themes/AbstractUploadPictureContentTheme.axaml"), UploadThemeAsset.Identity, 0x96668830629E0DFCUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Upload/Themes/DefaultList/UploadTextListItemHeaderTheme.axaml"), UploadThemeAsset.Identity, 0xDC0865E43D43379DUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Upload/Themes/DefaultList/UploadTextListItemTheme.axaml"), UploadThemeAsset.Identity, 0xDC0865E43D43379DUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Upload/Themes/PictureList/UploadPictureDefaultContentTheme.axaml"), UploadThemeAsset.Identity, 0xDC0865E43D43379DUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Upload/Themes/PictureList/UploadPicturePendingContentTheme.axaml"), UploadThemeAsset.Identity, 0xDC0865E43D43379DUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Upload/Themes/PictureList/UploadPicturePreviewContentTheme.axaml"), UploadThemeAsset.Identity, 0xDC0865E43D43379DUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Upload/Themes/PictureList/UploadPictureUploadingContentTheme.axaml"), UploadThemeAsset.Identity, 0xDC0865E43D43379DUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Upload/Themes/PictureShapeList/UploadPictureShapeDefaultContentTheme.axaml"), UploadThemeAsset.Identity, 0xDC0865E43D43379DUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Upload/Themes/PictureShapeList/UploadPictureShapeListTheme.axaml"), UploadThemeAsset.Identity, 0x96668830629E0DFCUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Upload/Themes/PictureShapeList/UploadPictureShapePreviewContentTheme.axaml"), UploadThemeAsset.Identity, 0xDC0865E43D43379DUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Upload/Themes/PictureShapeList/UploadPictureShapeUploadingContentTheme.axaml"), UploadThemeAsset.Identity, 0xDC0865E43D43379DUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Upload/Themes/UploadDefaultDropAreaTheme.axaml"), UploadThemeAsset.Identity, 0xDC0865E43D43379DUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Upload/Themes/UploadTheme.axaml"), UploadThemeAsset.Identity, 0x96668830629E0DFCUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Upload/Themes/UploadTriggerTheme.axaml"), UploadThemeAsset.Identity, 0xDC0865E43D43379DUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Window/Themes/FullscreenPopoverLayerTheme.axaml"), WindowTitleBarThemeAsset.Identity, 0xCCCE86C2A94518ADUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Window/Themes/WindowDrawnDecorationsTheme.axaml"), WindowThemeAsset.Identity, 0x0D1B6C1B0FB14ABEUL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/Window/Themes/WindowTheme.axaml"), WindowThemeAsset.Identity, 0xA96E41D3EF4B3285UL),
            new global::AtomUI.Theme.Schema.ControlThemeAssetDescriptor(new global::System.Uri("avares://AtomUI.Desktop.Controls/WindowTitleBar/Themes/WindowTitleBarTheme.axaml"), WindowTitleBarThemeAsset.Identity, 0x0CE2797AB36E2541UL),
        };
    }
}
