<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <RootNamespace>AtomUI.Toolkits.GalleryBase.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Headless" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Shouldly" />
        <PackageReference Include="xunit.v3" />
        <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/AtomUI.Toolkits.GalleryBase/AtomUI.Toolkits.GalleryBase.csproj" />
        <ProjectReference Include="../../src/AtomUI.Localization/AtomUI.Localization.csproj" />
    </ItemGroup>
</Project>
