<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(AtomUITargetFrameworks)</TargetFrameworks>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>GeneratedFiles</CompilerGeneratedFilesOutputPath>
        <AtomUIGenerateControlThemeAssetResources>true</AtomUIGenerateControlThemeAssetResources>
        <RootNamespace>AtomUI.Desktop.Controls</RootNamespace>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <Compile Remove="$(CompilerGeneratedFilesOutputPath)/**/*.cs"/>
        <Compile Remove="Window\Reflection\**" />
        <Compile Remove="Window\Visuals\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="ReactiveUI.Avalonia"/>
        <PackageReference Include="Avalonia.Desktop"/>
        <PackageReference Include="Avalonia.Wayland"/>
        <PackageReference Include="Avalonia.X11"/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="AtomUI.Desktop.Controls.DataGrid" />
        <InternalsVisibleTo Include="AtomUI.Desktop.Controls.ColorPicker" />
        <InternalsVisibleTo Include="AtomUI.Desktop.Controls.Extras" />
        <InternalsVisibleTo Include="AtomUI.Desktop.Controls.Tests" />
        <InternalsVisibleTo Include="AtomUI.Performance" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../AtomUI.Native/AtomUI.Native.csproj" />
        <ProjectReference Include="../AtomUI.Controls/AtomUI.Controls.csproj" />
        <ProjectReference Include="../AtomUI.Generator/AtomUI.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
      <AvaloniaXaml Remove="Window\Reflection\**" />
      <AvaloniaXaml Remove="Window\Visuals\**" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="Window\Reflection\**" />
      <EmbeddedResource Remove="Window\Visuals\**" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Remove="Window\Reflection\**" />
      <AdditionalFiles Remove="Window\Visuals\**" />
    </ItemGroup>

    <ItemGroup>
      <AvaloniaResource Remove="Window\Reflection\**" />
      <AvaloniaResource Remove="Window\Visuals\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Window\Reflection\**" />
      <None Remove="Window\Visuals\**" />
    </ItemGroup>

</Project>
