using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.RadioButton;

[LanguageProvider(LanguageCode.en_US, RadioButtonShowCase.LanguageId)]
internal partial class en_US
{
    public const string ScenarioBasic = "Basic";
    public const string ScenarioGroups = "Groups";
    public const string ScenarioOptions = "Options";
    public const string ScenarioStyles = "Styles";

    public const string BasicTitle = "Basic";
    public const string BasicDescription = "The simplest use.";
    public const string DisabledTitle = "Disabled";
    public const string DisabledDescription = "Disabled state of RadioButton.";
    public const string RadioGroupTitle = "Radio Group";
    public const string RadioGroupDescription = "A group of radio components.";
    public const string VerticalRadioGroupTitle = "Vertical Radio Group";
    public const string VerticalRadioGroupDescription = "Vertical Radio Group.";
    public const string ItemsSourceRadioGroupTitle = "Radio Group by Items source";
    public const string ItemsSourceRadioGroupDescription = "Radio Group.";
    public const string OptionButtonTitle = "Option Button";
    public const string OptionButtonDescription = "OptionButton Group.";
    public const string OptionButtonWithIconTitle = "Option Button with icon";
    public const string OptionButtonWithIconDescription = "OptionButton Group with icon.";
    public const string OptionStyleTitle = "option style";
    public const string OptionStyleDescription = "The combination of option button style.";
    public const string SolidOptionButtonTitle = "Solid option button";
    public const string SolidOptionButtonDescription = "Solid option button style.";
    public const string SizeTypeTitle = "Size type";
    public const string SizeTypeDescription = "There are three sizes available: large, medium, and small. It can coordinate with input box.";
    public const string P2TitleSizetype = "SizeType";
    public const string P2ContentRadio = "Radio";
    public const string P2ContentRadio1 = "Radio1";
    public const string P2ContentRadio2 = "Radio2";
    public const string P2ContentToggleDisabled = "toggle disabled";
    public const string P2TextLinechart = "LineChart";
    public const string P2TextDotchart = "DotChart";
    public const string P2TextBarchart = "BarChart";
    public const string P2TextPiechart = "PieChart";
    public const string P2ContentOptionA = "Option A";
    public const string P2ContentOptionB = "Option B";
    public const string P2ContentOptionC = "Option C";
    public const string P2ContentOptionD = "Option D";
    public const string P2ContentApple = "Apple";
    public const string P2ContentPear = "Pear";
    public const string P2ContentOrange = "Orange";
    public const string P2ContentMacos = "macOS";
    public const string P2ContentLinux = "Linux";
    public const string P2ContentWindows = "Windows";
    public const string P2ContentHangzhou = "Hangzhou";
    public const string P2ContentShanghai = "Shanghai";
    public const string P2ContentBeijing = "Beijing";
    public const string P2ContentChengdu = "Chengdu";
    public const string ScenarioExamples = "Examples";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "Design Token";
    public const string PageSubtitle = "Choose one option from a set of mutually exclusive choices.";
    public const string PageDescription =
        "RadioButton covers individual selections, grouped choices, data-driven options, option-button styles, icons, disabled states and size variants.";
    public const string ComponentCategory = "Data Entry";
    public const string ComponentStatusStable = "Stable";
    public const string ApiColumnProperty = "Property";
    public const string ApiColumnDescription = "Description";
    public const string ApiColumnType = "Type";
    public const string ApiColumnDefault = "Default";
    public const string ApiPropertyIsChecked = "Whether the radio option is selected.";
    public const string ApiPropertyContent = "Content displayed by the radio option.";
    public const string ApiPropertyIsEnabled = "Whether the option can be interacted with.";
    public const string ApiPropertyIsMotionEnabled = "Enables motion effects for radio interactions.";
    public const string ApiPropertyIsWaveSpiritEnabled = "Enables the click wave feedback effect.";
    public const string ApiPropertyCheckedItem = "Current selected item in a radio group.";
    public const string ApiPropertyItemsSource = "Data source used to generate radio group items.";
    public const string ApiPropertyItemTemplate = "Template used to render generated radio group items.";
    public const string ApiPropertyOrientation = "Layout direction of radio group items.";
    public const string ApiPropertyItemSpacing = "Horizontal spacing between radio group items.";
    public const string ApiPropertyLineSpacing = "Vertical spacing between wrapped radio group lines.";
    public const string ApiPropertyButtonStyle = "Option button visual style.";
    public const string ApiPropertySizeType = "Option button group size.";
    public const string ApiPropertySelectedItem = "Current selected item in an option button group.";
    public const string ApiPropertyIcon = "Icon displayed inside an option button.";
    public const string TokenColumnToken = "Token";
    public const string TokenColumnDescription = "Description";
    public const string TokenColumnScope = "Scope";
    public const string TokenColumnStatus = "Status";
    public const string TokenNameRadioSize = "Size of the radio indicator.";
    public const string TokenNameDotSize = "Size of the selected dot inside the radio indicator.";
    public const string TokenNameDotColorDisabled = "Color of the selected dot when disabled.";
    public const string TokenNameTextMargin = "Margin between the radio indicator and text content.";
    public const string TokenNameButtonBackground = "Default option button background.";
    public const string TokenNameButtonCheckedBackground = "Background of a checked option button.";
    public const string TokenNameButtonColor = "Default option button text color.";
    public const string TokenNameButtonPadding = "Padding inside an option button.";
    public const string TokenNameButtonSolidCheckedBackground = "Checked background used by solid option buttons.";
    public const string TokenNameContentFontSize = "Default font size for option button content.";
    public const string TokenNamePadding = "Default frame padding for option buttons.";
    public const string TokenScopeRadioButton = "RadioButton";
    public const string TokenScopeOptionButton = "OptionButton";
    public const string TokenStatusStable = "Stable";

}
