using AtomUI.Localization;

namespace AtomUIGallery.Localization;

[LanguageCatalog(ContractVersion = 1)]
public enum RadioButtonShowCaseLangResourceKind
{
    ScenarioBasic = 1,
    ScenarioGroups = 2,
    ScenarioOptions = 3,
    ScenarioStyles = 4,
    BasicTitle = 5,
    BasicDescription = 6,
    DisabledTitle = 7,
    DisabledDescription = 8,
    RadioGroupTitle = 9,
    RadioGroupDescription = 10,
    VerticalRadioGroupTitle = 11,
    VerticalRadioGroupDescription = 12,
    ItemsSourceRadioGroupTitle = 13,
    ItemsSourceRadioGroupDescription = 14,
    CheckedItemBindingTitle = 15,
    CheckedItemBindingDescription = 16,
    OptionButtonTitle = 17,
    OptionButtonDescription = 18,
    VerticalOptionButtonTitle = 19,
    VerticalOptionButtonDescription = 20,
    OptionButtonWithIconTitle = 21,
    OptionButtonWithIconDescription = 22,
    OptionStyleTitle = 23,
    OptionStyleDescription = 24,
    SolidOptionButtonTitle = 25,
    SolidOptionButtonDescription = 26,
    SizeTypeTitle = 27,
    SizeTypeDescription = 28,
    P2TitleSizetype = 29,
    P2ContentRadio = 30,
    P2ContentRadio1 = 31,
    P2ContentRadio2 = 32,
    P2ContentToggleDisabled = 33,
    P2TextLinechart = 34,
    P2TextDotchart = 35,
    P2TextBarchart = 36,
    P2TextPiechart = 37,
    P2ContentOptionA = 38,
    P2ContentOptionB = 39,
    P2ContentOptionC = 40,
    P2ContentOptionD = 41,
    P2ContentApple = 42,
    P2ContentPear = 43,
    P2ContentOrange = 44,
    P2ContentMacos = 45,
    P2ContentLinux = 46,
    P2ContentWindows = 47,
    P2ContentHangzhou = 48,
    P2ContentShanghai = 49,
    P2ContentBeijing = 50,
    P2ContentChengdu = 51,
    P2ContentSelectChengdu = 52,
    P2ContentClear = 53,
    P2ContentNone = 54,
    P2CheckedItemSummaryFormat = 55,
    ScenarioExamples = 56,
    PageSubtitle = 57,
    PageDescription = 58,
    ComponentCategory = 59,
    ComponentStatusStable = 60
}
