using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.RadioButton;

[LanguageProvider(LanguageCode.zh_CN, RadioButtonShowCase.LanguageId)]
internal partial class zh_CN
{
    public const string ScenarioBasic = "基础";
    public const string ScenarioGroups = "分组";
    public const string ScenarioOptions = "选项";
    public const string ScenarioStyles = "样式";

    public const string BasicTitle = "基础用法";
    public const string BasicDescription = "最简单的用法。";
    public const string DisabledTitle = "禁用";
    public const string DisabledDescription = "RadioButton 的禁用状态。";
    public const string RadioGroupTitle = "单选框组";
    public const string RadioGroupDescription = "一组单选组件。";
    public const string VerticalRadioGroupTitle = "垂直单选框组";
    public const string VerticalRadioGroupDescription = "垂直排列的单选框组。";
    public const string ItemsSourceRadioGroupTitle = "通过 ItemsSource 生成单选框组";
    public const string ItemsSourceRadioGroupDescription = "单选框组。";
    public const string OptionButtonTitle = "选项按钮";
    public const string OptionButtonDescription = "选项按钮组。";
    public const string OptionButtonWithIconTitle = "带图标的选项按钮";
    public const string OptionButtonWithIconDescription = "带图标的选项按钮组。";
    public const string OptionStyleTitle = "选项样式";
    public const string OptionStyleDescription = "选项按钮样式组合。";
    public const string SolidOptionButtonTitle = "实色选项按钮";
    public const string SolidOptionButtonDescription = "实色选项按钮样式。";
    public const string SizeTypeTitle = "尺寸类型";
    public const string SizeTypeDescription = "提供大号、中号和小号三种尺寸，可与输入框配合使用。";
    public const string P2TitleSizetype = "尺寸类型";
    public const string P2ContentRadio = "单选框";
    public const string P2ContentRadio1 = "单选框 1";
    public const string P2ContentRadio2 = "单选框 2";
    public const string P2ContentToggleDisabled = "切换禁用";
    public const string P2TextLinechart = "折线图";
    public const string P2TextDotchart = "点图";
    public const string P2TextBarchart = "柱状图";
    public const string P2TextPiechart = "饼图";
    public const string P2ContentOptionA = "选项 A";
    public const string P2ContentOptionB = "选项 B";
    public const string P2ContentOptionC = "选项 C";
    public const string P2ContentOptionD = "选项 D";
    public const string P2ContentApple = "苹果";
    public const string P2ContentPear = "梨";
    public const string P2ContentOrange = "橙子";
    public const string P2ContentMacos = "macOS";
    public const string P2ContentLinux = "Linux";
    public const string P2ContentWindows = "Windows";
    public const string P2ContentHangzhou = "杭州";
    public const string P2ContentShanghai = "上海";
    public const string P2ContentBeijing = "北京";
    public const string P2ContentChengdu = "成都";
    public const string ScenarioExamples = "示例";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "设计 Token";
    public const string PageSubtitle = "在一组互斥选项中选择一个值。";
    public const string PageDescription =
        "RadioButton 覆盖单个选择、分组选项、数据驱动选项、选项按钮样式、图标、禁用状态和尺寸变体。";
    public const string ComponentCategory = "数据录入";
    public const string ComponentStatusStable = "稳定";
    public const string ApiColumnProperty = "属性";
    public const string ApiColumnDescription = "说明";
    public const string ApiColumnType = "类型";
    public const string ApiColumnDefault = "默认值";
    public const string ApiPropertyIsChecked = "单选项是否被选中。";
    public const string ApiPropertyContent = "单选项显示的内容。";
    public const string ApiPropertyIsEnabled = "选项是否可交互。";
    public const string ApiPropertyIsMotionEnabled = "启用单选交互的动效。";
    public const string ApiPropertyIsWaveSpiritEnabled = "启用点击波纹反馈效果。";
    public const string ApiPropertyCheckedItem = "单选框组当前选中的项。";
    public const string ApiPropertyItemsSource = "用于生成单选框组条目的数据源。";
    public const string ApiPropertyItemTemplate = "用于渲染生成条目的模板。";
    public const string ApiPropertyOrientation = "单选框组条目的排列方向。";
    public const string ApiPropertyItemSpacing = "单选框组条目之间的水平间距。";
    public const string ApiPropertyLineSpacing = "单选框组换行后的垂直间距。";
    public const string ApiPropertyButtonStyle = "选项按钮视觉样式。";
    public const string ApiPropertySizeType = "选项按钮组尺寸。";
    public const string ApiPropertySelectedItem = "选项按钮组当前选中的项。";
    public const string ApiPropertyIcon = "选项按钮内部显示的图标。";
    public const string TokenColumnToken = "Token";
    public const string TokenColumnDescription = "说明";
    public const string TokenColumnScope = "作用域";
    public const string TokenColumnStatus = "状态";
    public const string TokenNameRadioSize = "单选指示器尺寸。";
    public const string TokenNameDotSize = "单选指示器内选中圆点尺寸。";
    public const string TokenNameDotColorDisabled = "禁用状态下选中圆点颜色。";
    public const string TokenNameTextMargin = "单选指示器与文本内容之间的间距。";
    public const string TokenNameButtonBackground = "选项按钮默认背景色。";
    public const string TokenNameButtonCheckedBackground = "选中选项按钮背景色。";
    public const string TokenNameButtonColor = "选项按钮默认文本颜色。";
    public const string TokenNameButtonPadding = "选项按钮内部边距。";
    public const string TokenNameButtonSolidCheckedBackground = "实色选项按钮选中背景色。";
    public const string TokenNameContentFontSize = "选项按钮内容默认字号。";
    public const string TokenNamePadding = "选项按钮默认框架内边距。";
    public const string TokenScopeRadioButton = "RadioButton";
    public const string TokenScopeOptionButton = "OptionButton";
    public const string TokenStatusStable = "稳定";

}
