using System.Collections.Immutable;
using System.Text;
using AtomUI.Generator.Localization.Catalog;
using AtomUI.Generator.Localization.Xliff;
using Microsoft.CodeAnalysis;

namespace AtomUI.Generator.Localization;

internal static class ApplicationLanguageBootstrapWriter
{
    internal static void Write(
        SourceProductionContext context,
        string? assemblyName,
        ImmutableArray<CompiledLanguageCatalog> compiledCatalogs,
        ApplicationLanguageHostInfo? application)
    {
        if (compiledCatalogs.IsEmpty || application is null)
        {
            return;
        }

        context.AddSource(
            "GeneratedApplicationLanguageBootstrap.g.cs",
            GeneratedSourceText.From(BuildSource(
                assemblyName,
                application,
                compiledCatalogs)));
    }

    private static string BuildSource(
        string? assemblyName,
        ApplicationLanguageHostInfo application,
        ImmutableArray<CompiledLanguageCatalog> compiledCatalogs)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        if (!string.IsNullOrEmpty(application.Namespace))
        {
            source.Append("namespace ").Append(application.Namespace).AppendLine();
            source.AppendLine("{");
        }

        var typeIndent = string.IsNullOrEmpty(application.Namespace) ? string.Empty : "    ";
        var memberIndent = typeIndent + "    ";
        var bodyIndent = memberIndent + "    ";
        source.Append(typeIndent).Append(application.AccessibilityModifier).Append(" partial class ")
              .Append(application.TypeName).AppendLine();
        source.Append(typeIndent)
              .AppendLine("    : global::AtomUI.Localization.IGeneratedApplicationLanguageBootstrap");
        source.Append(typeIndent).AppendLine("{");
        source.Append(memberIndent)
              .AppendLine("void global::AtomUI.Localization.IGeneratedApplicationLanguageBootstrap.RegisterApplicationLanguages(");
        source.Append(memberIndent)
              .AppendLine("    global::AtomUI.Localization.ILocalizationBuilder builder)");
        source.Append(memberIndent).AppendLine("{");
        source.Append(bodyIndent)
              .AppendLine("global::System.ArgumentNullException.ThrowIfNull(builder);");

        if (compiledCatalogs.Any(static catalog => catalog.OwnsCatalog))
        {
            source.Append(bodyIndent).Append("global::")
                  .Append(GeneratedThemeSchemaWriter.GetGeneratedNamespace(assemblyName))
                  .AppendLine(".GeneratedLanguageModuleRegistration.Register(builder);");
        }

        foreach (var catalog in compiledCatalogs.OrderBy(
                     static catalog => catalog.Catalog.CatalogId,
                     StringComparer.Ordinal))
        {
            foreach (var bundle in catalog.Bundles.Where(static bundle =>
                         bundle.SourceKind != LanguageFileSourceKind.ModuleBuiltIn))
            {
                LanguageModuleSourceWriter.WriteBundle(
                    source,
                    catalog.Catalog,
                    bundle,
                    bodyIndent);
            }
        }

        source.Append(memberIndent).AppendLine("}");
        source.Append(typeIndent).AppendLine("}");
        if (!string.IsNullOrEmpty(application.Namespace))
        {
            source.AppendLine("}");
        }
        return source.ToString();
    }
}
