using System.Collections.Immutable;
using System.Text;
using AtomUI.Generator.Localization.Catalog;
using AtomUI.Generator.Localization.Xliff;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace AtomUI.Generator.Localization;

internal static class LanguageModuleSourceWriter
{
    internal static void Write(
        SourceProductionContext context,
        string? assemblyName,
        ImmutableArray<CompiledLanguageCatalog> compiledCatalogs)
    {
        var ownedCatalogs = compiledCatalogs.Where(static catalog => catalog.OwnsCatalog)
                                             .OrderBy(static catalog => catalog.Catalog.CatalogId,
                                                 StringComparer.Ordinal)
                                             .ToArray();
        if (ownedCatalogs.Length == 0)
        {
            return;
        }

        context.AddSource(
            "GeneratedLanguageModuleRegistration.g.cs",
            GeneratedSourceText.From(BuildSource(assemblyName, ownedCatalogs)));
    }

    private static string BuildSource(
        string? assemblyName,
        IReadOnlyList<CompiledLanguageCatalog> catalogs)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.Append("[assembly: global::System.Reflection.AssemblyMetadata(")
              .Append(ToStringLiteral("AtomUILanguageModuleId"))
              .Append(", ")
              .Append(ToStringLiteral(catalogs[0].Catalog.ModuleId))
              .AppendLine(")]");
        source.AppendLine();
        source.Append("namespace ")
              .Append(GeneratedThemeSchemaWriter.GetGeneratedNamespace(assemblyName))
              .AppendLine();
        source.AppendLine("{");
        source.AppendLine("    internal static class GeneratedLanguageModuleRegistration");
        source.AppendLine("    {");
        source.AppendLine("        internal static void Register(global::AtomUI.Localization.ILocalizationBuilder builder)");
        source.AppendLine("        {");
        source.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(builder);");

        foreach (var catalog in catalogs)
        {
            WriteCatalog(source, catalog);
            foreach (var bundle in catalog.Bundles.Where(static bundle =>
                         bundle.SourceKind == LanguageFileSourceKind.ModuleBuiltIn))
            {
                WriteBundle(source, catalog.Catalog, bundle);
            }
        }

        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("}");
        return source.ToString();
    }

    private static void WriteCatalog(StringBuilder source, CompiledLanguageCatalog compiledCatalog)
    {
        var catalog = compiledCatalog.Catalog;
        source.AppendLine("            builder.AddCatalog(");
        source.Append("                new global::AtomUI.Localization.LanguageCatalogDescriptor<")
              .Append(catalog.TypeName).AppendLine(">(");
        source.Append("                    ").Append(ToStringLiteral(catalog.CatalogId)).AppendLine(",");
        source.Append("                    ").Append(catalog.ContractVersion).AppendLine(",");
        source.AppendLine("                    new global::AtomUI.Localization.LanguageCatalogUnitDescriptor[]");
        source.AppendLine("                    {");
        for (var slot = 0; slot < catalog.Units.Length; slot++)
        {
            var unit = catalog.Units[slot];
            source.Append("                        new global::AtomUI.Localization.LanguageCatalogUnitDescriptor(")
                  .Append(unit.Id).Append(", ")
                  .Append(ToStringLiteral(unit.Name)).Append(", ")
                  .Append(compiledCatalog.FormattedUnits[slot] ? "true" : "false")
                  .AppendLine("),");
        }
        source.AppendLine("                    },");
        source.AppendLine("                    static kind => kind switch");
        source.AppendLine("                    {");
        for (var slot = 0; slot < catalog.Units.Length; slot++)
        {
            source.Append("                        ").Append(catalog.TypeName).Append('.')
                  .Append(ToIdentifier(catalog.Units[slot].Name))
                  .Append(" => ").Append(slot).AppendLine(",");
        }
        source.AppendLine("                        _ => -1,");
        source.AppendLine("                    }));");
    }

    private static void WriteBundle(
        StringBuilder source,
        LanguageCatalogInfo catalog,
        CompiledTranslationBundle bundle)
    {
        source.AppendLine("            builder.AddTranslationBundle(");
        source.AppendLine("                new global::AtomUI.Localization.TranslationBundleDescriptor(");
        source.Append("                    ").Append(ToStringLiteral(catalog.CatalogId)).AppendLine(",");
        source.Append("                    ").Append(catalog.ContractVersion).AppendLine(",");
        source.Append("                    global::AtomUI.Localization.LanguageTag.Parse(")
              .Append(ToStringLiteral(bundle.Language)).AppendLine("),");
        source.Append("                    global::AtomUI.Localization.TranslationSourceKind.")
              .Append(bundle.SourceKind).AppendLine(",");
        source.Append("                    ").Append(ToStringLiteral(bundle.SourceIdentity)).AppendLine(",");
        source.AppendLine("                    new string?[]");
        source.AppendLine("                    {");
        foreach (var value in bundle.Values)
        {
            source.Append("                        ")
                  .Append(value is null ? "null" : ToStringLiteral(value))
                  .AppendLine(",");
        }
        source.AppendLine("                    }));");
    }

    private static string ToStringLiteral(string value)
    {
        return SyntaxFactory.LiteralExpression(
                                SyntaxKind.StringLiteralExpression,
                                SyntaxFactory.Literal(value))
                            .ToFullString();
    }

    private static string ToIdentifier(string value)
    {
        return SyntaxFacts.GetKeywordKind(value) == SyntaxKind.None ? value : "@" + value;
    }
}
