using AtomUIGallery.ShowCases.AboutUs;
using AtomUIGallery.ShowCases.Alert;
using AtomUIGallery.ShowCases.AutoComplete;
using AtomUIGallery.ShowCases.Avatar;
using AtomUIGallery.ShowCases.Badge;
using AtomUIGallery.ShowCases.Breadcrumb;
using AtomUIGallery.ShowCases.Button;
using AtomUIGallery.ShowCases.ButtonSpinner;
using AtomUIGallery.ShowCases.Calendar;
using AtomUIGallery.ShowCases.Card;
using AtomUIGallery.ShowCases.Carousel;
using AtomUIGallery.ShowCases.Cascader;
using AtomUIGallery.ShowCases.CheckBox;
using AtomUIGallery.ShowCases.Collapse;
using AtomUIGallery.ShowCases.ColorPicker;
using AtomUIGallery.ShowCases.ComboBox;
using AtomUIGallery.ShowCases.CustomizeTheme;
using AtomUIGallery.ShowCases.DataGrid;
using AtomUIGallery.ShowCases.DatePicker;
using AtomUIGallery.ShowCases.Descriptions;
using AtomUIGallery.ShowCases.Drawer;
using AtomUIGallery.ShowCases.DropdownButton;
using AtomUIGallery.ShowCases.Empty;
using AtomUIGallery.ShowCases.Expander;
using AtomUIGallery.ShowCases.FlexPanel;
using AtomUIGallery.ShowCases.FloatButton;
using AtomUIGallery.ShowCases.Form;
using AtomUIGallery.ShowCases.Grid;
using AtomUIGallery.ShowCases.GroupBox;
using AtomUIGallery.ShowCases.Icon;
using AtomUIGallery.ShowCases.ImagePreviewer;
using AtomUIGallery.ShowCases.InfoFlyout;
using AtomUIGallery.ShowCases.LineEdit;
using AtomUIGallery.ShowCases.List;
using AtomUIGallery.ShowCases.Mentions;
using AtomUIGallery.ShowCases.Menu;
using AtomUIGallery.ShowCases.Message;
using AtomUIGallery.ShowCases.Modal;
using AtomUIGallery.ShowCases.Notification;
using AtomUIGallery.ShowCases.NumberUpDown;
using AtomUIGallery.ShowCases.Pagination;
using AtomUIGallery.ShowCases.Palette;
using AtomUIGallery.ShowCases.PopupConfirm;
using AtomUIGallery.ShowCases.ProgressBar;
using AtomUIGallery.ShowCases.QRCode;
using AtomUIGallery.ShowCases.RadioButton;
using AtomUIGallery.ShowCases.Rate;
using AtomUIGallery.ShowCases.Result;
using AtomUIGallery.ShowCases.Segmented;
using AtomUIGallery.ShowCases.Select;
using AtomUIGallery.ShowCases.Separator;
using AtomUIGallery.ShowCases.Skeleton;
using AtomUIGallery.ShowCases.Slider;
using AtomUIGallery.ShowCases.Space;
using AtomUIGallery.ShowCases.Spin;
using AtomUIGallery.ShowCases.SplitButton;
using AtomUIGallery.ShowCases.Splitter;
using AtomUIGallery.ShowCases.Statistic;
using AtomUIGallery.ShowCases.Steps;
using AtomUIGallery.ShowCases.TabControl;
using AtomUIGallery.ShowCases.Tag;
using AtomUIGallery.ShowCases.TimePicker;
using AtomUIGallery.ShowCases.Timeline;
using AtomUIGallery.ShowCases.ToggleSwitch;
using AtomUIGallery.ShowCases.Tooltip;
using AtomUIGallery.ShowCases.Tour;
using AtomUIGallery.ShowCases.Transfer;
using AtomUIGallery.ShowCases.TreeSelect;
using AtomUIGallery.ShowCases.TreeView;
using AtomUIGallery.ShowCases.Upload;
using AtomUIGallery.ShowCases.Watermark;
using ReactiveUI;

namespace AtomUIGallery.ShowCases;

public sealed class ShowCaseViewModule : IViewModule
{
    public void RegisterViews(DefaultViewLocator locator)
    {
        locator.Map<AboutUsViewModel, AboutUsPage>(() => new AboutUsPage());
        locator.Map<PaletteViewModel, PaletteShowCase>(() => new PaletteShowCase());
        locator.Map<IconViewModel, IconShowCase>(() => new IconShowCase());
        locator.Map<CustomizeThemeViewModel, CustomizeThemeShowCase>(() => new CustomizeThemeShowCase());
        locator.Map<ButtonViewModel, ButtonShowCase>(() => new ButtonShowCase());
        locator.Map<FloatButtonViewModel, FloatButtonShowCase>(() => new FloatButtonShowCase());
        locator.Map<SplitButtonViewModel, SplitButtonShowCase>(() => new SplitButtonShowCase());
        locator.Map<SeparatorViewModel, SeparatorShowCase>(() => new SeparatorShowCase());
        locator.Map<SplitterViewModel, SplitterShowCase>(() => new SplitterShowCase());
        locator.Map<GridViewModel, GridShowCase>(() => new GridShowCase());
        locator.Map<BreadcrumbViewModel, BreadcrumbShowCase>(() => new BreadcrumbShowCase());
        locator.Map<ButtonSpinnerViewModel, ButtonSpinnerShowCase>(() => new ButtonSpinnerShowCase());
        locator.Map<ComboBoxViewModel, ComboBoxShowCase>(() => new ComboBoxShowCase());
        locator.Map<DropdownButtonViewModel, DropdownButtonShowCase>(() => new DropdownButtonShowCase());
        locator.Map<MessageViewModel, MessageShowCase>(() => new MessageShowCase());
        locator.Map<ModalViewModel, ModalShowCase>(() => new ModalShowCase());
        locator.Map<NotificationViewModel, NotificationShowCase>(() => new NotificationShowCase());
        locator.Map<PopupConfirmViewModel, PopupConfirmShowCase>(() => new PopupConfirmShowCase());
        locator.Map<DrawerViewModel, DrawerShowCase>(() => new DrawerShowCase());
        locator.Map<AlertViewModel, AlertShowCase>(() => new AlertShowCase());
        locator.Map<SpinViewModel, SpinShowCase>(() => new SpinShowCase());
        locator.Map<FlexPanelViewModel, FlexPanelShowCase>(() => new FlexPanelShowCase());
        locator.Map<CarouselViewModel, CarouselShowCase>(() => new CarouselShowCase());
        locator.Map<AvatarViewModel, AvatarShowCase>(() => new AvatarShowCase());
        locator.Map<CalendarViewModel, CalendarShowCase>(() => new CalendarShowCase());
        locator.Map<SkeletonViewModel, SkeletonShowCase>(() => new SkeletonShowCase());
        locator.Map<CardViewModel, CardShowCase>(() => new CardShowCase());
        locator.Map<CollapseViewModel, CollapseShowCase>(() => new CollapseShowCase());
        locator.Map<DescriptionsViewModel, DescriptionsShowCase>(() => new DescriptionsShowCase());
        locator.Map<EmptyViewModel, EmptyShowCase>(() => new EmptyShowCase());
        locator.Map<ExpanderViewModel, ExpanderShowCase>(() => new ExpanderShowCase());
        locator.Map<ImagePreviewerViewModel, ImagePreviewerShowCase>(() => new ImagePreviewerShowCase());
        locator.Map<CheckBoxViewModel, CheckBoxShowCase>(() => new CheckBoxShowCase());
        locator.Map<ToggleSwitchViewModel, ToggleSwitchShowCase>(() => new ToggleSwitchShowCase());
        locator.Map<RadioButtonViewModel, RadioButtonShowCase>(() => new RadioButtonShowCase());
        locator.Map<RateViewModel, RateShowCase>(() => new RateShowCase());
        locator.Map<SliderViewModel, SliderShowCase>(() => new SliderShowCase());
        locator.Map<ColorPickerViewModel, ColorPickerShowCase>(() => new ColorPickerShowCase());
        locator.Map<TagViewModel, TagShowCase>(() => new TagShowCase());
        locator.Map<SegmentedViewModel, SegmentedShowCase>(() => new SegmentedShowCase());
        locator.Map<GroupBoxViewModel, GroupBoxShowCase>(() => new GroupBoxShowCase());
        locator.Map<ResultViewModel, ResultShowCase>(() => new ResultShowCase());
        locator.Map<BadgeViewModel, BadgeShowCase>(() => new BadgeShowCase());
        locator.Map<StatisticViewModel, StatisticShowCase>(() => new StatisticShowCase());
        locator.Map<TimelineViewModel, TimelineShowCase>(() => new TimelineShowCase());
        locator.Map<QRCodeViewModel, QRCodeShowCase>(() => new QRCodeShowCase());
        locator.Map<LineEditViewModel, LineEditShowCase>(() => new LineEditShowCase());
        locator.Map<AutoCompleteViewModel, AutoCompleteShowCase>(() => new AutoCompleteShowCase());
        locator.Map<MentionsViewModel, MentionsShowCase>(() => new MentionsShowCase());
        locator.Map<SelectViewModel, SelectShowCase>(() => new SelectShowCase());
        locator.Map<CascaderViewModel, CascaderShowCase>(() => new CascaderShowCase());
        locator.Map<TreeSelectViewModel, TreeSelectShowCase>(() => new TreeSelectShowCase());
        locator.Map<TabControlViewModel, TabControlShowCase>(() => new TabControlShowCase());
        locator.Map<StepsViewModel, StepsShowCase>(() => new StepsShowCase());
        locator.Map<InfoFlyoutViewModel, InfoFlyoutShowCase>(() => new InfoFlyoutShowCase());
        locator.Map<WatermarkViewModel, WatermarkShowCase>(() => new WatermarkShowCase());
        locator.Map<ProgressBarViewModel, ProgressBarShowCase>(() => new ProgressBarShowCase());
        locator.Map<PaginationViewModel, PaginationShowCase>(() => new PaginationShowCase());
        locator.Map<MenuViewModel, MenuShowCase>(() => new MenuShowCase());
        locator.Map<TimePickerViewModel, TimePickerShowCase>(() => new TimePickerShowCase());
        locator.Map<DatePickerViewModel, DatePickerShowCase>(() => new DatePickerShowCase());
        locator.Map<UploadViewModel, UploadShowCase>(() => new UploadShowCase());
        locator.Map<TransferViewModel, TransferShowCase>(() => new TransferShowCase());
        locator.Map<FormViewModel, FormShowCase>(() => new FormShowCase());
        locator.Map<SpaceViewModel, SpaceShowCase>(() => new SpaceShowCase());
        locator.Map<NumberUpDownViewModel, NumberUpDownShowCase>(() => new NumberUpDownShowCase());
        locator.Map<ListViewModel, ListShowCase>(() => new ListShowCase());
        locator.Map<TreeViewViewModel, TreeViewShowCase>(() => new TreeViewShowCase());
        locator.Map<TourViewModel, TourShowCase>(() => new TourShowCase());
        locator.Map<DataGridViewModel, DataGridShowCase>(() => new DataGridShowCase());
        locator.Map<TooltipViewModel, TooltipShowCase>(() => new TooltipShowCase());
    }
}
