using AtomUI.Localization;

namespace AtomUIGallery.Localization;

[LanguageCatalog]
public enum BorderBeamShowCaseLangResourceKind
{
    ScenarioExamples,
    ComponentCategory,
    ComponentIntroducedVersion,
    PageSubtitle,
    PageDescription,
    BasicTitle,
    BasicDescription,
    CustomContainerTitle,
    CustomContainerDescription,
    CustomContainerContent,
    ShowOnHoverTitle,
    ShowOnHoverDescription,
    ShowOnHoverCardTitle,
    ShowOnHoverCardDescription,
    MultipleBeamsTitle,
    MultipleBeamsDescription,
    MultipleBeamsCardTitle,
    MultipleBeamsCardDescription,
    CustomizedColorTitle,
    CustomizedColorDescription,
    CustomizedColorCardDescription,
    DurationTitle,
    DurationDescription,
    DurationFastCardTitle,
    DurationFastCardDescription,
    DurationDefaultCardTitle,
    DurationDefaultCardDescription,
    DurationSlowCardTitle,
    DurationSlowCardDescription,
    SizeTitle,
    SizeDescription,
    SizeDefaultCardTitle,
    SizeDefaultCardDescription,
    SizeCompactCardTitle,
    SizeCompactCardDescription,
    SizeExtendedCardTitle,
    SizeExtendedCardDescription,
    LineWidthTitle,
    LineWidthDescription,
    LineWidthCardTitle,
    LineWidthCardDescription,
    NonUniformRadiusTitle,
    NonUniformRadiusDescription,
    NonUniformRadiusCardDescription
}
