namespace AtomUI.Desktop.Controls.CalendarView.Models;

internal readonly record struct CalendarCellState(
    DateTime Date,
    string Text,
    bool IsToday,
    bool IsBlackout,
    bool IsDisabled,
    bool IsInactive,
    bool IsSelected,
    bool IsRangeStart,
    bool IsRangeEnd,
    bool IsRangeMiddle,
    bool IsFocused,
    bool IsHidden,
    bool IsRangePreviewStart = false,
    bool IsRangePreviewEnd = false,
    bool IsRangePreviewMiddle = false,
    bool IsWeekNumber = false,
    bool IsWeekSelectionStart = false,
    bool IsWeekSelectionMiddle = false,
    bool IsWeekSelectionEnd = false,
    bool IsWeekRangeStart = false,
    bool IsWeekRangeMiddle = false,
    bool IsWeekRangeEnd = false,
    bool IsWeekHoverStart = false,
    bool IsWeekHoverMiddle = false,
    bool IsWeekHoverEnd = false);
