using System.Text;
using AtomUI.SourceGeneration;
using Microsoft.CodeAnalysis;

namespace AtomUI.Generator;

internal sealed class SemanticPartManifestWriter
{
    private readonly SourceProductionContext _context;
    private readonly string _generatedNamespace;
    private readonly string _controlCatalog;
    private readonly IReadOnlyList<SemanticControlDeclaration> _controls;

    internal SemanticPartManifestWriter(
        SourceProductionContext context,
        string? assemblyName,
        string controlCatalog,
        IReadOnlyList<SemanticControlDeclaration> controls)
    {
        _context = context;
        _generatedNamespace = GeneratedCodeNamespace.ForAssembly(assemblyName);
        _controlCatalog = controlCatalog;
        _controls = controls.OrderBy(
                                static control => control.ControlType.ToDisplayString(
                                    GeneratorSymbolDisplay.FullyQualifiedType),
                                StringComparer.Ordinal)
                            .ToArray();
    }

    internal void Write()
    {
        WriteManifest();
        foreach (var control in _controls)
        {
            WriteConstants(control);
        }
    }

    private void WriteManifest()
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.Append("namespace ").Append(_generatedNamespace).AppendLine(";");
        source.AppendLine();
        source.AppendLine("internal static class GeneratedSemanticPartManifest");
        source.AppendLine("{");
        source.AppendLine("    internal static global::System.Collections.Generic.IReadOnlyList<global::AtomUI.Theme.Schema.ControlSemanticDescriptor> GetDescriptors()");
        source.AppendLine("    {");
        if (_controls.Count == 0)
        {
            source.AppendLine("        return global::System.Array.Empty<global::AtomUI.Theme.Schema.ControlSemanticDescriptor>();");
        }
        else
        {
            source.AppendLine("        return new global::AtomUI.Theme.Schema.ControlSemanticDescriptor[]");
            source.AppendLine("        {");
            foreach (var control in _controls)
            {
                WriteControlDescriptor(source, control);
            }
            source.AppendLine("        };");
        }
        source.AppendLine("    }");
        source.AppendLine("}");

        _context.AddSource(
            "GeneratedSemanticPartManifest.g.cs",
            GeneratedSourceText.From(source.ToString()));
    }

    private void WriteControlDescriptor(StringBuilder source, SemanticControlDeclaration control)
    {
        var controlType = control.ControlType.ToDisplayString(GeneratorSymbolDisplay.FullyQualifiedType);
        source.AppendLine("            new global::AtomUI.Theme.Schema.ControlSemanticDescriptor(");
        source.Append("                typeof(").Append(controlType).AppendLine("),");
        source.Append("                new global::AtomUI.Theme.Schema.ControlTokenIdentity(\"")
              .Append(Escape(_controlCatalog))
              .Append("\", \"")
              .Append(Escape(control.ControlType.Name))
              .AppendLine("\"),");
        source.AppendLine("                new global::AtomUI.Theme.Schema.SemanticPartDescriptor[]");
        source.AppendLine("                {");
        source.AppendLine("                    new global::AtomUI.Theme.Schema.SemanticPartDescriptor(");
        source.AppendLine("                        \"root\",");
        source.AppendLine("                        \"root\",");
        source.AppendLine("                        null,");
        source.Append("                        typeof(").Append(controlType).AppendLine("),");
        source.AppendLine("                        global::AtomUI.Theme.SemanticPartCardinality.Single,");
        source.AppendLine("                        global::AtomUI.Theme.SemanticPartCustomization.Root,");
        source.AppendLine("                        null,");
        source.AppendLine("                        false,");
        source.AppendLine("                        \"6.0\",");
        source.AppendLine("                        false),");
        foreach (var part in control.Parts.OrderBy(static part => part.Path, StringComparer.Ordinal))
        {
            WritePartDescriptor(source, part);
        }
        source.AppendLine("                }),");
    }

    private static void WritePartDescriptor(StringBuilder source, SemanticPartDeclaration part)
    {
        var contractType = part.ContractType?.ToDisplayString(GeneratorSymbolDisplay.FullyQualifiedType) ??
                           "global::Avalonia.Controls.Control";
        source.AppendLine("                    new global::AtomUI.Theme.Schema.SemanticPartDescriptor(");
        source.Append("                        \"").Append(Escape(part.Name)).AppendLine("\",");
        source.Append("                        \"").Append(Escape(part.Path)).AppendLine("\",");
        source.Append("                        \"").Append(Escape(part.SelectorClass ?? string.Empty)).AppendLine("\",");
        source.Append("                        typeof(").Append(contractType).AppendLine("),");
        source.Append("                        global::AtomUI.Theme.SemanticPartCardinality.")
              .Append(GetCardinalityName(part.Cardinality))
              .AppendLine(",");
        source.Append("                        global::AtomUI.Theme.SemanticPartCustomization.")
              .Append(GetCustomizationName(part.Customization))
              .AppendLine(",");
        if (part.Customization == 2 && !string.IsNullOrWhiteSpace(part.ThemePropertyName))
        {
            var themeTargetType = part.ThemeTargetType?.ToDisplayString(
                                      GeneratorSymbolDisplay.FullyQualifiedType) ?? contractType;
            source.Append("                        new global::AtomUI.Theme.Schema.ControlThemeSemanticPartDescriptor(\"")
                  .Append(Escape(part.ThemePropertyName!))
                  .Append("\", \"")
                  .Append(Escape(themeTargetType))
                  .AppendLine("\"),");
        }
        else
        {
            source.AppendLine("                        null,");
        }
        source.Append("                        ").Append(part.CrossVisualRoot ? "true" : "false").AppendLine(",");
        source.Append("                        \"").Append(Escape(part.Since ?? string.Empty)).AppendLine("\",");
        source.Append("                        ").Append(part.RuntimeCreated ? "true" : "false").AppendLine("),");
    }

    private void WriteConstants(SemanticControlDeclaration control)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.Append("namespace ").Append(_generatedNamespace).AppendLine(";");
        source.AppendLine();
        source.Append("internal static class ").Append(control.ControlType.Name).AppendLine("SemanticParts");
        source.AppendLine("{");
        source.AppendLine("    internal const string Root = \"root\";");
        foreach (var part in control.Parts.OrderBy(static part => part.Path, StringComparer.Ordinal))
        {
            var memberName = ToMemberName(part.Name);
            source.Append("    internal const string ").Append(memberName).Append(" = \"")
                  .Append(Escape(part.Name)).AppendLine("\";");
            source.Append("    internal const string ").Append(memberName).Append("Class = \"")
                  .Append(Escape(part.SelectorClass ?? string.Empty)).AppendLine("\";");
        }
        source.AppendLine("}");

        _context.AddSource(
            $"{control.ControlType.Name}SemanticParts.g.cs",
            GeneratedSourceText.From(source.ToString()));
    }

    private static string ToMemberName(string value)
    {
        return string.Concat(value.Split('.').Select(static segment =>
            segment.Length == 0
                ? string.Empty
                : char.ToUpperInvariant(segment[0]) + segment.Substring(1)));
    }

    private static string GetCardinalityName(int value)
    {
        return value switch
        {
            1 => "Optional",
            2 => "Multiple",
            _ => "Single"
        };
    }

    private static string GetCustomizationName(int value)
    {
        return value switch
        {
            0 => "Root",
            2 => "SelectorAndTheme",
            _ => "Selector"
        };
    }

    private static string Escape(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
