using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using AtomUI.Controls.Data;
using AtomUI.Desktop.Controls.Utils;
using Avalonia.Data;
using Avalonia.Data.Core;
using Avalonia.Controls;
using Avalonia.Markup.Xaml.MarkupExtensions;
using Avalonia.Threading;
using Shouldly;
using Xunit;

namespace AtomUI.Desktop.Controls.Tests.DataGrid.DataMemberAccessors;

public class DataGridDataMemberAccessorsTests
{
    static DataGridDataMemberAccessorsTests() => AvaloniaTestApp.EnsureInitialized();

    [Fact]
    public void GeneratedAccessorsExposeDataGridMetadata()
    {
        DataMemberAccessorRegistry.TryGet(typeof(MetadataRow), out var descriptor).ShouldBeTrue();
        var descriptorMetadata = descriptor.ShouldBeAssignableTo<IDataMemberAccessorDescriptorMetadataProvider>();
        descriptorMetadata.IsDataTypeReadOnly.ShouldBeTrue();

        var visibleAccessor = descriptor.Accessors.Single(accessor => accessor.Path == nameof(MetadataRow.VisibleScore));
        var visibleMetadata = visibleAccessor.ShouldBeAssignableTo<IDataMemberAccessorMetadataProvider>().Metadata;
        visibleAccessor.ValueType.ShouldBe(typeof(int));
        visibleAccessor.CanWrite.ShouldBeTrue();
        visibleMetadata.DisplayName.ShouldBe("Visible score");
        visibleMetadata.AutoGenerateField.ShouldBe(true);
        visibleMetadata.Order.ShouldBe(2);
        visibleMetadata.IsReadOnly.ShouldBeFalse();
        visibleMetadata.IsEditable.ShouldBeTrue();

        var hiddenMetadata = descriptor.Accessors.Single(accessor => accessor.Path == nameof(MetadataRow.HiddenScore))
                                       .ShouldBeAssignableTo<IDataMemberAccessorMetadataProvider>()
                                       .Metadata;
        hiddenMetadata.AutoGenerateField.ShouldBe(false);

        var readOnlyMetadata = descriptor.Accessors.Single(accessor => accessor.Path == nameof(MetadataRow.ReadOnlyScore))
                                         .ShouldBeAssignableTo<IDataMemberAccessorMetadataProvider>()
                                         .Metadata;
        readOnlyMetadata.IsReadOnly.ShouldBeTrue();

        var nonEditableMetadata = descriptor.Accessors.Single(accessor => accessor.Path == nameof(MetadataRow.NonEditableScore))
                                            .ShouldBeAssignableTo<IDataMemberAccessorMetadataProvider>()
                                            .Metadata;
        nonEditableMetadata.IsEditable.ShouldBeFalse();
    }

    [Fact]
    public void LocalSourceSchemaIsAvailableForAnEmptyTypedSource()
    {
        var field = new DataGridFieldId("visible-score");
        var descriptor = DataGridLocalSourceDescriptor.For<MetadataRow>(
                static row => DataGridRowKey.FromInt64(row.VisibleScore))
            .Field(field, static row => row.VisibleScore);
        using var source = DataGridLocalSource.Create(Array.Empty<MetadataRow>(), descriptor);

        source.Schema.ItemType.ShouldBe(typeof(MetadataRow));
        source.Schema.Fields.Length.ShouldBe(1);
        source.Schema.Fields[0].Id.ShouldBe(field);
        source.Schema.Fields[0].ValueType.ShouldBe(typeof(int));
        var displayAccessor = source.Schema.Fields[0].DisplayAccessor.ShouldNotBeNull();
        displayAccessor.ItemType.ShouldBe(typeof(MetadataRow));
        displayAccessor.ValueType.ShouldBe(typeof(int));
        displayAccessor.PropertyChangedName.ShouldBeNull();
        displayAccessor.GetValue(new MetadataRow { VisibleScore = 42 }).ShouldBe(42);
    }

    [Fact]
    public void FieldIdIsNotUsedAsAPropertyChangedName()
    {
        var field = new DataGridFieldId("protocol-visible-score");
        var descriptor = DataGridLocalSourceDescriptor.For<MetadataRow>(
                static row => DataGridRowKey.FromInt64(row.VisibleScore))
            .Field(
                field,
                static row => row.VisibleScore,
                propertyChangedName: nameof(MetadataRow.VisibleScore));
        using var source = DataGridLocalSource.Create(Array.Empty<MetadataRow>(), descriptor);

        var displayAccessor = source.Schema.Fields[0].DisplayAccessor.ShouldNotBeNull();
        displayAccessor.PropertyChangedName.ShouldBe(nameof(MetadataRow.VisibleScore));
        displayAccessor.PropertyChangedName.ShouldNotBe(field.Value);
    }

    [Fact]
    public void AutoGeneratedFieldBindingIsCompiledAndReleasesPropertyChangedSubscription()
    {
        var row = new TrackingRow { Name = "before" };
        var accessor = DataGridFieldDisplayAccessor.Create<TrackingRow, string?>(
            static item => item.Name,
            propertyChangedName: nameof(TrackingRow.Name));
        var field = new DataGridFieldSchema(
            new DataGridFieldId("server-name"),
            typeof(string),
            DataGridSortDirections.None,
            [],
            canGroup: false,
            displayAccessor: accessor);
        var binding = AtomUI.Desktop.Controls.DataGrid.CreateAutoGeneratedColumnBinding(field);

        binding.ShouldBeOfType<CompiledBindingExtension>();
        var target = new TextBlock { DataContext = row };
        using (target.Bind(TextBlock.TextProperty, binding))
        {
            target.Text.ShouldBe("before");
            row.SubscriptionCount.ShouldBe(1);
            row.Name = "after";
            target.Text.ShouldBe("after");
        }
        row.SubscriptionCount.ShouldBe(0);
    }

    [Fact]
    public void AutoGenerateColumnsUsesOnlyTheSchemaDisplayAccessor()
    {
        var descriptor = DataGridLocalSourceDescriptor.For<MetadataRow>(
                static row => DataGridRowKey.FromInt64(row.VisibleScore))
            .Field(
                "protocol-visible-score",
                static row => row.VisibleScore,
                propertyChangedName: nameof(MetadataRow.VisibleScore));
        using var source = DataGridLocalSource.Create(
            new[] { new MetadataRow { VisibleScore = 42 } },
            descriptor);
        var grid = new AtomUI.Desktop.Controls.DataGrid
        {
            AutoGenerateColumns = true,
            ItemsSource = source
        };
        var window = new Window { Width = 360, Height = 240, Content = grid };

        try
        {
            window.Show();
            Dispatcher.UIThread.RunJobs();
            window.UpdateLayout();
            Dispatcher.UIThread.RunJobs();

            grid.Columns.Count.ShouldBe(1);
            var column = grid.Columns[0].ShouldBeAssignableTo<DataGridBoundColumn>();
            column.FieldId.ShouldBe(new DataGridFieldId("protocol-visible-score"));
            column.Binding.ShouldBeOfType<CompiledBindingExtension>();
        }
        finally
        {
            window.Close();
            Dispatcher.UIThread.RunJobs();
        }
    }

    [Fact]
    public void DataGridBoundColumnAppliesDefaultModeAndConverterToCompiledBindingExtension()
    {
        var binding = CreateCompiledBindingExtension(nameof(SampleRow.Name));
        var column = new DataGridTextColumn { Binding = binding };

        column.Binding.ShouldBeSameAs(binding);
        binding.Mode.ShouldBe(BindingMode.TwoWay);
        binding.Converter.ShouldBeSameAs(DataGridValueConverter.Instance);
    }

    [Fact]
    public void DataGridBoundColumnRejectsOneWayToSourceCompiledBindingExtension()
    {
        var binding = CreateCompiledBindingExtension(nameof(SampleRow.Name));
        binding.Mode = BindingMode.OneWayToSource;

        Should.Throw<InvalidOperationException>(() =>
            new DataGridTextColumn { Binding = binding });
    }

    private static CompiledBindingExtension CreateCompiledBindingExtension(string propertyName)
    {
        var pathBuilder = new CompiledBindingPathBuilder();
        var property = new ClrPropertyInfo(
            propertyName,
            target => ((SampleRow)target).Name,
            (target, value) => ((SampleRow)target).Name = (string?)value,
            typeof(string));
        pathBuilder.Property(property, static (_, _) => throw new NotSupportedException());
        return new CompiledBindingExtension(pathBuilder.Build());
    }

    [GenerateDataMemberAccessors]
    public partial class SampleRow
    {
        public string? Name { get; set; }

        public int? Score { get; set; }
    }

    [GenerateDataMemberAccessors]
    [ReadOnly(true)]
    public partial class MetadataRow
    {
        [Display(ShortName = "Visible score", AutoGenerateField = true, Order = 2)]
        public int VisibleScore { get; set; }

        [Display(AutoGenerateField = false)]
        public int HiddenScore { get; set; }

        [ReadOnly(true)]
        public int ReadOnlyScore { get; set; }

        [Editable(false)]
        public int NonEditableScore { get; set; }
    }

    private sealed class TrackingRow : INotifyPropertyChanged
    {
        private string? _name;
        private PropertyChangedEventHandler? _propertyChanged;

        public int SubscriptionCount { get; private set; }

        public string? Name
        {
            get => _name;
            set
            {
                _name = value;
                _propertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Name)));
            }
        }

        public event PropertyChangedEventHandler? PropertyChanged
        {
            add
            {
                _propertyChanged += value;
                SubscriptionCount++;
            }
            remove
            {
                _propertyChanged -= value;
                SubscriptionCount--;
            }
        }
    }
}
