<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(AtomUITargetFrameworks)</TargetFrameworks>
        <Nullable>enable</Nullable>
        <RootNamespace>AtomUI.Toolkits.GalleryBase</RootNamespace>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>GeneratedFiles</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <Compile Remove="$(CompilerGeneratedFilesOutputPath)/**/*.cs"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
        <PackageReference Include="Avalonia.AvaloniaEdit" />
        <PackageReference Include="AvaloniaEdit.TextMate" />
        <PackageReference Include="ReactiveUI.Avalonia" />
        <PackageReference Include="TextMateSharp.Grammars" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../AtomUI.Desktop.Controls/AtomUI.Desktop.Controls.csproj" />
        <ProjectReference Include="../AtomUI.Generator/AtomUI.Generator.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"
                          PrivateAssets="all" />
    </ItemGroup>

</Project>
