// <auto-generated />
#nullable enable
using System.Runtime.CompilerServices;

namespace AtomUI.Controls.Data.Generated
{
    internal static class DataMemberAccessorRegistration_global__AtomUIGallery_ShowCases_DataGrid_DataGridBaseInfo
    {
        [ModuleInitializer]
        internal static void Register()
        {
            global::AtomUI.Controls.Data.DataMemberAccessorRegistry.Register(
                new global::AtomUI.Controls.Data.DataMemberAccessorDescriptor<global::AtomUIGallery.ShowCases.DataGrid.DataGridBaseInfo>(
                    static () => new global::AtomUIGallery.ShowCases.DataGrid.DataGridBaseInfo(),
                    new global::AtomUI.Controls.Data.IDataMemberAccessor[]
                    {
                        new global::AtomUI.Controls.Data.DataMemberAccessor<global::AtomUIGallery.ShowCases.DataGrid.DataGridBaseInfo, string>("Key", static instance => instance.Key, static (instance, value) => instance.Key = value, metadata: global::AtomUI.Controls.Data.DataMemberAccessorMetadata.Default),
                        new global::AtomUI.Controls.Data.DataMemberAccessor<global::AtomUIGallery.ShowCases.DataGrid.DataGridBaseInfo, string>("Name", static instance => instance.Name, static (instance, value) => instance.Name = value, metadata: global::AtomUI.Controls.Data.DataMemberAccessorMetadata.Default),
                        new global::AtomUI.Controls.Data.DataMemberAccessor<global::AtomUIGallery.ShowCases.DataGrid.DataGridBaseInfo, int>("Age", static instance => instance.Age, static (instance, value) => instance.Age = value, metadata: global::AtomUI.Controls.Data.DataMemberAccessorMetadata.Default),
                        new global::AtomUI.Controls.Data.DataMemberAccessor<global::AtomUIGallery.ShowCases.DataGrid.DataGridBaseInfo, string>("Address", static instance => instance.Address, static (instance, value) => instance.Address = value, metadata: global::AtomUI.Controls.Data.DataMemberAccessorMetadata.Default),
                        new global::AtomUI.Controls.Data.DataMemberAccessor<global::AtomUIGallery.ShowCases.DataGrid.DataGridBaseInfo, string>("Money", static instance => instance.Money, static (instance, value) => instance.Money = value, metadata: global::AtomUI.Controls.Data.DataMemberAccessorMetadata.Default),
                        new global::AtomUI.Controls.Data.DataMemberAccessor<global::AtomUIGallery.ShowCases.DataGrid.DataGridBaseInfo, global::System.Collections.Generic.List<global::AtomUIGallery.ShowCases.DataGrid.TagInfo>>("Tags", static instance => instance.Tags, static (instance, value) => instance.Tags = value, metadata: global::AtomUI.Controls.Data.DataMemberAccessorMetadata.Default),
                    },
                    false));
        }
    }
}
