using AtomUI.Localization;

namespace AtomUIGallery.Localization;

[LanguageCatalog(ContractVersion = 1)]
public enum AlertShowCaseLangResourceKind
{
    BasicTitle = 1,
    BasicDescription = 2,
    MoreTypesTitle = 3,
    MoreTypesDescription = 4,
    ClosableTitle = 5,
    ClosableDescription = 6,
    DescriptionTitle = 7,
    DescriptionDescription = 8,
    IconTitle = 9,
    IconDescription = 10,
    CustomActionTitle = 11,
    CustomActionDescription = 12,
    LoopBannerTitle = 13,
    LoopBannerDescription = 14,
    PageSubtitle = 15,
    PageDescription = 16,
    ComponentCategory = 17,
    ComponentStatusStable = 18,
    ScenarioExamples = 19,
    ApiEventCloseRequest = 20,
    P2DescriptionErrorDescriptionErrorDescriptionErrorDescriptionErrorDesc = 21,
    P2DescriptionSuccessDescriptionSuccessDescriptionSuccessDescription = 22,
    P2DescriptionInfoDescriptionInfoDescriptionInfoDescriptionInfoDescript = 23,
    P2DescriptionWarningDescriptionWarningDescriptionWarningDescriptionWar = 24,
    P2DescriptionErrorDescriptionErrorDescriptionErrorDescriptionErrorDesc2 = 25,
    P2DescriptionDetailedDescriptionAndAdviceAboutSuccessfulCopywriting = 26,
    P2DescriptionAdditionalDescriptionAndInformationAboutCopywriting = 27,
    P2DescriptionThisIsAWarningNoticeAboutCopywriting = 28,
    P2DescriptionThisIsAnErrorMessageAboutCopywriting = 29,
    P2ContentSuccessText = 30,
    P2ContentInfoText = 31,
    P2ContentWarningText = 32,
    P2ContentErrorText = 33,
    P2ContentWarningTextWarningTextWarningTextWarningText = 34,
    P2ContentUndo = 35,
    P2ContentDetail = 36,
    P2ContentDone = 37,
    P2ContentAccept = 38,
    P2ContentDecline = 39,
    P2ContentICanBeAReactComponentMultipleReact = 40,
    P2MessageSuccessText = 41,
    P2MessageInfoText = 42,
    P2MessageWarningText = 43,
    P2MessageErrorText = 44,
    P2MessageSuccessTips = 45,
    P2MessageInformationalNotes = 46,
    P2MessageWarning = 47,
    P2MessageError = 48
}
