using AtomUI.Localization;

namespace AtomUIGallery.Localization;

[LanguageCatalog(ContractVersion = 2)]
public enum AlertShowCaseLangResourceKind
{
    BasicTitle,
    BasicDescription,
    MoreTypesTitle,
    MoreTypesDescription,
    ClosableTitle,
    ClosableDescription,
    DescriptionTitle,
    DescriptionDescription,
    IconTitle,
    IconDescription,
    CustomActionTitle,
    CustomActionDescription,
    LoopBannerTitle,
    LoopBannerDescription,
    PageSubtitle,
    PageDescription,
    ComponentCategory,
    ComponentStatusStable,
    ScenarioExamples,
    ApiEventCloseRequest,
    P2DescriptionErrorDescriptionErrorDescriptionErrorDescriptionErrorDesc,
    P2DescriptionSuccessDescriptionSuccessDescriptionSuccessDescription,
    P2DescriptionInfoDescriptionInfoDescriptionInfoDescriptionInfoDescript,
    P2DescriptionWarningDescriptionWarningDescriptionWarningDescriptionWar,
    P2DescriptionErrorDescriptionErrorDescriptionErrorDescriptionErrorDesc2,
    P2DescriptionDetailedDescriptionAndAdviceAboutSuccessfulCopywriting,
    P2DescriptionAdditionalDescriptionAndInformationAboutCopywriting,
    P2DescriptionThisIsAWarningNoticeAboutCopywriting,
    P2DescriptionThisIsAnErrorMessageAboutCopywriting,
    P2ContentSuccessText,
    P2ContentInfoText,
    P2ContentWarningText,
    P2ContentErrorText,
    P2ContentWarningTextWarningTextWarningTextWarningText,
    P2ContentUndo,
    P2ContentDetail,
    P2ContentDone,
    P2ContentAccept,
    P2ContentDecline,
    P2ContentICanBeAReactComponentMultipleReact,
    P2MessageSuccessText,
    P2MessageInfoText,
    P2MessageWarningText,
    P2MessageErrorText,
    P2MessageSuccessTips,
    P2MessageInformationalNotes,
    P2MessageWarning,
    P2MessageError
}
