using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.Collapse;

[LanguageProvider(LanguageCode.en_US, CollapseShowCase.LanguageId)]
internal partial class en_US
{
    public const string ScenarioExamples = "Examples";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "Design Token";
    public const string ComponentCategory = "Data Display";
    public const string ComponentStatusStable = ".NET 10";
    public const string PageSubtitle = "Stack related content sections that can expand or collapse independently.";
    public const string PageDescription = "Collapse organizes dense information into panels. It supports accordion behavior, nested panels, borderless and ghost styles, custom spacing, icon placement, and icon-only trigger mode.";
    public const string ApiColumnProperty = "Property";
    public const string ApiColumnDescription = "Description";
    public const string ApiColumnType = "Type";
    public const string ApiColumnDefault = "Default";
    public const string ApiPropertySizeType = "Controls header and content density.";
    public const string ApiPropertyIsGhostStyle = "Removes the panel surface background for a ghost presentation.";
    public const string ApiPropertyIsBorderless = "Removes the outer border while keeping panel structure.";
    public const string ApiPropertyIsAccordion = "Allows only one panel to be expanded at a time.";
    public const string ApiPropertyTriggerType = "Controls whether the header or only the icon toggles expansion.";
    public const string ApiPropertyExpandIconPosition = "Places the expand icon before or after the header content.";
    public const string ApiPropertyIsMotionEnabled = "Controls expand and collapse motion.";
    public const string ApiPropertyItemHeaderPadding = "Applies header padding to generated collapse items.";
    public const string ApiPropertyItemContentPadding = "Applies content padding to generated collapse items.";
    public const string ApiPropertyIsSelected = "Controls whether a collapse item is expanded.";
    public const string ApiPropertyIsShowExpandIcon = "Controls whether a collapse item shows its expand icon.";
    public const string ApiPropertyExpandIcon = "Custom expand icon for an individual item.";
    public const string ApiPropertyAddOnContent = "Additional content rendered in the item header.";
    public const string ApiPropertyAddOnContentTemplate = "Template used to render item add-on content.";
    public const string ApiPropertyHeaderPadding = "Overrides header padding for an individual item.";
    public const string ApiPropertyContentPadding = "Overrides content padding for an individual item.";
    public const string TokenColumnToken = "Token";
    public const string TokenColumnDescription = "Description";
    public const string TokenColumnScope = "Scope";
    public const string TokenColumnStatus = "Status";
    public const string TokenNameHeaderPadding = "Default collapse header padding.";
    public const string TokenNameHeaderBg = "Default collapse header background.";
    public const string TokenNameContentPadding = "Default collapse content padding.";
    public const string TokenNameContentBg = "Default collapse content background.";
    public const string TokenNameCollapseHeaderPaddingSM = "Small size collapse header padding.";
    public const string TokenNameCollapseHeaderPaddingLG = "Large size collapse header padding.";
    public const string TokenNameCollapseContentPaddingSM = "Small size collapse content padding.";
    public const string TokenNameCollapseContentPaddingLG = "Large size collapse content padding.";
    public const string TokenNameCollapsePanelBorderRadius = "Panel border radius.";
    public const string TokenNameLeftExpandButtonMargin = "Margin used when the expand icon is on the left.";
    public const string TokenNameRightExpandButtonMargin = "Margin used when the expand icon is on the right.";
    public const string TokenScopeComponent = "Component";
    public const string TokenStatusStable = "Stable";
    public const string ScenarioBasic = "Basic";
    public const string ScenarioAppearance = "Appearance";
    public const string ScenarioBehavior = "Behavior";
    public const string CollapseTitle = "Collapse";
    public const string CollapseDescription = "By default, any number of panels can be expanded at a time. The first panel is expanded in this example.";
    public const string SizeTitle = "Size";
    public const string SizeDescription = "Ant Design supports a default collapse size as well as a large and small size. If a large or small collapse is desired, set the size property to either large or small respectively. Omit the size property for a collapse with the default size.";
    public const string AccordionTitle = "Accordion";
    public const string AccordionDescription = "In accordion mode, only one panel can be expanded at a time.";
    public const string NestedPanelTitle = "Nested panel";
    public const string NestedPanelDescription = "Collapse is nested inside the Collapse.";
    public const string BorderlessTitle = "Borderless";
    public const string BorderlessDescription = "A borderless style of Collapse.";
    public const string NoArrowTitle = "No Arrow";
    public const string NoArrowDescription = "You can hide the arrow icon by passing IsShowExpandIcon={False} to CollapsePanel component.";
    public const string ExpandIconLocationTitle = "Expand icon location";
    public const string ExpandIconLocationDescription = "The expand icon can be placed in front or in the back.";
    public const string GhostCollapseTitle = "Ghost Collapse";
    public const string GhostCollapseDescription = "Making collapse's background to transparent.";
    public const string CollapsibleTitle = "Collapsible";
    public const string CollapsibleDescription = "Specify the trigger area of collapsible by collapsible.";
    public const string CustomPaddingTitle = "Custom Header And Content Padding";
    public const string CustomPaddingDescription = "Please set custom header margins and content spacing.";
    public const string P2HeaderThisIsPanelHeaderN1 = "This is panel header 1";
    public const string P2HeaderThisIsPanelHeaderN2 = "This is panel header 2";
    public const string P2HeaderThisIsPanelHeaderN3 = "This is panel header 3";
    public const string P2TitleDefaultSize = "Default Size";
    public const string P2HeaderThisIsDefaultSizePanelHeader = "This is default size panel header";
    public const string P2TitleSmallSize = "Small Size";
    public const string P2HeaderThisIsSmallSizePanelHeader = "This is small size panel header";
    public const string P2TitleLargeSize = "Large Size";
    public const string P2HeaderThisIsLargeSizePanelHeader = "This is large size panel header";
    public const string P2HeaderThisPanelCanOnlyBeCollapsedByClicking = "This panel can only be collapsed by clicking text";
    public const string P2HeaderThisPanelCanOnlyBeCollapsedByClicking2 = "This panel can only be collapsed by clicking icon";
    public const string P2HeaderThisPanelCanTBeCollapsed = "This panel can't be collapsed";
    public const string P2TextADogIsATypeOfDomesticatedAnimal = "A dog is a type of domesticated animal. Known for its loyalty and faithfulness, it can be found as a welcome guest in many households across the world.";
    public const string P2TextExpandIconPosition = "Expand Icon Position:";
    public const string P2ContentStart = "Start";
    public const string P2ContentEnd = "End";

}
