using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.Collapse;

[LanguageProvider(LanguageCode.zh_CN, CollapseShowCase.LanguageId)]
internal partial class zh_CN : LanguageProvider
{
    public const string ScenarioExamples = "示例";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "设计变量";
    public const string ComponentCategory = "数据展示";
    public const string ComponentStatusStable = ".NET 10";
    public const string PageSubtitle = "将相关内容组织成可独立展开和收起的面板。";
    public const string PageDescription = "Collapse 用于把密集信息分组到多个面板中，支持手风琴、嵌套面板、无边框与幽灵样式、自定义间距、图标位置和仅图标触发展开。";
    public const string InfoNamespaceLabel = "命名空间:";
    public const string InfoPackageLabel = "包:";
    public const string InfoBaseClassLabel = "基类:";
    public const string ApiColumnProperty = "属性";
    public const string ApiColumnDescription = "说明";
    public const string ApiColumnType = "类型";
    public const string ApiColumnDefault = "默认值";
    public const string ApiPropertySizeType = "控制标题和内容区域的密度。";
    public const string ApiPropertyIsGhostStyle = "移除面板表面背景，呈现幽灵样式。";
    public const string ApiPropertyIsBorderless = "移除外边框，同时保留面板结构。";
    public const string ApiPropertyIsAccordion = "同一时间只允许展开一个面板。";
    public const string ApiPropertyTriggerType = "控制点击标题区域或仅点击图标触发展开。";
    public const string ApiPropertyExpandIconPosition = "将展开图标放在标题内容前方或后方。";
    public const string ApiPropertyIsMotionEnabled = "控制展开和收起动效。";
    public const string ApiPropertyItemHeaderPadding = "应用到生成的折叠项标题内边距。";
    public const string ApiPropertyItemContentPadding = "应用到生成的折叠项内容内边距。";
    public const string ApiPropertyIsSelected = "控制折叠项是否展开。";
    public const string ApiPropertyIsShowExpandIcon = "控制折叠项是否显示展开图标。";
    public const string ApiPropertyExpandIcon = "单个折叠项的自定义展开图标。";
    public const string ApiPropertyAddOnContent = "渲染在折叠项标题中的额外内容。";
    public const string ApiPropertyAddOnContentTemplate = "用于渲染折叠项额外内容的模板。";
    public const string ApiPropertyHeaderPadding = "覆盖单个折叠项的标题内边距。";
    public const string ApiPropertyContentPadding = "覆盖单个折叠项的内容内边距。";
    public const string TokenColumnToken = "变量";
    public const string TokenColumnDescription = "说明";
    public const string TokenColumnScope = "作用域";
    public const string TokenColumnStatus = "状态";
    public const string TokenNameHeaderPadding = "折叠面板标题默认内边距。";
    public const string TokenNameHeaderBg = "折叠面板标题默认背景。";
    public const string TokenNameContentPadding = "折叠面板内容默认内边距。";
    public const string TokenNameContentBg = "折叠面板内容默认背景。";
    public const string TokenNameCollapseHeaderPaddingSM = "小尺寸折叠面板标题内边距。";
    public const string TokenNameCollapseHeaderPaddingLG = "大尺寸折叠面板标题内边距。";
    public const string TokenNameCollapseContentPaddingSM = "小尺寸折叠面板内容内边距。";
    public const string TokenNameCollapseContentPaddingLG = "大尺寸折叠面板内容内边距。";
    public const string TokenNameCollapsePanelBorderRadius = "面板圆角。";
    public const string TokenNameLeftExpandButtonMargin = "展开图标位于左侧时的外边距。";
    public const string TokenNameRightExpandButtonMargin = "展开图标位于右侧时的外边距。";
    public const string TokenScopeComponent = "组件";
    public const string TokenStatusStable = "稳定";
    public const string ScenarioBasic = "基础";
    public const string ScenarioAppearance = "外观";
    public const string ScenarioBehavior = "行为";
    public const string CollapseTitle = "折叠面板";
    public const string CollapseDescription = "默认情况下，可以同时展开任意数量的面板。本示例中第一个面板处于展开状态。";
    public const string SizeTitle = "尺寸";
    public const string SizeDescription = "Ant Design 支持默认、大号和小号三种折叠面板尺寸。需要大号或小号时分别设置 size 属性；省略 size 属性时使用默认尺寸。";
    public const string AccordionTitle = "手风琴";
    public const string AccordionDescription = "在手风琴模式下，同一时间只能展开一个面板。";
    public const string NestedPanelTitle = "嵌套面板";
    public const string NestedPanelDescription = "在 Collapse 内嵌套 Collapse。";
    public const string BorderlessTitle = "无边框";
    public const string BorderlessDescription = "无边框样式的 Collapse。";
    public const string NoArrowTitle = "隐藏箭头";
    public const string NoArrowDescription = "可以向 CollapsePanel 传入 IsShowExpandIcon={False} 来隐藏箭头图标。";
    public const string ExpandIconLocationTitle = "展开图标位置";
    public const string ExpandIconLocationDescription = "展开图标可以放在前方或后方。";
    public const string GhostCollapseTitle = "幽灵折叠面板";
    public const string GhostCollapseDescription = "让 Collapse 的背景透明。";
    public const string CollapsibleTitle = "可折叠触发区域";
    public const string CollapsibleDescription = "通过 collapsible 指定折叠触发区域。";
    public const string CustomPaddingTitle = "自定义标题和内容间距";
    public const string CustomPaddingDescription = "请设置自定义标题边距和内容间距。";
    public const string P2HeaderThisIsPanelHeaderN1 = "这是面板标题 1";
    public const string P2HeaderThisIsPanelHeaderN2 = "这是面板标题 2";
    public const string P2HeaderThisIsPanelHeaderN3 = "这是面板标题 3";
    public const string P2TitleDefaultSize = "默认尺寸";
    public const string P2HeaderThisIsDefaultSizePanelHeader = "这是默认尺寸面板标题";
    public const string P2TitleSmallSize = "小尺寸";
    public const string P2HeaderThisIsSmallSizePanelHeader = "这是小尺寸面板标题";
    public const string P2TitleLargeSize = "大尺寸";
    public const string P2HeaderThisIsLargeSizePanelHeader = "这是大尺寸面板标题";
    public const string P2HeaderThisPanelCanOnlyBeCollapsedByClicking = "只能点击文字折叠此面板";
    public const string P2HeaderThisPanelCanOnlyBeCollapsedByClicking2 = "只能点击图标折叠此面板";
    public const string P2HeaderThisPanelCanTBeCollapsed = "此面板不能折叠";
    public const string P2TextADogIsATypeOfDomesticatedAnimal = "狗是一种被驯养的动物。它以忠诚和可靠著称，在世界各地许多家庭中都是受欢迎的成员。";
    public const string P2TextExpandIconPosition = "展开图标位置：";
    public const string P2ContentStart = "开始";
    public const string P2ContentEnd = "结束";

    protected override Type GetResourceKindType() => typeof(CollapseShowCaseLangResourceKind);
}
