using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.Collapse;

[LanguageProvider(LanguageCode.zh_TW, CollapseShowCase.LanguageId)]
internal partial class zh_TW : LanguageProvider
{
    public const string ScenarioExamples = "示例";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "設計變量";
    public const string ComponentCategory = "數據展示";
    public const string ComponentStatusStable = ".NET 10";
    public const string PageSubtitle = "將相關內容組織成可獨立展開和收起的面板。";
    public const string PageDescription = "Collapse 用於把密集信息分組到多個面板中，支持手風琴、嵌套面板、無邊框與幽靈樣式、自定義間距、圖標位置和僅圖標觸發展開。";
    public const string ApiColumnProperty = "屬性";
    public const string ApiColumnDescription = "說明";
    public const string ApiColumnType = "類型";
    public const string ApiColumnDefault = "默認值";
    public const string ApiPropertySizeType = "控制標題和內容區域的密度。";
    public const string ApiPropertyIsGhostStyle = "移除面板表面背景，呈現幽靈樣式。";
    public const string ApiPropertyIsBorderless = "移除外邊框，同時保留面板結構。";
    public const string ApiPropertyIsAccordion = "同一時間只允許展開一個面板。";
    public const string ApiPropertyTriggerType = "控制點擊標題區域或僅點擊圖標觸發展開。";
    public const string ApiPropertyExpandIconPosition = "將展開圖標放在標題內容前方或後方。";
    public const string ApiPropertyIsMotionEnabled = "控制展開和收起動效。";
    public const string ApiPropertyItemHeaderPadding = "應用到生成的折疊項標題內邊距。";
    public const string ApiPropertyItemContentPadding = "應用到生成的折疊項內容內邊距。";
    public const string ApiPropertyIsSelected = "控制折疊項是否展開。";
    public const string ApiPropertyIsShowExpandIcon = "控制折疊項是否顯示展開圖標。";
    public const string ApiPropertyExpandIcon = "單個折疊項的自定義展開圖標。";
    public const string ApiPropertyAddOnContent = "渲染在折疊項標題中的額外內容。";
    public const string ApiPropertyAddOnContentTemplate = "用於渲染折疊項額外內容的模板。";
    public const string ApiPropertyHeaderPadding = "覆蓋單個折疊項的標題內邊距。";
    public const string ApiPropertyContentPadding = "覆蓋單個折疊項的內容內邊距。";
    public const string TokenColumnToken = "變量";
    public const string TokenColumnDescription = "說明";
    public const string TokenColumnScope = "作用域";
    public const string TokenColumnStatus = "狀態";
    public const string TokenNameHeaderPadding = "折疊面板標題默認內邊距。";
    public const string TokenNameHeaderBg = "折疊面板標題默認背景。";
    public const string TokenNameContentPadding = "折疊面板內容默認內邊距。";
    public const string TokenNameContentBg = "折疊面板內容默認背景。";
    public const string TokenNameCollapseHeaderPaddingSM = "小尺寸折疊面板標題內邊距。";
    public const string TokenNameCollapseHeaderPaddingLG = "大尺寸折疊面板標題內邊距。";
    public const string TokenNameCollapseContentPaddingSM = "小尺寸折疊面板內容內邊距。";
    public const string TokenNameCollapseContentPaddingLG = "大尺寸折疊面板內容內邊距。";
    public const string TokenNameCollapsePanelBorderRadius = "面板圓角。";
    public const string TokenNameLeftExpandButtonMargin = "展開圖標位於左側時的外邊距。";
    public const string TokenNameRightExpandButtonMargin = "展開圖標位於右側時的外邊距。";
    public const string TokenScopeComponent = "組件";
    public const string TokenStatusStable = "穩定";
    public const string ScenarioBasic = "基礎";
    public const string ScenarioAppearance = "外觀";
    public const string ScenarioBehavior = "行為";
    public const string CollapseTitle = "折疊面板";
    public const string CollapseDescription = "默認情況下，可以同時展開任意數量的面板。本示例中第一個面板處於展開狀態。";
    public const string SizeTitle = "尺寸";
    public const string SizeDescription = "Ant Design 支持默認、大號和小號三種折疊面板尺寸。需要大號或小號時分別設置 size 屬性；省略 size 屬性時使用默認尺寸。";
    public const string AccordionTitle = "手風琴";
    public const string AccordionDescription = "在手風琴模式下，同一時間只能展開一個面板。";
    public const string NestedPanelTitle = "嵌套面板";
    public const string NestedPanelDescription = "在 Collapse 內嵌套 Collapse。";
    public const string BorderlessTitle = "無邊框";
    public const string BorderlessDescription = "無邊框樣式的 Collapse。";
    public const string NoArrowTitle = "隱藏箭頭";
    public const string NoArrowDescription = "可以向 CollapsePanel 傳入 IsShowExpandIcon={False} 來隱藏箭頭圖標。";
    public const string ExpandIconLocationTitle = "展開圖標位置";
    public const string ExpandIconLocationDescription = "展開圖標可以放在前方或後方。";
    public const string GhostCollapseTitle = "幽靈折疊面板";
    public const string GhostCollapseDescription = "讓 Collapse 的背景透明。";
    public const string CollapsibleTitle = "可折疊觸發區域";
    public const string CollapsibleDescription = "通過 collapsible 指定折疊觸發區域。";
    public const string CustomPaddingTitle = "自定義標題和內容間距";
    public const string CustomPaddingDescription = "請設置自定義標題邊距和內容間距。";
    public const string P2HeaderThisIsPanelHeaderN1 = "這是面板標題 1";
    public const string P2HeaderThisIsPanelHeaderN2 = "這是面板標題 2";
    public const string P2HeaderThisIsPanelHeaderN3 = "這是面板標題 3";
    public const string P2TitleDefaultSize = "默認尺寸";
    public const string P2HeaderThisIsDefaultSizePanelHeader = "這是默認尺寸面板標題";
    public const string P2TitleSmallSize = "小尺寸";
    public const string P2HeaderThisIsSmallSizePanelHeader = "這是小尺寸面板標題";
    public const string P2TitleLargeSize = "大尺寸";
    public const string P2HeaderThisIsLargeSizePanelHeader = "這是大尺寸面板標題";
    public const string P2HeaderThisPanelCanOnlyBeCollapsedByClicking = "只能點擊文字折疊此面板";
    public const string P2HeaderThisPanelCanOnlyBeCollapsedByClicking2 = "只能點擊圖標折疊此面板";
    public const string P2HeaderThisPanelCanTBeCollapsed = "此面板不能折疊";
    public const string P2TextADogIsATypeOfDomesticatedAnimal = "狗是一種被馴養的動物。它以忠誠和可靠著稱，在世界各地許多家庭中都是受歡迎的成員。";
    public const string P2TextExpandIconPosition = "展開圖標位置：";
    public const string P2ContentStart = "開始";
    public const string P2ContentEnd = "結束";

    protected override Type GetResourceKindType() => typeof(CollapseShowCaseLangResourceKind);
}
