using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.LineEdit;

[LanguageProvider(LanguageCode.zh_CN, LineEditShowCase.LanguageId)]
internal partial class zh_CN
{
    public const string ScenarioBasic = "基础";
    public const string ScenarioState = "状态";
    public const string ScenarioSearch = "搜索";
    public const string ScenarioTextArea = "文本域";

    public const string BasicUsageTitle = "基础用法";
    public const string BasicUsageDescription = "基础用法示例。";
    public const string InputSizesTitle = "输入框三种尺寸";
    public const string InputSizesDescription = "输入框有三种尺寸：大号（40px）、默认（32px）和小号（24px）。";
    public const string VariantsTitle = "变体";
    public const string VariantsDescription = "输入框的变体。";
    public const string DisabledTitle = "禁用";
    public const string DisabledDescription = "输入框禁用样式的变体。";
    public const string PrePostTabTitle = "前置/后置标签";
    public const string PrePostTabDescription = "使用前置和后置标签的示例。";
    public const string WithClearIconTitle = "带清除图标";
    public const string WithClearIconDescription = "带移除图标的输入框，点击图标可清空全部内容。";
    public const string PasswordBoxTitle = "密码框";
    public const string PasswordBoxDescription = "密码类型输入框。";
    public const string PrefixAndSuffixTitle = "前缀和后缀";
    public const string PrefixAndSuffixDescription = "在输入框内部添加前缀或后缀图标。";
    public const string InputStatusTitle = "状态";
    public const string InputStatusDescription = "通过 status 为 Input 添加状态，可设置为错误或警告。";
    public const string SearchBoxTitle = "搜索框";
    public const string SearchBoxDescription = "将标准输入框和搜索按钮组合创建搜索框的示例。";
    public const string SearchEditSizeTypeTitle = "SearchEdit 尺寸";
    public const string SearchEditSizeTypeDescription = "SearchEdit 支持大号、中号、小号，也支持通过 Custom 配合本地高度和字号自定义。";
    public const string DisabledSearchBoxTitle = "禁用搜索框";
    public const string DisabledSearchBoxDescription = "将标准输入框和搜索按钮组合创建搜索框的示例。";
    public const string SearchBoxWithLoadingTitle = "带加载状态的搜索框";
    public const string SearchBoxWithLoadingDescription = "onSearch 时显示搜索加载状态。";
    public const string TextAreaTitle = "文本域";
    public const string TextAreaDescription = "用于多行输入。";
    public const string AutoSizeTextAreaTitle = "高度自适应内容";
    public const string AutoSizeTextAreaDescription = "textarea 类型 Input 的 autoSize 属性会让高度根据内容自动调整。可以向 autoSize 提供选项对象，指定自动调整的最小和最大行数。";
    public const string CharacterCountingTitle = "带字数统计";
    public const string CharacterCountingDescription = "显示字数统计。";
    public const string TextAreaStatusTitle = "状态";
    public const string TextAreaStatusDescription = "通过 status 为 TextArea 添加状态，可设置为错误或警告。";
    public const string P2PlaceholderTextBasicUsage = "基础用法";
    public const string P2PlaceholderTextLarge = "大号";
    public const string P2PlaceholderTextMiddle = "中号";
    public const string P2PlaceholderTextSmall = "小号";
    public const string P2PlaceholderTextCustom = "自定义";
    public const string P2TitleNormal = "普通";
    public const string P2PlaceholderTextOutlined = "线框风格";
    public const string P2PlaceholderTextFilled = "填充风格";
    public const string P2PlaceholderTextBorderless = "无边框";
    public const string P2PlaceholderTextUnderlined = "下划线";
    public const string P2TitleLeftaddonAndRightaddon = "左侧附加和右侧附加";
    public const string P2TextMysite = "我的站点";
    public const string P2PlaceholderTextInputWithClearIcon = "带清除图标的输入框";
    public const string P2PlaceholderTextTextareaWithClearIcon = "带清除图标的文本域";
    public const string P2PlaceholderTextInputPassword = "输入密码";
    public const string P2PlaceholderTextEnterYourUsername = "输入用户名";
    public const string P2PlaceholderTextError = "错误";
    public const string P2PlaceholderTextWarning = "警告";
    public const string P2PlaceholderTextErrorWithPrefix = "带前缀的错误";
    public const string P2PlaceholderTextWarningWithPrefix = "带前缀的警告";
    public const string P2TitleSearch = "搜索";
    public const string P2PlaceholderTextInputSearchText = "输入搜索文本";
    public const string P2TitleFilled = "填充风格";
    public const string P2TitleBorderless = "无边框";
    public const string P2TitleUnderlined = "下划线";
    public const string P2PlaceholderTextInputSearchLoadingDefault = "默认搜索加载";
    public const string P2PlaceholderTextInputSearchLoadingWithEnterbutton = "带搜索按钮的搜索加载";
    public const string P2PlaceholderTextMaxlengthIsN6 = "最大长度为 6";
    public const string P2PlaceholderTextDisabled = "禁用";
    public const string P2PlaceholderTextAutosizeHeightBasedOnContentLines = "根据内容行数自动调整高度";
    public const string P2PlaceholderTextAutosizeHeightWithMinimumAndMaximumNumberOf = "按最小和最大行数自动调整高度";
    public const string P2PlaceholderTextCanResize = "可调整大小";
    public const string P2PlaceholderTextDisableResize = "禁止调整大小";

    public const string P2SearchButtonTextSearch = "搜索";

    public const string P2SearchButtonTextText = "搜索一下";
    public const string PageSubtitle = "采集单行文本、搜索输入、密码和多行文本。";
    public const string PageDescription = "LineEdit 覆盖标准输入框、前后置附加、清除操作、密码显示、前缀后缀、校验状态、SearchEdit 和 TextArea 场景。";
    public const string ComponentCategory = "数据录入";
    public const string ComponentStatusStable = "稳定";
    public const string ScenarioExamples = "示例";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "设计变量";
    public const string ApiColumnProperty = "属性";
    public const string ApiColumnDescription = "说明";
    public const string ApiColumnType = "类型";
    public const string ApiColumnDefault = "默认值";
    public const string ApiPropertyPlaceholderText = "输入为空时显示的占位文本。";
    public const string ApiPropertyText = "当前可编辑文本值。";
    public const string ApiPropertyIsAllowClear = "文本可清除时显示清除按钮。";
    public const string ApiPropertySizeType = "设置输入框尺寸。";
    public const string ApiPropertyStyleVariant = "选择线框、填充、无边框或下划线表现。";
    public const string ApiPropertyStatus = "应用错误或警告等校验状态样式。";
    public const string ApiPropertyLeftAddOn = "输入框外框前置附加内容。";
    public const string ApiPropertyRightAddOn = "输入框外框后置附加内容。";
    public const string ApiPropertyInnerLeftContent = "输入框内部、文本区域之前渲染的内容。";
    public const string ApiPropertyInnerRightContent = "输入框内部、文本区域之后渲染的内容。";
    public const string ApiPropertyRevealPassword = "控制密码显示状态。";
    public const string ApiPropertySearchButtonStyle = "设置 SearchEdit 按钮样式。";
    public const string ApiPropertySearchButtonText = "SearchEdit 按钮显示文本。";
    public const string ApiPropertyIsOperating = "显示 SearchEdit 加载状态并防止重复搜索点击。";
    public const string ApiPropertyLines = "TextArea 初始可见行数。";
    public const string ApiPropertyIsAutoSize = "允许 TextArea 高度随内容增长。";
    public const string ApiPropertyIsShowCount = "显示当前字符数。";
    public const string ApiPropertyIsResizable = "允许 TextArea 手动调整大小。";
    public const string TokenColumnToken = "变量";
    public const string TokenColumnDescription = "说明";
    public const string TokenColumnScope = "作用域";
    public const string TokenColumnStatus = "状态";
    public const string TokenScopeComponent = "组件";
    public const string TokenStatusStable = "稳定";
    public const string TokenNameInputFontSize = "LineEdit 默认字体大小。";
    public const string TokenNameInputFontSizeLG = "LineEdit 大号字体大小。";
    public const string TokenNameInputFontSizeSM = "LineEdit 小号字体大小。";
    public const string TokenNameFontSize = "TextArea 默认字体大小。";
    public const string TokenNameFontSizeLG = "TextArea 大号字体大小。";
    public const string TokenNameFontSizeSM = "TextArea 小号字体大小。";
    public const string TokenNameResizeHandleSize = "TextArea 调整大小手柄尺寸。";
    public const string TokenNameResizeIndicatorLineColor = "TextArea 调整大小指示线颜色。";
    public const string TokenNameRightAddOnPadding = "TextArea 默认右侧附加内边距。";
    public const string TokenNameRightAddOnPaddingSM = "TextArea 小号右侧附加内边距。";
    public const string TokenNameRightAddOnPaddingLG = "TextArea 大号右侧附加内边距。";

}
