using AtomUI.Localization;

namespace AtomUIGallery.Localization;

[LanguageCatalog(ContractVersion = 1)]
public enum CardShowCaseLangResourceKind
{
    ScenarioExamples = 1,
    ComponentCategory = 2,
    ComponentStatusStable = 3,
    PageSubtitle = 4,
    PageDescription = 5,
    BasicTitle = 6,
    BasicDescription = 7,
    ScenarioBasic = 8,
    ScenarioLayout = 9,
    ScenarioAdvanced = 10,
    NoBorderTitle = 11,
    NoBorderDescription = 12,
    SimpleCardTitle = 13,
    SimpleCardDescription = 14,
    CustomizedContentTitle = 15,
    CustomizedContentDescription = 16,
    CardInColumnTitle = 17,
    CardInColumnDescription = 18,
    LoadingCardTitle = 19,
    LoadingCardDescription = 20,
    GridCardTitle = 21,
    GridCardDescription = 22,
    InnerCardTitle = 23,
    InnerCardDescription = 24,
    WithTabsTitle = 25,
    WithTabsDescription = 26,
    MoreContentConfigurationTitle = 27,
    MoreContentConfigurationDescription = 28,
    P2HeaderLargeSizeCard = 29,
    P2HeaderDefaultSizeCard = 30,
    P2HeaderSmallSizeCard = 31,
    P2HeaderCardTitle = 32,
    P2HeaderEuropeStreetBeat = 33,
    P2HeaderCardTitle2 = 34,
    P2HeaderTab1 = 35,
    P2HeaderTab2 = 36,
    P2HeaderArticle = 37,
    P2HeaderApp = 38,
    P2HeaderProject = 39,
    P2ContentMore = 40,
    P2TextCardContent = 41,
    P2TextThisIsTheDescription = 42,
    P2ContentContent = 43,
    P2ContentContent1 = 44,
    P2ContentContent2 = 45,
    P2ContentArticleContent = 46,
    P2ContentAppContent = 47,
    P2ContentProjectContent = 48,
    P2ContentThisIsTheDescription = 49
}
