using AtomUI.Localization;

namespace AtomUIGallery.Localization;

[LanguageCatalog(ContractVersion = 2)]
public enum CardShowCaseLangResourceKind
{
    ScenarioExamples,
    ComponentCategory,
    ComponentStatusStable,
    PageSubtitle,
    PageDescription,
    BasicTitle,
    BasicDescription,
    ScenarioBasic,
    ScenarioLayout,
    ScenarioAdvanced,
    NoBorderTitle,
    NoBorderDescription,
    SimpleCardTitle,
    SimpleCardDescription,
    CustomizedContentTitle,
    CustomizedContentDescription,
    CardInColumnTitle,
    CardInColumnDescription,
    LoadingCardTitle,
    LoadingCardDescription,
    GridCardTitle,
    GridCardDescription,
    InnerCardTitle,
    InnerCardDescription,
    WithTabsTitle,
    WithTabsDescription,
    MoreContentConfigurationTitle,
    MoreContentConfigurationDescription,
    P2HeaderLargeSizeCard,
    P2HeaderDefaultSizeCard,
    P2HeaderSmallSizeCard,
    P2HeaderCardTitle,
    P2HeaderEuropeStreetBeat,
    P2HeaderCardTitle2,
    P2HeaderTab1,
    P2HeaderTab2,
    P2HeaderArticle,
    P2HeaderApp,
    P2HeaderProject,
    P2ContentMore,
    P2TextCardContent,
    P2TextThisIsTheDescription,
    P2ContentContent,
    P2ContentContent1,
    P2ContentContent2,
    P2ContentArticleContent,
    P2ContentAppContent,
    P2ContentProjectContent,
    P2ContentThisIsTheDescription
}
