using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.Card;

[LanguageProvider(LanguageCode.en_US, CardShowCase.LanguageId)]
internal partial class en_US : LanguageProvider
{
    public const string ScenarioExamples = "Examples";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "Design Token";
    public const string ComponentCategory = "Data Display";
    public const string ComponentStatusStable = ".NET 10";
    public const string PageSubtitle = "Group related content and actions in a compact container.";
    public const string PageDescription = "Card presents information in a contained surface. It supports headers, extra actions, cover media, metadata, grid sections, tabs, loading placeholders, hover feedback, and borderless presentation.";
    public const string ApiColumnProperty = "Property";
    public const string ApiColumnDescription = "Description";
    public const string ApiColumnType = "Type";
    public const string ApiColumnDefault = "Default";
    public const string ApiPropertyExtra = "Additional content rendered in the card header action area.";
    public const string ApiPropertyExtraTemplate = "Template used to render the extra header content.";
    public const string ApiPropertyStyleVariant = "Controls whether the card is outlined or borderless.";
    public const string ApiPropertySizeType = "Controls card header and body density.";
    public const string ApiPropertyIsLoading = "Shows a loading placeholder while card content is unavailable.";
    public const string ApiPropertyIsInnerMode = "Renders the card as an inner card nested inside another card.";
    public const string ApiPropertyIsHoverable = "Enables hover affordance for clickable or selectable cards.";
    public const string ApiPropertyCover = "Content rendered above the card body as a cover area.";
    public const string ApiPropertyCoverTemplate = "Template used to render the cover content.";
    public const string ApiPropertyActions = "Action buttons rendered in the card footer action area.";
    public const string ApiPropertyBoxShadow = "Shadow used by hoverable and elevated card surfaces.";
    public const string ApiPropertyIsMotionEnabled = "Controls motion effects for supported card interactions.";
    public const string TokenColumnToken = "Token";
    public const string TokenColumnDescription = "Description";
    public const string TokenColumnScope = "Scope";
    public const string TokenColumnStatus = "Status";
    public const string TokenNameHeaderBg = "Card header background color.";
    public const string TokenNameHeaderFontSizeLG = "Header font size for large cards.";
    public const string TokenNameHeaderFontSize = "Header font size for default cards.";
    public const string TokenNameHeaderFontSizeSM = "Header font size for small cards.";
    public const string TokenNameHeaderHeightLG = "Header height for large cards.";
    public const string TokenNameHeaderHeight = "Header height for default cards.";
    public const string TokenNameHeaderHeightSM = "Header height for small cards.";
    public const string TokenNameBodyPadding = "Default padding inside the card body.";
    public const string TokenNameHeaderPadding = "Default padding inside the card header.";
    public const string TokenNameActionsBg = "Background color of the card action area.";
    public const string TokenNameActionsSpacing = "Spacing between card action items.";
    public const string TokenNameTabsMarginBottom = "Bottom margin used by tabs embedded in cards.";
    public const string TokenNameExtraColor = "Text color for the extra header area.";
    public const string TokenNameCardShadows = "Default shadow used by card surfaces.";
    public const string TokenNameCardActionsIconSize = "Icon size used by card action buttons.";
    public const string TokenNameCardGridItemShadows = "Border-like shadow used between grid card items.";
    public const string TokenScopeComponent = "Component";
    public const string TokenStatusStable = "Stable";
    public const string BasicTitle = "Basic";
    public const string BasicDescription = "A basic card containing a title, content and an extra corner content. Supports two sizes: default and small.";
    public const string ScenarioBasic = "Basic";
    public const string ScenarioLayout = "Layout";
    public const string ScenarioAdvanced = "Advanced";
    public const string NoBorderTitle = "No border";
    public const string NoBorderDescription = "A borderless card on a gray background.";
    public const string SimpleCardTitle = "Simple card";
    public const string SimpleCardDescription = "A simple card only containing a content area.";
    public const string CustomizedContentTitle = "Customized content";
    public const string CustomizedContentDescription = "You can use Card.Meta to support more flexible content.";
    public const string CardInColumnTitle = "Card in column";
    public const string CardInColumnDescription = "Cards usually cooperate with grid column layout in overview page.";
    public const string LoadingCardTitle = "Loading card";
    public const string LoadingCardDescription = "Shows a loading indicator while the contents of the card is being fetched.";
    public const string GridCardTitle = "Grid card";
    public const string GridCardDescription = "Grid style card content..";
    public const string InnerCardTitle = "Inner card";
    public const string InnerCardDescription = "It can be placed inside the ordinary card to display the information of the multilevel structure.";
    public const string WithTabsTitle = "With tabs";
    public const string WithTabsDescription = "More content can be hosted..";
    public const string MoreContentConfigurationTitle = "Support more content configuration";
    public const string MoreContentConfigurationDescription = "A Card that supports cover, avatar, title and description.";
    public const string P2HeaderLargeSizeCard = "Large size card";
    public const string P2HeaderDefaultSizeCard = "Default size card";
    public const string P2HeaderSmallSizeCard = "Small size card";
    public const string P2HeaderCardTitle = "Card title";
    public const string P2HeaderEuropeStreetBeat = "Europe Street beat";
    public const string P2HeaderCardTitle2 = "Card Title";
    public const string P2HeaderTab1 = "Tab1";
    public const string P2HeaderTab2 = "Tab2";
    public const string P2HeaderArticle = "article";
    public const string P2HeaderApp = "app";
    public const string P2HeaderProject = "project";
    public const string P2ContentMore = "More";
    public const string P2TextCardContent = "Card content";
    public const string P2TextThisIsTheDescription = "This is the description";
    public const string P2ContentContent = "Content";
    public const string P2ContentContent1 = "content1";
    public const string P2ContentContent2 = "content2";
    public const string P2ContentArticleContent = "article content";
    public const string P2ContentAppContent = "app content";
    public const string P2ContentProjectContent = "project content";

    public const string P2ContentThisIsTheDescription = "This is the description";

    protected override Type GetResourceKindType() => typeof(CardShowCaseLangResourceKind);
}
