using AtomUI.Theme.Language;

namespace AtomUIGallery.ShowCases.Card;

[LanguageProvider(LanguageCode.zh_CN, CardShowCase.LanguageId)]
internal partial class zh_CN
{
    public const string ScenarioExamples = "示例";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "设计变量";
    public const string ComponentCategory = "数据展示";
    public const string ComponentStatusStable = ".NET 10";
    public const string PageSubtitle = "用紧凑容器组织相关内容与操作。";
    public const string PageDescription = "Card 用于在独立的内容面板中呈现信息，支持标题、额外操作、封面媒体、元信息、栅格区域、标签页、加载占位、悬停反馈和无边框样式。";
    public const string ApiColumnProperty = "属性";
    public const string ApiColumnDescription = "说明";
    public const string ApiColumnType = "类型";
    public const string ApiColumnDefault = "默认值";
    public const string ApiPropertyExtra = "渲染在卡片标题操作区的额外内容。";
    public const string ApiPropertyExtraTemplate = "用于渲染标题额外内容的模板。";
    public const string ApiPropertyStyleVariant = "控制卡片为描边样式或无边框样式。";
    public const string ApiPropertySizeType = "控制卡片标题和内容区域的密度。";
    public const string ApiPropertyIsLoading = "在卡片内容不可用时显示加载占位。";
    public const string ApiPropertyIsInnerMode = "将卡片渲染为嵌套在另一个卡片中的内部卡片。";
    public const string ApiPropertyIsHoverable = "为可点击或可选择的卡片启用悬停反馈。";
    public const string ApiPropertyCover = "渲染在卡片内容上方的封面区域。";
    public const string ApiPropertyCoverTemplate = "用于渲染封面内容的模板。";
    public const string ApiPropertyActions = "渲染在卡片底部操作区的操作按钮集合。";
    public const string ApiPropertyBoxShadow = "悬停或浮层卡片表面使用的阴影。";
    public const string ApiPropertyIsMotionEnabled = "控制卡片支持的交互动效。";
    public const string TokenColumnToken = "变量";
    public const string TokenColumnDescription = "说明";
    public const string TokenColumnScope = "作用域";
    public const string TokenColumnStatus = "状态";
    public const string TokenNameHeaderBg = "卡片标题背景色。";
    public const string TokenNameHeaderFontSizeLG = "大尺寸卡片标题字号。";
    public const string TokenNameHeaderFontSize = "默认尺寸卡片标题字号。";
    public const string TokenNameHeaderFontSizeSM = "小尺寸卡片标题字号。";
    public const string TokenNameHeaderHeightLG = "大尺寸卡片标题高度。";
    public const string TokenNameHeaderHeight = "默认尺寸卡片标题高度。";
    public const string TokenNameHeaderHeightSM = "小尺寸卡片标题高度。";
    public const string TokenNameBodyPadding = "卡片内容区域默认内边距。";
    public const string TokenNameHeaderPadding = "卡片标题区域默认内边距。";
    public const string TokenNameActionsBg = "卡片操作区背景色。";
    public const string TokenNameActionsSpacing = "卡片操作项之间的间距。";
    public const string TokenNameTabsMarginBottom = "卡片内嵌标签页的底部外边距。";
    public const string TokenNameExtraColor = "标题额外区域文字颜色。";
    public const string TokenNameCardShadows = "卡片表面的默认阴影。";
    public const string TokenNameCardActionsIconSize = "卡片操作按钮图标尺寸。";
    public const string TokenNameCardGridItemShadows = "栅格卡片项之间的边线阴影。";
    public const string TokenScopeComponent = "组件";
    public const string TokenStatusStable = "稳定";
    public const string BasicTitle = "基础卡片";
    public const string BasicDescription = "包含标题、内容和右上角额外内容的基础卡片。支持默认和小号两种尺寸。";
    public const string ScenarioBasic = "基础";
    public const string ScenarioLayout = "布局";
    public const string ScenarioAdvanced = "高级";
    public const string NoBorderTitle = "无边框";
    public const string NoBorderDescription = "灰色背景上的无边框卡片。";
    public const string SimpleCardTitle = "简单卡片";
    public const string SimpleCardDescription = "只包含内容区域的简单卡片。";
    public const string CustomizedContentTitle = "自定义内容";
    public const string CustomizedContentDescription = "可以使用 Card.Meta 支持更灵活的内容。";
    public const string CardInColumnTitle = "栅格中的卡片";
    public const string CardInColumnDescription = "卡片通常在概览页面中配合栅格列布局使用。";
    public const string LoadingCardTitle = "加载中卡片";
    public const string LoadingCardDescription = "卡片内容获取过程中显示加载指示。";
    public const string GridCardTitle = "栅格卡片";
    public const string GridCardDescription = "栅格样式的卡片内容。";
    public const string InnerCardTitle = "内部卡片";
    public const string InnerCardDescription = "可放置在普通卡片内部，用于展示多级结构信息。";
    public const string WithTabsTitle = "带标签页";
    public const string WithTabsDescription = "可以承载更多内容。";
    public const string MoreContentConfigurationTitle = "支持更多内容配置";
    public const string MoreContentConfigurationDescription = "支持封面、头像、标题和描述的卡片。";
    public const string P2HeaderLargeSizeCard = "大尺寸卡片";
    public const string P2HeaderDefaultSizeCard = "默认尺寸卡片";
    public const string P2HeaderSmallSizeCard = "小尺寸卡片";
    public const string P2HeaderCardTitle = "卡片标题";
    public const string P2HeaderEuropeStreetBeat = "欧洲街拍";
    public const string P2HeaderCardTitle2 = "卡片标题";
    public const string P2HeaderTab1 = "标签页 1";
    public const string P2HeaderTab2 = "标签页 2";
    public const string P2HeaderArticle = "文章";
    public const string P2HeaderApp = "应用";
    public const string P2HeaderProject = "项目";
    public const string P2ContentMore = "更多";
    public const string P2TextCardContent = "卡片内容";
    public const string P2TextThisIsTheDescription = "这是描述内容";
    public const string P2ContentContent = "内容";
    public const string P2ContentContent1 = "内容 1";
    public const string P2ContentContent2 = "内容 2";
    public const string P2ContentArticleContent = "文章内容";
    public const string P2ContentAppContent = "应用内容";
    public const string P2ContentProjectContent = "项目内容";

    public const string P2ContentThisIsTheDescription = "这是描述内容";

}
