<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>$(AtomUITargetFrameworks)</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>GeneratedFiles</CompilerGeneratedFilesOutputPath>
        <AtomUIGenerateControlThemeAssetResources>true</AtomUIGenerateControlThemeAssetResources>
        <AtomUIRegistrationPackageId>$(AssemblyName)</AtomUIRegistrationPackageId>
        <AtomUIRegistrationEntries>AtomUI.Desktop.Controls.DataGridThemeManagerBuilderExtensions.UseDesktopDataGrid</AtomUIRegistrationEntries>
        <AtomUILanguageContractVersion>2</AtomUILanguageContractVersion>
        <RootNamespace>AtomUI.Desktop.Controls</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Remove="$(CompilerGeneratedFilesOutputPath)/**/*.cs"/>
    </ItemGroup>

    <ItemGroup>
        <AvaloniaXaml Update="Themes/DataGridOperationButtons.axaml;Themes/DataGridRowExpanderTheme.axaml;Themes/Filters/DataGridFilterMenuItemTheme.axaml;Themes/Filters/DataGridFilterTreeItemTheme.axaml"
                       AtomUIRegistrationUnit="DataGrid" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../AtomUI.Generator/AtomUI.Generator.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"
                          PrivateAssets="all"/>
        <ProjectReference Include="../AtomUI.Desktop.Controls/AtomUI.Desktop.Controls.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="AtomUI.Desktop.Controls.DataGrid.Tests" />
    </ItemGroup>

</Project>
