using AtomUI.Localization;

namespace AtomUIGallery.Localization;

[LanguageCatalog]
public enum CalendarShowCaseLangResourceKind
{
    PageSubtitle,
    PageDescription,
    ComponentCategory,
    ComponentStatusStable,
    ScenarioExamples,
    BasicTitle,
    BasicDescription,
    CardTitle,
    CardDescription,
    CustomHeaderTitle,
    CustomHeaderDescription,
    CustomHeaderContentTitle,
    CustomHeaderMonthText,
    CustomHeaderYearText,
    LunarCalendarTitle,
    LunarCalendarDescription,
    LunarCalendarCardTitle,
    LunarCalendarCardDescription,
    SelectableCalendarTitle,
    SelectableCalendarDescription,
    SelectableCalendarSelectedMessage,
    ShowWeekTitle,
    ShowWeekDescription,
    NoticeCalendarTitle,
    NoticeCalendarDescription,
    NoticeCalendarWarningEventText,
    NoticeCalendarUsualEventText,
    NoticeCalendarErrorEventText,
    NoticeCalendarLongUsualEventText,
    NoticeCalendarErrorEvent1Text,
    NoticeCalendarErrorEvent2Text,
    NoticeCalendarErrorEvent3Text,
    NoticeCalendarErrorEvent4Text,
    NoticeCalendarBacklogText,
    CrossDateEventsTitle,
    CrossDateEventsDescription,
    CrossDateEventsReleaseText,
    CrossDateEventsDesignReviewText,
    CrossDateEventsMaintenanceText,
    CrossDateEventsBugFixText,
    SemanticPartStyleTitle,
    SemanticPartStyleDescription,
    SemanticRootDescription,
    SemanticHeaderDescription,
    SemanticBodyDescription,
    SemanticContentDescription,
    SemanticItemDescription,
    SemanticItemContentDescription
}
