using AtomUI.Localization;

namespace AtomUIGallery.Localization;

[LanguageCatalog(ContractVersion = 1)]
public enum NumberUpDownShowCaseLangResourceKind
{
    ScenarioBasic = 1,
    ScenarioRange = 2,
    ScenarioStyle = 3,
    ScenarioAddon = 4,
    BasicUsageTitle = 5,
    BasicUsageDescription = 6,
    SpinnerModeTitle = 7,
    SpinnerModeDescription = 8,
    HideHandleTitle = 9,
    HideHandleDescription = 10,
    StringModeTitle = 11,
    StringModeDescription = 12,
    KeyboardBehaviorTitle = 13,
    KeyboardBehaviorDescription = 14,
    MouseWheelBehaviorTitle = 15,
    MouseWheelBehaviorDescription = 16,
    MinMaxTitle = 17,
    MinMaxDescription = 18,
    DecimalStepTitle = 19,
    DecimalStepDescription = 20,
    SizesTitle = 21,
    SizesDescription = 22,
    VariantsTitle = 23,
    VariantsDescription = 24,
    DisabledTitle = 25,
    DisabledDescription = 26,
    PrePostTabTitle = 27,
    PrePostTabDescription = 28,
    WithClearIconTitle = 29,
    WithClearIconDescription = 30,
    PrefixAndSuffixTitle = 31,
    PrefixAndSuffixDescription = 32,
    StatusTitle = 33,
    StatusDescription = 34,
    P2PlaceholderTextInputWeight = 35,
    P2PlaceholderTextKeyboardDisabled = 36,
    P2PlaceholderTextFocusAndScrollWheel = 37,
    P2PlaceholderTextInputWithClearIcon = 38,
    P2PlaceholderTextEnterYourValue = 39,
    P2PlaceholderTextError = 40,
    P2PlaceholderTextWarning = 41,
    P2PlaceholderTextErrorWithPrefix = 42,
    P2PlaceholderTextWarningWithPrefix = 43,
    P2TextRawValuePrefix = 44,
    P2ContentKeyboardEnabled = 45,
    ScenarioExamples = 46,
    PageSubtitle = 47,
    PageDescription = 48,
    ComponentCategory = 49,
    ComponentStatusStable = 50
}
