using AtomUI.Localization;

namespace AtomUIGallery.Localization;

[LanguageCatalog(ContractVersion = 2)]
public enum NumberUpDownShowCaseLangResourceKind
{
    ScenarioBasic,
    ScenarioRange,
    ScenarioStyle,
    ScenarioAddon,
    BasicUsageTitle,
    BasicUsageDescription,
    SpinnerModeTitle,
    SpinnerModeDescription,
    HideHandleTitle,
    HideHandleDescription,
    StringModeTitle,
    StringModeDescription,
    KeyboardBehaviorTitle,
    KeyboardBehaviorDescription,
    MouseWheelBehaviorTitle,
    MouseWheelBehaviorDescription,
    MinMaxTitle,
    MinMaxDescription,
    DecimalStepTitle,
    DecimalStepDescription,
    SizesTitle,
    SizesDescription,
    VariantsTitle,
    VariantsDescription,
    DisabledTitle,
    DisabledDescription,
    PrePostTabTitle,
    PrePostTabDescription,
    WithClearIconTitle,
    WithClearIconDescription,
    PrefixAndSuffixTitle,
    PrefixAndSuffixDescription,
    StatusTitle,
    StatusDescription,
    P2PlaceholderTextInputWeight,
    P2PlaceholderTextKeyboardDisabled,
    P2PlaceholderTextFocusAndScrollWheel,
    P2PlaceholderTextInputWithClearIcon,
    P2PlaceholderTextEnterYourValue,
    P2PlaceholderTextError,
    P2PlaceholderTextWarning,
    P2PlaceholderTextErrorWithPrefix,
    P2PlaceholderTextWarningWithPrefix,
    P2TextRawValuePrefix,
    P2ContentKeyboardEnabled,
    ScenarioExamples,
    PageSubtitle,
    PageDescription,
    ComponentCategory,
    ComponentStatusStable
}
