using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.FloatButton;

[LanguageProvider(LanguageCode.en_US, FloatButtonShowCase.LanguageId)]
internal partial class en_US
{
    public const string BasicTitle = "Basic";
    public const string BasicDescription = "The most basic usage.";
    public const string TypeTitle = "Type";
    public const string TypeDescription = "Change the type of the FloatButton with the type property.";
    public const string ShapeTitle = "Shape";
    public const string ShapeDescription = "Change the shape of the FloatButton with the shape property.";
    public const string TooltipTitle = "FloatButton with tooltip";
    public const string TooltipDescription = "Setting the tooltip property shows the FloatButton with a tooltip.";
    public const string DescriptionTitle = "Description";
    public const string DescriptionDescription = "Setting the description property allows you to show a FloatButton with a description.";
    public const string GroupTitle = "FloatButton Group";
    public const string GroupDescription = "When multiple buttons are used together, FloatButtonGroup is recommended. By setting the shape property of FloatButton.Group, you can change the group shape. The FloatButton.Group shape overrides the shape of FloatButtons inside.";
    public const string MenuModeTitle = "Menu mode";
    public const string MenuModeDescription = "Open menu mode with trigger, which could be hover or click.";
    public const string ControlledModeTitle = "Controlled mode";
    public const string ControlledModeDescription = "Set the component to controlled mode through open. IsOpen binds two-way by default and works together with trigger.";
    public const string PlacementTitle = "Placement";
    public const string PlacementDescription = "Customize animation placement. Four preset placements are provided: top, right, bottom, and left. The default placement is top.";
    public const string BadgeTitle = "Badge";
    public const string BadgeDescription = "FloatButton with Badge.";
    public const string BackTopTitle = "BackTop";
    public const string BackTopDescription = "BackTop makes it easy to go back to the top of the page.";
    public const string P2TooltipSinceN5N25N0 = "Since 5.25.0+";
    public const string P2TooltipDocuments = "Documents";
    public const string P2DescriptionHelpInfo = "HELP INFO";
    public const string P2TextScrollToBottom = "Scroll to bottom";
    public const string PageSubtitle = "Floating actions that stay available inside a scrollable region.";
    public const string PageDescription = "FloatButton provides quick access to important actions, grouped menus, badges, and back-to-top behavior while keeping controls anchored to the active content area.";
    public const string ComponentCategory = "General";
    public const string ComponentStatusStable = ".NET 10";
    public const string ScenarioExamples = "Examples";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "Design Token";
    public const string ApiColumnProperty = "Property";
    public const string ApiColumnDescription = "Description";
    public const string ApiColumnType = "Type";
    public const string ApiColumnDefault = "Default";
    public const string ApiPropertyPlacement = "Anchoring position of the floating button or group within its host.";
    public const string ApiPropertyFloatOffsetX = "Horizontal offset applied after placement is calculated.";
    public const string ApiPropertyFloatOffsetY = "Vertical offset applied after placement is calculated.";
    public const string ApiPropertyIcon = "Icon displayed inside the button.";
    public const string ApiPropertyTooltip = "Tooltip text displayed when hovering the button.";
    public const string ApiPropertyTooltipColor = "Optional color for the tooltip.";
    public const string ApiPropertyDescription = "Text or content displayed in a square FloatButton.";
    public const string ApiPropertyButtonType = "Visual button type.";
    public const string ApiPropertyShape = "Button shape.";
    public const string ApiPropertyHref = "Optional URI associated with the button.";
    public const string ApiPropertyIsMotionEnabled = "Controls whether open, close, and visibility animations are enabled.";
    public const string ApiPropertyIsBadgeEnabled = "Shows a badge on the floating button.";
    public const string ApiPropertyIsDotBadge = "Uses a dot badge instead of a count badge.";
    public const string ApiPropertyBadgeCount = "Count displayed in the badge.";
    public const string ApiPropertyBadgeColor = "Badge color token or color name.";
    public const string ApiPropertyBadgeOverflowCount = "Maximum count before the badge shows overflow text.";
    public const string ApiPropertyTrigger = "Interaction that opens a FloatButton group menu.";
    public const string ApiPropertyMenuPlacement = "Direction where group menu items are placed.";
    public const string ApiPropertyIsOpen = "Controlled open state for a FloatButton group. Two-way binding is enabled by default.";
    public const string ApiPropertyToTopDuration = "Duration of the back-to-top scroll animation.";
    public const string ApiPropertyTarget = "ScrollViewer controlled by BackTopFloatButton.";
    public const string ApiPropertyVisibilityHeight = "Scroll offset required before BackTopFloatButton becomes visible.";
    public const string TokenColumnToken = "Token";
    public const string TokenColumnDescription = "Description";
    public const string TokenColumnScope = "Scope";
    public const string TokenColumnStatus = "Status";
    public const string TokenNameFloatButtonSize = "Base FloatButton width and height.";
    public const string TokenNameFloatButtonIconSize = "Icon size inside FloatButton.";
    public const string TokenNameSquareBadgeOffset = "Badge offset used by square FloatButton.";
    public const string TokenNameCircleBadgeOffset = "Badge offset used by circular FloatButton.";
    public const string TokenNamePrimaryColor = "Foreground color for primary FloatButton content.";
    public const string TokenNameDescriptionLineHeight = "Line height for description text.";
    public const string TokenNameFloatOffsetX = "Default horizontal floating offset.";
    public const string TokenNameFloatOffsetY = "Default vertical floating offset.";
    public const string TokenScopeComponent = "Component";
    public const string TokenStatusStable = "Stable";

}
