using AtomUI.Theme.Language;

namespace AtomUIGallery.ShowCases.CustomizeTheme;

[LanguageProvider(LanguageCode.en_US, CustomizeThemeShowCase.LanguageId)]
internal partial class en_US
{
    public const string ScenarioExamples = "Examples";
    public const string ScenarioApi = "API";
    public const string ScenarioDesignToken = "Design Token";
    public const string ComponentCategory = "General";
    public const string ComponentStatusStable = ".NET 10";
    public const string PageSubtitle = "Customize AtomUI themes with shared tokens, algorithms, component tokens, and nested local theme scopes.";
    public const string PageDescription = "Customize Theme demonstrates the ThemeConfigProvider model used to override seed tokens, derived tokens, preset algorithms, component-scoped tokens, and nested theme contexts without changing the global application theme.";
    public const string ApiColumnMember = "Member";
    public const string ApiColumnDescription = "Description";
    public const string ApiColumnType = "Type";
    public const string ApiColumnDefault = "Default";
    public const string ApiMemberThemeConfigProviderAlgorithms = "Theme algorithms applied by this provider, such as Default, Dark, or Compact.";
    public const string ApiMemberThemeConfigProviderSharedTokenSetters = "Shared token overrides that affect all descendants under the provider.";
    public const string ApiMemberThemeConfigProviderControlTokenInfoSetters = "Component token override groups keyed by a control token id.";
    public const string ApiMemberTokenSetterKey = "Design token key to override.";
    public const string ApiMemberTokenSetterValue = "String value used to override the token.";
    public const string ApiMemberTokenSetterCatalog = "Optional token catalog used when the key belongs to a specific catalog.";
    public const string ApiMemberControlTokenInfoSetter = "Control token id, for example Button or AddOnDecoratedBox.";
    public const string ApiMemberControlTokenInfoSetterEnableAlgorithm = "Whether the component token override participates in the theme algorithm calculation.";
    public const string ApiMemberControlTokenInfoSetterSetters = "Token setters applied to the selected component token.";
    public const string TokenColumnToken = "Token";
    public const string TokenColumnDescription = "Description";
    public const string TokenColumnScope = "Scope";
    public const string TokenColumnStatus = "Status";
    public const string TokenNameColorPrimary = "Primary brand color used by interactive components.";
    public const string TokenNameBorderRadius = "Shared corner radius seed used to derive component radii.";
    public const string TokenNameColorBgContainer = "Container background color used by controls and surfaces.";
    public const string TokenNameButtonColorPrimary = "Button component primary color override.";
    public const string TokenNameAddOnDecoratedBoxColorPrimary = "AddOnDecoratedBox component primary color override used by input decorations.";
    public const string TokenScopeShared = "Shared";
    public const string TokenScopeComponent = "Component";
    public const string TokenStatusStable = "Stable";
    public const string CustomizeDesignTokenTitle = "Customize Design Token";
    public const string CustomizeDesignTokenDescription = "By modifying token property of theme, we can modify Design Token globally. Some tokens will affect other tokens. We call these tokens Seed Token.";
    public const string PresetAlgorithmsTitle = "Use Preset Algorithms";
    public const string PresetAlgorithmsDescription = "Themes with different styles can be quickly generated by modifying algorithm. Ant Design 5.0 provides three sets of preset algorithms by default: DefaultAlgorithm, DarkAlgorithm, CompactAlgorithm.";
    public const string RuntimeTokenUpdatesTitle = "Runtime Token Updates";
    public const string RuntimeTokenUpdatesDescription = "ThemeConfigProvider listens to TokenSetter changes and republishes one scoped snapshot without adding extra resource provider layers.";
    public const string CustomizeComponentTokenTitle = "Customize Component Token";
    public const string CustomizeComponentTokenDescription = "In addition to Design Token, each component has its own Component Token for style customization, and different components do not affect each other. Component Design Tokens can also be overridden in this way.";
    public const string NestedThemeTitle = "Nested Theme";
    public const string NestedThemeDescription = "By nesting ConfigProvider you can apply a local theme to part of your page. Design Tokens that are not changed in the child theme inherit from the parent theme.";
    public const string P2PlaceholderTextPleaseInput = "Please input";
    public const string P2ContentPrimaryButton = "Primary Button";
    public const string P2ContentDefaultButton = "Default Button";
    public const string P2ContentTextButton = "Text Button";
    public const string P2ContentLinkButton = "Link Button";
    public const string P2ContentApple = "Apple";
    public const string P2ContentPear = "Pear";
    public const string P2ContentOrange = "Orange";
    public const string P2ContentSubmit = "Submit";
    public const string P2ContentUseBlue = "Blue";
    public const string P2ContentUseGreen = "Green";
    public const string P2ContentUseMagenta = "Magenta";
    public const string P2TextEnableAlgorithm = "Enable algorithm:";
    public const string P2TextDisableAlgorithm = "Disable algorithm:";
    public const string P2ContentThemeN1 = "Theme 1";
    public const string P2ContentThemeN2 = "Theme 2";
    public const string P2ContentThemeN3 = "No inherit";

}
