using AtomUI.Theme.Language;

namespace AtomUIGallery.ShowCases.CustomizeTheme;

[LanguageProvider(LanguageCode.en_US, CustomizeThemeShowCase.LanguageId)]
internal partial class en_US
{
    public const string ScenarioExamples = "Examples";
    public const string ComponentCategory = "General";
    public const string ComponentStatusStable = ".NET 10";
    public const string PageSubtitle = "Customize AtomUI themes with shared tokens, algorithms, component tokens, and nested local theme scopes.";
    public const string PageDescription = "Customize Theme demonstrates the ThemeConfigProvider model used to override seed tokens, derived tokens, preset algorithms, component-scoped tokens, and nested theme contexts without changing the global application theme.";
    public const string ApiMemberThemeConfigProviderConfig = "Immutable scoped theme configuration. Runtime updates replace the complete value.";
    public const string ApiMemberThemeConfigInherit = "Whether this configuration inherits and merges the parent theme configuration.";
    public const string ApiMemberThemeConfigAlgorithms = "Ordered global algorithm identities. A null value inherits the parent algorithm chain.";
    public const string ApiMemberThemeConfigTokens = "Global token overrides keyed by token name.";
    public const string ApiMemberThemeConfigControls = "Control theme configurations keyed by ControlTokenIdentity.";
    public const string ApiMemberControlThemeConfigAlgorithm = "How the control applies algorithms: Unspecified, Disabled, Global, or Custom.";
    public const string ApiMemberControlThemeConfigAlgorithms = "Ordered custom control algorithms used only when Algorithm is Custom.";
    public const string ApiMemberControlThemeConfigTokens = "Token overrides applied only to the selected control token family.";
    public const string CustomizeDesignTokenTitle = "Customize Design Token";
    public const string CustomizeDesignTokenDescription = "By modifying token property of theme, we can modify Design Token globally. Some tokens will affect other tokens. We call these tokens Seed Token.";
    public const string PresetAlgorithmsTitle = "Use Preset Algorithms";
    public const string PresetAlgorithmsDescription = "Themes with different styles can be quickly generated by modifying algorithm. Ant Design 5.0 provides three sets of preset algorithms by default: DefaultAlgorithm, DarkAlgorithm, CompactAlgorithm.";
    public const string RuntimeTokenUpdatesTitle = "Runtime Token Updates";
    public const string RuntimeTokenUpdatesDescription = "Replace ThemeConfigProvider.Config with a new immutable ThemeConfig to publish one scoped snapshot without adding resource provider layers.";
    public const string CustomizeComponentTokenTitle = "Customize Component Token";
    public const string CustomizeComponentTokenDescription = "In addition to Design Token, each component has its own Component Token for style customization, and different components do not affect each other. Component Design Tokens can also be overridden in this way.";
    public const string NestedThemeTitle = "Nested Theme";
    public const string NestedThemeDescription = "By nesting ConfigProvider you can apply a local theme to part of your page. Design Tokens that are not changed in the child theme inherit from the parent theme.";
    public const string P2PlaceholderTextPleaseInput = "Please input";
    public const string P2ContentPrimaryButton = "Primary Button";
    public const string P2ContentDefaultButton = "Default Button";
    public const string P2ContentTextButton = "Text Button";
    public const string P2ContentLinkButton = "Link Button";
    public const string P2ContentApple = "Apple";
    public const string P2ContentPear = "Pear";
    public const string P2ContentOrange = "Orange";
    public const string P2ContentSubmit = "Submit";
    public const string P2ContentUseBlue = "Blue";
    public const string P2ContentUseGreen = "Green";
    public const string P2ContentUseMagenta = "Magenta";
    public const string P2TextEnableAlgorithm = "Enable algorithm:";
    public const string P2TextDisableAlgorithm = "Disable algorithm:";
    public const string P2ContentThemeN1 = "Theme 1";
    public const string P2ContentThemeN2 = "Theme 2";
    public const string P2ContentThemeN3 = "No inherit";

}
