using AtomUI.Theme.Language;
using AtomUIGallery.Localization;

namespace AtomUIGallery.ShowCases.CustomizeTheme;

[LanguageProvider(LanguageCode.en_US, CustomizeThemeShowCase.LanguageId)]
internal class en_US : LanguageProvider
{
    public const string CustomizeDesignTokenTitle = "Customize Design Token";
    public const string CustomizeDesignTokenDescription = "By modifying token property of theme, we can modify Design Token globally. Some tokens will affect other tokens. We call these tokens Seed Token.";
    public const string PresetAlgorithmsTitle = "Use Preset Algorithms";
    public const string PresetAlgorithmsDescription = "Themes with different styles can be quickly generated by modifying algorithm. Ant Design 5.0 provides three sets of preset algorithms by default: DefaultAlgorithm, DarkAlgorithm, CompactAlgorithm.";
    public const string CustomizeComponentTokenTitle = "Customize Component Token";
    public const string CustomizeComponentTokenDescription = "In addition to Design Token, each component has its own Component Token for style customization, and different components do not affect each other. Component Design Tokens can also be overridden in this way.";
    public const string NestedThemeTitle = "Nested Theme";
    public const string NestedThemeDescription = "By nesting ConfigProvider you can apply a local theme to part of your page. Design Tokens that are not changed in the child theme inherit from the parent theme.";

    protected override Type GetResourceKindType() => typeof(CustomizeThemeShowCaseLangResourceKind);
}
