using AtomUI.Theme.TokenSystem;

namespace AtomUI.Desktop.Controls.DesignTokens
{
    public static class DataGridTokenKey
    {
        public static readonly TokenResourceKey BodySortBg = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.BodySortBg");
        public static readonly TokenResourceKey BorderColor = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.BorderColor");
        public static readonly TokenResourceKey CellFontSize = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.CellFontSize");
        public static readonly TokenResourceKey CellFontSizeMD = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.CellFontSizeMD");
        public static readonly TokenResourceKey CellFontSizeSM = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.CellFontSizeSM");
        public static readonly TokenResourceKey CellPadding = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.CellPadding");
        public static readonly TokenResourceKey CellPaddingMD = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.CellPaddingMD");
        public static readonly TokenResourceKey CellPaddingSM = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.CellPaddingSM");
        public static readonly TokenResourceKey ColumnReorderActiveBg = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.ColumnReorderActiveBg");
        public static readonly TokenResourceKey ExpandIconBg = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.ExpandIconBg");
        public static readonly TokenResourceKey ExpandIconHalfInner = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.ExpandIconHalfInner");
        public static readonly TokenResourceKey ExpandIconMargin = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.ExpandIconMargin");
        public static readonly TokenResourceKey ExpandIconScale = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.ExpandIconScale");
        public static readonly TokenResourceKey ExpandIconSize = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.ExpandIconSize");
        public static readonly TokenResourceKey FilterDropdownBg = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.FilterDropdownBg");
        public static readonly TokenResourceKey FilterDropdownMenuBg = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.FilterDropdownMenuBg");
        public static readonly TokenResourceKey FilterIndicatorPadding = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.FilterIndicatorPadding");
        public static readonly TokenResourceKey FixedHeaderSortActiveBg = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.FixedHeaderSortActiveBg");
        public static readonly TokenResourceKey FooterBg = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.FooterBg");
        public static readonly TokenResourceKey FooterColor = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.FooterColor");
        public static readonly TokenResourceKey HeaderBg = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.HeaderBg");
        public static readonly TokenResourceKey HeaderBorderRadius = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.HeaderBorderRadius");
        public static readonly TokenResourceKey HeaderColor = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.HeaderColor");
        public static readonly TokenResourceKey HeaderFilterHoverBg = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.HeaderFilterHoverBg");
        public static readonly TokenResourceKey HeaderIconColor = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.HeaderIconColor");
        public static readonly TokenResourceKey HeaderIconHoverColor = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.HeaderIconHoverColor");
        public static readonly TokenResourceKey HeaderSortActiveBg = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.HeaderSortActiveBg");
        public static readonly TokenResourceKey HeaderSortHoverBg = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.HeaderSortHoverBg");
        public static readonly TokenResourceKey HeaderSplitColor = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.HeaderSplitColor");
        public static readonly TokenResourceKey LeftFrozenShadows = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.LeftFrozenShadows");
        public static readonly TokenResourceKey PaginationMargin = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.PaginationMargin");
        public static readonly TokenResourceKey RightFrozenShadows = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.RightFrozenShadows");
        public static readonly TokenResourceKey RowExpandedBg = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.RowExpandedBg");
        public static readonly TokenResourceKey RowHoverBg = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.RowHoverBg");
        public static readonly TokenResourceKey RowReorderIndicatorSize = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.RowReorderIndicatorSize");
        public static readonly TokenResourceKey RowSelectedBg = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.RowSelectedBg");
        public static readonly TokenResourceKey RowSelectedHoverBg = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.RowSelectedHoverBg");
        public static readonly TokenResourceKey SelectionColumnWidth = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.SelectionColumnWidth");
        public static readonly TokenResourceKey SortIconSize = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.SortIconSize");
        public static readonly TokenResourceKey SortIndicatorLayoutMargin = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.SortIndicatorLayoutMargin");
        public static readonly TokenResourceKey TableBg = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableBg");
        public static readonly TokenResourceKey TableBodySortBg = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableBodySortBg");
        public static readonly TokenResourceKey TableBorderColor = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableBorderColor");
        public static readonly TokenResourceKey TableExpandColumnWidth = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableExpandColumnWidth");
        public static readonly TokenResourceKey TableExpandedRowBg = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableExpandedRowBg");
        public static readonly TokenResourceKey TableExpandIconBg = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableExpandIconBg");
        public static readonly TokenResourceKey TableFilterButtonContainerMargin = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableFilterButtonContainerMargin");
        public static readonly TokenResourceKey TableFilterButtonLayoutSeparatorMargin = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableFilterButtonLayoutSeparatorMargin");
        public static readonly TokenResourceKey TableFilterButtonSpacing = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableFilterButtonSpacing");
        public static readonly TokenResourceKey TableFilterDropdownBg = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableFilterDropdownBg");
        public static readonly TokenResourceKey TableFilterDropdownHeight = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableFilterDropdownHeight");
        public static readonly TokenResourceKey TableFilterDropdownPadding = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableFilterDropdownPadding");
        public static readonly TokenResourceKey TableFilterDropdownSearchWidth = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableFilterDropdownSearchWidth");
        public static readonly TokenResourceKey TableFilterDropdownWidth = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableFilterDropdownWidth");
        public static readonly TokenResourceKey TableFixedHeaderSortActiveBg = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableFixedHeaderSortActiveBg");
        public static readonly TokenResourceKey TableFontSize = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableFontSize");
        public static readonly TokenResourceKey TableFontSizeMiddle = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableFontSizeMiddle");
        public static readonly TokenResourceKey TableFontSizeSmall = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableFontSizeSmall");
        public static readonly TokenResourceKey TableFooterBg = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableFooterBg");
        public static readonly TokenResourceKey TableFooterTextColor = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableFooterTextColor");
        public static readonly TokenResourceKey TableHeaderBg = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableHeaderBg");
        public static readonly TokenResourceKey TableHeaderCellSplitColor = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableHeaderCellSplitColor");
        public static readonly TokenResourceKey TableHeaderFilterActiveBg = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableHeaderFilterActiveBg");
        public static readonly TokenResourceKey TableHeaderSortBg = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableHeaderSortBg");
        public static readonly TokenResourceKey TableHeaderSortHoverBg = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableHeaderSortHoverBg");
        public static readonly TokenResourceKey TableHeaderTextColor = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableHeaderTextColor");
        public static readonly TokenResourceKey TablePadding = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TablePadding");
        public static readonly TokenResourceKey TablePaddingMiddle = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TablePaddingMiddle");
        public static readonly TokenResourceKey TablePaddingSmall = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TablePaddingSmall");
        public static readonly TokenResourceKey TableRadius = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableRadius");
        public static readonly TokenResourceKey TableRowHoverBg = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableRowHoverBg");
        public static readonly TokenResourceKey TableSelectedRowBg = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableSelectedRowBg");
        public static readonly TokenResourceKey TableSelectedRowHoverBg = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableSelectedRowHoverBg");
        public static readonly TokenResourceKey TableSelectionColumnWidth = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableSelectionColumnWidth");
        public static readonly TokenResourceKey TableTopLeftColumnCornerRadius = new TokenResourceKey("AtomUI.Desktop.Controls.DataGrid.TableTopLeftColumnCornerRadius");
    }
}