// <auto-generated />
using System;
using System.Collections.Generic;

namespace AtomUI.Theme.Tokens;

internal static class TokenValueConverterRegistry
{
    public static Dictionary<Type, ITokenValueConverter> Create()
    {
        ITokenValueConverter[] valueConverters = new ITokenValueConverter[]
        {
            new global::AtomUI.Theme.Tokens.BoolTokenValueConverter(),
            new global::AtomUI.Theme.Tokens.BoxShadowsTokenValueConverter(),
            new global::AtomUI.Theme.Tokens.BoxShadowTokenValueConverter(),
            new global::AtomUI.Theme.Tokens.BrushTokenValueConverter(),
            new global::AtomUI.Theme.Tokens.ColorTokenValueConverter(),
            new global::AtomUI.Theme.Tokens.CornerRadiusTokenValueConverter(),
            new global::AtomUI.Theme.Tokens.DimensionTokenValueConverter(),
            new global::AtomUI.Theme.Tokens.DoubleTokenValueConverter(),
            new global::AtomUI.Theme.Tokens.EasingTokenValueConverter(),
            new global::AtomUI.Theme.Tokens.FloatTokenValueConverter(),
            new global::AtomUI.Theme.Tokens.FontFamilyTokenValueConverter(),
            new global::AtomUI.Theme.Tokens.FontWeightTokenValueConverter(),
            new global::AtomUI.Theme.Tokens.ImmutableBrushTokenValueConverter(),
            new global::AtomUI.Theme.Tokens.ImmutableTransformTokenValueConverter(),
            new global::AtomUI.Theme.Tokens.IntegerTokenValueConverter(),
            new global::AtomUI.Theme.Tokens.LineStyleTokenValueConverter(),
            new global::AtomUI.Theme.Tokens.NullableColorTokenValueConverter(),
            new global::AtomUI.Theme.Tokens.NullableTextDecorationTokenValueConverter(),
            new global::AtomUI.Theme.Tokens.PenLineCapTokenValueConverter(),
            new global::AtomUI.Theme.Tokens.PenLineJoinTokenValueConverter(),
            new global::AtomUI.Theme.Tokens.PointTokenValueConverter(),
            new global::AtomUI.Theme.Tokens.SizeTokenValueConverter(),
            new global::AtomUI.Theme.Tokens.SolidColorBrushTokenValueConverter(),
            new global::AtomUI.Theme.Tokens.StringTokenValueConverter(),
            new global::AtomUI.Theme.Tokens.TextDecorationTokenValueConverter(),
            new global::AtomUI.Theme.Tokens.ThicknessTokenValueConverter(),
            new global::AtomUI.Theme.Tokens.TimeSpanTokenValueConverter(),
        };

        var map = new Dictionary<Type, ITokenValueConverter>(valueConverters.Length);
        foreach (var valueConverter in valueConverters)
        {
            map.Add(valueConverter.TargetType(), valueConverter);
        }

        return map;
    }
}
